### ISSUE TITLE
Agent can not be configured if run under System account

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vsts-agent#1001]
## **Agent version and platform**
Version of your agent? 2.112.0
<br>
OS of the machine running the agent? Windows 2016
<br>
## **VSTS type and version**
On-Prem TFS
<br>
2017
<br>
## **What's not working?** 
Installing agent under System account does not work.
Image below showing that executing exact same command line under System account (top window) fails to authenticate while running exact same EXE under user account works. I need configuration to be run under System account since it's what DSC using for launching EXE by default.
![image](https://cloud.githubusercontent.com/assets/13176884/26698333/37c4a4cc-46db-11e7-9a69-37f4a3ecd031.png)

<br>
## **Agent and Worker's diag log**

```
[2017-06-01 19:58:39Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2017-06-01 19:58:39Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2017-06-01 19:58:39Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2017-06-01 19:58:39Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2017-06-01 19:58:39Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2017-06-01 19:58:39Z INFO Terminal] WRITE LINE: 
[2017-06-01 19:58:39Z INFO Terminal] WRITE LINE: >> Connect:
[2017-06-01 19:58:39Z INFO Terminal] WRITE LINE: 
[2017-06-01 19:58:39Z INFO CommandSettings] Arg 'url': 'https://vsts/tfs'
[2017-06-01 19:58:39Z INFO CommandSettings] Remove url from Arg dictionary.
[2017-06-01 19:58:39Z INFO ConfigurationManager] GetCredentialProvider
[2017-06-01 19:58:39Z INFO CommandSettings] Arg 'auth': 'PAT'
[2017-06-01 19:58:39Z INFO CommandSettings] Remove auth from Arg dictionary.
[2017-06-01 19:58:39Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-06-01 19:58:39Z INFO CredentialManager] GetCredentialProvider
[2017-06-01 19:58:39Z INFO CredentialManager] Creating type PAT
[2017-06-01 19:58:39Z INFO CredentialManager] Creating credential type: PAT
[2017-06-01 19:58:39Z INFO PersonalAccessToken] EnsureCredential
[2017-06-01 19:58:39Z INFO CommandSettings] Arg 'token': '********'
[2017-06-01 19:58:39Z INFO CommandSettings] Remove token from Arg dictionary.
[2017-06-01 19:58:39Z INFO PersonalAccessToken] GetVssCredentials
[2017-06-01 19:58:39Z INFO PersonalAccessToken] token retrieved: 52 chars
[2017-06-01 19:58:39Z INFO ConfigurationManager] cred retrieved
[2017-06-01 19:58:39Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-06-01 19:58:40Z INFO CommandSettings] Flag 'unattended': 'True'
[2017-06-01 19:58:40Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://vsts.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
```

**Comment by TingluoHuang** [comment]
@artisticcheese check your PAT make sure it's valid, we noticed when the PAT wrong, the client fallback to NTLM which is wrong. but that may explains the behavior you saw.

**Comment by artisticcheese** [comment]
@TingluoHuang  There is no reason to check since I cut and paste PAT in both CMD windows. I did not type it. I'm 100% sure they are correct.

**Comment by TingluoHuang** [comment]
@artisticcheese are you able to get fiddler trace for both see what auth header been set?

**Comment by TingluoHuang** [comment]
@artisticcheese here is the doc for capture http trace.
https://www.visualstudio.com/en-us/docs/build/troubleshooting#http-trace-logs

if you try agent > 2.114.0 the agent has built in function to trace http traffic.

**Comment by TingluoHuang** [comment]
@artisticcheese I am whether you PAT has right permission

**Comment by TingluoHuang** [comment]
I mean*

**Comment by artisticcheese** [comment]
PAT is `EXACTLY` the same in both cases as you can see. The only difference under which account it's being run. Please check screenshot, CMD on top is being executed as SYSTEM account and CMD below is being executed as "Administrator" account. It's not an issue of permission of PAT, configuration of VSTS server or mistyped something. I'm trying to capture HTTPS logs.

**Comment by artisticcheese** [comment]
I have HTTPS trace. It's attached. You can see PAT is in fact passed in CMD execution.

![image](https://cloud.githubusercontent.com/assets/13176884/26700010/6f5f412a-46e1-11e7-8a96-562180c709a0.png)

[a.zip](https://github.com/Microsoft/vsts-agent/files/1045991/a.zip)

**Comment by TingluoHuang** [comment]
@artisticcheese 
in the Fiddler trace.
first request used PAT got 401.
Authorization: Basic VnN0c0FnZW50OjRzaWd4em1wNm9sb2NhcHZvb3Jmc2szeHhrdm1wZjIyNmFzbmpidnljeGtvb2xhcjI3YXE=
second request fallback to use NTLM still got 401.
Authorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAKADk4AAAADw==

I guess if you try the same test on the user account, the user account will succeed on the NTLM fallback.
the fallback is a bug in the build agent, i will fix it soon.

now, we need figure out what's wrong with your PAT. can you check your TFS AT's event log? see whether there is any record correlated to this auth failure?

**Comment by artisticcheese** [comment]
Where I can find TFS AT log?

**Comment by artisticcheese** [comment]
Here is entry I see in Debug Log in Event Viewer

```
ExceptionType Microsoft.VisualStudio.Services.DelegatedAuthorization.Exceptions.InvalidAccessTokenKeyException 
 
   Message Microsoft.VisualStudio.Services.DelegatedAuthorization.Exceptions.InvalidAccessTokenKeyException: InvalidAccessTokenKeyException at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.TranslateException(Int32 errorNumber, SqlException sqlException, SqlError sqlError) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.TranslateException(SqlException sqlException) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.MapException(SqlException ex, QueryExecutionState queryState) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.HandleException(Exception exception) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommand(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) at Microsoft.VisualStudio.Services.CircuitBreaker.Command.<>c__DisplayClass7_0.<Execute>b__0() at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.<Execute>d__28.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.CircuitBreaker.Command.Execute(Action run, Action fallback) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommandWithBaseCircuitBreaker(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteReader() at Microsoft.VisualStudio.Services.DelegatedAuthorization.DataAccess.DelegatedAuthorizationComponent11.GetAccessTokenByKey(String accessTokenHash, Boolean isPublic) 
 

```

**Comment by TingluoHuang** [comment]
@artisticcheese i am not sure what's that error means. you might need create case with Customer support.
does the time this Exception shows in the event view exactly same as when you config the agent?

**Comment by artisticcheese** [comment]
Yes, it's showing up when I try to join

**Comment by TingluoHuang** [comment]
@artisticcheese are you hitting this in your production environment or test environment?

**Comment by TingluoHuang** [comment]
@artisticcheese can you share your TFS version? 2017 RTM or any QU?

**Comment by artisticcheese** [comment]
Test Environment and I can see that issue with Permissions for PAT. If I enabled all permissions then it works but if I choose only "Agent Pool (read/manage)" then it refuses to connect. It's 2017 RTM Express.

**Comment by TingluoHuang** [comment]
how did you setup your TFS instance? did you restore any backup database or fresh deploy?
I will send email to our IdentityTeam, let them help take a look.

**Comment by TingluoHuang** [comment]
@artisticcheese can you also show me your IIS setting for this TFS app?
like this:
![image](https://cloud.githubusercontent.com/assets/1750815/26703375/4c1e3ba6-46f7-11e7-98a7-5ca9d1f54a6c.png)

**Comment by artisticcheese** [comment]
It was PAT mistype after after all. I just got confused why it worked under user account but not system but it was because of fallback bug you mentioned.

**Comment by TingluoHuang** [comment]
@artisticcheese  you mean type the pat wrong? you said you copy paste it? how can that be wrong?

**Comment by artisticcheese** [comment]
it was wrong but still worked because it fall back to NTLM authentication behind the scene since account which I'm logged on to my agent and VSTS server using the same username and password.
