### ISSUE TITLE
RHEL Dependencies Clarification

### ISSUE THREAD

**Issue by MarkHerhold** [Microsoft/vsts-agent#1038]
## **What's not working?** 

According to the [RHEL docs](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envredhat.md), RHEL installs need the `icu` dependency via yum. I don't see this getting installed on my machines and wonder if it's an issue.

I don't believe this is an issue, but would like to hear from the experts. 😄 Please advise.

```
sudo yum -y install libunwind.x86_64 icu
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
No package icu available.
Resolving Dependencies
--> Running transaction check
---> Package libunwind.x86_64 2:1.1-5.el7_2.2 will be installed
--> Finished Dependency Resolution
```

## **Agent version and platform**
Agent v2.119.1 running RHEL 7.2

## **VSTS type and version**
VisualStudio.com

**Comment by TingluoHuang** [comment]
@MarkHerhold 
Please try out the latest agent release
https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.0

the latest agent contains a script which should install all required dependencies for you.

**Comment by TingluoHuang** [comment]
https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.1
