### ISSUE TITLE
configuring agent via command line args on-prem

### ISSUE THREAD

**Issue by AshwiniChalla** [Microsoft/vsts-agent#104]
I have tried configuring agent by following
./run.sh --Url "http://machinename:8080/tfs" --Auth Negotiate --UserName username --Password password

But it says 
VS30063: You are not authorized to access http://machinename:8080.
Failed to connect.  Try again or ctrl-c to quit

Any help here ?

**Comment by bryanmacfarlane** [comment]
Per the readme, this preview does not cover on-prem,  It's VSTS service only.  We are currently working on integrated and Dev15 server changes to make on-prem just work

**Comment by AshwiniChalla** [comment]
Iam trying from master code. And linux onprem is working by giving inputs interactively to run.sh
what is not working is passing the same inputs as arguments.

**Comment by bryanmacfarlane** [comment]
Thanks - I just want to make it clear that *some stuff* happens to work on prem.  It's not complete yet.

Can you repro against VSTS

**Comment by AshwiniChalla** [comment]
It worked for vsts. I will wait till onprem support. thanks.
