### ISSUE TITLE
dev.sh error downloading dotnetsdk 1.0.1

### ISSUE THREAD

**Issue by JacobHenner** [Microsoft/vsts-agent#1045]
When attempting to use dev.sh, 
```

/vsts-agent/src /vsts-agent/src
./dev.sh: line 42: failed: command not found


-----------------------------------------
Ensure Dotnet SDK
-----------------------------------------
Download dotnetsdk into /vsts-agent/src/../_dotnetsdk/1.0.1
./Misc/dotnet-install.sh: line 142: VERSION_ID: unbound variable
./Misc/dotnet-install.sh: line 150: VERSION_ID: unbound variable
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.1/dotnet-sdk-1.0.1-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.1/dotnet-sdk-1.0.1-linux-x64.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed: dotnet-install.sh Failed with return code 1

```

**Comment by TingluoHuang** [comment]
@JacobHenner what's your os? the error is because it can't detect your OS from ` . /etc/os-release`

**Comment by JacobHenner** [comment]
@TingluoHuang This particular attempt was from Arch. Can the script be changed to handle unsupported distros gracefully?

**Comment by TingluoHuang** [comment]
@JacobHenner the script is coming from https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh
you can open an issue in there repository to report your problem.

**Comment by TingluoHuang** [comment]
@JacobHenner since you are on ArchLinux, i am not sure whether dotnet core 1.1 support that platform.
I think when we start adopt netcore 2.0 your platform should be supported.
