### ISSUE TITLE
Configure tags during vsts-agent setup

### ISSUE THREAD

**Issue by aqmdla2002-2** [Microsoft/vsts-agent#1046]
Nowadays, we install vsts-agent and after that, we configure tags in vsts portal.
See the possibility to configure machine tags during vsts-agent setup.

**Comment by TingluoHuang** [comment]
@chshrikh I think this is a Deployment group question?
@aqmdla2002-2  can you provide more information about the question you have?
ex, how did you config the agent? what commands you run? can you share the diag log from _diag folder under agent root directory?

**Comment by aqmdla2002-2** [comment]
We want to us Deployment group to make continuous delivery in one project.

We install the agent following the info in "Register machine". For example, for Ubuntu 16.04:

mkdir vstsagent;cd vstsagent;curl -fkSL -o vstsagent.tar.gz https://github.com/Microsoft/vsts-agent/releases/download/v2.119.1/vsts-agent-ubuntu.16.04-x64-2.119.1.tar.gz;tar -zxvf vstsagent.tar.gz;./config.sh --deploymentgroup --acceptteeeula --agent $HOSTNAME --url https://xxx.visualstudio.com/ --work _work --projectname xxx --deploymentgroupname Staging --auth PAT --token xxx --runasservice;sudo ./svc.sh install;sudo ./svc.sh start

We use Ansible to deploy the vsts agent.

The problem is that after we deploy the agent, we have to add the tags manually in the VSTS portal (Deployment Groups). It could be an improvement if we could setup the machine tags during the vsts agent deployment.

**Comment by chshrikh** [comment]
@aqmdla2002-2 this is possible.  You need to specify additional command line options =>                                 
  "--adddeploymentgrouptags --deploymentgrouptags 'SAMPLE-TAG1,SAMPLE-TAG2'"

 Your command may look like this then - 

mkdir vstsagent;cd vstsagent;curl -fkSL -o vstsagent.tar.gz https://github.com/Microsoft/vsts-agent/releases/download/v2.119.1/vsts-agent-ubuntu.16.04-x64-2.119.1.tar.gz;tar -zxvf vstsagent.tar.gz;./config.sh --deploymentgroup --acceptteeeula --agent $HOSTNAME --url https://xxx.visualstudio.com/ --work _work --projectname xxx --deploymentgroupname Staging --auth PAT --token xxx --runasservice --adddeploymentgrouptags --deploymentgrouptags 'tag1,tg2';sudo ./svc.sh install;sudo ./svc.sh start

**Comment by aqmdla2002-2** [comment]
A lot of thanks for your asssistance. This is what we need.
One last comment, I think these parameters should be documented in the help output. For example (Ubuntu 16.04):
``logiadmin@lgmadhbepswt26v:/opt/vstsagent/bin$ sudo ./Agent.Listener --help
Visual Studio Team Services Agent
Copyright (c) Microsoft Corporation

Run the agent using the convenience cmd or shell script wrappers.

Print agent version information:
Win  : .\config.cmd --version and config.cmd --commit
Unix : ./config.sh --version and ./config.sh --commit

Display command line help:
Win  : .\config.cmd --help
Unix : ./config.sh --help

Configure the agent and exit:
Win  : .\config.cmd [arguments] [options]
Unix : ./config.sh [arguments] [options]

Unconfigure the agent:
Win  : .\config.cmd remove
Unix : ./config.sh remove

Run agent interactively (must be configured):
Win  : .\run.cmd [arguments] [options]
Unix : ./run.sh [arguments] [options]


Configure Arguments:
-----------------------------------------------------------------------------
--url                  URL of the server.  Examples:
                       https://myaccount.visualstudio.com or http://onprem:8080/tfs
--auth                 Authentication type. Valid options are PAT (Personal Access Token),
                       Negotiate (Kerberos or NTLM) and Integrated (Windows default credentials)
--pool                 Pool name for agent to join
--agent                Agent name
--work                 Work directory where job data is stored.
                       Defaults to _work under the root of the agent directory.
                       Work directory is owned by a given agent and should not share between multiple agents.
--windowslogonaccount  Windows logon account name if runasservice option is chosen (Only on Windows)
--windowslogonpassword Windows logon account password if runasservice option is chosen (Only on Windows)


Remove Arguments:
-----------------------------------------------------------------------------
--auth                 Authentication type. Valid options are PAT (Personal Access Token),
                       Negotiate (Kerberos or NTLM) and Integrated (Windows default credentials)


Options:
-----------------------------------------------------------------------------
--unattended     Unattended config. You will not be prompted.
                 All answers must be supplied to the command line.
--acceptteeeula  Accept TEE end user license agreement. (Only on Linux and OSX)
--replace        Replace the agent in a pool. If another agent is listening
                 by that name, or it will start failing with a conflict.
--runasservice   Configure the agent as service. (Only on Windows, need administrator permission to configure windows service)


Arguments by Auth Type:
-----------------------------------------------------------------------------
PAT:
--token        Personal Access Token data. Best to paste value in.

Negotiate:
--username     domain\username or UPN
--password     windows account password

Integrated: does not take any additional arguments


Unattended configure and unconfigure examples:
-----------------------------------------------------------------------------
Remember to check return code when using unattended configuration
Unattend configuration for VSTS with PAT authentication
Win  : .\config.cmd --unattended --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent
Unix : ./config.sh --unattended --acceptteeeula --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent

Unattend configuration for on-premise TFS with integrated (windows) and (Linux/OSX) negotiate authentication
Win  : .\config.cmd --unattended --url http://mylocaltfsserver:8080/tfs --auth Integrated --pool default --agent myagent
Unix : ./config.sh --unattended --acceptteeeula --url http://mylocaltfsserver:8080/tfs --auth Negotiate --username DOMAIN\USER_NAME --password MyPassword --pool default --agent myagent

Unattend configuration for VSTS with PAT authentication and replace existing agent with same agent name
Win  : .\config.cmd --unattended --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent --replace
Unix : ./config.sh --unattended --acceptteeeula --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent --replace

Unattend configuration for VSTS with PAT authentication and specify agent work directory
Win  : .\config.cmd --unattended --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent --work D:\agent_work
Unix : ./config.sh --unattended --acceptteeeula --url https://myaccount.visualstudio.com --auth PAT --token <token> --pool default --agent myagent --work usr/local/agent_work

Unattend configuration for on-premise TFS with integrated authentication and configure agent as Windows service run as NetworkService
Win  : .\config.cmd --unattended --url http://mylocaltfsserver:8080/tfs --auth Integrated --pool default --agent myagent --runasservice

Unattend configuration for on-premise TFS with integrated authentication and configure agent as Windows service run as a domain account
Win  : .\config.cmd --unattended --url http://mylocaltfsserver:8080/tfs --auth Integrated --pool default --agent myagent --runasservice --windowslogonaccount DOMAIN\USER_NAME --windowslogonpassword MyPassword

Unattend unconfiguration for VSTS with PAT authentication
Win  : .\config.cmd remove --unattended --auth PAT --token <token>
Unix : ./config.sh remove --unattended --auth PAT --token <token>

Unattend unconfiguration for on-premise TFS with integrated (windows) and (Linux/OSX) negotiate authentication
Win  : .\config.cmd remove --unattended --auth Integrated
Unix : ./config.sh remove --unattended --auth Negotiate --username DOMAIN\USER_NAME --password MyPassword``

**Comment by chshrikh** [comment]
@aqmdla2002-2 now this is documented. May be with next deployment it will be available.
