### ISSUE TITLE
Unquoted path vulnerability

### ISSUE THREAD

**Issue by MichelZ** [Microsoft/vsts-agent#1048]
## **Agent version and platform**
Version of your agent? TFS2017U1, Windows
## **VSTS type and version**
TFS2017U1
## **What's not working?** 
Security Scanner (Tenable Nessus) Plugin 63155 complains about untrusted path.
https://www.tenable.com/plugins/index.php?view=single&id=63155

Please consider adding quotes to the windows service executable path here:
https://github.com/Microsoft/vsts-agent/blob/ce24a985fbf0a2825c7ccb8a43c72475dad166c4/src/Agent.Listener/Configuration/NativeWindowsServiceHelper.cs#L497

Thanks

**Comment by TingluoHuang** [comment]
@MichelZ cool, thanks for report this, do you want to create a PR to fix this?
