### ISSUE TITLE
Demand and Capabilities

### ISSUE THREAD

**Issue by tarunaroraonline** [Microsoft/vsts-agent#1049]
Is there any plan to support a check for capability does not exist? I have two types of agents, one that are using domain account and other using local service account. I have created a demand to identify domain by adding that capability to the relevant agents. I don't want to create another demand on the other agents now, I just want to add a check in my build to verify that the build gets on an agent that does not have that capability. Today it seems you can only check for exists and value when checking for capability. 

How can i route the build to agents that don't have that specific capability?

**Comment by TingluoHuang** [comment]
@tarunaroraonline i don't think you can do that today, you have to tag those agents a different capability for routing.
i will defer @bryanmacfarlane @chrisrpatterson for your feature request.

**Comment by ericsciple** [comment]
@bryanmacfarlane @chrisrpatterson to consider. closing the issue here since this is outside the scope of this repo (the agent itself). this is a limitation on the server side. user voice is a better place for this feature request: https://visualstudio.uservoice.com/forums/330519-team-services
