### ISSUE TITLE
Question: Will tasks written in Powershell ever be supported on Mac/Linux?

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-agent#1053]
Apologies if this has already been asked and answered, but I was unable to find any other issues on this topic. 

I know that today tasks have to be written in Node.js in order to be leveraged on all platforms. However, I hear that Powershell itself is now cross-platform, so are there any plans/considerations to support the ability to run tasks written in powershell on Mac/Linux? 

(This is probably the wrong place for this but...) I was also thinking it would be helpful if there could be some kind of indicator on Marketplace extensions for build/release tasks as to which platforms were supported. For example, we recently discovered that the CLI Task from the [SonarQube extension](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube) can only be executed on Windows. We didn't find out until we ran a build with the task (on a Linux based agent) and got the 'no task execution handler for your OS' error message, and after some digging found the repo on GitHub with only powershell implementations of the tasks.

**Comment by bryanmacfarlane** [comment]
task lib repo has more details.  https://github.com/Microsoft/vsts-task-lib

Right now it's node (xplat) and powershell (windows).  We are looking @ xplat powershell but we actually have more requests for writing in net core (C#).  That's probably where we will go next.
