### ISSUE TITLE
Agent doesn't automatically fetch updated tags

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vsts-agent#106]
_From @aeschli on November 17, 2015 13:12_

Tags are supposed to be immutable. Situations do occur, though, in which we must update tags. The build agent never seems to fetch the updated tags. We had to manually connect to the agent and run `git fetch --tags`.

@joaomoreno 

_Copied from original issue: Microsoft/vso-agent#152_

**Comment by aeschli** [comment]
_From @bryanmacfarlane on April 29, 2016 11:20_

Can you log this issue in the new agent?  We'll make sure the new one handles this

https://github.com/Microsoft/vsts-agent

**Comment by TingluoHuang** [comment]
@aeschli  this is the git command we run on fetch in new agent:
// git fetch --tags --prune --progress origin [+refs/pull/*:refs/remote/pull/*]

**Comment by TingluoHuang** [comment]
@aeschli can you help us confirm whether this is still an issue to you?

**Comment by joaomoreno** [comment]
We are still in the old agent, just close this, since we probably got a workaround for it.
