### ISSUE TITLE
NUnit FixtureSetup failures do not count as failures

### ISSUE THREAD

**Issue by alanmcgovern** [Microsoft/vsts-agent#1061]
Some of our test fixtures use a method annotated with [TestFixtureSetup] to perform some once-off initialisation/validation. If that setup method throws an exception, nunit will correctly mark the entire fixture as failed and not run any tests. I've attached a copy of a test run which fails in this way.

An example of a failing suite can be seen here. It is an `xml` file but i had to rename it to `txt` to upload it here: 
[failures.txt](https://github.com/Microsoft/vsts-agent/files/1130490/failures.txt)

**Comment by alanmcgovern** [comment]
As recommended by @SadagopanRajaram we're going to work around this by ensuring our process exit code indicates failure. That way we will know when we have to manually review the result xml.

I may also try to rewrite the test so that we catch the exception from the fixture-level setup and manually re-throw it inside the per-test [Setup] method. That should give us good visibility into each individual test failure. At the moment the NUnit xml is incomplete as it lists zero tests in the event of a fixture-level exception.

**Comment by bryanmacfarlane** [comment]
@alanmcgovern - doesn't seem like an agent issue (agent is generic and just runs tasks).  Is it a task or test factoring issue?

**Comment by bryanmacfarlane** [comment]
If it's a task issue log in vsts-tasks repo.

**Comment by alanmcgovern** [comment]
If you're telling me this is a task issue, then it is a task issue and i'll file it against that repository. I don't have the knowledge to answer your question :p
