### ISSUE TITLE
Allow processes which use HTTP connections selectively bypass HTTP proxy. 

### ISSUE THREAD

**Issue by JacobHenner** [Microsoft/vsts-agent#1064]
From https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#how-do-i-configure-the-agent-to-work-through-a-web-proxy-and-connect-to-team-services:

> Your build definition and scripts must still handle proxy configuration for each task and tool you run in your build. For example, if you are using a task that makes a REST API call, you must configure the proxy for that task.

However, it's not always clear what is considered a task/tool, versus functionality of the agent itself (e.g. connections to Jenkins, SVN).

Would it be possible to: 
1. Clarify the documentation linked above to demonstrate which features will use the proxy? Changes like e31a02c63215501daf573e87329b69f44f2933a4 add to the confusion, since prior to this change, Jenkins did not use the VSTS agent proxy settings, although the Jenkins connectivity is technically a feature of the agent, not a task. 
2. Allow users to bypass the proxy for either certain tasks, or certain hosts? On our network, many components of our CI/CD pipeline are hosted internally, and the proxy that allows the agent to connect to VSTS in the cloud does not permit connections to internal destinations.

(See #1037 for a related issue). 

Thank you.

**Comment by TingluoHuang** [comment]
@JacobHenner I implemented a proxy bypass list in the agent, do you want to try it out? I can give you instruction if you want to try.
 #1065

**Comment by JacobHenner** [comment]
@TingluoHuang Yes, that'd be helpful. Thank you.

**Comment by TingluoHuang** [comment]
@JacobHenner here is how you can try out:
1. git clone the repo.
2. checkout branch `users/tihuang/proxybypass`
3. run `$(reporoot)/src/dev.cmd/sh layout`
4. `$(reporoot)/_layout` will contains the full agent layout you can try.
5. when you add `.proxy` file, you can also add `.proxybypass` file, which contains lines of uri regex that you want to bypass the proxy.

`.proxybypass` sample:
```
http://mycompany.com/svnserver
http://mycompany.com/jenkins/artifacts
```

**Comment by JacobHenner** [comment]
Due to restrictions within the corporate network, I'm unable to compile
this to test. Could you possibly upload the binary package somewhere? Thanks

On Jul 7, 2017 16:29, "Ting" <notifications@github.com> wrote:

@JacobHenner <https://github.com/jacobhenner> here is how you can try out:

   1. git clone the repo.
   2. checkout branch users/tihuang/proxybypass
   3. run $(reporoot)/src/dev.cmd/sh layout
   4. $(reporoot)/_layout will contains the full agent layout you can try.
   5. when you add .proxy file, you can also add .proxybypass file, which
   contains lines of uri regex that you want to bypass the proxy.

.proxybypass sample:

http://mycompany.com/svnserverhttp://mycompany.com/jenkins/artifacts

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-agent/issues/1064#issuecomment-313785308>,
or mute the thread

**Comment by TingluoHuang** [comment]
[binary.zip](https://github.com/Microsoft/vsts-agent/files/1136784/binary.zip)
1. stop your agent
2. replace your agent's binaries under /bin folder with the .zip
3. add .proxy and .proxybypass file.
4. restart agent.

**Comment by TingluoHuang** [comment]
@JacobHenner the binary is built for 2.119.1 version agent.

**Comment by JacobHenner** [comment]
It appears to have worked. Thank you. Do you have an ETA for when it'll be
incorporated into a release?

**Comment by TingluoHuang** [comment]
Within this week i will create a github release.

**Comment by JacobHenner** [comment]
Do you have an updated timeline for release? We would like to start using
this feature in production.

Thank you.

On Jul 11, 2017 12:16, "Ting" <notifications@github.com> wrote:

Within this week i will create a github release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-agent/issues/1064#issuecomment-314496012>,
or mute the thread

**Comment by ericsciple** [comment]
@JacobHenner https://github.com/Microsoft/vsts-agent/releases/tag/v2.120.0

**Comment by TingluoHuang** [comment]
@JacobHenner I guess i can close this since 2.120.1 has been released. let me know if you need more help.

**Comment by JacobHenner** [comment]
2.120.1 is still marked as pre-release on the GitHub releases page, and
when selecting "upgrade all agents" in VSTS 2.119 is still used. When will
2.120 be considered stable and released?

On Aug 9, 2017 21:33, "Ting" <notifications@github.com> wrote:

@JacobHenner <https://github.com/jacobhenner> I guess i can close this
since 2.120.1 has been released. let me know if you need more help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-agent/issues/1064#issuecomment-321425633>,
or mute the thread

**Comment by bryanmacfarlane** [comment]
We are rolling through our early hosted build scale units and watching for issues.  When we complete that (next day or two), we will mark released.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by philip-reed** [comment]
Hi, 

I'm trying to use this proxybypass to see if it helps with this issue:

![capture](https://user-images.githubusercontent.com/7798175/49736379-e4898a80-fc81-11e8-9083-bd1e56cfbb3d.PNG)

Red redacted  = `https://hostnoTLD/WHDS.....`

The following is what I currently have in the .proxybypass file, but it appears to have no effect:
`https://hostnoTLD`

**Comment by TingluoHuang** [comment]
@philip-reed what's the back redacted? make sure it's in right format. like: `http://127.0.0.1:8080`, i am surprised your proxy server is on `https://`

**Comment by TingluoHuang** [comment]
@philip-reed what's in your `.proxybypass` file? 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=vsts&tabs=windows#specify-proxy-bypass-urls

**Comment by philip-reed** [comment]
@TingluoHuang Not sure why the proxybypass file was being ignored....but, looks like someone had added HTTP_PROXY & HTTPS_PROXY environment vars which shouldn't have been there.  So have removed them and my build is now working.  

Thanks.
