### ISSUE TITLE
Stopping agent running as a service Linux and OSX does not "disconnect" from the queue right away

### ISSUE THREAD

**Issue by stiliev** [Microsoft/vsts-agent#107]
I was able to stop the service on both Ubuntu and Centos with this command: “sudo systemctl stop service_name”. However the web UI did not immediately change the status to offline and the log file is not flushed, which makes me think it was not a clean exit.

**Comment by bryanmacfarlane** [comment]
I saw the same on OSX in my testing.  Update title to OSX as well.  I think it's in the js host


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bryanmacfarlane** [comment]
If you look at the current agent, on shutdown (ctrl-c), I believe it deletes the session.
