### ISSUE TITLE
Agent haven't found MSBUILD 15

### ISSUE THREAD

**Issue by gandarez** [Microsoft/vsts-agent#1073]
## **Agent version and platform**
Agent 2.112.0
Windows Server 2016
On-Prem TFS 2017.1

## **What's not working?** 
After installed Visual Studio Build Tools 20017 (MSBUILD 15) the Agent haven't found it. 

![image](https://user-images.githubusercontent.com/782854/28131416-2e374298-6710-11e7-8ef1-30d5d823de4e.png)
![image](https://user-images.githubusercontent.com/782854/28131371-0f07f0ca-6710-11e7-8867-6379b06f40ee.png)
![image](https://user-images.githubusercontent.com/782854/28131557-9fb6030a-6710-11e7-91d6-fd30c4512254.png)

**Comment by gandarez** [comment]
After looking at registry I realized there's only MSBuild 4.0 registered, so my question is why Visual Studio Build Tools 2017 didn't write correctly there?

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\4.0

**Comment by TingluoHuang** [comment]
@gandarez Can you run `"{your agent root}\externals\vswhere\vswhere.exe" -all` and paste the result? VS is playing hidden and seek with us. :D

**Comment by ericsciple** [comment]
The task was updated in tfs 2017 u2 with a fix. The workaround is to specify the location to msbuild or I can send you an updated task zip that you can upload to your server.

**Comment by ericsciple** [comment]
fyi VS 2017 doesnt write the registry keys since it supports side by side installs within the same major version. It has a different interface for finding the location of VS (COM API), or a tool like vswhere.exe which is a wrapper over the COM API.

**Comment by gandarez** [comment]
@TingluoHuang there's no vswhere folder under the path you metioned

![image](https://user-images.githubusercontent.com/782854/28137464-c5e98c28-6723-11e7-9818-e4b57a8c7285.png)

**Comment by gandarez** [comment]
@ericsciple please send to my email address;
