### ISSUE TITLE
Agent does not find VS Test Agent 2017

### ISSUE THREAD

**Issue by gandarez** [Microsoft/vsts-agent#1076]
## **Agent version and platform**
Agent 2.117.2
Windows Server 2016
On-Prem TFS 2017.1

## **What's not working?** 
Related issue #1073 

It successfully found MSBUILD 15 but didn't find VS Test Agent 2017. The strange thing is that the version 2.112.0 found it.
Is there a trick to get it working? Or should I input the capability manually?

**v2.112.0**
![image](https://user-images.githubusercontent.com/782854/28165664-23ad89c2-67ab-11e7-97a4-26e63f463aac.png)

**v2.117.2**
![image](https://user-images.githubusercontent.com/782854/28165685-3681fd3a-67ab-11e7-9b4e-95c20f525a90.png)

**Comment by gandarez** [comment]
Also tried the latest version 2.119.1 and the same "problem" happens

**Comment by gandarez** [comment]
I manually input as user capability and it has worked.

**Comment by ericsciple** [comment]
@gandarez do you have multiple installations of VS 2017?

**Comment by gandarez** [comment]
@ericsciple No, just one and actually it's just build tools.

**Comment by nigurr** [comment]
@gandarez I do see only VS 2017 is installed. Can you please run this in your machine and paste the output https://github.com/Microsoft/vswhere/releases/download/1.0.71/vswhere.exe

**Comment by gandarez** [comment]
@nigurr all installations related to Visual Studio 2017 shows up as Visual Studio 2017 only.

![image](https://user-images.githubusercontent.com/782854/28212669-e679ceca-6878-11e7-9448-72b563309df8.png)


```
C:\Inst>vswhere.exe -all
Visual Studio Locator version 1.0.71 [query version 1.10.80.60812]
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by nigurr** [comment]
@gandarez Currently we are not supporting Test agent as vstest capability.
To unblock, you need to add vstest capability manually. We already have backlog item to fix this.

**Comment by gandarez** [comment]
@nigurr Strangely in another try it included automatically "vstest" capability. I was using version 112.
