### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#1078]
Based on discussions int he internal ALM Champs channels:

It would be lovely if the SDK and the Agent would work together to expose web proxy information that is important for that agent. This allows task developers to correctly pass that information to the tools they execute or set the required environment variables.

My idea would be that it'd be possible to configure a Service Endpoint with the proxy URL and credentials. Then have the ability to set the default proxy endpoint at the agent level in the UI or in the agent when installing it. The VSTS-Task-Lib could then give us access to the endpoint through a well known service endpont (akin to the VSSServiceEndpoint, like VSSProxyEndpoint).

I understand this must go hand-in hand with the agent itself, so I'll post a similar issues in both repositories.

Related VSTS-Task-Lib issue: https://github.com/Microsoft/vsts-task-lib/issues/269

**Comment by bryanmacfarlane** [comment]
The agent already supports proxy config.  See documentation.

**Comment by rlrhuisman** [comment]
Proxy support for the agent is only for the agent itself. This is about the custom tasks that are build for the agent. E.g. if a custom task needs to query vsts rest services, it needs the same proxy settings to reach the vsts environment as the agent itself executs.

**Comment by bryanmacfarlane** [comment]
Yes, and that's why there's a PR in the task lib - so tasks have access to proxy config - done once
