### ISSUE TITLE
Unattened VSTS Agent install - Force use of config

### ISSUE THREAD

**Issue by tarunaroraonline** [Microsoft/vsts-agent#1089]
I am trying to use the unattended install of VSTS Agent, is there any way to associate a web proxy when calling the .\config.cmd with the parameters or just before it to ensure that the configuration goes via the specific web proxy? 

For context, i am calling this through a custom script extension in an ARM template, unfortunately the machine is provisioined and domain jointed but since this step is run through the local account doing the ARM template deployment it does not pick up the proxy by itself. 

``` PowerShell
# Retrieve the path to the config.cmd file.
$agentConfigPath = [System.IO.Path]::Combine($agentInstallationPath, 'config.cmd')
Write-Verbose "Agent Location = $agentConfigPath" -Verbose
if (![System.IO.File]::Exists($agentConfigPath))
{
    Write-Error "File not found: $agentConfigPath" -Verbose
    return
}

# Call the agent with the configure command and all the options (this creates the settings file) without prompting
# the user or blocking the cmd execution

Write-Verbose "Configuring agent" -Verbose

# Set the current directory to the agent dedicated one previously created.
Push-Location -Path $agentInstallationPath

.\config.cmd --unattended --url $serverUrl --auth PAT --token $PersonalAccessToken --pool $PoolName --agent $AgentName --runasservice

Pop-Location
```

**Comment by TingluoHuang** [comment]
@tarunaroraonline https://github.com/Microsoft/vsts-agent/blob/9869a1f9d81115bebcc480d4c228c505be0df8a3/docs/design/proxy.md#configuration

As long as you follow the doc create a `.proxy` file before you call ./config.cmd in your script, the config will follow the proxy.

**Comment by tarunaroraonline** [comment]
Yup adding.proxy and zipping the file fixed the issue.
