### ISSUE TITLE
PATH being overridden

### ISSUE THREAD

**Issue by anweiss** [Microsoft/vsts-agent#109]
I'm currently running the agent in a Docker container and modifying the PATH environment variable in my Dockerfile follows:

```
ENV PATH "$GOPATH/bin:/usr/local/go/bin:$PATH"
```

If I `/bin/bash` in to the container, I can verify that the PATH is set correctly. However, the actual build tasks themselves seem to be using a different PATH and overriding what my image sets for PATH. The overriding path is as follows as viewed from the Agent Capabilities listing:

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

This requires me to use the fully-qualified path to any executales I run in a Build task.

I'm using v2.99.0-0428 of the agent but this also occurred with v0.7.

Thanks

**Comment by bryanmacfarlane** [comment]
Agent or tasks doesn't set or override path.  Are you running interactively or as a service?

**Comment by anweiss** [comment]
Interactively

**Comment by bryanmacfarlane** [comment]
Ignore PATH in the capabilities.  That does not represent run time.  It's config time and we actually shouldn't be registering PATH as a cap

A more interesting test is to add a command line task and run env or echo $PATH.  Either that or a shell script task that does the same

**Comment by anweiss** [comment]
So here's the PATH that gets displayed when I run `env` in a command line task:

```
2016-05-01T20:24:53.1095510Z PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

And here is the PATH when I run `env` directly from within the same container that is executing the build:

```
PATH=/opt/buildagent/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

So I'm not sure where the first PATH is coming from...which is what is overriding my desired PATH behavior.

**Comment by danbridgellc** [comment]
I just verified my build using same approach as @anweiss and the PATH output in build process does match my PATH setting.

I am running agent as a service on OS X

Any suggestions to have the correct PATH value picked up by build process?

**Comment by anweiss** [comment]
Hey @danbridgellc, so does your PATH output in the build process indeed match that of your intended PATH setting? Your last statement seems to contradict this...not sure if you meant to say "does not match"...

**Comment by danbridgellc** [comment]
sorry you are correct - it DOES NOT match!  sorry for typo

**Comment by danbridgellc** [comment]
so digging into things, I just found that the agent uses a .plist file (at least when it is set to run as a service) and it has Environment variable section...I set the PATH env variable to see if it affected the build and it in fact does!  So while not ideal, I can set the PATH in that .plist file and my build now executes completely!

The path to the .plist file for me is $HOME/Library/LaunchAgents

Hope that might help for now...

**Comment by bryanmacfarlane** [comment]
@danbridgellc - that's correct.  when you say yes to svc, we simply create osx service plist and call launchctl to start.  That plist has the end.  That's why I asked @anweiss if running as svc but he said interactive.

In node agent, we would snapshot your current env into the plist.  Not perfect since it doesn't get updates.  I will make that change in this agent and output to console when configuring as a svc where to change.

But, that still doesn't explain what @anweiss is seeing.  Investigating ...

**Comment by dbeattie71** [comment]
I've been trying to figure out how to set the path as well since the Xamarin.iOS build step can't find nuget.  Adding a Command Line step env outputs PATH=/usr/bin:/bin:/usr/sbin:/sbin.  I'm running as a service.

**Comment by bryanmacfarlane** [comment]
@dbeattie71 - yes, that is how to manage the path when running as a svc.  You then need to stop the service (./svc.sh stop ... wait for red in admin console) and then start it (./svc.sh start).  Did that work for you?

**Comment by dbeattie71** [comment]
Yes it did, thanks.

**Comment by bryanmacfarlane** [comment]
Cool.  I'll use this issue to populate the initial plist with the current env to avoid that in most cases.

@anweiss - qq - you mentioned docker.  Do you have the issue if you run interactive outside of docker (from plain cli, no service).  Trying to tease the issues apart here.  thx

**Comment by stiliev** [comment]
@anweiss I could not make a repro using the info from your first post. I tested with an interactive agent (not running as a service) built from the latest code on master and run it on Ubuntu 14.04. I made a build with two tasks: a "Command line" and a "Shell script". In the task scripts I called "env" that prints an environment identical with the agent environment.
We need more info to narrow down. Is it possible Docker is relevant to the issue? Maybe you can try just plain Ubuntu to see if the issue will go away.

**Comment by anweiss** [comment]
hey @bryanmacfarlane and @stiliev ... after a bit more digging, I found that when running the agent in interactive mode on the host itself, it picks up the updated `PATH` variable without issue. So it seems to be specific to how the agent reads the `PATH` from within a Docker container.

A `docker inspect` shows the `PATH` as I intend it. And more so, if I display the `PATH` from within a Bash shell in the container, it displays the `PATH` correctly. However, when the agent runs as part of a build task and displays the `PATH`, it is different than what `docker inspect` shows.

**Comment by stiliev** [comment]
To summarize:
- PATH has not been overridden for interactive agents running on OSX, Linux, Windows.
- we added ability to set the PATH for OSX, Linux agents running as a service with PRs https://github.com/Microsoft/vsts-agent/pull/118 https://github.com/Microsoft/vsts-agent/pull/99
- There is an issue with PATH overridden when agent is running in Docker. We do not test or officially support Docker for now, so I'm not able to track this issue down.

**Comment by bryanmacfarlane** [comment]
Just to clarify - it's not that we don't support Docker.  It's that we aren't providing a Docker solution.  You are free to create one.  Whats clear here is we aren't overriding the PATH and we're persisting in the plist correctly.
