### ISSUE TITLE
Project name with spaces causes install script to fail.

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/vsts-agent#1091]
## **Agent version and platform**
**Latest**
**Linux**
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
Project not found, need to type it by hand.
<br>

It's simple:

--work _work --projectname My Project

that line is executed as "My"

So then it's not found, thankfully, and so it asks for projects name, then type My Project and works without any issue.

Should the script include the project's name inside quotes? Would that work?

Cheers

**Comment by hir0pr0tagonist** [comment]
--work _work --projectname "My Project" ?

**Comment by andreujuanc** [comment]
I know, but that's the script that's being generated in visualstudio.com 
Obviously I can manually change it, but why not just include those quotes by default? 

:)

**Comment by ericsciple** [comment]
Makes sense. I'll fwd this along to the appropriate team. It's not an issue with the agent (this repo) so i'm planning to close the issue here after I fwd.

**Comment by andreujuanc** [comment]
@ericsciple I see! Thanks.

**Comment by chshrikh** [comment]
@andreujuanc this has been fixed, with next deployment you will see the project name will have quotes by default. Thanks

**Comment by andreujuanc** [comment]
<3
