### ISSUE TITLE
Temporary keychain cannot be added

### ISSUE THREAD

**Issue by hir0pr0tagonist** [Microsoft/vsts-agent#1094]
## **Agent version and platform**
Version of your agent? 2.119.1
<br>
OS of the machine running the agent? OSX Sierra 10.12.5
<br>
## **VSTS type and version**
VisualStudio.com
<br>

## **What's not working?** 
After a new setup of OSX, and a fresh installation of the agent, an iOS build fails with the error message "Failed to add the temporary keychain to the keychains search path."
The preceding commands appear to succeed without errors. Noteworthy: the command 

/usr/bin/security list-keychain -d user

results in a different keychain being listed when run from the agent/buld process, than when run "interactively" from the shell in OSX. Both processes, however, are run as the same user in OSX !!!
Please see attached screenshots.

I have not added any certificates to either the login, or the system keychain. I am relying on the agent's XCode build task to handle this for me - is this assumption correct ?

<br>
## **Agent and Worker's diag log**
<br>
Nothing relevant in the logs related to this error...

![xcode_build_agent](https://user-images.githubusercontent.com/2031896/28569086-9d9c6866-7138-11e7-9651-0c3bee5623d7.png)

![shell_commands](https://user-images.githubusercontent.com/2031896/28569122-cb3347b8-7138-11e7-9def-90f4448ea57a.png)

![build_task](https://user-images.githubusercontent.com/2031896/28569250-60ae4054-7139-11e7-9165-054d0f80e1f8.png)

**Comment by bryanmacfarlane** [comment]
This is not an issue with the agent.  It's generic.  Perhaps you want to create an issue in the vsts-tasks repo

**Comment by hir0pr0tagonist** [comment]
How is this generic when the same command, executed ostensibly under the same user account (!), produces two different results ? In other words, it references two different keychains. 
I can see how the command sequence is handled in the VSTS task - but clearly its execution is the responsibility of the agent, and this is where the problems lie.  It has something to do with the context in which the agent process runs - I'll investigate on my own.

**Comment by Fizcko** [comment]
@hir0pr0tagonist i have the same results as you. Do you find something ?
