### ISSUE TITLE
Agent calling wrong URL

### ISSUE THREAD

**Issue by Alluca82** [Microsoft/vsts-agent#1101]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Yes

## Agent version and platform
Version of your agents: 2.117.2 and 2.119.1 + (1.105.7)

OS of the machine running the agent?
Windows Server 2012 R2

## VSTS type and version
On-Prem TFS2017 Update 2

## What's not working?
When starting a build the agent - this screen comes - the queue only contents the new job

![image](https://user-images.githubusercontent.com/15999640/28716540-28621240-739e-11e7-860b-b29b199876d1.png)

Nothing happing and after 10 min the job are stopped.

It looks like the called url (see in file "Worker-log.txt") to TFS are without the port, which make the call fail...

If I make this call (http://ServerName/tfs/DefaultCollection/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1) in Fiddler I get status 404.
But if I add the port 8080 - I get status 200

In the agent log the call got 8080 in it (http://ServerName:8080/tfs/_apis/distributedtask/pools/1/messages?sessionId=eb3ff9fb-022c-403e-8d1e-51ec7680a967&lastMessageId=2), but get status 202

The same build job works fine on build agent version 1.105.7

## Agent and Worker's diag log
[Worker-log.txt](https://github.com/Microsoft/vsts-agent/files/1183073/Worker-log.txt)
Agent-log can be submitted on request... need to do some cleaning first

**Comment by bryanmacfarlane** [comment]
If you open the TFS admin console, what is the notification url and server url set to?  What url is the agent configured with (in .agent)

**Comment by Alluca82** [comment]
Where do I find these setting... I got these on the "Application Tier"
![image](https://user-images.githubusercontent.com/15999640/28719057-d8290aa8-73a8-11e7-8625-3f94fba7e59a.png)

url in agent: http://MachineName:8080/tfs/

**Comment by bryanmacfarlane** [comment]
What's the value of public URL?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Alluca82** [comment]
Public URL: http://tfs.skdev.sdc.dk/tfs

**Comment by TingluoHuang** [comment]
#1133

**Comment by TingluoHuang** [comment]
@Alluca82 this should be fixed with latest agent release, please give a try.

**Comment by Alluca82** [comment]
@TingluoHuang Thanks version v2.120.2 worked ;)
