### ISSUE TITLE
Multiple build agents on same machine (did work with build agent 1.x)

### ISSUE THREAD

**Issue by pekkah** [Microsoft/vsts-agent#1102]
## Agent version and platform
Windows Server 2012 R2, agent version: '2.119.1

## VSTS type and version
VisualStudio.com

## What's not working?
Cannot configure multiple build agents on same machine

## Description
When running config.cmd I'm getting a "Cannot configure the agent because it is already configured. To reconfigure the
agent, run 'config.cmd remove' or './config.sh remove' first." error.

I tried this by extracting the second agent to different folder from the first one. With build agent 1.x we had three agents running on same build machine. Is this not supported anymore?

**Comment by kirkone** [comment]
Hi,

you can run multiple agents on the same mashine but you have to use a sepereate folder for each agent. Also the work folder must be seperate for each agent.

Greetings, KirK

**Comment by pekkah** [comment]
After reboot I could configure second agent. No idea what changed.
