### ISSUE TITLE
How to close agent after work is done?

### ISSUE THREAD

**Issue by kirkone** [Microsoft/vsts-agent#1103]
Hello,

I am fiddling around with build agents in docker and my target is to get a fresh agent every time.
Running the agent in Docker for Windows works as expected but the agent keeps running after a build i finished.

My question is: **Can I force the agent to shutdown after his first job is finished**?

Thanks for your help.
KirK

**Comment by TingluoHuang** [comment]
https://hub.docker.com/r/microsoft/vsts-agent/

**Comment by kirkone** [comment]
@TingluoHuang thanks for the answer, but I do not understand.

I use this image already but this agent also keeps running after finishing his work. Maybe I got something wrong.

What I want to achieve is the same behavior like the hostet agents in VSTS. I start an agent, The agent waits for a job. After the job is done the agent should close. So my Docker environment can provide a new agent.

thanks,
KirK

**Comment by TingluoHuang** [comment]
@kirkone what's docker command you run? if you just `docker run`, the agent should got unconfigure after every build.

**Comment by kirkone** [comment]
I run the container with
```
docker run -e VSTS_ACCOUNT=kirkone -e VSTS_TOKEN=xxxx...xxxx
qvkopq -it kirk/vsts-agent:windows-10.0.14393
```
and the agent keeps waiting for new jobs after finishing the first one.

**Comment by TingluoHuang** [comment]
@kirkone sorry, i was misunderstand your question, since VSTS machine management service provide similar feature for our hosted build. I don't think the agent has ability to stop after every job at this point.
What's the reason you want a fresh agent for every build? are you not only care about the working folder of each build?

**Comment by kirkone** [comment]
the reason behind this is that people tend to break our agents by installing custom programs at build time. For example the install a new version of npm global and than other projects will fail on our "shared agents".
I thought it would be a good idea to start with a fresh copy every time.
Maybe it is a better idea to solve the root cause of our problems by convince the people not to do such things.

Regardless, I think a "use only one time" switch can provide some extra benefits to the agents in general. I'm not experienced with such things but I will try to provide a PR for this if you want.

Thank you very much,
KirK

**Comment by TingluoHuang** [comment]
@kirkone we have the concept of running each job inside a docker container. i think that should give you most of the isolation you want.
We have a doc here: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/runtaskindocker.md

**Comment by kirkone** [comment]
looks promising, I will have a look.
Thank you
