### ISSUE TITLE
FilePath input is not prepended by source directory for windows agent

### ISSUE THREAD

**Issue by AshwiniChalla** [Microsoft/vsts-agent#111]
FilePath input(vsts-task) is expected to be prepended by source directory.
This happens in case of linux agent but not for windows agent.
for example, filepath "resultFiles\a.xml" is supposed to be chanaged as "C:\buildDir\_work\1\s\resultFiles\a.xml"
To repro create a build definition with publish test results task which has 'testResultsFiles' a filePath input
From debug logs you can find the difference between how it is prepended for linux and not for windows agents.

**Comment by bryanmacfarlane** [comment]
very odd.  Same code -- hmmm.  Ting, can you investigate?

**Comment by TingluoHuang** [comment]
@AshwiniChalla what is your repo type? git or tfvc?

**Comment by AshwiniChalla** [comment]
git repo

**Comment by TingluoHuang** [comment]
@AshwiniChalla Can you share a repro? or an agent diag log + definition JSON.

**Comment by bryanmacfarlane** [comment]
She said windows box.

**Comment by TingluoHuang** [comment]
#197 should fix this.
