### ISSUE TITLE
default tfs 2017.2 agent (2.112.0) is not finding VS buildtool 2017 (15.3.0)

### ISSUE THREAD

**Issue by Tasteful** [Microsoft/vsts-agent#1140]
## Agent version and platform
Version of your agent? 2.112.0

OS of the machine running the agent? Windows Server 2012r2

## VSTS type and version
VisualStudio.com or On-Prem TFS? On-Prem TFS 2017.2

## What's not working?
Default VSTS-Agent (that is shipped with TFS 2017.2) is not finding the msbuild 15.3 that is shipped with VS Build Tool 2017 (15.3).

With the new 15.3 release today the VS BuildTool version string is `15.3.26730.3` and that is not matching the minor version here https://github.com/Microsoft/vsts-tasks/blob/c18988a1e02681e95ec85dc4b0a28766ce8f0e50/Tasks/Common/MSBuildHelpers/PathFunctions.ps1#L328

Workaround was to comment out ` -and $_.Version.Minor -eq 0 ` from above file `{agent root}\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.0.49\ps_modules\MSBuildHelpers\PathFunctions.ps1`.

**Comment by ericsciple** [comment]
can you try the latest agent https://github.com/Microsoft/vsts-agent/releases

**Comment by ericsciple** [comment]
Nevermind it looks like the issue you hit is with the task (vsts-tasks repo, not this repo). The task has been fixed in master and released with later updates.
