### ISSUE TITLE
Is VSTS Agent Extension Azure VM compatible with TFS on premise?

### ISSUE THREAD

**Issue by LockTar** [Microsoft/vsts-agent#1141]
I want to use the VSTS Agent Extension in Azure. I created an ARM template for this but gives a strange error. The only issue related to this is #1044. I can't find any documentation about it. 

I get the detailed message:
_Enable failed for plugin (name: Microsoft.VisualStudio.Services.TeamServicesAgent, version 1.12.0.0) with exception Command C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.12.0.0\enable.cmd of Microsoft.VisualStudio.Services.TeamServicesAgent has exited with Exit code: -1_

We are using Team Foundation Server 2017 Update 1. We are planning to upgrade to Update 2 very soon. 

Is it compatible with one of those versions?

**Comment by chrisrpatterson** [comment]
@LockTar  that extension is for Deployment Groups and TFS 2017 Update 1 does not support that feature.

**Comment by Cristie** [comment]
@LockTar Learn more, https://www.visualstudio.com/en-us/docs/build/concepts/definitions/release/deployment-groups/#deploy-agents-to-a-deployment-group

**Comment by LockTar** [comment]
Any suggestion in which version of TFS this is supported? As I said, we are about to update to Update 2. Or will it be supported in Update x? Thanks

**Comment by nschonni** [comment]
@LockTar it's at the top of the page @Cristie included

 > At present, deployment groups are not available in Team Foundation Server.
