### ISSUE TITLE
Missing capabilities after upgrading to Visual Studio 2017 15.3

### ISSUE THREAD

**Issue by mbp** [Microsoft/vsts-agent#1142]
Agent version 2.116.1
Windows Server 2016
VSTS type: VisualStudio.com

## What's not working?
After upgrading to Visual Studio 2017 15.3 on build server and re-starting agent, build fails with:

    No agent could be found with the following capabilities: DotNetFramework, msbuild, visualstudio, vstest

It would appear the visualstudio and vstest capabilities are gone missing, I had to add them manually as user-defined capabilities.

## Agent and Worker's diag log

Comparing logs before and after upgrade, it appears that the vswhere command no longer gives any output:

```
[2017-08-15 08:08:45Z INFO PowerShellCapabilitiesProvider] STDOUT: & C:\agent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe -version '[15.0,15.1)' -latest -format json
[2017-08-15 08:08:45Z INFO PowerShellCapabilitiesProvider] STDOUT: []
```

**Comment by TingluoHuang** [comment]
@mbp update to latest agent version should fix the problem for you. the latest VS release change it's versioning convention. before, it's always 15.0.1, 15.0.2, 15.0.3, 15.0.x. However, from 15.3, it change to use the minor version .15.3, 15.4, 15.5...

**Comment by mbp** [comment]
Thanks, that did the trick.

I did not think there was a newer version, since the Releases page here on GitHub says 2.120.2 is a pre-release.
