### ISSUE TITLE
How can I update historical build artifacts (artifactlocation, downloadUrl) following a server move?

### ISSUE THREAD

**Issue by mayeager22** [Microsoft/vsts-agent#1144]
My build artifacts are being moved from one fileshare \\ULYSSES\DevOps to a new fileshare \\archives\DevOps.

While I was able to update the build definition to make subsequent builds go to this new location, my already completed builds are still holding on to the old drop location. 

Is there a way I can update these through Rest API?

## Agent version and platform
Version of your agent? 1.104.0

OS of the machine running the agent? Windows

## VSTS type and version
On-Prem TFS

If On-Prem TFS, which release, 2017 Update 1 RTM?

## What's not working?
Rest API call to get build artifacts still shows old location.

{"count":2,"value":[{"id":177,"name":"ManageAccountingService_20170622.1","resource":{"type":"filepath","data":"\\\\ulysses\\DevOps\\ManageAccountingService","properties":{"artifactlocation":"\\\\ULYSSES\\DevOps\\ManageAccountingService"},"url":"http://tfs-prod-01:8080/tfs/TCDRS/da3aa702-f996-40c1-987a-4ff44bbe01b0/_apis/build/builds/2174/artifacts?artifactName=ManageAccountingService_20170622.1","downloadUrl":"file://ulysses/DevOps/ManageAccountingService"}},{"id":179,"name":"build.SourceLabel","resource":{"type":"TfvcLabel","data":"ManageAccountingService_20170622.1","url":"http://tfs-prod-01:8080/tfs/TCDRS/da3aa702-f996-40c1-987a-4ff44bbe01b0/_apis/build/builds/2174/artifacts?artifactName=build.SourceLabel","downloadUrl":"http://tfs-prod-01:8080/tfs/TCDRS/_apis/tfvc/items/ManageAccountingService_20170622.1?api-version=1.0&$format=zip&fileName=build.SourceLabel"}}]}

There are 2 of them because I have a "Debug" and a "Release" configuration built.

**Comment by TingluoHuang** [comment]
@mayeager22 I don't think we have that REST Api at this point. You can use https://visualstudio.uservoice.com/forums/330519-team-services to provide feedback for the service. I am going to close this issue, since it's not scope to a 2.x vsts-agent issue.
