### ISSUE TITLE
Doesn't create a working build with VS 15.3.1

### ISSUE THREAD

**Issue by MikeYeager** [Microsoft/vsts-agent#1153]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
yes I have

## Agent version and platform
Version of your agent? 2.102.0/2.100.1...
2.120.1

OS of the machine running the agent? OSX/Windows/Linux...
Win 8.1 Enterprise

## VSTS type and version
VisualStudio.com or On-Prem TFS?
On-prem TFS

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
2017 RTM

If VisualStudio.com, what is your account name? http://account.visualstudio.com

## What's not working?
Please include error messages and screenshots
The standard "Visual Studio Build" still doesn't work for VS 2017 (15.3.1). After installing this latest agent I now see MSBuild 15.0 under capabilities, and the path looks right, but it said 15.0 was not found and reverted to 14.0 when I ran the build. the build failed because I'm using C# 7 features. I had to replace the VS Build task with an MSBuild task in order to get it to work.

## Agent and Worker's diag log
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@MikeYeager I thinks this is a known task issue for VS 15.3. There was a breaking versioning changes in VS since 15.3 which break the logic in the task we have to find VS. I guess the latest 2017 QU should has the fix, @ericsciple can confirm.

VS used to version there stuff 15.0.1/15.0.2/15.0.3/etc.
from 15.3, VS start version 15.3.0/15.3.1/15.3.2/etc.

**Comment by ericsciple** [comment]
Yep the workaround is use the msbuild task and specify the location (radio option).

[The fix](https://github.com/Microsoft/vsts-tasks/commit/7affcc0f508635ee299a094844a6143315cff0dd) is in TFS 2017 U2. Another workaround would be to apply the fix to the tasks in the agent cache (`_work/_tasks/...`).
