### ISSUE TITLE
Can't find CryptoInitializer DLL on OSX

### ISSUE THREAD

**Issue by ColinDabritzViewpoint** [Microsoft/vsts-agent#116]
After entering a VSTS URL and Personal Access Token, the setup process running ./run.sh fails with "System.Net.Http.Curlhandler" threw an exception.

In the diag log file, the stack trace ends at 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified Module could not be found.
at Interop.CryptoInitialzier.EnsureOpenSslInitialized()
etc.

The URL is HTTPS, so OpenSsl certainly should be in play. Perhaps a missing component?

I'm running preview 2, from vsts-agent-darwin-2.99.0-0428.tar.gz

I can provide more if it would be helpful, although the error line was pretty specific about the missing DLL.

**Comment by NanosoftDK** [comment]
Your problem is described here: #110 
also look here https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/latebreaking.md

**Comment by bryanmacfarlane** [comment]
Yep.  Thanks @NanosoftDK !

**Comment by ColinDabritzViewpoint** [comment]
Good find, I'm looking at version 0.9.8zh shipped 14 Jan 2016.

I'm somewhat hesitant to update a core OS component like this, the system is up to date as far as Apple updates are concerned. Moving forward what is the intent for support/requirements for decencies like this?

Thanks much.

**Comment by bryanmacfarlane** [comment]
Ideally, I would like for the install instructions to have no dependencies (apt-get, brew etc...).  I agree on your hesitations.  We will see how close we can get.  Thanks for confirming and dogfooding!
