### ISSUE TITLE
After upgrading VS2017 to Version 15.3.1, it has disappeared from the Capabilities list of the agent

### ISSUE THREAD

**Issue by LarsOleKMD** [Microsoft/vsts-agent#1167]
## Agent version and platform
Agent.Version 2.112.0 
win 2012 R2
On-Prem TFS  2017 UP 1

## What's not working?

After upgrading VS2017 to Version 15.3.1, it has disappeared from the Capabilities list of the agent
The previous of VS2017 is worked

Build says No agent could be found with the following capabilities: msbuild, visualstudio

**Comment by bryanmacfarlane** [comment]
Download latest agent.  Fixed in later version.  Latest fine to use with on prem

**Comment by greadtm** [comment]
We are upgrading from TFS 2017 Update 1 to Update 2 next week. Is this fix included in agent version 2.1220.0? Is it safe for us to upgrade to 2.122.0 TFS on premise?

**Comment by bryanmacfarlane** [comment]
Yes, it's safe to use latest 2.x with TFS on premises >= 2017

**Comment by bryanmacfarlane** [comment]
And yes, it has the fix.  VS changed it's version reporting format so the later agent version reacted.

**Comment by LarsOleKMD** [comment]
Yes the agent can see VS2017 again, and build. 
But there is a problem with building "code UI test" project, if I open project in VS2017 on the buld server can i build the manual, some references is lose when the agent run it
