### ISSUE TITLE
Azure App Service Deploy Task Question - Multiple Sites 

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vsts-agent#1172]
Hello

I am sure I am missing something obvious.

Is there an easy way to deploy to multiple resources groups or sites with out having to create 100 tasks?

Our current setup...

A number of resources groups each have a separate portal in them.  Need to create release process that deploys a new build to all the resource groups.  I could create a separate task for each site however that becomes unmanageable after a few sites :)

As said I am sure I am missing something obvious.

From

Russell

**Comment by bryanmacfarlane** [comment]
Please create an issue in the vsts-tasks repo

**Comment by russelldyas** [comment]
Apologies thought I had..  I must of had a senior moment
