### ISSUE TITLE
Can't connect. Execution stays in Conneting to server...

### ISSUE THREAD

**Issue by rodrigomocca** [Microsoft/vsts-agent#1173]
I'm trying to configure a new Deployment agent.
I'm behind a proxy, but I've copied the .proxy file to the agent root folder.
The script execution stays in Connecting to server....
What can I do?

**Comment by TingluoHuang** [comment]
@rodrigomocca can you share your agent diag log?

**Comment by stephenmichaelf** [comment]
@rodrigomocca Please reopen if you are still facing this issue.
