### ISSUE TITLE
failed to register machine to Deployment Group windows server 2008

### ISSUE THREAD

**Issue by 8bitreid** [Microsoft/vsts-agent#1174]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Failed to load the dll from [C:\vstsagent\A1\bin\coreclr.dll], Hresult: 0x8007007f
Failed to bind to CoreCLR at 'C:\vstsagent\A1\bin\coreclr.dll'
## Agent version and platform
Version of your agent? 2.102.2

OS of the machine running the agent? OSX/Windows/Linux...
Windows Server 2008 r2

## VSTS type and version
VisualStudio.com

quantros.visualstudio.com

## What's not working?
Please include error messages and screenshots
Failed to load the dll from [C:\vstsagent\A1\bin\coreclr.dll], Hresult: 0x8007007f
Failed to bind to CoreCLR at 'C:\vstsagent\A1\bin\coreclr.dll'

## Agent and Worker's diag log
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@8bitreid make sure you are on 2008 R2 SP1

**Comment by TingluoHuang** [comment]
https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0-supported-os.md

**Comment by 8bitreid** [comment]
@TingluoHuang I am on Server 2008 R2 SP2
![2017-08-30 12_54_16-systeminfo](https://user-images.githubusercontent.com/9111792/29884768-79a5806c-8d82-11e7-8651-0cdfce8e1dba.png)

**Comment by nschonni** [comment]
Service pack 2, means you're on R1, not R2

**Comment by 8bitreid** [comment]
Not supported OS.
