### ISSUE TITLE
Support V2 agent for windows with TFS2015

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vsts-agent#1186]
![image](https://user-images.githubusercontent.com/15381181/29999133-1a63abac-900b-11e7-85ce-6d97c425709d.png)

**Comment by bryanmacfarlane** [comment]
What issue are you having where you need the 2.x agent with 2015?

**Comment by TingluoHuang** [comment]
@StingyJack also the limitation is not actually on the agent side, it's the windows tasks we shipped in TFS2015. Those tasks are not good authored and taking hard dependency on the 1.x agent.

**Comment by StingyJack** [comment]
I couldn't run VS 2017 or MSBuild 15 compilations on our TFS 2015 server without a bunch of research and hacking, compounded what is probably the most buggy VS ever. I did get it to work  eventually but not without a missed deadline. 

All that research and hacking is nothing compared to having to both learn and setup a non-microsoft windows operating system just to build programs written in a microsoft programming language that were created with a microsoft IDE and a microsoft service platform on a microsoft windows platform.  Its disconcerting how fast the responses of "wont fix in the version you have, please upgrade to next major version" seem to come nowadays.

**Comment by ericsciple** [comment]
I think the only thing related to the agent for this scenario is the routing capability, which can be added as a [user capability](https://www.visualstudio.com/en-us/docs/build/concepts/agents/agents#capabilities).

For the task workaround, the MSBuild tasks provides an advanced input to choose the path to MSBuild (older task doesn't know about future VS versions).

**Comment by bryanmacfarlane** [comment]
Just so you're aware of the core issue - TFS2015 (and it's tasks) shipped way before VS2017 existed.   So, it didn't have knowledge of how to find it (and it changed).  It's not about won't fixing a bug - there was feature work that went into TFS2017 to work well (automatically find it) with VS2017.  As Eric pointed out, there's a manual setting for the msbuild to use.

**Comment by StingyJack** [comment]
> TFS2015 (and it's tasks) shipped way before VS2017 existed

Wasn't  that also true for the other checkbox column that _is_ checked? 

>routing capability
No idea what that is. but I'll go look now. I just wanted basic ability to compile a solution with c#6 and 7 features that had started to be used by the team but the build agents were rejecting checkins.

**Comment by StingyJack** [comment]
Also stuff like this gets silently broken. Tests pass that are found, but more than half of the tests we had have disappeared from the results. I can open a "problem" through visual studio, but it will either get perma-triaged or closed-without-reading by FN, or someone else will reply back later and either assert its not a bug or i must major version upgrade (sometimes 2)... for a programs < 3 years old. 

I get it - new and shiny is fun, but minor updates to existing (and still new) programs to address functionality gaps is really what most of us (and our customers) can afford the time for - A 5 minute build agent install, or a 10 minute VS update. Not the rigmarole of fully specced and planned over the weekend upgrade.

```
2017-09-07T04:08:03.2931528Z Executing the powershell script: D:\tfsbuildagentinstall\tasks\VSTest\1.0.30\VSTest.ps1
2017-09-07T04:08:04.9779744Z ##[debug]Calling Invoke-VSTest for all test assemblies
2017-09-07T04:08:05.0871758Z Working folder: d:\tfs\a1\36
2017-09-07T04:08:05.0871758Z Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "d:\tfs\a1\36\s\SMTrunk\Tools\VcsIntegrationTestHarness\bin\Release\AssociationVerificationTests.dll" <clipped several dozen assembly names>
2017-09-07T04:08:05.5395816Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1 
2017-09-07T04:08:05.5395816Z Copyright (c) Microsoft Corporation.  All rights reserved. 
2017-09-07T04:08:06.1635896Z Starting test execution, please wait... 
2017-09-07T04:08:20.8121774Z Warning: Unable to load types from the test source 'd:\tfs\a1\36\s\SMTrunk\Tools\VcsIntegrationTestHarness\bin\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'. Some or all of the tests in this source may not be discovered. 
2017-09-07T04:08:22.0913938Z Warning: Input string was not in a correct format. 
2017-09-07T04:08:22.1225942Z Warning: Input string was not in a correct format. 
2017-09-07T04:08:22.1849950Z Warning: Input string was not in a correct format. 
2017-09-07T04:08:22.2317956Z Warning: Input string was not in a correct format. 
2017-09-07T04:08:22.2785962Z Warning: Input string was not in a correct format.
2017-09-07T04:08:22.3253968Z Warning: Input string was not in a correct format.
```

**Comment by bryanmacfarlane** [comment]
Log an issue in the vsts-tasks repo for your test task issue.

**Comment by bryanmacfarlane** [comment]
> Wasn't that also true for the other checkbox column that is checked?

No.  VSTS, TFS2017 shipped along with or after VS2017 versions.  Linux/OSX not relevant.

**Comment by StingyJack** [comment]
So should I generally use the relevant github project (if present) for reporting issues, or continue to use the VS in-app feedback. I'd prefer the former. 

That other column is `OSX/Unix`, which got an updated build agent to work for TFS 2015 but windows did not. If that column isnt correct, thats fine, but that is specifically the gap I'm talking about.

**Comment by bryanmacfarlane** [comment]
It's not a gap because that slot is filled by the 1.x agent that shipped with TFS2015.    The reason it's supported for nix is we deprecated the node agent.  Also there's no issue in the agent that prevents it with working with 2015 - it's all the 2015 tasks that shipped with tfs 2015 which have the issues (some of peaked into internals of the 1.x agent and broke coupling).  So, there's nothing to "fix" in the agent to fill that gap.

**Comment by StingyJack** [comment]
@bryanmacfarlane  - I think I get what you mean. The source of this v2/Tfs14 complaint is that I have a problem with built artifact download speed on the LAN being really slow compared to windows file copy from the same machines.

I'm only here because I'm trying to see if the v2 agent addresses this problem. The MSFT advice [over here](https://developercommunity.visualstudio.com/content/problem/77641/tfs-build-v2-agent-downloads-artifacts-slowly-v1-u.html) is something cryptic about robocopy and "update to TFS 2018 to see if it resolves your issue."  

Trying the agent update seems like a lot less work than updating 2 major versions of TFS in the hopes that the upgrade corrects the d/l speed problem. Is that a known issue that is resolved in v2?
