### ISSUE TITLE
Packages failed nuget restore VS 2017 in VSTS projects .net standard

### ISSUE THREAD

**Issue by izefler** [Microsoft/vsts-agent#1190]
Hello,

I need help!

I am using an on-premises build server, Windows with VS 2017 installed, I have other applications with the same features and works perfectly.

However for a specific application the error occurs!

In the task nuget restore it can not restore all the packages, the following error occurs:

Committing restore...
Generating MSBuild file d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\MRV.Obras.Mobile.Forms.csproj.nuget.g.props.
Generating MSBuild file d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\MRV.Obras.Mobile.Forms.csproj.nuget.g.targets.
Writing lock file to disk. Path: d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\project.assets.json
Restore failed in 545.85 ms for d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj.
Errors in d:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj
    Unable to resolve 'd:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Core\MRV.Obras.Mobile.Forms.Core.csproj' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'd:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.OrdemServico\MRV.Obras.Mobile.Forms.OrdemServico.csproj' for '.NETStandard,Version=v1.5'.
Errors in d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj
    Unable to resolve 'd:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj' for '.NETStandard,Version=v1.6'.
NuGet Config files used:
    d:\a\15\s\src\dev\nuget.config
Feeds used:
    http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin
    https://api.nuget.org/v3/index.json
Installed:
    100 package(s) to packages.config projects
    56 package(s) to d:\a\15\s\src\dev\Shared\MRV.Obras.Mobile.Domain.OrdemServico\MRV.Obras.Mobile.Domain.OrdemServico.csproj
    56 package(s) to d:\a\15\s\src\dev\Shared\MRV.Obras.Mobile.Domain.Core\MRV.Obras.Mobile.Domain.Core.csproj
    35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.Core\MRV.Obras.Mobile.Forms.Core.csproj
    35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.OrdemServico\MRV.Obras.Mobile.Forms.OrdemServico.csproj
    29 package(s) to d:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj
    35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj
Error: d:\a\_tool\NuGet\4.0.0\x64\nuget.exe failed with return code: 1
Packages failed to restore

Print settings task nuget:

![image](https://user-images.githubusercontent.com/2823190/30078540-e81652b2-9253-11e7-8555-776a39802601.png)

Print settings file nuget:

![image](https://user-images.githubusercontent.com/2823190/30078566-fb54e9f6-9253-11e7-83d5-793e2116353b.png)

**Comment by ericsciple** [comment]
It looks like you are having an issue with one of the tasks, not the agent. The NuGet Restore task is from this repo: https://github.com/Microsoft/vsts-tasks

Please open an issue in the vsts-tasks repo instead.

**Comment by izefler** [comment]
Thanks!!

**Comment by IvanAlekseev** [comment]
This one might be related https://github.com/Microsoft/vsts-tasks/issues/5065
