### ISSUE TITLE
Could both build and release definition use the same agent or each must use different agent?

### ISSUE THREAD

**Issue by lorenz31** [Microsoft/vsts-agent#1193]
This is my first time working with CI/CD using VSTS so please bare with me.

I'm currently creating a release definition for our project and I'm stuck with this problem, **could both build and release definition use the same agent** if yes, then how? If no, what are other options to do this?

**Comment by ericsciple** [comment]
Agents are in pools, and queues map to pools. https://www.visualstudio.com/en-us/docs/build/concepts/agents/pools-queues

**Comment by ericsciple** [comment]
...sorry, i mean to say "yes" both build and release definitions can use the same agent. As long as you have permission, you can choose the same queue either a build definition or a release definition.

**Comment by lorenz31** [comment]
@ericsciple Thanks for the response. I've already got it working :)
