### ISSUE TITLE
config. sh results in "Value cannot be null.  Parameter name: identifier" on MAC

### ISSUE THREAD

**Issue by zlogo** [Microsoft/vsts-agent#1195]
## Agent version and platform
2.122.0

OS of the machine running the agent? 
OSX 

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? 
http://swissre-dwp.visualstudio.com

## What's not working?
When running config.sh on Mac receiving a Value cannot be null.  Parameter name: identifier error from the server.

## Agent and Worker's diag log
...
[2017-09-06 08:35:40Z ERR  VisualStudioServices] GET request to https://swissre-dwp.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: InternalServerError
[2017-09-06 08:35:40Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2017-09-06 08:35:40Z INFO AgentServer] Catch exception during connect. 4 attemp left.
[2017-09-06 08:35:40Z ERR  AgentServer] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Value cannot be null.  Parameter name: identifier
...

**Comment by stephenmichaelf** [comment]
@zlogo Could you set the following environment variable on the Agent server(stop the agent, set, then start the agent):

set VSTS_AGENT_HTTPTRACE=true

Then run the build again and send the logs to:

stfrance at microsoft.com
tihuang at microsoft.com

NOTE: Please do NOT post these logs publicly as they may have sensitive information.

**Comment by zlogo** [comment]
@stephenmichaelf I have sent the logs, thanks.

**Comment by stephenmichaelf** [comment]
@zlogo Thanks we are looking into this now.

**Comment by peakyy** [comment]
Hi @zlogo,

I'm sorry about the issue you are facing. Recently, you migrated your account from being MSA backed to AAD backed. In this process unfortunately Personal Access Tokens (PATs) become invalidated. The 500 "internal service error" you saw should have been a 403 "unauthorized", and we are working to fix that now.
**Workaround:** Login to your account and create a new PAT via the UI. Using that new PAT associated with your new AAD backed account you should be up and running. Let us know if that doesn't work for you.

**Comment by zlogo** [comment]
Hi @peakyy,

Thanks for the swift response. I followed the steps and now everything works just fine.

**Comment by TingluoHuang** [comment]
@peakyy thanks for your input.
@zlogo i will close issue as now.
