### ISSUE TITLE
Linux agent depends on libicu52 but isn't listed as a prerequisite

### ISSUE THREAD

**Issue by j0tt** [Microsoft/vsts-agent#1201]
## Agent version and platform
Ubuntu 16 LTS / 2.100.2

## OS of the machine running the agent? 
Ubuntu 16 LTS (But running in Linux Subsystem for Windows)

## VSTS type and version
VisualStudio.com

## What's not working?
After installing prerequisites and downloading/extracting the agent, running `./config.sh` fails with
`Failed to initialize CoreCLR, HRESULT: 0x80131500`

## Workaround
`wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.6_amd64.deb`

`sudo dpkg -i libicu52_52.1-3ubuntu0.6_amd64.deb`

**Comment by bryanmacfarlane** [comment]
We build the agent for ubuntu 14 and ubuntu 16.  The 16 build does not need libicu52.  But we had a bug where we were only offering the ubuntu 14 agent in the download (should be fixed now).  If you try and run an agent built for 14 on a 16 box, you will see this.  Please confirm.

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envubuntu.md

**Comment by bryanmacfarlane** [comment]
Per comments above, not an issue.  Reactivate if you have more info

**Comment by j0tt** [comment]
Sorry :( I forgot to try and repro. I need to do it on a clean machine, and when I do I'll let you know.

**Comment by j0tt** [comment]
Okay, new machine (luckily I just got a new work computer):

Installed Ubuntu Subsystem for Windows
`~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial`

ran:
`~$ sudo apt-get install -y libunwind8 libcurl3`
`~$ git --version`
`git version 2.14.1`
`~$ mkdir vstsagent && cd vstsagent`
`~/vstsagent$ tar zxvf ~/Downloads/vsts-agent-ubuntu.14.04-x64-2.123.0.tar.gz`
`./config.sh`

Outputs:
`Failed to initialize CoreCLR, HRESULT: 0x80131500`

**Comment by j0tt** [comment]
Oh boy PEBKAC

The default agent download is 14.04-x64. Clicking the different agent versions on the left side doesn't change the page look at all, maybe the download button should be more specific? "download for Ubunto 14.04-x64"?

Anywayyyyyyy entirely my fault, nothing to see here.

**Comment by bryanmacfarlane** [comment]
Good point.  Default should be 16.  Sorted 14 first.

Also note that we had a bug that sprint where 16 didn't show up so it may not have been your fault :)

**Comment by bryanmacfarlane** [comment]
Also - very soon, we will just a "linux" agent.

**Comment by mingalsuo** [comment]
@bryanmacfarlane, can you give any updates on 'very soon'? I'm part of a project where we utilize vsts-agent and found that vsts-agent does not run on current Debian Stable. Oldstable works still.

I assume that "just a linux agent" is the same as "moving our agent to core clr 2.0 self contained app" as you mentioned in another issue and both will become true very soon.

Thanks,
mingalsuo

**Comment by bryanmacfarlane** [comment]
It's coded and we're testing.  We're hoping it rolls out in this sprint.  Should be week(s) away.  We can provided a private if you want.

**Comment by mingalsuo** [comment]
@bryanmacfarlane, private beta? Sure :)

**Comment by bryanmacfarlane** [comment]
send me a mail.  bryanmac and that's at microsoft dot com
