### ISSUE TITLE
Agent uses very old version of NuGet

### ISSUE THREAD

**Issue by mwijnands** [Microsoft/vsts-agent#1204]
https://github.com/Microsoft/vsts-agent/blob/b8f6864f8faad7f56dbca38c2bb84cba4ffa93c8/src/Misc/externals.sh#L147

Why is the build agent using v3.3 of NuGet.exe? When using the NuGet Packager step with TFS 2017 it uses the NuGet.exe from the externals folder. (it used 3.5 before, but after agent 2.117.2 it uses 3.3 again..)

**Comment by TingluoHuang** [comment]
@mwijnands which agent version you are using has nuget 3.5? the 2.x agent package nuget 3.3 since version 2.104.

**Comment by bryanmacfarlane** [comment]
in later versions of the task, the agent (and what it carries) is irrelevant.  vsts and tfs 2018 comes with a tool installer task for nuget where you specify what version you want.

**Comment by mwijnands** [comment]
@TingluoHuang it's possible that we replaced it with nuget 3.5 ourselfs now that I think of it... After updating to TFS 2017 Update 2 we ended up with the following folders, where 2.117.2 contains nuget 3.3 and 2.112.2 contains nuget 3.5.

![image](https://user-images.githubusercontent.com/1771830/30296485-a81f993e-9744-11e7-864d-2f050c650693.png)

It would help if you can choose which NuGet version the NuGet Packager step uses, just like with the NuGet restore step. Now it seems fixed to v3.3. I know a custom path to NuGet.exe can be specified but we would need to set that for every build definition.

**Comment by TingluoHuang** [comment]
@mwijnands we need got confirm from Nuget team to see whether we can bump it in the agent. Historically, Nuget is not good at compatibility, so we just use the safest version that we been told by Nuget team.

**Comment by jdshkolnik** [comment]
I'm hitting an issue which might be related. When I use the deprecated NuGet Packager task, it uses externals\nuget.exe which contains 4.3 and works fine. When I use the new NuGet task, it uses an older version that appears under the _tool folder even if I first delete it.

**Comment by TingluoHuang** [comment]
@jdshkolnik log an issue at https://github.com/microsoft/vsts-tasks, the new NuGet task should work, if not, it's a bug for that task.

**Comment by ppejovic** [comment]
@TingluoHuang @bryanmacfarlane I'm aware that the NuGet tool installer step is available, but we have many builds based on version 0.* of the NuGet restore step. This step ignores the version downloaded by the tool installer and uses the version distributed with the agent, i.e. v3.3.0. 

This causes problems as restores of packages that target .NET Standard fails, as support for this was introduced in v3.4.0. What's worse is that v3.3.0 only has problems with these packages when they are not already in cache. If another build has run on the same agent using the latest installer and restore steps the package will be in cache and the problem doesn't surface. 

Is there any likelihood that the nuget.exe version will be bumped?
