### ISSUE TITLE
After upgrade to 2.120.2, get OutOfMemoryError as compiling Xamarin Android project

### ISSUE THREAD

**Issue by heavenwing** [Microsoft/vsts-agent#1206]
## Have you try trouble shooting doc?
YES

## Agent version and platform
2.120.2 on Windows
Agent.OS	Windows_NT
Agent.OSVersion	6.3.9600
VS 15.3.4

## VSTS type and version
VisualStudio.com
baicyx.visualstudio.com

## What's not working?
Get a error below as compiled Xamarin Android:
`
2017-09-14T01:31:34.8764472Z ##[error]COMPILETODALVIK(0,0): Error : 
2017-09-14T01:31:34.8764472Z COMPILETODALVIK : UNEXPECTED TOP-LEVEL error :  [E:\vstsagent\_work\5\s\src\Mcs.MobilePlatform.App.Shell.Droid\Mcs.MobilePlatform.App.Shell.Droid.csproj]
2017-09-14T01:31:48.5015687Z   Exception in thread "main" 
2017-09-14T01:31:48.5015687Z   Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
`

I found workaround that setting JDK to X64 can solved this problem. Ref to: https://social.msdn.microsoft.com/Forums/en-US/0b9511a8-039c-4abc-a5ea-04aaa1c11219/error-visual-studio-online-build-xamarin-android-java-heap-size?forum=TFService

But, my question is agent version 2.120.1 is working, why not for 2.120.2

And, I found another problem that after set "JDK Version" option to "default" and "JDK Architecture" to "x64", agent still use x86 jdk to compile code. Then I have to set  "JDK Version" option to "JDK8", agent use x64 jdk finally.

My JDK setting of agent is:
java	C:\Program Files\Java\jre1.8.0_144
java_8_x64	C:\Program Files\Java\jre1.8.0_144
JAVA_HOME	C:\Program Files\Java\jdk1.8.0_131
jdk	C:\Program Files\Java\jdk1.8.0_131
jdk_8	C:\Program Files (x86)\Java\jdk1.8.0_112
jdk_8_x64	C:\Program Files\Java\jdk1.8.0_131

**Comment by ericsciple** [comment]
Is the agent memory consumption different? Each task is run in a separate process and the agent reads the output streams and exit code.

**Comment by bryanmacfarlane** [comment]
This isn't the agent.  It has no concept of xamarin.  It's just running the process.  Create an issue in the vsts-tasks repo
