### ISSUE TITLE
SSDT 15.3 on hosted VS2017 agent

### ISSUE THREAD

**Issue by johncollinson2001** [Microsoft/vsts-agent#1208]
Hi,

I have a hosted build on visualstudio.com for a solution that includes SSIS projects (.dtproj). 

The build was working fine using the VS2015 hosted agent, but following the latest release of SSDT (and its support for SSIS projects in VS2017) I have migrated my solution to Visual Studio 2017, and modified my build definition to run on the VS2017 hosted agent.

The build is failing with the following error: `The element <DeploymentModel> beneath element <Project> is unrecognized.` referring to the .dtproj file.

I believe this is because the latest version of SSDT is not installed on the agent. Could you clarify if/when this may available? 

If there is a long wait, are there any workarounds other than using a private agent? (e.g. ignore .dtproj files in the build - is this possible?)

Many thanks

**Comment by schwaizi** [comment]
Hi, i have similar issue with Agent queue Hosted 2017.

Myy script is using Devenev to build .ispac file from SSIS project (.dtproj)

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Devenv.com

and the result is:

> The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660528&projecttype=159641D6-6404-4A2A-AE62-294DE0FE8301

It works fine on my on-premise build agent with SSDT for VS2017 installed.

**Comment by saranad** [comment]
Currently, SSDT version - Version: 14.0.16121.0 is installed on the VS2017 pools. https://github.com/adventworks/hosted-pool-images/blob/master/vs2017-on-windows-2016/image.md

Are you still facing issues?

**Comment by bryanmacfarlane** [comment]
Not an issue with the agent application (this repo)

**Comment by johncollinson2001** [comment]
Hi,

Apologies for the delayed response.

Thanks @saranad - I can see from the list of software installed that 14.0.16121.0 is installed, this post is all about when 15.3.0 is likely to be installed.

Thanks @bryanmacfarlane, however where should I raise this issue? SSDT 15.3 provides support for SSIS projects in Visual Studio 2017, however VSTS builds fail due to the outdated version of SSDT in the image. I understand this is not a bug with the agent per-say, but it is kippering those of use who have recently upgraded to SSDT 15.3/VS2017 and want to build our solutions on VSTS.

Please can you advise what the normal course of action is in this case?

For anyone who's come across this thread, the only workaround I've found so far (which is far from ideal) is to create a build configuration which ignores the SSIS projects and specify this configuration in the VSTS build. (Yuk!)
