### ISSUE TITLE
Windows Preview: Build directory cleanup tweaks

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#121]
1) Should not follow junction points.
2) Should retry on files.
3) (Nice to have) Should retry on directories.

**Comment by bryanmacfarlane** [comment]
lower pri than other work like tf.exe

**Comment by ericsciple** [comment]
This was for tracking and the junction point work was done. The lack of retries doesn't seem to be hindering us so so closing for now.
