### ISSUE TITLE
VSTS Agent configuration - Exception after entering PAT token while creating new RSA key

### ISSUE THREAD

**Issue by PT2911** [Microsoft/vsts-agent#1220]
## Have you try trouble shooting doc?
NA

## Agent version and platform
Version of your agent? 
2.122.1

OS of the machine running the agent? OSX/Windows/Linux...
Windows Server 2012 Datacenter

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? 
https://pratiktayde.visualstudio.com

## What's not working?
While trying to configure agent for my VSTS account, getting unhandled exception after entering PAT token. Not sure about the cause.
Any help is much appreciated.

regards,
Pratik

![image](https://user-images.githubusercontent.com/32224558/30774978-5ab5d308-a0a8-11e7-972b-46954257c66f.png)

![image](https://user-images.githubusercontent.com/32224558/30775111-e34ac16c-a0ab-11e7-9873-6464c939cf74.png)

## Agent and Worker's diag log
[Agent_20170923-113749-utc.log](https://github.com/Microsoft/vsts-agent/files/1326669/Agent_20170923-113749-utc.log)

**Comment by TingluoHuang** [comment]
@PT2911 check whether the CNG Key Isolation Windows Service is running on your box.
![image](https://user-images.githubusercontent.com/1750815/30778887-82d43a90-a0ae-11e7-9402-1cfe7a514671.png)

**Comment by PT2911** [comment]
Hi TingluoHuang,
CNG Key Isolation Windows Service was stopped on my box,
After starting the sevice, I was able to Configure the agent.


Thanks & regards,
Pratik
