### ISSUE TITLE
Detected Package Downgrade

### ISSUE THREAD

**Issue by dagrooms52** [Microsoft/vsts-agent#1225]
## Operating System
OSX

## What's not working?
Nuget Restore on this repo

## Commands
`cd Microsoft.VisualStudio.Services.Agent/`
`dotnet restore`

## Output
```/Users/d748115/source/vstsagent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj : error NU1605: Detected package downgrade: System.Net.Http from 4.3.2 to 4.3.0. Reference the package directly from the project to select a different version. 
/Users/d748115/source/vstsagent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj : error NU1605:  Microsoft.VisualStudio.Services.Agent (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.2) -> System.Net.Http (>= 4.3.2) 
/Users/d748115/source/vstsagent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj : error NU1605:  Microsoft.VisualStudio.Services.Agent (>= 1.0.0) -> System.Net.Http (>= 4.3.0)
Restore failed in 27.46 sec for /Users/d748115/source/vstsagent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj.```

**Comment by dagrooms52** [comment]
Ultimately this is just in the way of my exploration into doing a custom build of the VSTS agent for ARM CPU devices, specifically a Raspberry Pi 3. Is it possible to run the agent on a Raspberry Pi 3?

**Comment by TingluoHuang** [comment]
I think you might need netcore 2.0 in order to make ARM works. We are in the process of moving agent from netcore 1.1 to netcore 2.0 right now.
but even we finish the move, you still need some extra work to make it actually working for ARM.

check the following branch for some hint.
https://github.com/Microsoft/vsts-agent/tree/users/edgedevs/v2arm

**Comment by scyentyfyc** [comment]
I know this is closed, but it is the only thread I found talking about ARM / Raspberry Pi... which makes me wonder, how does everybody else automate deployment to ARMv7 / aarch64 machines?

**Comment by dagrooms52** [comment]
I have a Mac machine running a VSTS task to ssh into a ras pi, all using the services provided by resin.io
