### ISSUE TITLE
YAML roadmap

### ISSUE THREAD

**Issue by pakdev** [Microsoft/vsts-agent#1227]
Is the motivation behind the "localRun" option to allow dev machines to execute the same tasks as the build machines (in addition to serializing build definitions)? That would be ideal. 

If so, when can we expect a public preview? Am I able to test this today if I manually create a YAML config? I assume a build definition to YAML exporter is in the works? Thanks!

**Comment by bryanmacfarlane** [comment]
Yes to both questions.  It is coming in preview very soon (we're dogfooding internally).

**Comment by Davilink** [comment]
Is there a Bitbucket YAML Support Roadmap ?

**Comment by bryanmacfarlane** [comment]
@Davilink - have you tried to create a new definition of type yaml from the web UI and thenspecify BitBucket as the source provider?  You should then be able to specify or browse to the yaml file.  Auto creating the definition via checking in a yaml file will only be done for VSTS git repos.

**Comment by Davilink** [comment]
@bryanmacfarlane No i didn't tried, because i only read the documentation https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml and it's said that wasn't support yet in Bitbucket.

**Comment by ericsciple** [comment]
it requires some work on the server side to enable, i'm not sure where that work is on the backlog. i'll ask some folks internally.

**Comment by Davilink** [comment]
Any news ?

**Comment by ericsciple** [comment]
I checked. It's not on the immediate backlog (next couple months).

It's not a bug. And we typically don't track feature requests in this repo. I believe User Voice is what we are currently using to track feature requests.

**Comment by Davilink** [comment]
I created a UserVoice Post : https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/33037504-yaml-bitbucket-task

**Comment by bryanmacfarlane** [comment]
Thanks.  I've forward this to the folks doing the work.
