### ISSUE TITLE
Errors from invoking TF.exe are only logged as output

### ISSUE THREAD

**Issue by ppejovic** [Microsoft/vsts-agent#1229]
Errors from invoking tf.exe used to be logged at error level in the v1.105.6 agent:

![image](https://user-images.githubusercontent.com/585084/31238897-2d068e14-a9b0-11e7-802e-ce111d585ef9.png)

Using the `tf unshelve` example above, this would lead to the _"No appropriate mapping..."_ errors appearing on in the _Issues_ section of the build summary. It's clear from these issues why the _Get sources_ step has failed.

Running the same example on the v2.\*.* agents (up to and including v2.123.0) the output is as follows:

![image](https://user-images.githubusercontent.com/585084/31239212-352cb91e-a9b1-11e7-92da-917a596ae609.png)

Note, the _"No appropriate mapping..."_ errors are just logged as output. The only thing you see on the build summary now is _"Exit code 100 returned from process: file name 'tf', arguments 'vc unshelve..."_, which isn't particularly helpful. Additionally, if you have a large unshelve operation and just one of the files does not have an appropriate mapping it's not easy to identify the issue when browsing through the log for the step. This behavior applies across all `tf` operations from looking at the code.

The issue appears to be at the code block below. Could this be changed to use `ExecutionContext.Warning()` or `ExecutionContext.Error()` to make tf errors easier to debug?

https://github.com/Microsoft/vsts-agent/blob/51fb22576b5168e761144a13bb54102824d7cc0f/src/Agent.Worker/Build/TfsVCCommandManager.cs#L118-L124

**Comment by TingluoHuang** [comment]
@ppejovic the 1.x agent is not actually invoke tf.exe, it is using TFS Client OM, so you can get a C# exception UnshelveException. the 2.x agent is directly call into tf.exe and only reply on return code to decide whether the operation is succeed or not.

**Comment by stephenmichaelf** [comment]
Closing this, please reopen if you have issues.
