### ISSUE TITLE
Agent not properly checking out PR for Bitbucket PR-triggered build

### ISSUE THREAD

**Issue by Jakkob** [Microsoft/vsts-agent#1232]
I'm really enjoying the new native Bitbucket integration in VSTS, except for one issue.

Builds that are triggered by a Bitbucket PR do indeed trigger correctly, they just don't appear to checkout the right commit/branch/ref.

The following appears to be part of the issue:
https://github.com/Microsoft/vsts-agent/blob/4b6dfc4a520b555af88908a7622e3247808fbe5a/src/Agent.Worker/Build/GitSourceProvider.cs#L1019-L1024

That method looks for a GitHub-like PR ref on the remote repo (Ex. `refs/pull-requests/{pr_number}`). This would normally be fine, unfortunately [Bitbucket.org doesn't support PR refs](https://bitbucket.org/site/master/issues/5814/refify-pull-requests-by-making-them-a-ref).

Regardless of what I try, I can't get my builds to checkout anything but the most recent commit on the target branch when using PR CI triggering.

Are there any plans to address this in the agent code, or possibly plans to address in in the VSTS codebase?

Edit:

It looks like [Atlassian provides a `merge_commit` value in their API responses](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D) (It's aaaaaall the way at the bottom). I guess that VSTS itsself is not sending the merge commit hash to the Agent for building?

**Comment by TingluoHuang** [comment]
the bug should be fixed on the server side, please reopen the issue if problem still happen.
