### ISSUE TITLE
What is the point of the 'externals' folder if we have to install software anyway?

### ISSUE THREAD

**Issue by IAMtheIAM** [Microsoft/vsts-agent#1234]
This may be a noob question but I am new to setting up an on-premise agent. Since we have to install the software using either their native executables or by manually adding to the path, what is the point of having the prebundled software in `externals` like `node` and `node-5.10.0`? Because, the agent won't be able to see that software unless its manually added to the path.

I tried adding new software to the `externals` folder like `yarn` and `phantomjs` but it was not able to automatically recognize it. So that means I just have to install it normally, and the externals folder does even get used. 

What is the proper way to use `externals` and for what purpose?

Lastly, `externals` contains `node` folder and in that `node.exe` but it doesn't include `npm.cmd` - so whats the point of bundling node without npm?

## Agent version and platform
Version of your agent? 2.102.0/2.100.1...
2.123.0 
OS of the machine running the agent? OSX/Windows/Linux...
windows 10 
## VSTS type and version
VisualStudio.com or On-Prem TFS?
visual studio online, on premise agent

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?

If VisualStudio.com, what is your account name? http://account.visualstudio.com

**Comment by ericsciple** [comment]
The externals folder is an internal implementation detail of the agent. You should not add files there. They will be deleted when the agent updates.

**Comment by IAMtheIAM** [comment]
OK, but where is the documentation on that? For example, there is contained `node` and `node-5.10.1`. How and when do I choose to use the correct version of node? Secondly, if I am installed node and setting the path, why does the agent require another copy of `node.exe` within externals? Same with git. What is the reason for having a second copy of git?

**Comment by ericsciple** [comment]
The agent internally uses node and bundles the version it uses.

On Windows the agent carries a copy of git (actually mingit or portable, i forgot). It simply reduces the setup cost. Download the agent and core dependencies are included in the download (accounts for internet disconnected scenarios).

**Comment by ericsciple** [comment]
If you need to use a specific version of node in your custom scripts then you will need to download node - note there is a Node Tool build/release task that will download a specific version of Node and add it to your PATH for the duration of the job.

**Comment by brunis** [comment]
@ericsciple that is incorrect, having nodejs installed (nodejs windows installer in programfiles) in the wanted version has no effect, neither does it have any effect installing a specific one with task: NodeTool@0 in yaml and even though the Agent's capabilities sections says node.js = C:\Program Files\Nodejs, tasks like gulp and grunt will use the externals node16.

**Comment by phil8526** [comment]
@brunis Did you ever find a workaround for getting the agent to use the correct version of node? UseNode@1 doesn't seem to do anything at all.
