### ISSUE TITLE
VSSDK workload recently removed from the Hosted VS2017 agent?

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/vsts-agent#1235]
## Agent version and platform

Latest Hosted VS2017

Windows

## VSTS type and version
VisualStudio.com 

## What's not working?

Starting from Oct. 6 Friday, our Visual Studio extension project stopped producing VSIX.  I tried a sample VSIX project and it failed to build with the following error
```
VSIXProject1\VSIXProject1.csproj(132,11): Error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets" was not found. Also, tried to find "VSSDK\Microsoft.VsSDK.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

**Comment by jeremymeng** [comment]
@TingluoHuang Where's the issue tracked?

I tried adding Microsoft.VisualStudio.Sdk.BuildTasks.14.0 nupkg to my project but it gave a build error:

```
3>C:\Users\yumeng\.nuget\packages\microsoft.visualstudio.sdk.buildtasks.14.0\14.0.215\tools\VSSDK\Microsoft.VsSDK.targets(104,5): error VSSDK1047: There was a problem opening the VSIXManifest Schema. Could not find file 'C:\Users\yumeng\.nuget\packages\microsoft.visualstudio.sdk.buildtasks.14.0\14.0.215\tools\VSSDK\schemas\PackageManifestSchema.xsd'.
```

**Comment by TingluoHuang** [comment]
@jeremymeng have you try add all 3 packages prefix with `Microsoft.VisualStudio.Sdk`

**Comment by jeremymeng** [comment]
@TingluoHuang I didn't think the other two packages matter from their descriptions so I didn't add them.

After I add the other two packages, still getting an error

![image](https://user-images.githubusercontent.com/7583839/31413158-d63ac89a-adcc-11e7-9f50-b1f40e2950c2.png)

**Comment by jeremymeng** [comment]
My project is a little customized though, not like the ones created from the extension templates.

**Comment by bryanmacfarlane** [comment]
Not an agent (this app) bug.  That's a hosted image update and follow on issue with pulling via nuget.

If you email me at bryanmac and that's at microsoft dot com, I'll put you in contact with VSSSDK folks.
