### ISSUE TITLE
Add support for passing replace parameter

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-agent#1238]
I need to be able to pass the [replace](https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L126) argument into the [VM extension](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/howto-provision-deployment-group-agents#deploytask)

I have a release that always recreates a VM and adds it to a deployment group via an ARM template, and it fails the second deployment with this error:

```
VM has reported a failure when processing extension 'TeamServicesAgent'.
The Extension failed to execute: Agent Configuration failed with error - DeploymentGroup 45 already contains a machine with name VM1-DG.
```

**Comment by TingluoHuang** [comment]
@chshrikh for deployment group question.

**Comment by chshrikh** [comment]
@sachinma can you check this

**Comment by RoopeshNair** [comment]
We will add to our backlog. For now, as a workaround, can you delete the target from the deployment group first as part of your workflow using REST APIs.
