### ISSUE TITLE
Agent does not connect with TFS

### ISSUE THREAD

**Issue by bootrider** [Microsoft/vsts-agent#1245]
## Agent version and platform
Version of your agent? 2.123.0

OS of the machine running the agent? Windows

## VSTS type and version
On-Prem TFS 2017 Update 2 RTM
Microsoft Visual Studio Team Foundation Server 
Version 15.117.26714.0 

## What's not working?
Trying to install the agent, when configuration is required, the agent dies testing the agent connection with response that "the audience of the token is invalid"

try to install the Agent version 2.120.2...runs perfectly

[![enter image description here][1]][1]

## Agent and Worker's diag log
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

  [1]: https://i.stack.imgur.com/pCR8r.png

**Comment by TingluoHuang** [comment]
@bootrider can you try https://github.com/Microsoft/vsts-agent/releases/tag/v2.122.1 as well, and send both agent diag log (2.120.2, 2.122.1, 2.123.0) to me? tihuang AT Microsoft.com

**Comment by TingluoHuang** [comment]
@bootrider I think I figured out what's going wrong.
here is the assembly with the fix, would you like to try it out?
If you want, you can just unzip the following file and replace the files under `<AgentRoot>/bin` folder.
[Agent.Listener.zip](https://github.com/Microsoft/vsts-agent/files/1388258/Agent.Listener.zip)

**Comment by TingluoHuang** [comment]
#1248

**Comment by TingluoHuang** [comment]
@bootrider even i can guess where might cause the problem, but i still can't repro the issue. would you might help me capture a Fiddler trace for the agent when you hit the error with 2.123.0 agent?

**Comment by bootrider** [comment]
@TingluoHuang  after unzip the agent listener an place the files in the bin folder of the Agent 2.123, it works without problem

**Comment by TingluoHuang** [comment]
@bootrider thanks for your log. The fix will be included in next version agent release.
