### ISSUE TITLE
Satelite assemblies from libraries not copied for build with xbuild

### ISSUE THREAD

**Issue by Brosten** [Microsoft/vsts-agent#1246]
## Agent version and platform
2.123.0 OSX

## VSTS type and version
On-Prem TFS (2017-QU1)

## What's not working?
Satelite assemblies from libraries not copied for build with xbuild
More described here:
https://bugzilla.xamarin.com/show_bug.cgi?id=44726

But since there are no actions for one year from the xamarin-bug, I thought this might be a better Place to ask about progress around this?

**Comment by bryanmacfarlane** [comment]
This is the CI agent repo which has no concept of xamarin (it's a CI agent app).  Xamarin is the best place to log that bug.
