### ISSUE TITLE
https://java.visualstudio.com/ certificate had expired

### ISSUE THREAD

**Issue by vszakats** [Microsoft/vsts-agent#1260]
This may not be the best place to report this — though maybe someone reading this can relay the issue to the responsible internal team:

<https://java.visualstudio.com/> site's TLS certificate expired a few days ago:
![screen shot 2017-10-23](https://user-images.githubusercontent.com/1446897/31900127-c73d8c00-b81d-11e7-9c4d-473f8af84200.png)

**Comment by TingluoHuang** [comment]
@madhurig FYI,

**Comment by madhurig** [comment]
@vszakats: Thanks for reporting it, we had some outage in our system causing the renewal to not go through. It has been fixed now. 

Thanks,
Madhuri

**Comment by vszakats** [comment]
@madhurig: I can see it now fixed on the live page — Thanks a lot for your quick response and fix.
