### ISSUE TITLE
Info results returned from git showing as error in build step

### ISSUE THREAD

**Issue by patnolan** [Microsoft/vsts-agent#1262]
Hi,

My build definition has a step which executes a powershell script (snippet below). The script pushes the code into GitHub. It's all working perfectly, however the output produced by calls to git are being displayed in the log as errors (see attached screenshot). This also means the build failed even though everything worked as expected.

I found the same questions being asked [here](https://stackoverflow.com/questions/30166089/git-output-shown-as-error-in-team-build-2013) but no solution was found. As you can see I have tried " | Write-Host" and "exit 0" but neither of these work.

Is there a way to have these return messages resolved as info and not considered to be errors?

```
param(
    [string] $GitRepoUrl
)

Write-Host "GitRepoUrl: $GitRepoUrl" 

Set-Location $Env:BUILD_SOURCESDIRECTORY

Write-Host ">>git init"
git init | Write-Host

Write-Host ">>git remote add origin $GitRepoUrl"
git remote add origin $GitRepoUrl | Write-Host

Write-Host ">>Start-SshAgent -Quiet"
Start-SshAgent -Quiet | Write-Host

Write-Host ">>ssh-add c:\git\id_rsa.pub"
ssh-add c:\git\id_rsa.pub | Write-Host

Write-Host ">>ssh -T git@github.com"
ssh -T git@github.com | Write-Host

Write-Host ">>ssh -Tv git@github.com"
ssh -Tv git@github.com | Write-Host
```

![Uploading build.png…]()

**Comment by bryanmacfarlane** [comment]
You need to redirect stderr to stdout for calls that you know result in non error case stderr output (git writes progress, status to stderr).

Does this help?

https://stackoverflow.com/questions/8925323/redirection-of-standard-and-error-output-appending-to-the-same-log-file

**Comment by stephenmichaelf** [comment]
@patnolan Any luck with this?

**Comment by patnolan** [comment]
Hi @bryanmacfarlane thanks for checking in.

After a lot of mucking around and trying heaps of different options, the only option that seemed to work was using the following syntax to pipe to file

git commit --message "Build $Env:BUILDVERSION" *>> $Env:BUILD_SOURCESDIRECTORY\CommitToGit_output.txt

**Comment by chaveen** [comment]
I found this article suggesting to use quiet mode in git commands. This suggestion worked for me!

http://donovanbrown.com/post/How-to-git-push-from-VSTS-build
