### ISSUE TITLE
Azure extension fails to install because zip cannot be deleted

### ISSUE THREAD

**Issue by sibbl** [Microsoft/vsts-agent#1267]
We're using a RM template to set up a Windows VM including the VSTS agent extension. However, the whole step fails because the zip cannot be deleted after successful setup of the extension. So the agent is starting properly and the VM is showing up in the deployment group. 

The error message is as follows:

```
VM has reported a failure when processing extension 'VSTS-Agent'

Error message: "The Extension failed to execute: The process cannot access the file 'C:\\VSTSAgent\\agent.zip' because it is being used by another process..

More information about the failure can be found in the logs located under 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.12.0.0' on the VM."
```

Our guess is that the setup is faster than Defender checking the content of the ZIP. What might be a possible solution?

**Comment by TingluoHuang** [comment]
@chshrikh is this a deployment group extension?
@sibbl the easiest solution would be add a Try-Catch or don't delete the download zip.

**Comment by sibbl** [comment]
@TingluoHuang yes, that would be a great idea but nothing a user of the extension can do ;) Here's a link to the description of which extension exactly we're using: https://gallery.azure.com/artifact/20161101/microsoft.vsts-agent-windows-arm.1.0.0/Artifacts/MainTemplate.json

**Comment by chshrikh** [comment]
@sachinma to help sibble

**Comment by bishal-pdMSFT** [comment]
The VM extension does not delete agent zip package after configuration. It only deletes the package when new package is downloaded next time.

@sibbl can you please provide full logs from 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.12.0.0'. on the VM. You will need to get the logs for correct timestamp when this error happened. Or repro the issue again and get the latest logs.

**Comment by sibbl** [comment]
@bishal-pdMSFT we can reproduce it during the setup of a new VM.

Please [find the logs in this vsts-agent-logs.zip](https://github.com/Microsoft/vsts-agent/files/1433811/vsts-agent-logs.zip). It seems that the `enable.cmd` does not wait for the `install.cmd` to complete and both run at the same time?

**Comment by TingluoHuang** [comment]
Thanks @chandlerkent 

@chshrikh @bishal-pdMSFT 
please check the log.

**Comment by bishal-pdMSFT** [comment]
Apologies for the delay - somehow I missed mail notification.
Looking at the logs, it seems two instances of enable.cmd start running in parallel causing this error - first one is actually successful and hence you can see that VM has been added to deployment group, but second one fails. 
We will investigate this more to find why two instances are running. 
@tedeshpa

**Comment by tejasd1990** [comment]
Hi all,
we have fixed this issue and published a new extension version. Please let us know if the issue persists.
@chshrikh can we close this issue after waiting for a few days?

**Comment by TingluoHuang** [comment]
I am going to close the issue for now, please reopen if needed.
