### ISSUE TITLE
Use [ci skip] rather than ***NO_CI***

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-agent#1270]
Most of the others CI use `[ci skip]` or `[skip ci]` (e.g. [Travis](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build), [CircleCI](https://circleci.com/docs/1.0/skip-a-build/), [Concourse](https://github.com/concourse/git-resource#behavior), [Codeship](https://documentation.codeship.com/general/projects/skipping-builds/), [Bitrise](http://devcenter.bitrise.io/tips-and-tricks/skip-a-build/), [Appveyor](https://www.appveyor.com/docs/how-to/filtering-commits/), [GitlabCI](https://docs.gitlab.com/ee/ci/yaml/README.html#skipping-jobs)) 

Some dependencies use `[ci skip]` as default to skip automatically versioning from their CI, why not make VSTS also accept it?

**Comment by TingluoHuang** [comment]
@marceloavf `***NO_CI***` has been there for at least 6+ years from what i can remember.
@chrisrpatterson see how we want to take this feedback.

**Comment by marceloavf** [comment]
What I suggest is to give some options to the user:
- Specify what kind of commit should not trigger a build.
- And/Or ignore those `***NO_CI***`, `[ci skip]` in specific branch for an user that want a pull request to trigger a build after merge.

**Comment by TingluoHuang** [comment]
@marceloavf i would suggest submit your feedback at here: https://visualstudio.uservoice.com/forums/330519-team-services
since the feature you request is for server side.

**Comment by hugovk** [comment]
Here's the link, but it's been closed for voting with no comment as to why:

* https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/32068780-use-ci-skip-rather-than-no-ci

Please could someone say why voting is closed?

---

AppVeyor also respect `[skip ci]` and `[ci skip]` in the commit message title, and also `[skip appveyor]`.

* https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message

Travis CI support `[<KEYWORD> skip]` and `[skip <KEYWORD>]` where `<KEYWORD>` is either `ci`, `travis`, `travis ci`, `travis-ci`, or `travisci`.

* https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

This inconsistency means Azure Pipelines builds when others do not. It wastes resources at Azure Pipelines, can cause confusion when a build is made when it shouldn't, and can cause builds to fail when they shouldn't be run.

Thank you!

**Comment by nschonni** [comment]
> Please could someone say why voting is closed?

https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services has the announcement about the move to developer community

**Comment by hugovk** [comment]
Thanks!

I found the new issue and the good news is it's being worked on.

* https://developercommunity.visualstudio.com/idea/420289/add-support-ci-skip-and-azure-skip-to-azure-pipeli.html?childToView=443074#comment-443074

**Comment by DavidStaheli** [comment]
This is available now.  You can tell Azure Pipelines to skip running a pipeline that a commit would normally trigger. Just include `[skip ci]` in the commit message of the HEAD commit and Azure Pipelines will skip running CI. You can also use any of the variations below. This is supported for commits to Azure Repos Git, Bitbucket Cloud, GitHub, and GitHub Enterprise Server.

- `[skip ci]` or `[ci skip]`
- `skip-checks: true` or `skip-checks:true`
- `[skip azurepipelines]` or `[azurepipelines skip]`
- `[skip azpipelines]` or `[azpipelines skip]`
- `[skip azp]` or `[azp skip]`
- `***NO_CI***`

**Comment by vutkin** [comment]
@DavidStaheli [skip ci] is not working.
https://developercommunity.visualstudio.com/content/problem/430367/no-ci-not-being-honored-in-azure-devops.html

**Comment by hugovk** [comment]
Can confirm `[ci skip]` not working.

See https://github.com/python-pillow/Pillow/pull/3805 which skipped Travis CI and AppVeyor but not Azure Pipelines.

**Comment by mloskot** [comment]
_(copying from my [comment posted to Developer Community in response to @hugovk](https://developercommunity.visualstudio.com/idea/420289/add-support-ci-skip-and-azure-skip-to-azure-pipeli.html?childToView=546628#comment-546628))_

I have been using this feature in variety of projects (e.g. Boost library) and it has worked fine.

Here are two test PRs

1. `[skip ci]` - https://github.com/mloskot/ci-test/pull/2
2. `[skip azp]` - https://github.com/mloskot/ci-test/pull/3

The PR from 1. is skipped by all CI services configured for the test repo (Travis CI, CircleCI, AppVeyor, AzP).
The PR from 2. is skipped by AzP only, and the other three run the build.
I have no idea why it's not working for others.

**Comment by hugovk** [comment]
Also works in @mloskot's test repo:

3. `[ci skip]` - https://github.com/mloskot/ci-test/pull/4

But as mentioned, `[ci skip]` doesn't work in https://github.com/python-pillow/Pillow/pull/3805. Why are some repos working and others not?

**Comment by DavidStaheli** [comment]
Thanks for reporting this problem.  We're looking into it ASAP.

**Comment by mloskot** [comment]
### UPDATE to https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-486608120

I'm sorry for confusion, but that 'worked' due to issues in my own configuration. Please, forget that comment.

-----

I can confirm neither `[skip ci]` nor `[skip azp]` is working on Azure Pipelines

1. `[skip ci]` - https://github.com/mloskot/ci-test/pull/2 - Azure builds, but should NOT
2. `[skip azp]` - https://github.com/mloskot/ci-test/pull/3 - Azure builds, but should NOT

**Comment by kelliejos** [comment]
@mloskot and @hugovk , thanks for reporting the issue! Are you currently seeing CI builds running when the [skip ci] or [skip azp] commands are used or only PR builds? Azure DevOps only supports the [skip ci] command variations for CI builds. PR builds will always be run, even if the commit comment contains a [skip ci] command. 

If adding an option to skip PR builds is feature you would like to see, please be sure to suggest a feature on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?sort=votes&type=idea&openOnly=true)!

**Comment by vutkin** [comment]
Hi, Could anyone reopen an issue?

**Comment by mloskot** [comment]
> Are you currently seeing CI builds running when the [skip ci] or [skip azp] commands are used or only PR builds?
> Azure DevOps only supports the [skip ci] command variations for CI builds.


That may explain my confusion. I have seen builds skipped for non-PRs. That convinced me all eorks fine.

**Comment by vutkin** [comment]
@kelliejos We are not talking about PRs, regular builds aren't skipped.

**Comment by hugovk** [comment]
> @mloskot and @hugovk , thanks for reporting the issue! Are you currently seeing CI builds running when the [skip ci] or [skip azp] commands are used or only PR builds? Azure DevOps only supports the [skip ci] command variations for CI builds. PR builds will always be run, even if the commit comment contains a [skip ci] command.
> 
> If adding an option to skip PR builds is feature you would like to see, please be sure to suggest a feature on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?sort=votes&type=idea&openOnly=true)!

I'm talking about PR builds. On the project I mentioned, (virtually) everything is done via feature branches and PRs (as is standard practice on many projects), so I've not seen it on non-PR builds.

Travis CI and AppVeyor skip PR (and non-PR) builds when the skip tag is present, it's a command from the author not to expend CI resources on the PR.

I don't understand the difference between PR and CI builds on AzP. Aren't PR builds just a subset of CI builds? Is the difference documented somewhere? Thanks!

**Comment by mloskot** [comment]
@vishnugms 
> @kelliejos We are not talking about PRs, regular builds aren't skipped.

For https://github.com/boostorg/gil/ library, Azure Pipelines skip builds for any non-PR commits with `[skip azp]` in the message. For example, for commit https://github.com/boostorg/gil/commit/427956fa3f2b61a38f88ae436851ad5705df43be in `develop` branch:

```
commit 427956fa3f2b61a38f88ae436851ad5705df43be
Author: Mateusz Łoskot <mateusz@loskot.net>
Date:   Fri Apr 19 21:40:36 2019 +0200

    [circleci] Enable builds for all branches [skip appveyor]

    One leftover and missing from db8c76bf54c3f073c392152896d9d4c5de67132e

    [skip travis]
    [skip azp]
```

AzP did not start any build at https://dev.azure.com/boostorg/gil/_build

You will see there similar commit, as on screenshot below, but this is for *previous* different commit https://github.com/boostorg/gil/commit/db8c76bf54c3f073c392152896d9d4c5de67132e does not contain any `[skip azp]` in the message, so it was built:

![image](https://user-images.githubusercontent.com/80741/56752461-9684a780-6788-11e9-952f-c42f2b10b247.png)

So, for Boost.GIL project, skipping has worked fine for long time now.

----

That is why I'm being confused because the skippers have worked for me (for non-PR builds) since day one AzP announced the skipping feature.

**Comment by kelliejos** [comment]
@mloskot and @hugovk Azure DevOps does not permit skipping PR builds as they are gated builds.  Allowing a user to bypass gated builds increases the chances that a breaking change could be merged into the code base. Azure DevOps honors the [skip ci] commands on CI builds as the change being built has already been merged.

**Comment by vutkin** [comment]
@kelliejos Why do you think that you know that end-users want? I want use skippers for all builds.
I confirm that AzDevOps doesn't respect skippers from official docs. My code is stored in AzRepos.

![image](https://user-images.githubusercontent.com/25753488/56759317-6269b080-67a1-11e9-9388-db1e9ec52e39.png)

**Comment by hugovk** [comment]
Thanks, but for GitHub PRs, it looks really weird when `[CI skip]` is ignored by Azure Pipelines but honoured by Travis CI and AppVeyor.

I agree it does increase the chance of a breaking change, but sometimes we really do want to skip all CI builds (like a minor or docs change).

**Comment by mloskot** [comment]
> sometimes we really do want to skip all CI builds (like a minor or docs change)

Indeed. Trying to not to waste resources (electricity) at micro-scale may turn into significant saving.
I do purposely add skippers when I know a build is unnecessary and, yes, I do it with a bit of eco-friendly mind on purpose.

**Comment by rgommers** [comment]
> Allowing a user to bypass gated builds increases the chances that a breaking change could be merged into the code base.

There's still a reviewer involved. Second guessing humans isn't helpful. Example: on a repo where I'm a maintainer I made an edit to a plan text file. I want to send it via a PR so it's visible to other maintainers that I'm making a change (pushing directly to master is considered bad form). But I don't need to trigger hours of CPU time worth of CI builds. I'm 99.99% sure I'm not breaking anything. And in the very unlikely case I did break something, I can just go back and fix it or revert the change.

**Comment by MarcoGorelli** [comment]
> @mloskot and @hugovk Azure DevOps does not permit skipping PR builds as they are gated builds. Allowing a user to bypass gated builds increases the chances that a breaking change could be merged into the code base. Azure DevOps honors the [skip ci] commands on CI builds as the change being built has already been merged.

Surely if someone is just making a simple typo fix PR then it should be possible to avoid running 30-60 minutes' worth of tests?
