### ISSUE TITLE
Yaml pipeline parser reverses template step order

### ISSUE THREAD

**Issue by chcosta** [Microsoft/vsts-agent#1275]
The yaml pipeline parser in the preview functionality reverses the order of steps deserialized from a template.

https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Listener/DistributedTask.Pipelines/Yaml/PipelineParser.cs#L440

```
foreach (IStep step in template.Steps)
{
     steps.Insert(i, step);
}

i += template.Steps.Count;
```

I can't imagine this is intentional.  I'd expect this code is intended to be something more like...

```
foreach (IStep step in template.Steps)
{
    steps.Insert(i++, step);
}
```

I haven't done any validation, but at a cursory glance, I'd assume that this needs to be changed as well.

https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Listener/DistributedTask.Pipelines/Yaml/PipelineParser.cs#L421-L451

**Comment by TingluoHuang** [comment]
@chcosta all yaml code in agent repository is out of date and not been used, we moved the code to our internal repository, the bug has been fixed there. i will close the issue here.
