### ISSUE TITLE
[Question] How do I update the PAT on the agent?

### ISSUE THREAD

**Issue by BluMist** [Microsoft/vsts-agent#128]
I have the agent set up to run as a service and using PAT, what happens if the PAT expires? I don't see a way to re-configure the agent.

**Comment by bryanmacfarlane** [comment]
There is an unconfigure cmd which isn't implemented yet.

But, all you have to do is delete the .Agent and .Credentials file to unconfigure.

When we're done, it won't matter because we only be used to register the agent.  We will download and encrypt a token used at runtime

**Comment by bryanmacfarlane** [comment]
see issue #125

**Comment by bryanmacfarlane** [comment]
closing since answered and tracking in #125
