### ISSUE TITLE
Unable to get sources from Github Enterprise with proxy

### ISSUE THREAD

**Issue by tinoji** [Microsoft/vsts-agent#1281]
## Have you try trouble shooting doc?
Yes

## Agent version and platform
2.123.0

OS of the machine running the agent
Windows

## VSTS type and version
VisualStudio.com

## What's not working?
I want to get source from Github Enterprise via an authenticated proxy.
First, I tried to set environment variables `VSTS_HTTP_PROXY`, `VSTS_HTTP_PROXY_USERNAME` and `VSTS_HTTP_PROXY_PASSWORD` in the build definition. I referred this issue: https://github.com/Microsoft/vsts-agent/issues/670

Second, set proxy git config by using `prejobexecution`.
http://www.codewrecks.com/blog/index.php/2017/06/10/running-powershell-before-get-sources-in-vsts-tfs-build/

```
git config --global http.sslVerify true
git config --global https.sslVerify true
git config --global https.proxy http://username:pass@IP:port
```

However, the following error occurred in both.

```
******************************************************************************
Starting: Get Sources
******************************************************************************
Syncing repository: my github connection (Git)
Prepending Path environment variable with directory containing 'git.exe'.
git version
git version 2.12.2.windows.3
git lfs version
git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)
git init "d:\a\1\s"
Initialized empty Git repository in d:/a/1/s/.git/
git remote add origin https://git.my.domain/my-organization/my-branch
git config gc.auto 0
git config --get-all http.https://git.my.domain/my-organization/my-branch.extraheader
git config --get-all http.proxy
git remote set-url origin https://********:********@git.my.domain/my-organization/my-branch
git remote set-url --push origin https://********:********@git.my.domain/my-organization/my-branch
git fetch --tags --prune --progress --no-recurse-submodules origin
* Couldn't find host git.my.domain in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying **.**.**.**[server IP]...
* TCP_NODELAY set
* Connected to git.my.domain (**.**.**.**[server IP]) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\LR\mms\Services\Mms\Provisioner\TaskAgent\agents\2.123.0\externals\git\mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* Unknown SSL protocol error in connection to git.my.domain:443 
* Closing connection 0
fatal: unable to access 'https://********:********@git.my.domain/my-organization/my-branch/': Unknown SSL protocol error in connection to git.my.domain:443 
Git fetch failed with exit code: 128
******************************************************************************
Finishing: Get Sources
******************************************************************************
```

Get sources setting is:
```
Server URL: https://git.my.domain/organization/branch
User name: my user name
Password/Token Key: my password (and tried token also)
```

**Comment by TingluoHuang** [comment]
@tinoji i noticed you are using hosted build agent, do you really need a proxy to connect to your Github Enterprise repository? the hosted agent is an Azure VM that already on public internet.
```
Unknown SSL protocol error in connection to git.my.domain:443 
```
Can you fetch your git repository from any machine in public network (like: Azure VM)?

**Comment by tinoji** [comment]
@TingluoHuang 
I did it and noticed that `@` in proxy user name was not escaped! I can fetch the repo by modified git config!! thx:)
But I can't do that with environmental variables of the build definition. Is it the only way to create git-config prejobexecution? It would be not easy for general users...

**Comment by TingluoHuang** [comment]
@tinoji for VSTS hosted build, we normally assume any resource you consumed in your build is in public internet.
can you share more detail about your github enterprise configuration? why need to use proxy access it? does the git repo not public accessible from internet?

**Comment by tinoji** [comment]
Yes. Our on-premises github enterprise is restricted within the company network. We always have to use proxy to access it from the other networks.
In such a case, do you recommend using TFS instead?

**Comment by TingluoHuang** [comment]
still depends i think, if most resource you build needs is in your private network then TFS might make more sense, like: your use some UNC share for build drops or like you are using github enterprise behind proxy.

@madhurig for more idea or suggestion.

**Comment by madhurig** [comment]
@tinoji: For your case, it makes sense to use an on-premises agent that is behind the firewall and not use "Hosted" agent. The agent can be installed and configured on Windows, Linux or macOS. Please check our documentation on how to configure the on-premises agent with VSTS: https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows 

Thanks,
Madhuri

**Comment by tinoji** [comment]
@TingluoHuang @madhurig 
It seems a better way to use the on-premises agent 👍  But the method I described above serves my needs for now. I'll consider it. Thanks a lot! You can close this issue! 
Later, I'll leave my custom build task for someone's help.

**Comment by tinoji** [comment]
This is a build task to set git proxy :)
https://github.com/tinoji/vsts-task-gitProxy

**Comment by madhurig** [comment]
Thanks @tinoji! 

We are building better support for GitHub Enterprise. Would you be willing to try out the feature and give us feedback? Please send us your VSTS account name if you would like to participate in the early preview. You can email me at madhurig at microsoft.com. 

Thanks,
Madhuri

**Comment by tinoji** [comment]
So cool!! Of course I want!
I'll email you soon!
