### ISSUE TITLE
Can't register deployment group agent with manually created PAT token

### ISSUE THREAD

**Issue by keenjus** [Microsoft/vsts-agent#1284]
## Agent version and platform
2.124.0 on Windows Server 2016

## VSTS type and version
VisualStudio.com

## What's not working?

[Official docs say](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows)
> For the scope select **Agent Pools (read, manage)** and make sure all the other boxes are cleared. If its a deployment group agent, for the scope select **Deployment group (read, manage)** and make sure all the other boxes are cleared.

But the **Deployment group (read, manage)** option does not exist although **Agent Pools (read, manage)** does.

So when I create a PAT token with the scope **Agent Pools (read/manage)** I get the following errors when trying to configure the agent:
> You are not authorized to access https://\<account\>.visualstudio.com
> TF400813: Resource not available for anonymous access. Client authentication required.

But it works with the automatically generated PAT token when copying the install script. I checked what scopes it uses but none are selected even though "Selected scopes" option is ticked.

When I add the **Agent Pools (read, manage)** scope to the automatically generated PAT token and save the changes it doesn't work anymore, giving me the same authorization/access errors.

Is this intended?

**Comment by TingluoHuang** [comment]
@chshrikh

**Comment by spongessuck** [comment]
I just set one up by clicking on the 'Registration Script' link on the right side of the toolbar when you open a deployment group and clicked the 'use PAT in registration script' checkbox and that seemed to work, although the token itself wasn't configured with any permissions when I looked in my security settings.

Docs should be updated if things have changed, though.

**Comment by keenjus** [comment]
@spongessuck If you add a random scope or select "All scopes" does it stop working?

**Comment by chshrikh** [comment]
This has been fixed and will be available in next deployment ( 2-3 days ). With this fix, you will be able to see the PAT scope option. Deployment group (read, manage) will be available in your security page for generating the PAT. Meanwhile you can get unblocked by using the automatically generated PAT in the configuration script form Deployment Group Page; Select the deployment group -> click on Details -> enable the option 'Use personal access token in the script for authentication' -> Copy the script..

**Comment by chshrikh** [comment]
this is has been fixed.
