### ISSUE TITLE
AutoLogon mode not working when installed using Azure Extension or DevTestLabs artifact

### ISSUE THREAD

**Issue by EdwinVW** [Microsoft/vsts-agent#1287]
## Agent version and platform
2.124.0 (on Windows 10 Pro x64)
VSTS

## What's not working?
I install the agent using an Azure Extension or DevTestLabs Artifact while deploying a VM. But then the AutoLogon mode does not work. This means that when the machine is started, the agent is not automatically started. I use the same user-account to run the agent as to logon to the machine. When I run the same command when logged into the machine (RDP), it does work. By comparing the logs I think it has something to do with the way the user is logged in when running the command from the Azure Extension or DevTestLabs Artifact (see logging).

I see this behaviour on Windows 10 Pro v.1709 (x64) and Windows Server 2016 (x64). What is strange is that on Windows 10 RS2 Pro (x64), it does work as expected when installed from Azure Extension or DevTestLabs artifact (I tried this as an experiment).

This is the command-line I use (secrets obfuscated):
` .\config.cmd --unattended --url https://myaccount.visualstudio.com --auth pat --token 61...8a --pool MyPool --runAsAutoLogon --windowsLogonAccount testuser1 --windowsLogonPassword 0a...4R --overwriteAutoLogon`

## Agent and Worker's diag log
In the logs I find a difference. When running from the Azure Extension or DevTestLabs Artifact, a warning is emitted in the log about not being able to find the user's SID in the registry for inserting the run task:

From Azure Extension or DevTestLabs Artifact (notice the warning):
```
...
[2017-11-03 11:09:45Z INFO HostContext] Well known directory 'Root': 'C:\Build'
[2017-11-03 11:09:45Z INFO AutoLogonRegistryManager] Agent auto logon startup command: 'C:\Windows\system32\cmd.exe /D /S /C start "Agent with AutoLogon" "C:\Build\run.cmd" --startuptype autostartup'
-> [2017-11-03 11:09:45Z WARN WindowsRegistryManager] Couldnt get the subkey 'S-1-5-21-2773755948-758306923-2095025604-500\SOFTWARE\Microsoft\Windows\CurrentVersion\Run. Will not be able to set the value.
[2017-11-03 11:09:45Z INFO NativeWindowsServiceHelper] Successfully unloaded the profile for testuser1.
[2017-11-03 11:09:45Z INFO WhichUtil] Which: 'powercfg.exe'
[2017-11-03 11:09:45Z INFO WhichUtil] Location: 'C:\Windows\system32\powercfg.exe'
[2017-11-03 11:09:45Z INFO AutoLogonManager] Running powercfg.exe with /Change monitor-timeout-ac 0
[2017-11-03 11:09:45Z INFO ProcessInvoker] Starting process:
...
```

When logged into the machine:
```
...
[2017-11-03 11:26:53Z INFO HostContext] Well known directory 'Root': 'C:\Build'
[2017-11-03 11:26:53Z INFO AutoLogonRegistryManager] Agent auto logon startup command: 'C:\Windows\system32\cmd.exe /D /S /C start "Agent with AutoLogon" "C:\Build\run.cmd" --startuptype autostartup'
[2017-11-03 11:26:53Z INFO WhichUtil] Which: 'powercfg.exe'
[2017-11-03 11:26:53Z INFO WhichUtil] Location: 'C:\Windows\system32\powercfg.exe'
[2017-11-03 11:26:53Z INFO AutoLogonManager] Running powercfg.exe with /Change monitor-timeout-ac 0
[2017-11-03 11:26:53Z INFO ProcessInvoker] Starting process:
...
```

**Comment by TingluoHuang** [comment]
@dpksinghal @nigurr for auto-logon question.

**Comment by nigurr** [comment]
@EdwinVW Thanks for reaching out. We will be investigating into this issue. Can you please try using RS2 build to unblock temporarily?

**Comment by EdwinVW** [comment]
Yes, I'm not blocked at the moment. Thanks for looking into this issue!

**Comment by nigurr** [comment]
@EdwinVW sorry for the delayed response. Can you please share the template which you are using to spin up the agent?
or Sample build definition?

**Comment by EdwinVW** [comment]
@nigurr I don't use a template or build definition. I use a DevTestLabs artifact (which is in fact a Powershell script) to install the agent. I've included the PowerShell script I used as attachment.

[install-buildagent.zip](https://github.com/Microsoft/vsts-agent/files/1551546/install-buildagent.zip)

**Comment by nigurr** [comment]
@EdwinVW from the DevTestlabs repo, there's no official support for interactive agent - https://github.com/Azure/azure-devtestlab/blob/master/Artifacts/windows-vsts-build-agent/vsts-agent-install.ps1#L248
Can you please check once?

**Comment by EdwinVW** [comment]
@nigurr I know. The artifact I mentioned in my last comment was created by me. I took the standard artifact you're referring to and changed the command-line in this script so it uses uses the autologon feature. I've attached the script in my last comment.

**Comment by ShreyasRmsft** [comment]
Could you try a few things:

1) Have you tried re-running the artifact after say manually running the script on the vm once via rdp
2) Manually check if the subkey exists (the one the script claims doesn't)
3) Try out a simple powershell script that just tries to read this subkey and run it as an artifact or extension

It is a possibility that when running scripts via an atifact they may not have access to certain parts of the registry on those particular OSes

This is just a hunch but it will provide us with more info as to what is going on.

**Comment by ShreyasRmsft** [comment]
@EdwinVW Hi any progress?

**Comment by EdwinVW** [comment]
@ShreyasRmsft 

1. This works. Also when logging in using RDP first and then running the artifact on this machine from DevTestLabs, it works.
2. If I log in using RDP and check the key it exists.
3. No time to execute this (I'm not actively working on the project I needed this for).

**Comment by ShreyasRmsft** [comment]
@EdwinVW, this artifact is in our backlog. We will look into the issue more closely when we pick it up. I am closing this issue out now.

**Comment by sayandaw** [comment]
When we join the Machine to the Domain the Autologon does not work !
Was this fixed? Using 

Agent.Version | 2.171.1
-- | --
