### ISSUE TITLE
Custom condition reference Agentless Phase

### ISSUE THREAD

**Issue by tiagorosendo** [Microsoft/vsts-agent#1291]
Which add of #711 we can use custom conditions to run a task, in my scenario i need apply a custom condition based on my previous agentless phase, have any way to make this?

For example: i will deploy my app in K8s cluster, after deploy i have a manual intervention task, if this intervention is reject i need to rollback my deploy, if is resumed i need ignore rollback task and go to next env...

**Comment by bryanmacfarlane** [comment]
Not an agent issue.  Create an issue here:  https://developercommunity.visualstudio.com
