### ISSUE TITLE
Git-lfs support missing

### ISSUE THREAD

**Issue by pete-thompson** [Microsoft/vsts-agent#1297]
## Agent version and platform
2.124.0
Windows

## VSTS type and version
VisualStudio.com

## What's not working?
git-lfs isn't installed with the agent, so a pulling from a repository enabled with lfs fails. 

I had an older version of the agent running which used to work just fine with lfs, but I had to reinstall it. My builds started failing after the reinstall. I've worked around the problem by putting a copy of git-lfs into the <agent>/externals/git/cmd folder - git lfs now functions correctly.

**Comment by TingluoHuang** [comment]
@pete-thompson the agent has never packaged git-lfs with it. you always need to install git-lfs yourself.

**Comment by pete-thompson** [comment]
Older versions of the agent included git-lfs - my build server was working fine until I had to uninstall/reinstall the agent at which point builds that relied on git-lfs failed. I hadn't installed git-lfs previously. Sadly I don't recall exactly which version I was using previously (it would have been installed early in 2017).

**Comment by bryanmacfarlane** [comment]
@pete-thompson - can you point me to the version that contained git-lfs?  We never did that.  But I would be interested in unzipping the version you're referring to and taking a look.  The releases tab has all the versions.
