### ISSUE TITLE
Unable to queue builds via API using YAML definitions

### ISSUE THREAD

**Issue by cameronattard** [Microsoft/vsts-agent#1298]
## Agent version and platform
Version of your agent? 
2.124.0

OS of the machine running the agent?
Linux

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? 
https://origin-energy.visualstudio.com

## What's not working?
When I try to trigger a build using https://origin-energy.visualstudio.com/DefaultCollection/CloudServices/_apis/build/builds?api-version=2.0, I get the following response:
`{
    "ClassName": "Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException",
    "Message": "Could not queue the build because there were validation errors or warnings.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146232832,
    "Source": null,
    "WatsonBuckets": null,
    "m_logException": false,
    "m_reportException": false,
    "m_errorCode": 0,
    "m_logLevel": "warning",
    "m_eventId": 3000,
    "ValidationResults": [
        {
            "result": "error",
            "message": "An error occurred while loading the YAML build definition. An object ID must be 40 characters long and only have hex digits. Passed in object ID: ."
        }
    ]
}`

This only happens when queueing using the API. Manual triggers from the web UI and git triggers work fine.

**Comment by ericsciple** [comment]
@cameronattard did you queue the build against a branch, tag, or commit? My guess is you queued against a commit, but did not use the full 40 char sha (queue against short hash not impl yet)

**Comment by cameronattard** [comment]
Just managed to get it working by explicitly specifying sourceBranch: "/refs/heads/master". Previously I was omitting that field as the documentation states: "The branch to build. This is optional. If not specified, the default branch for the definition will be used."

Is there any way to specify the default branch in the YAML build definition?

**Comment by bryanmacfarlane** [comment]
Also, you might want to use a later api version ?? not sure if needed.  Anyways, I would recommend you try it in the browser and then use browser dev tools or fiddler to see what our app does (we use the public api)

closing since I think you figured it out
