### ISSUE TITLE
PowerShell 2.* preview step fails on Linux

### ISSUE THREAD

**Issue by jamesbannan** [Microsoft/vsts-agent#1300]
## Agent version and platform
2.120.2

OS of the machine running the agent? OSX/Windows/Linux...
Ubuntu 16.04 LTS

## VSTS type and version
VisualStudio.com

## What's not working?
I have a VSTS Build using the native PowerShell step (preview version 2.*) to run an Inline Script PowerShell script on an Ubuntu-based worker agent.

This was working, but PowerShell on Linux has recently changed the executable from `powershell` to `pwsh`. This is causing the native step to fail with:

`2017-11-20T02:08:35.3898680Z ##[error]Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

A workaround might be to create a bash alias and make it available to all users, but that's cludgy.

**Comment by jamesbannan** [comment]
These are the details of the step:

`Task         : PowerShell
Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.125.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)`

**Comment by ericsciple** [comment]
Closing the issue on this repo and [opening here](https://github.com/Microsoft/vsts-tasks/issues/5894)
