### ISSUE TITLE
YAML definitions unable to find Service Endpoints.

### ISSUE THREAD

**Issue by MarcusFelling** [Microsoft/vsts-agent#1301]
## Agent version and platform
Version of your agent? 2.102.0/2.100.1...
**2.124.0**

OS of the machine running the agent? OSX/Windows/Linux...
**Windows Server 2012 R2**

## VSTS type and version
**VisualStudio.com**

If VisualStudio.com, what is your account name? http://account.visualstudio.com
**https://outselldev.visualstudio.com**

## What's not working?
New YAML definition is unable to find Service Endpoint. I've tried ID (GUID) and name.
"An error occurred while loading the YAML build definition. A service endpoint with name 2ed127ec-13ed-4132-8956-56c3345188f5 could not be found. The service endpoint does not exist or has not been authorized for use. "

YAML definition:
[portal.txt](https://github.com/Microsoft/vsts-agent/files/1486325/portal.txt)

## Agent and Worker's diag log
Unable to queue build because of this error.

**Comment by ericsciple** [comment]
@MarcusFelling can you try making a trivial edit in the definition editor in the web UI and saving the definition? if you have use permission on the endpoin, clicking save should load the file, discover you use the endpoint in the file, and then authorize it's use based on your permissions.

is your yaml file in a VSTS repo or a GitHub repo?

**Comment by MarcusFelling** [comment]
Thanks for the quick reply! I have made an edit to a variable in the build definition, saved, and get the same error. The yaml file is at the root of my VSTS repo. The build definition is in a folder called YAML.

**Comment by MarcusFelling** [comment]
Turns out it was because I was using a topic branch to test. I merged the yaml file into the master branch and changed the default branch in the definition to master. Sounds like this is still a bug? I should be able to test yaml changes in a topic branch.

**Comment by ericsciple** [comment]
It's a limitation of how [resource authorization for yaml](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-authz.md#resources) works today. In the future we are planning to have a way to manage in the web UI. Today we don't apply resource authorization on-push for every branch. I'm not sure whether we will totally relax that constraint in the future, or whether this is a partial approach (e.g. only on trigger branches). Feedback welcome.
