### ISSUE TITLE
Updating a Release Name

### ISSUE THREAD

**Issue by alexdegroot** [Microsoft/vsts-agent#1303]
I'm trying to update my Release-name based on a version I read from my artifact folder. In this way I can visually relate the artifact number to the release.
When I on incident used the Build-update step, it did update the associated build:
Write-Host "##vso[build.updatebuildnumber]$($Env:BUILD_BUILDNUMBER)-($version)"
Is this expected behavior?
Most important, how do I update my Releasename, as this doesn't seem to work:
Write-Host "##vso[release.updatereleasenumber]$version"
Thank you!

Original item: https://github.com/Microsoft/vsts-task-lib/issues/289
Agent Version: 2.117.2

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB can comment on the enhancement request.

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB ?

**Comment by GitHubSriramB** [comment]
@alexdegroot - we don't support ##vso[release.updatereleasenumber] command. We will be adding this support.

What is the value of $version variable you have used in the script? Would you be able to achieve what you want by setting relevant release name mask on the release definition?

**Comment by alexdegroot** [comment]
@GitHubSriramB $version is resolved from some artifacts. I use the release to publish NuGet-nupkg files. I do extract the version out of it and execute some quality measurements. Then I do a NuGet publish and tag the source code. I'd like to have visual tractability for successful releases which did indeed publish something.

**Comment by GitHubSriramB** [comment]
Thanks for clarifying. We have added this to our backlog.
