### ISSUE TITLE
CCMenu Support

### ISSUE THREAD

**Issue by devandanger** [Microsoft/vsts-agent#1304]
Curious if you guys plan to or have any current support for CCMenu.  Like the [following](https://github.com/erikdoe/ccmenu/wiki/Server-Implementor-Notes)

Understandably this is probably not the most appropriate place to look for a feature request, figured I'd give it a shot though.

**Comment by ericsciple** [comment]
User voice would be a better place for this type of feature request (server side). This repo is for the agent itself.

**Comment by devandanger** [comment]
Done thanks.
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/32444444-vsts-support-for-ccmenu
