### ISSUE TITLE
TFS 2018 Event Log Debug

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/vsts-agent#1306]
I have a local TFS 2018 server. I also upgrade from 2018 RC to the latest release. 

I have noticed that the Microsoft-Team Foundation Server 2018 event log is logging hundreds of informational debug entries, most with: TFS ProductTrace Entry. Every minute there are 3 or 4 event log entries generated which quickly add up.

Is this normal logging behavoir? Can I turn this off?

**Comment by nschonni** [comment]
https://developercommunity.visualstudio.com/spaces/22/index.html might be a better place for this one. This issue tracker is just for the build agent
