### ISSUE TITLE
Failure in logging telemetry is failing the task

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-agent#1315]
## Have you try trouble shooting doc?
Release https://mseng.visualstudio.com/96a62c4a-58c2-4dbb-94b6-5979ebc7f2af/_release?releaseId=29465&_a=release-logs

I had a look at code to see where the below exception can come from, it looks like the below exception might happen while doing GetClient call in the initialize method of CustomerIntelligenceService if it fails to get location data to get the client. In our scenario we were running out of sockets on agent so most of the APIs  calls would have failed. 

I think we should handle this failure also while trying to publish telemetry and ignore the error.

## Agent version and platform
Hosted Agent 11

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? 
http://mseng.visualstudio.com

## What's not working?
Logging telemetry in tasks in logging an error on failure, it should just be a warning.

**Comment by omeshp** [comment]
Another release that failed because of this issue: https://mseng.visualstudio.com/b924d696-3eae-4116-8443-9a18392d8544/_release?definitionId=1198&releaseId=2303410&_a=release-logs

**Comment by nigurr** [comment]
Addressed here: https://github.com/Microsoft/vsts-agent/pull/1324
