### ISSUE TITLE
Xamarin.Android capability missing on OS X on-prem build agent

### ISSUE THREAD

**Issue by kacperryniec** [Microsoft/vsts-agent#1317]
## Agent version and platform
Agent.Version | 2.126.0

OS of the machine running the agent? OSX 

## VSTS type and version
VisualStudio.com + OnPrem Agent hosted on OS X

If VisualStudio.com, what is your account name? http://solidbraincom.visualstudio.com

## What's not working?
Xamarin.Android capability is missing. There's no /Library/Frameworks/Xamarin.Android.framework/Commands/generator file on the build machine.

**Comment by kacperryniec** [comment]
The solution mentioned in one of the old comments: https://github.com/Microsoft/vsts-tasks/issues/2889#issuecomment-254662620 seems to do the trick, however, it would be nice to know why it stopped working.

Quick fix: "Manually add the Xamarin.Android capability to each of my eight agent instances by entering the key Xamarin.Android and the value."

**Comment by andrewtechhelp** [comment]
I think this might be related (if not the same) as an issue I raised in the VSTS Tasks repository a month or so ago: https://github.com/Microsoft/vsts-tasks/issues/5660

**Comment by bryanmacfarlane** [comment]
Yeah, the agent itself (this repo) has no knowledge of xamarin, etc...  That's a task concern.  Agent just knows how to exec tasks.

**Comment by kacperryniec** [comment]
@bryanmacfarlane well it seems that the line that's causing this issue - exact check for the capability "Xamarin.Android, is in this repo...
https://github.com/Microsoft/vsts-agent/blob/2b1051a2f934f6e25e422715108993117f562598/src/Microsoft.VisualStudio.Services.Agent/Capabilities/NixCapabilitiesProvider.cs#L76

**Comment by oliverchristen** [comment]
Since version 8.1.0 of Xamarin.Android there is no such file '/Library/Frameworks/Xamarin.Android.framework/Commands/generator' any more and I had to add the Xamarin.Android capability manually.
