### ISSUE TITLE
VSTS Agent Installation on Alpine Linux

### ISSUE THREAD

**Issue by BrendanThompson** [Microsoft/vsts-agent#1319]
Hi there,

Trying to get some automation done with building VSTS Agents, and am having a few issues. Below are the details. (**Not TFS On-Prem**)

|Operating System|Agent Version|
|---|---|
|Alpine Linux|v2.124.0|

## What's not working?
After downloading and extracting the latest version of the `vsts-agent-*` agent (_I have tried both Ubuntu and Rhel_) and then attempting to execute
```
/vsts/bin/Agent.Listener
```
I get the following error:
```
./bin/Agent.Listener: No such file or directory
```
Although the file clearly exists, and is executable. I presume its because there isn't support for Alpine, however would like some confirmation. If there is no support for Alpine are there plans to support it in the future?

**Comment by bryanmacfarlane** [comment]
alpine linux is not yet supported by net core

https://github.com/dotnet/core/issues/226 

when they support it, we will

**Comment by bryanmacfarlane** [comment]
reactivate if that doesn't answer your question

**Comment by zioalex** [comment]
I think that today there is a full .NET support as documented here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine .
This is related to the #2931 
Can we resume this one?

**Comment by SymbioticKilla** [comment]
@bryanmacfarlane Any plans? It would very nice to decrease the size of images and limit CVEs warnings.

**Comment by KarenTazayan** [comment]
Hi everyone, 

Any news about this topic?

I really need it to run official **docker:dind** images as build agents in Azure Pipelines. Especially when .NET 6 is officially supported on Alpine.

**Comment by faizan1196** [comment]
hi @KarenTazayan  im also working on that but now docker inside docker is not working i am also stuck on that however i have some improvement using img solution but now stuck to install missing dependencies. for devops agent iputils-ping \ libcurl4 \ libicu60 \ libunwind8 \ netcat \ libssl1.0 \

**Comment by jakuboskera** [comment]
Please reopen this and implement VSTS Agent on Alpine Linux.

**Comment by dbwodlf3** [comment]
https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md
