### ISSUE TITLE
Deploy Agent: API resource location is not registered

### ISSUE THREAD

**Issue by EP01** [Microsoft/vsts-agent#1322]
## Agent version and platform
2.124.0 onwards ...

## OS of the machine running the agent? OSX/Windows/Linux...
Windows Server 2008 R2

## VSTS type and version
On-Prem TFS 

## If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
2018 (Version 16.122.27102.1)

## What's not working?
When I try to register an agent as part of a deployment group with any version of the agent from 2.124.0 onwards I get the error `API resource location [GUID] is not registered on [URL]`.

![agent](https://user-images.githubusercontent.com/22454118/33774495-58fe8962-dc33-11e7-95dd-cec85034a16f.PNG)

This screenshot was taken after trying 2.126.0 and I have tried 2.124.0, 2.125.0, and 2.125.1 which all show the same behaviour. Version 2.123.0 works fine.

**Comment by TingluoHuang** [comment]
@EP01 what server URL did you typed? make sure it doesn't contains `/yourcollection`, ex. `http://myTFS:8080/tfs` instead of `http://myTFS:8080/tfs/DefaultCollection`.
if you still have the issue, please send me your Agent diag log to `tihuang @ microsoft.com`

**Comment by EP01** [comment]
@TingluoHuang The server URL is definitely in the correct format. I've just emailed you the log file. Thanks!

**Comment by TingluoHuang** [comment]
@EP01 thanks for sharing the log, i checked the code, looks like API resource location 2f0aa599-c121-4256-a5fd-ba370e0ae7b6 is not there for TFS2018 RTM.
@chshrikh can you help customer about his deployment group agent configure?
he is getting error during agent config.
```
API resource location 2f0aa599-c121-4256-a5fd-ba370e0ae7b6 is not registered on http://tfs:8080/tfs/DefaultCollection
```

**Comment by EP01** [comment]
Thanks @TingluoHuang! Configuring an agent version 2.123.0 works fine on TFS2018 RTM, so this must be because of a change made between 2.123.0 and 2.124.0.

**Comment by chshrikh** [comment]
@EP01 yes there are few additional changes present with latest agent version for deployment group which are not supported with TFS 2018 RTM. You need to use agent of version 2.123.0 which is compatible with TFS 2018 RTM.

**Comment by BonScottCH** [comment]
Hi Iam having the same issue with version 2.181.0. Ist there a place where i can download 2.123.0 ? or is there a bugfix planned at some point?
We are running TFS 2018 on site.
