### ISSUE TITLE
Each TFS NPM build task has unnecessary delays of 2 * 3 minutes

### ISSUE THREAD

**Issue by erikrenberg** [Microsoft/vsts-agent#1325]
We're using TFS 2017 Update 2 on premises, and we have builds that use NPM tasks. We've noticed a two 3 minute+ delays in each NPM task in our builds. The builds do work, but of course take unnecessarily long.

_What is causing these delays? Is it a bug in vsts-agent? Or in Node that is causing node to not terminate correctly?_

More info:
* We've tried updating the vsts-agent on the build server to 2.124 (from 2.117.2) but it makes no difference. 
* Running on Windows 10 x64.
* Running npm on a command prompt has no delays.

This questions is very much like the following one, but as you will be able to see below, it is not _installing_ that cases the delays, but instead *the delays occur for every npm command*. https://stackoverflow.com/questions/46900297/tfs-npm-install-build-task-hanging/46901603#46901603.

We're using Node 8.9.0 which is the new LTS (Long Time Support) compared to the above answer which mentions 6.x LTW which is still available.

The following log file clearly shows the two delays. The build just calls **"npm version"**. The log shows that the **tasks calls npm.cmd twice (marked in bold**) Each of those commands runs quickly but **after it is done, it waits for 3 minutes and 8 seconds before continuing (also marked bold)**.

When I look at the processes on the build computer, I see the node-processes in task manager, and towards the end when the last 3 minutes have passed, they disappear and the build completes.

_I'd like to be able to use the latest Node LTS and not have these delays...._ Anybody got any ideas?

> 2017-12-11T12:18:56.8791238Z ##[section]Starting: Build
> 2017-12-11T12:18:56.8811239Z Current agent version: '2.124.0'
> ....
> **2017-12-11T12:18:59.4928761Z [command]C:\Program Files\nodejs\npm.cmd config list -l**
> 2017-12-11T12:18:59.8608148Z npm info it worked if it ends with ok
> 2017-12-11T12:18:59.8608148Z npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 2017-12-11T12:18:59.8608148Z npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 2017-12-11T12:18:59.8608148Z npm verb cli   'prefix',
> 2017-12-11T12:18:59.8608148Z npm verb cli   '-g' ]
> 2017-12-11T12:18:59.8608148Z npm info using npm@5.5.1
> 2017-12-11T12:18:59.8608148Z npm info using node@v8.9.0
> 2017-12-11T12:18:59.8638322Z npm verb exit [ 0, true ]
> 2017-12-11T12:18:59.8648327Z npm info ok 
> 2017-12-11T12:19:00.2308372Z npm info it worked if it ends with ok
> 
> ....
> 
> 2017-12-11T12:19:00.2438380Z version = false
> 2017-12-11T12:19:00.2438380Z versions = false
> 2017-12-11T12:19:00.2438380Z viewer = "browser"
> 2017-12-11T12:19:00.2438380Z 
> 2017-12-11T12:19:00.2438380Z 
> 2017-12-11T12:19:00.2438380Z npm verb exit [ 0, true ]
> **2017-12-11T12:19:00.2438380Z npm info ok 
> 2017-12-11T12:22:08.4599528Z ##[debug]rc:0**
> 2017-12-11T12:22:08.4599528Z ##[debug]success:true
> 2017-12-11T12:22:08.4639831Z ##[debug]exec tool: C:\Program Files\nodejs\npm.cmd
> 2017-12-11T12:22:08.4639831Z ##[debug]Arguments:
> 2017-12-11T12:22:08.4639831Z ##[debug]   version
> **2017-12-11T12:22:08.4639831Z [command]C:\Program Files\nodejs\npm.cmd version**
> 2017-12-11T12:22:08.9200693Z npm info it worked if it ends with ok
> 2017-12-11T12:22:08.9210539Z npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 2017-12-11T12:22:08.9210539Z npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 2017-12-11T12:22:08.9210539Z npm verb cli   'prefix',
> 2017-12-11T12:22:08.9220697Z npm verb cli   '-g' ]
> 2017-12-11T12:22:08.9220697Z npm info using npm@5.5.1
> 2017-12-11T12:22:08.9220697Z npm info using node@v8.9.0
> 2017-12-11T12:22:08.9260537Z npm verb exit [ 0, true ]
> 2017-12-11T12:22:08.9260537Z npm info ok 
> 2017-12-11T12:22:09.2800875Z npm info it worked if it ends with ok
> 2017-12-11T12:22:09.2800875Z npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 2017-12-11T12:22:09.2810914Z npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 2017-12-11T12:22:09.2810914Z npm verb cli   'version' ]
> 2017-12-11T12:22:09.2810914Z npm info using npm@5.5.1
> 2017-12-11T12:22:09.2810914Z npm info using node@v8.9.0
> 2017-12-11T12:22:09.3470911Z { npm: '5.5.1',
> 2017-12-11T12:22:09.3470911Z   ares: '1.10.1-DEV',
> 2017-12-11T12:22:09.3470911Z   cldr: '31.0.1',
> 2017-12-11T12:22:09.3470911Z   http_parser: '2.7.0',
> 2017-12-11T12:22:09.3470911Z   icu: '59.1',
> 2017-12-11T12:22:09.3470911Z   modules: '57',
> 2017-12-11T12:22:09.3470911Z   nghttp2: '1.25.0',
> 2017-12-11T12:22:09.3470911Z   node: '8.9.0',
> 2017-12-11T12:22:09.3470911Z   openssl: '1.0.2l',
> 2017-12-11T12:22:09.3470911Z   tz: '2017b',
> 2017-12-11T12:22:09.3470911Z   unicode: '9.0',
> 2017-12-11T12:22:09.3470911Z   uv: '1.15.0',
> 2017-12-11T12:22:09.3470911Z   v8: '6.1.534.46',
> 2017-12-11T12:22:09.3470911Z   zlib: '1.2.11' }
> 2017-12-11T12:22:09.3490815Z npm verb exit [ 0, true ]
> **2017-12-11T12:22:09.3490815Z npm info ok 
> 2017-12-11T12:25:17.5877149Z ##[debug]rc:0**
> 2017-12-11T12:25:17.5877149Z ##[debug]success:true
> 2017-12-11T12:25:17.5887154Z ##[debug]Npm command succeeded with code: 0
> 2017-12-11T12:25:17.5887154Z ##[debug]cleaning up...
> 2017-12-11T12:25:17.5947468Z ##[debug]task result: Succeeded
> 2017-12-11T12:25:17.5997217Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]npm exited with return code: 0
> 2017-12-11T12:25:17.6027223Z ##[section]Finishing: npm version

**Comment by bryanmacfarlane** [comment]
This is not an agent issue.  Create an issue in the vsts-tasks repo (however I believe it's something to do with npm)  But we can route from there.
