### ISSUE TITLE
Agent pre-requisites problem   ./config.sh

### ISSUE THREAD

**Issue by guanzhongpeng** [Microsoft/vsts-agent#1327]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
Ubuntu 16.04 LTS

## VSTS type and version
TFS 2018

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?

If VisualStudio.com, what is your account name? http://account.visualstudio.com

## What's not working?
agent  insall

## Agent and Worker's diag log

When i  execute  ./config.sh

myagent@i-nlrkmuag:/data/myagent$ ./config.sh
Failed to load /data/myagent/bin/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/data/myagent/bin/libcoreclr.so'

**Comment by bryanmacfarlane** [comment]
Pre-reqs are not installed correctly.  Covered here
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-linux#check-prerequisites

You can also install the latest agent from github releases - v2.126.0 or greater (VSTS in the docs).  It works fine.  What's good about that version is it now carries a script to install the pre-reqs for you.

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envlinux.md

https://github.com/Microsoft/vsts-agent/releases/tag/v2.126.0

**Comment by mocleiri** [comment]
I hit the same error in 2.165.1 when building a docker container for the agent.  For me I saw the error when the current working directory wasn't in the agent directory when running config.sh. 

After I cd'd to the agent directory it worked fine.

**Comment by armanriazi** [comment]
Yep, the red messages because the command-line path is out of folder agent, so it is the better "cd" to agent folder and then run "config.sh"
