### ISSUE TITLE
Multiple Agents via ARM template

### ISSUE THREAD

**Issue by joricteixeira** [Microsoft/vsts-agent#1330]
## Agent version and platform
Azure VM Extension 1.0 with minor auto upgrade

OS of the machine running the agent?
2012-R2-Datacenter
and
2016-Datacenter

## VSTS type and version
VisualStudio.com

joricteixeira.visualstudio.com
and
braspag.visualstudio.com

## What's not working?
I've provisioned a VM from template:
https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-with-rdp-port

And customized adding 2 Microsoft.VisualStudio.Services.TeamServicesAgent resources

> {
           "name": "[concat(parameters('vmName'),'/TeamServicesAgentClassito')]",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [
                "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]"
            ],
            "properties": {
                "publisher": "Microsoft.VisualStudio.Services",
                "type": "TeamServicesAgent",
                "typeHandlerVersion": "1.0",
                "autoUpgradeMinorVersion": true,
                "forceUpdateTag": "1.0",
                "settings": {
                    "VSTSAccountName": "joricteixeira",
                    "TeamProject": "Classito",
                    "DeploymentGroup": "Sandbox",
                    "AgentName": "[concat(parameters('vmName'), '.Classito')]",
                    "Tags": "jobs,web,scus"
                },
                "protectedSettings": {
                    "PATToken": "####"
                }
            }
        },
        {
            "name": "[concat(parameters('vmName'),'/TeamServicesAgentPartyRental')]",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "location": "[resourceGroup().location]",
            "apiVersion": "2015-06-15",
            "dependsOn": [
                "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]"
            ],
            "properties": {
                "publisher": "Microsoft.VisualStudio.Services",
                "type": "TeamServicesAgent",
                "typeHandlerVersion": "1.0",
                "autoUpgradeMinorVersion": true,
                "forceUpdateTag": "1.0",
                "settings": {
                    "VSTSAccountName": "joricteixeira",
                    "TeamProject": "PartyRental",
                    "DeploymentGroup": "Sandbox",
                    "AgentName": "[concat(parameters('vmName'), '.PartyRental')]",
                    "Tags": "jobs,web,scus"
                },
                "protectedSettings": {
                    "PATToken": "####"
                }
            }
        }

I'm getting the following error:

> {
   "error": {
    "code": "BadRequest",
    "message": "Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'TeamServicesAgentPartyRental' with handler 'Microsoft.VisualStudio.Services.TeamServicesAgent' already added or specified in input."
  }
}

BTW:
When I add multiple agents using the script generated by the VSTS (only changing the agentName) it works just fine.

**Comment by bryanmacfarlane** [comment]
This seems to be an issue with that template (in that other repo) and not the agent itself.  Seems like you should log an issue in that repo.

**Comment by bishal-pdMSFT** [comment]
@joricteixeira Microsoft.VisualStudio.Services.TeamServicesAgent is azure VM extension which internally configures VSTS agent on VM. Although VSTS allows mutiple agents to be configured on a VM, azure does not allow multiple VM extension of same type on a VM. And hence you see the error: `"Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'TeamServicesAgentPartyRental' with handler 'Microsoft.VisualStudio.Services.TeamServicesAgent' already added or specified in input."`

**Comment by bishal-pdMSFT** [comment]
@bryanmacfarlane @joricteixeira please close this issue.
