### ISSUE TITLE
Change in Agent Download Location Breaks GitHub API Parsing

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/vsts-agent#1333]
I noticed that in version `2.126.0`, the builds are now being hosted in Azure as opposed to previously being hosted on GitHub:

```
## Agent Downloads
|         | Package                                                                                                       |
| ------- | ----------------------------------------------------------------------------------------------------------- |
| Windows | [vsts-agent-win-x64-2.126.0.zip](https://vstsagentpackage.azureedge.net/agent/2.126.0/vsts-agent-win-x64-2.126.0.zip)      |
| macOS   | [vsts-agent-osx-x64-2.126.0.tar.gz](https://vstsagentpackage.azureedge.net/agent/2.126.0/vsts-agent-osx-x64-2.126.0.tar.gz)   |
| Linux   | [vsts-agent-linux-x64-2.126.0.tar.gz](https://vstsagentpackage.azureedge.net/agent/2.126.0/vsts-agent-linux-x64-2.126.0.tar.gz) |
```

Prior to this, I was able to get the latest version of macOS agent using Ruby using a method like this:

```ruby
def latest_release
  uri = ::URI.parse('https://api.github.com/repos/Microsoft/vsts-agent/releases/latest')
  response = ::Net::HTTP.get_response(uri)
  body = ::JSON.parse(response.body)
  body['assets'].select { |asset| asset['name'] =~ /osx/ }.first['browser_download_url']
end
```

I'm opening this issue to get a few questions answered so that I can adjust the [macOS vsts-agent Chef cookbook](https://github.com/americanhanko/vsts-agent-macos-cookbook) and the [vsts-agent cookbook](https://github.com/Microsoft/vsts-agent-cookbook) (current standard) accordingly.
- Is this change permanent?
- Will the release notes format will stay the same?
- Would it be possible to set up something like `https://vstsagentpackage.azureedge.net/agent/latest` that would redirect to the latest version?

**Comment by TingluoHuang** [comment]
- Is this change permanent? `YES`

Here is the way i would suggest to get latest agent version.
`https://account.visualstudio.com/_apis/distributedtask/packages/agent?%24top=1` (top 1 of all agents)
`https://account.visualstudio.com/_apis/distributedtask/packages/agent/osx-x64?%24top=1` (top 1 of osx agent)

You will get a JSON response like this:
```
{
	"count": 1,
	"value": [{
		"type": "agent",
		"platform": "osx-x64",
		"createdOn": "2017-12-05T19:38:28.167Z",
		"version": {
			"major": 2,
			"minor": 126,
			"patch": 0
		},
		"downloadUrl": "https://vstsagentpackage.azureedge.net/agent/2.126.0/vsts-agent-osx-x64-2.126.0.tar.gz",
		"infoUrl": "https://go.microsoft.com/fwlink/?LinkId=798199",
		"filename": null
	}]
}
```

Then you can get the download Url.

**Comment by americanhanko** [comment]
Thanks @TingluoHuang !
