### ISSUE TITLE
Allow to expand inline expressions on task parameters

### ISSUE THREAD

**Issue by jmelosegui** [Microsoft/vsts-agent#1336]
Using TFS I want to deploy the same web application to two different locations (West, Central). For this, I am trying to run phases concurrently to both locations using the `Run on multiple agents in parallel` option.
![image](https://user-images.githubusercontent.com/450246/34176456-e7e670b6-e4cd-11e7-906a-acf3c26cde45.png)

The following sample contains only one step `Deploy Website files`

![image](https://user-images.githubusercontent.com/450246/34176465-f408e86a-e4cd-11e7-8001-5edf9c7ea15c.png)

Here my question.

How can I provide a different value for the variables `$(WebsiteServer)`, `$(UserName)` and `$(Password)` based on the [multiplier](https://docs.microsoft.com/en-us/vsts/build-release/test/test-with-unified-agent-and-phases#multiple-executions)?

I have tried to configure multiple variables in the environment.

![image](https://user-images.githubusercontent.com/450246/34176484-ffdaf980-e4cd-11e7-8f50-7496300774ad.png)

And then use them like `$($(Location).WebsiteServer))` but that does not expand correctly.

I am thinking now on creating a custom task that will create variables at release time base on the hardcoded values and use those variables instead. But it seems hacky.

Is there a better way to solve this?

It is not ideal that tasks cannot expand inline expression parameters.

**Comment by TingluoHuang** [comment]
@jmelosegui i don't think we support nested variable expansion `$($(Location).WebsiteServer))` today.

**Comment by ericsciple** [comment]
We do support recursive macro expansion (for example, foo=$(bar), bar=baz

But we not support building up the macro name itself.

We have a plan to add expressions to the agent side. So you could do something like `$[ variables[concat(variables.location, '.WebsiteServer' ]` but we do not support that syntax on the agent side today.

As a workaround you could add a script at the beginning of the phase to initialize the variables that you want to use within the phase. For example, cmdline task:
`echo ##vso[task.setvariable variable=WebsiteLocation]%$(Location)_WEBSITESERVER%`

See [this page](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch)

**Comment by ericsciple** [comment]
you could also do separate environments with variables specific to the environment
