### ISSUE TITLE
node version is way behind official

### ISSUE THREAD

**Issue by IAMtheIAM** [Microsoft/vsts-agent#1337]
The agent is way behind, were on node v9.0 now and its using `user-agent = "npm/3.10.10 node/v6.11.5 win32 x64"`, please update asap

This is for `VSTS hosted` and `VSTS Hosted 2017` build agents

**Comment by TingluoHuang** [comment]
@IAMtheIAM can you share more detail about the problem you hit? are you a task author that writing customize vsts task? or you just want to use node.exe to run some script?

**Comment by IAMtheIAM** [comment]
I am just using vsts as a build agent for my node npm tasks.

It ships with 
```
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Package Management.
Version      : 1.0.8
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
; cli configs
user-agent = "npm/3.10.10 node/v6.11.5 win32 x64"
```
However I just realized I can upgrade it with the [Node Tool Installer](https://docs.microsoft.com/en-us/vsts/build-release/tasks/tool/node-js) and set the version I want. However I just think it would be good if by default, it used the latest version, maybe getting updated once a month.

**Comment by ericsciple** [comment]
this is the repo for the build agent itself, not the hosted image. we will pass along this feedback to the folks who manage the software on the hosted image

**Comment by IAMtheIAM** [comment]
Oh ok, great. Thanks!

**Comment by ericsciple** [comment]
Fyi, this has been updated in the repo that is now used to manage the hosted vs 2017 image. Here is the commit https://github.com/Microsoft/vsts-image-generation/commit/9a7fd1c311fc08eefff2dfb078a92c9b910d6ee1

I am told the change will roll out with the next image update, but a few things are still pending before that release is ready. My guess is within the next few weeks or so.

It looks like it was bumped to node 8, which makes sense to me since that is the latest LTS.

I would expect only the Hosted VS 2017 image to get the update, since the older hosted image contains the "VS 2015 era" of tools. The Hosted VS 2017 image is for VS 2017 era of tools.

**Comment by TingluoHuang** [comment]
@PhillipLeBlanc for macOS Preview image problem.

**Comment by rolandpeelen** [comment]
```
Node.js v6.14.4
NPM 3.10.10
```

on the hosted MacOS. Really... ?

**Comment by madhurig** [comment]
You can use the [Node Tool Installer Task](https://docs.microsoft.com/pt-br/azure/devops/pipelines/tasks/tool/node-js?view=vsts) to download the version you wish during your build or release. 

Thanks,
Madhuri

**Comment by rolandpeelen** [comment]
Fair enough. We ended up writing a bash script installing nvm and running it with that version. It had a pleasant side effect of speeding up the build times (normally between 15 and 30 minute, now between 5 and 10)

```
#!/usr/bin/env bash

echo '-------------------------------------------------------------------';
echo '--- Install NVM ---------------------------------------------------';
echo '-------------------------------------------------------------------';
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash;
npm config delete prefix;
source /Users/vsts/.bashrc;

echo '-------------------------------------------------------------------';
echo '--- Install Node @9.8.0 -------------------------------------------';
echo '-------------------------------------------------------------------';
nvm install 9.8.0;

echo '-------------------------------------------------------------------';
echo '--- Update the path to overwrite node and npm versions ------------';
echo '-------------------------------------------------------------------';
export PATH="/Users/vsts/.nvm/versions/node/v9.8.0/bin/npm:$PATH"
export PATH="/Users/vsts/.nvm/versions/node/v9.8.0/bin/node:$PATH"
which npm;
which node;

echo '-------------------------------------------------------------------';
echo '--- Install Dependencies ------------------------------------------;'
echo '-------------------------------------------------------------------';
npm install;


echo '-------------------------------------------------------------------';
echo '--- Run the test --------------------------------------------------';
echo '-------------------------------------------------------------------';
npm run test;

echo '-------------------------------------------------------------------';
echo '--- Build the prod version ----------------------------------------';
echo '-------------------------------------------------------------------';
npm run build.prod;
```

**Comment by Spongman** [comment]
it doesn't help that the `npm` task uses a hard-coded path to npm.

**Comment by rolandpeelen** [comment]
@Spongman - My solution is definately a workaround. I think the easiest way to implement this is to actually have VSTS read out the engine from package.json like heroku does
