### ISSUE TITLE
Async Command timeout

### ISSUE THREAD

**Issue by danbridgellc** [Microsoft/vsts-agent#134]
When using a Copy Publish Artifact task, I encounter an HTTP Timeout during execution of the async upload command.

So looking for enhancement...

Although the default timeout of 5 minutes is typically plenty, there are occasions where it is not - obviously it may not make sense to change the default timeout but would be ideal to add a configuration/capability setting to override when truly needed.

**Comment by TingluoHuang** [comment]
fixed with #335
