### ISSUE TITLE
Configure an agent for both build and deployment

### ISSUE THREAD

**Issue by tolgabalci** [Microsoft/vsts-agent#1346]
**Have you try trouble shooting doc?**
Yes

**Agent version and platform**
Version of your agent? 2.126.0

OS of the machine running the agent? OSX/Windows/Linux...
Windows Server 2012 R2 standard

**VSTS type and version**
VisualStudio.com

## Issue
I would like configure an agent for both build and deployment.  Is this possible?  If so how?  **What would the config.cmd look like to accomplish this?**

When I run:
.\config.cmd --deploymentgroup --deploymentgroupname "MY DEPLOY" --pool "MY POOL" --agent "agent1"

The [--pool "MY POOL"] options seems to be ignored.  The agent appears under Deployment Groups, but not my "MY POOL" Agent Queue.  

If I remove [--deploymentgroup --deploymentgroupname "TIM DEV"], then the agent appears under my "MY POOL" Agent Queue just fine. (Obviously, though it is not listed in the Deployment Groups any longer.)

**Comment by bryanmacfarlane** [comment]
No, each instance of the agent is configured build or deployment agent.  That's why we allow SxS instances on a machine.  They are xcopy, unzip, configure in two SxS directories.
