### ISSUE TITLE
Wrong SourceBranch and SourceVersion with variables in workspace mapping (sever path)

### ISSUE THREAD

**Issue by reinaldoarrosi** [Microsoft/vsts-agent#1349]
## Agent version and platform
Agent version: 2.117.2
OS: Windows

## VSTS type and version
On-premise TFS 2017 Update 2 RTM (15.117.26714.0)

## What's not working?
When using TFVC repository and using variables in workspace mapping (Sever Path) both Build.SourceBranch and Build.SourceVersion do not have the expected values.

Given the following scenario: 
- 2 branches called "$/MyTeamProject/branch1" and "$/MyTeamProject/branch2"
- Latest changeset in "$MyTeamProject" is 1000
- Latest changeset in "branch1" is 1001
- Latest changeset in "branch2" is 1002

Create one build definition with a variable called "BranchName" with an empty default value and mark "Settable at queue time". In "Get Sources" set the "Server Path" to "$/MyTeamProject/$(BranchName)",

Queue a build from this build definition and set variable "BranchName" to "branch1".

**Expected:** during build the predefined variables "Build.SourceBranch" and "Build.SourceVersion" should have these values: "$/MyTeamProject/branch1" and "1001"

**What actually happens:** predefined variables "Build.SourceBranch" and "Build.SourceVersion" have these values: "$/MyTeamProject/" and "1000"

It's important to notice that, the "Get Sources" task works correctly (gets the latest version from "branch1"). Also, if I set the variable "BranchName" to "branch1" *in the build definition* (not during queue time) everything works as expected.

**Comment by yaananth** [comment]
Thanks for the report!
We have identified a bug, and we will be fixing it in VSTS next sprint.
TFS 2018 Update 2 will have the fix.

**Comment by michelkamp** [comment]
Same issue here. This caused almost a big problem here. Detected it looking at the build details.... Imagine you have a Main and Develop branch. In my case the code of develop branch was always used even when i specified the Main to use.... so almost released develop versions as main to customers.... ;-( 
2018 update 2 should be this month right ?

**Comment by petekapakos** [comment]
We are experiencing the same issue.  We are using TFS 2017 On Premise Update 3.0
I also found that this bug was identified in VSTS here
https://developercommunity.visualstudio.com/content/problem/201376/build-definition-queue-time-variables-not-applying.html

A workaround is to keep updating the value in the build template and saving every time you want to build from a different branch.  Obviously not ideal and results in a bloated template history, but we are making it work.

Should we expect an update/fix to TFS 2017? Or will we have to upgrade to 2018?

**Comment by bryanmacfarlane** [comment]
@yaananth - please update the dev community issue since this is a server side issue.  Closing the agent issue since it’s not an agent issue

**Comment by neshant** [comment]
whoever comes to this thread should realize that you should refer to . I was using Build variables in my release pipeline hence it was picking up the wrong one. Using release pipeline just works fine.

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch
