### ISSUE TITLE
Need the ability to know if agent is interactive from task environment

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vsts-agent#1368]
As part of VsTest task, we provide the ability to run UI tests on agent machines. For UI tests it is necessary that the agent should run in Interactive mode.

We need to be able to determine this from the task so that the users can be warned if their agents are not running in interactive mode. Currently the environment does not contain this information (though I can see this information in the agent capabilities).

**Comment by bryanmacfarlane** [comment]
this isn't an issue since it's not a current capability of the agent.   since you're in vsts, have your PM send a feature request to our team

**Comment by TingluoHuang** [comment]
@bryanmacfarlane There is a `InteractiveSession=true/false` capability to indicate whether the agent is running as service or interactive. That capability is added as part of the agent AutoLogon feature.
