### ISSUE TITLE
Upgrade to the latest .NET Core runtime/sdk

### ISSUE THREAD

**Issue by RubenDelange** [Microsoft/vsts-agent#1369]
## Agent version and platform
Version of your agent? 2.126.0
OS of the machine running the agent? Windows

## VSTS type and version
VisualStudio.com

## What's not working?
The .NET Core runtime/sdk version on our build agent is currently 2.0.3 (dotnet --info). Is there a way to upgrade to the latest 2.1.4 SDK ~ 2.0.5 runtime version (cfr. security fixes)?
Or do we have to wait until the build agents are upgraded?

Thanks in advance!

**Comment by TingluoHuang** [comment]
@RubenDelange are you taking about the hosted agent? if so, please log an issue at https://github.com/Microsoft/vsts-image-generation
that's the repo for all image related question.

**Comment by RubenDelange** [comment]
Ok, will do, thx for the input!
