### ISSUE TITLE
why vsts Host VS2017 agent have no aspnetcore:2.0 and aspnetcore-build:2.0 image,and not cache them after build?

### ISSUE THREAD

**Issue by dadream** [Microsoft/vsts-agent#1370]
below is build step:
Step 1/17 : FROM microsoft/aspnetcore:2.0 AS base
2.0: Pulling from microsoft/aspnetcore
Digest: sha256:9a2eeddfde6da6e26196885a8146bd3339b4b929f3bb623c883997a80a19e576
Status: Downloaded newer image for microsoft/aspnetcore:2.0
 ---> 9132983c48eb
Step 2/17 : WORKDIR /app
 ---> 546179902768
Removing intermediate container 0074470d4f5a
Step 3/17 : EXPOSE 80
 ---> Running in e906a907f8d4
 ---> daf75ddec54e
Removing intermediate container e906a907f8d4
Step 4/17 : FROM microsoft/aspnetcore-build:2.0 

every build need much time to pulling aspnetcore image,why not add them in agent?

**Comment by TingluoHuang** [comment]
@dadream please log an issue at https://github.com/Microsoft/vsts-image-generation
that's the repo for all image related question.
