### ISSUE TITLE
Support Crome Headless

### ISSUE THREAD

**Issue by Davilink** [Microsoft/vsts-agent#1378]
I don't know if i should post it here or elsewhere but here the problem, i want to use the Hosted Agent for our Pipeline, but we can't run any Karma test or Integration test (We use Angular in our project with .Net Core) because there not installed browser in the hosted Agent. I was going to use PhantomJS but i get 2 problem :
1. PhantomJS take a lot memory compare to Chrome in Headless mode
2. PhantomJS project will not be maintened : https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

So do you think i will be possible to add the Chrome Browser in the Hosted Agent ?
The Headless mode let use chrome in a windowsless environnement, so perfect for CI Agent.

## Agent version and platform
All

OS of the machine running the agent? OSX/Windows/Linux...
All

## VSTS type and version
VSTS

**Comment by TingluoHuang** [comment]
@Davilink i would like to redirect to https://github.com/Microsoft/vsts-image-generation
The hosted agent is running as Admin, so you should be able to install chrome as part of your build as long as chrome has unattended installation mode.

**Comment by Davilink** [comment]
@TingluoHuang Thx i will post in the other repo, but i would prefer a native installation.
