### ISSUE TITLE
git-lfs fails to checkout repo

### ISSUE THREAD

**Issue by BrendanThompson** [Microsoft/vsts-agent#1382]
## General Information

**Agent Version:** `2.126.0`
**Operating System:** `CentOS 7` (_From Azure marketplace_)
**VSTS Type:** `Online`
**git Version:** `2.15.1`
**git-lfs Version:** `git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3; git d2f6752)`

## What's not working?
When attempting to do a build it fails when it tries to do the `git-lfs` fetch, the normal checkout of the git repo works fine.

## VSTS Errors

```
error: failed to fetch some objects from 'https://github.com/CatFactory/meow.git/info/lfs'
...
##[error]Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

These are the only useful things shown in the logs. The rest is run the percentage completion printing `Git LFS: (0 of 39 files) 0 B / 319.15 MB` over and over again

## Attempted rectification

I reinstalled the agent completely, prior to the install i remove everything to do with VSTS on the VM.

I have also reviewed the following links in an effort to resolve the problem:
- [Git LFS fails on batch fetch from agent (agent 2.124.0, git 2.14.2.windows.1, git lfs 2.3.4)](https://developercommunity.visualstudio.com/content/problem/150542/git-lfs-fails-on-batch-fetch-from-agent-agent-2124.html)
- #1134
- [Downloading Git LFS Files from TFS or VSTS](https://kamranicus.com/posts/2017-06-14-downloading-git-lfs-files-from-tfs-vsts)
- #1356
- Myriad of other `git-lfs` repo issues as well.

**Comment by TingluoHuang** [comment]
@BrendanThompson please try the latest version agent 2.127.0 https://github.com/Microsoft/vsts-agent/releases/tag/v2.127.0
where was a behavior change on how github implement their LFS object storage that cause this failure.

**Comment by BrendanThompson** [comment]
@TingluoHuang that version didn't even show up in my VSTS portal earlier! 😆

**Comment by TingluoHuang** [comment]
@BrendanThompson it's in a release process right now, it may take about 5 days to hit all VSTS account. (safe deployment)

**Comment by BrendanThompson** [comment]
@TingluoHuang amazing haha! So warning, it's `pre-release`

**Comment by BrendanThompson** [comment]
Thank you very much @TingluoHuang that has worked perfectly!!

![image](https://user-images.githubusercontent.com/2595712/35258137-9baa33a0-0051-11e8-913c-d3db9f5b8b43.png)

Have been looking at this for hours! Have to say MS support via GH is far superior to regular support channels!!

**Comment by TingluoHuang** [comment]
@BrendanThompson we will flip the `pre-release` flag when the deployment finish for all VSTS account.
