### ISSUE TITLE
Password is in clear text in .Credentials file

### ISSUE THREAD

**Issue by rusergeev** [Microsoft/vsts-agent#139]
I noticed, that build account user name and password are stored in agent\.Credentials:

```
{
  "Scheme": "Negotiate",
  "Data": {
    "username": "DOMAIN\\BuildUser",
    "password": "asfk(KOJ292la#",
    "url": "https://tfs.company.com/tfs"
  }

```
Is it going to be like that?

**Comment by ericsciple** [comment]
This PR is changing it: https://github.com/Microsoft/vsts-agent/pull/97

Has a dependency on some server side changes rolling out to production.

**Comment by bryanmacfarlane** [comment]
That's one of the reasons this preview is VSTS only.  

Note also that the file is locked down to the account that's configuring in the local directory for the agent that the account is configuring.
