### ISSUE TITLE
Please reconsider build agent support for Windows 7, Windows Server 2008R2

### ISSUE THREAD

**Issue by eriawan** [Microsoft/vsts-agent#1392]
## Background
Current agent (from v2.112.x to latest 2.x) still support Windows 7 for agent deployment on Windows. 
As far as I know, Windows 7's mainstream support is ended on January 13, 2015.
This brings many questions/challenges from the perspective of IT pro maintenance, because Windows 7 itself is not having mainstream support anymore:
https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

Also on that page, Windows 8.1 mainstream support is also ended. But we can still support Windows 8.1, because we should provide smoother path to Windows 10 and based on the fact that Windows 8.1 mainstream support is just ended in January 2018.

On server side, Windows 7 is equal to Windows Server 2008 R2 and its mainstream support is ended: https://support.microsoft.com/en-us/lifecycle/search/1163
**Note:** *On that link, Windows Server 2012 R2 still has mainstream support, until 10/9/2018.*

Unfortunately, in the docs of VSTS/TFS, I can't find any page that explicitly state the OS requirements for Windows. 
For example: https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows

## Agent version and platform
Agent version: 2.x

OS of the machine running the agent: Windows

## VSTS type and version
VisualStudio.com and On-Prem TFS 2017/2017U1/2018

## Suggestions

1. Please end build agent support for Windows 7 and Windows 8, including Windows server counterparts: the Windows Server 2008R2, Windows Server 2012.
2. Provide minimum Windows version requirement to be at least Windows 8.1. Having Windows 10 with minimum Build 15086 (Windows 10 1511) should be documented as highly recommended.

cc @bryanmacfarlane and VSTS agent team

**Comment by TingluoHuang** [comment]
@eriawan the agent is written in dotnet core, i think we will just follow what dotnet core has.
https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**Comment by eriawan** [comment]
@TingluoHuang 

Thanks for the reply! Ok, I'll post my suggestion on dotnet/coreclr and dotnet/sdk too.

**Comment by bryanmacfarlane** [comment]
Closing here since it's a dotnet coreclr issue
