### ISSUE TITLE
Windows nanoserver 1709 docker containers not supported

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-agent#1393]
I'm assuming the OS used of the windows agents is older than 1709.  Please upgrade the OS to at least 1709 so windows nanoserver docker container builds will be supported.

Thanks.

**Comment by TingluoHuang** [comment]
@AceHack what is this for?  can you provide more detail?

**Comment by AceHack** [comment]
I have a .NET core project with windows docker support.  Nanoserver 1709 is the default when you do File -> new project and select ASP.NET with windows docker support.  This simple hello world project will not build using hosted build agents and the docker or docker compose vsts build tasks.  Thanks.

**Comment by AceHack** [comment]
Here is a super simple project that will not work using VSTS hosted build agents.

[HelloWorld.zip](https://github.com/Microsoft/vsts-agent/files/1682389/HelloWorld.zip)

Here is someone else having the same issue but posted the issue in the wrong GitHub repo so it got closed.

https://github.com/Microsoft/vsts-tasks/issues/5697

Also, these are the "official" VSTS Microsoft build tasks I'm using to build the solution, I've tried them both.

![image](https://user-images.githubusercontent.com/578953/35634181-11e21d12-0679-11e8-8809-747d9731e057.png)

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Docker/containerbuild.ts
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DockerCompose/dockercomposebuild.ts

So summed up
1) I'm using the "official" Microsoft ASP.NET core Visual Studio template with Windows Docker support.
2) I'm using the "official" Microsoft VSTS Docker build tasks
3) I'm using the "official" hosted windows (VS2017) build agent
4) I'm creating the simplest of hello world applications
5) It does not work

Thanks

**Comment by AceHack** [comment]
For what it's worth, here is how I created the "Hello World" application, I made no other changes after hitting File -> New Project.

![image](https://user-images.githubusercontent.com/578953/35634608-159cd324-067a-11e8-98c4-bdd07f3f5eac.png)

**Comment by TingluoHuang** [comment]
@vijayma @chrisrpatterson for idea.

**Comment by chrisrpatterson** [comment]
Yes they are older than 1709 but we can't just upgrade them as that will break container and potentially other builds that are currently running fine.  

Window Server 1709 and future versions will only ship as the server core sku so when we setup those pools the will not have any tooling installed on them aside from Docker and the agent as VS is not supported on the server core sku.  In alignment with the next update to Window Server due out this spring we will add an additional pool that will support the newer container workloads.

**Comment by AceHack** [comment]
@chrisrpatterson I’m not sure what you mean that 1709 only ships as windows server sku.  I’m running windows 10 1709 right now and have custom windows 10 desktop 1709 VMs no server sku involved with Visual Studio installed.  Also I’ve installed visual studio on windows server without any issues in the past.  Thanks.

**Comment by chrisrpatterson** [comment]
The Server version of 1709 only ships with Windows Server Core not full Windows Server.  Full Windows Server includes the full desktop experience and a bunch of other components.  Windows Server Core does not include the desktop experience and is a more stripped down version of Windows Server.  

Yes you can install Windows 10 1709 and run the containers along with Visual Studio but we do not run our Azure based build VMs on the Windows 10 client as it is not licenses for that sort of usage.

**Comment by bryanmacfarlane** [comment]
Closing this out since this is not an issue with the agent application.  As Chris noted the service will create another docker pool soon.

Until then, a private agent on your own VM unblocks you

**Comment by aarcosolutions** [comment]
@bryanmacfarlane @chrisrpatterson I understand it is not an issue with agent application but the underlying OS on which agent is running. However this is an block issue and building custom build agent is time consuming. So before I go down that route, I wanted to check if any progress on this issue? As you mentioned in you previous message that a new docker pool will be created. Can you please share more information on that?

**Comment by ryanLeenay** [comment]
Currenlty Im running into an issue wehre it seems as though nanoserver 1709 is the only image that successfully sends requests to Azure Batch. Is there any particular workaround here? Is there any image that is suffictinetly similar to nanoserve 1709
