### ISSUE TITLE
Exit code 100 from 'tf' on OSX when using HTTPS

### ISSUE THREAD

**Issue by shaynemarriage** [Microsoft/vsts-agent#1397]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
**Yes**

## Agent version and platform
Version of your agent? 2.102.0/2.100.1...
**2.122.1**

OS of the machine running the agent? OSX/Windows/Linux...
**OSX**

## VSTS type and version
**On-Prem TFS**

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
**2018 RTM**

If VisualStudio.com, what is your account name? http://account.visualstudio.com

## What's not working?
**Build fails with: Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://tfsservername.com/tfs/Project/" -jwt:******** -noprompt'. When connecting over HTTPS.**

## Agent and Worker's diag log
[Agent_20180131-171010-utc.log](https://github.com/Microsoft/vsts-agent/files/1682971/Agent_20180131-171010-utc.log)
[Worker_20180131-171027-utc.log](https://github.com/Microsoft/vsts-agent/files/1682972/Worker_20180131-171027-utc.log)

**Comment by TingluoHuang** [comment]
@shaynemarriage can you share your full build log? the last few lines before `tf` exit should provide more info about the error.

**Comment by shaynemarriage** [comment]
Sorry about that, here's the complete file.
[Agent_20180131-171010-utc.log](https://github.com/Microsoft/vsts-agent/files/1683618/Agent_20180131-171010-utc.log)

**Comment by TingluoHuang** [comment]
@shaynemarriage not the agent log. :D share the log where i can see the `Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://tfsservername.com/tfs/Project/" -jwt:****** -noprompt'. ` :D

**Comment by shaynemarriage** [comment]
Isn't that the attached worker log line 386?

**Comment by TingluoHuang** [comment]
I need the build log from your TFS Web UI for that build. :D

**Comment by TingluoHuang** [comment]
like this:
![image](https://user-images.githubusercontent.com/1750815/35652875-906f4472-06b3-11e8-9440-6d6899b32d37.png)

**Comment by shaynemarriage** [comment]
I'm having one of those days. Here it is.
[1_Build.txt](https://github.com/Microsoft/vsts-agent/files/1683685/1_Build.txt)

**Comment by TingluoHuang** [comment]
2018-01-31T17:12:52.7398280Z ##[debug]An error occurred: Connection reset
2018-01-31T17:12:55.0743840Z An error occurred: Connection reset
2018-01-31T17:12:55.1308280Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://tfs.servername.com/tfs/Legacy/" -jwt:******** -noprompt'.

did you install your CA cert into JAVA cert store on that machine?

**Comment by shaynemarriage** [comment]
No, it's only loaded in IIS.

**Comment by TingluoHuang** [comment]
i mean the java store on your OSX

**Comment by TingluoHuang** [comment]
also, can you access your TFS site from browser on that OSX machine?

**Comment by shaynemarriage** [comment]
Not there either; didn't know this was necessary

**Comment by shaynemarriage** [comment]
Maybe I need to add our internal CA to the cert store?

**Comment by shaynemarriage** [comment]
Oh wait, that one is comodo.

**Comment by TingluoHuang** [comment]
i assume you are using self-signed server cert right?
in order to let any client successfully talk to the server, you need to install that cert's CA cert into any client machine's proper cert store.
otherwise client will throw error since it can't finish SSL handshake.

**Comment by shaynemarriage** [comment]
No, it's a wildcard cert. The OSX browser works fine with it, because Apple includes the Comodo CA cert in the OSX cert store. The agent is able to download the tasks, but it fails getting the sources from TFVC.

**Comment by shaynemarriage** [comment]
I think I know what to do. Let me give it a shot and get back to you. Thanks for the help.

**Comment by gravufo** [comment]
@shaynemarriage Update to the latest Java (the first version that worked for me was 1.8.0_152-b16).
I had the same issue and it seems to be related to Java and how it handles Server Name Indication (SNI) when SSL is enforced.

Make sure the java that's in your path is the correct version by typing `java -version`.

@bryanmacfarlane @TingluoHuang I suggest you update the documentation to reflect this issue/solution.

**Comment by TingluoHuang** [comment]
@gravufo thanks, i have updated the doc with your information.
