### ISSUE TITLE
Do not sign the assemblies using tfs and agent

### ISSUE THREAD

**Issue by jrgcubano** [Microsoft/vsts-agent#1398]
## Context
Agent: v2.129.0
OS: Windows Server 2012 R2 Standard
VSTS type and version: On-Prem TFS (2018) Version 16.122.27102.1
TFS Build Definition: Use a single PowerShell Task
MSBuild Version: '15.5.180.51428'

## What's not working?
A simple project build with net 4.6.1
```
2018-02-01T14:54:24.5509343Z CSC : warning CS8002: Referenced assembly 'PMS.SharedKernelBC, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Agents\tfs-agent\_work\1\s\modules\security\src\PMS.SecurityAC.CQRSMappings\PMS.SecurityAC.CQRSMappings.csproj]
```

If I do the same process from the console of the agent machine, it works perfectly.

I checked the public key from the project and exists:
```
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools> .\sn.exe -T C:\....\Test\PMS.SharedKernelBC.1.1.0\lib\net461\PMS.SharedKernelBC.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key token is ead45c61f822c97a
```

I saw #1124. I suppose it will be something similar.

Thanks in advance for your help.

**Comment by TingluoHuang** [comment]
@jrgcubano how is the agent configure? run as service or run interactively. if running as service will the service run as user matter?

**Comment by jrgcubano** [comment]
@TingluoHuang  Running as windows service

**Comment by jrgcubano** [comment]
@TingluoHuang Was that...I was using the wrong user from an old agent.. my mistake. Thank you very much!
