### ISSUE TITLE
VSTS YAML build supporting GitHub Enterprise

### ISSUE THREAD

**Issue by RobPurcellUK** [Microsoft/vsts-agent#1408]
Hi,

I'm trying out the YAML build definition preview, and just noticed that 'VSTS or GitHub' really does mean GitHub only and not GitHub Enterprise.

I can create a new build, say it's a YAML build, choose my GHE repo and the .yml file. But then I get the error message below.

`Unable to get the file content from the GitHub repository '<org>/<repo>' for the source version '6f1afd6cc9e59294b0e03dcf78a0977fd1f1ae26' and file path '/.vsts-ci-yml'. NotAcceptable`

What are the plans for this feature? It'll be super-useful for us being able to version the builds with the code, build per branch etc. Are you working on getting it out of preview before adding features, or is there a chance of more source locations being supported soon?

Thanks

**Comment by bryanmacfarlane** [comment]
This is on the backlog.  Actually will be service side code (backlog not managed here).  GHE work is in progress.
