### ISSUE TITLE
Register as Windows service not possible: Elevated account cannot access internet

### ISSUE THREAD

**Issue by JanFelixReuter** [Microsoft/vsts-agent#1411]
I cannot both configure the agent and register it as a Windows service, because elevated accounts cannot access the internet in my corporate network. Running the agent interactively is working fine as a non-elevated user, but running `config.cmd` as an elevated user does not work because it cannot register the agent with VSO.

Is there are a way to run only the service registration as an elevated user?

- Agent version 2.127.0
- Windows
- VisualStudio.com

**Comment by chrisrpatterson** [comment]
You could should be able to create a service for the agent using sc create.  Just make sure the user you pick as the user running the service has all of the necessary permissions to the agent files on disk.

**Comment by TingluoHuang** [comment]
Steps to install agent service manually:
1. Run `bin\AgentService.exe init` from elevated commandline prompt, make sure return code is 0, this will create event log entry for the agent service.
2. Run `sc create <servicename> binPath="<youragentroot>\bin\AgentService.exe" start="delayed-auto" DisplayName="<servicedisplayname>"` from elevated commandline prompt.
3. Go to task manager find the service you created, change it's run as account as needed.
