### ISSUE TITLE
Use system git instead of agent git version

### ISSUE THREAD

**Issue by Kreism** [Microsoft/vsts-agent#1415]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
Version of your agent? 2.117.2

OS of the machine running the agent? Windows

## VSTS type and version
On-Prem TFS

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
TFS 2017 Update 3

## What's not working?
How can we tell the agent to use the system git version and not his own?
There is the possibility to define this in the build job, with system.prefergitfrompath, but there is too much effort to adjust this with more than 100 build jobs.
We need all agents on the server to use the system GIT version. So how can I configure it per agent, not per build job?

Thanks
Martin

**Comment by bryanmacfarlane** [comment]
We don't have a way to set per agent or pool.  We do have a feature request on the backlog to set variables on the pools which would get merged but it's not very high on the backlog.  For right now, you need to set in the definition.

The only other option would be to add an environment variable override here:  https://github.com/Microsoft/vsts-agent/blob/65856f3e7335739948b61711d0ebe0c54a2b6806/src/Agent.Worker/Build/GitSourceProvider.cs#L312

If you want to do a PR, then we could take it.

**Comment by Kreism** [comment]
@bryanmacfarlane Thanks for your Feedback. Flyingdot done that for my in  #1424 
Is there a way to build this so that we can test / use it? Unfortunately, it has become somewhat urgent for us in the meantime. Thank you very much

**Comment by ericsciple** [comment]
`.\dev.cmd layout`

> Unfortunately, it has become somewhat urgent for us in the meantime

Can you confirm that adding the variable on each definition works for you?

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-agent/blob/master/docs/contribute.md

**Comment by ericsciple** [comment]
...has instructions for building the source code.

**Comment by Kreism** [comment]
Hi @ericsciple Thanks fount it and I was able to create a build an test it. 
Yes. I can confirm this is working with a system evn. variable for all build agent on that server.

**Comment by TingluoHuang** [comment]
@Kreism thanks for your contribution, i left some feedback on the PR.

**Comment by mjring** [comment]
Can somebody help clarify this a little? In what version did the "System.PreferGitFromPath" build definition variable get supported? According to GitHub, it was added with agent v2.133.0; however, I seem to be able to use this with build agent v2.131.0 (TFS 2018 U2). cc @TingluoHuang

**Comment by TingluoHuang** [comment]
@mjring are you set as definition variable or environment variable on the machine? we support set as env since beginning.

**Comment by mjring** [comment]
> @mjring are you set as definition variable or environment variable on the machine? we support set as env since beginning.

@TingluoHuang This is being set as a definition variable. It is not set as an environment variable on the private agent machine. I can successfully toggle the System.PreferGitFromPath to TRUE and FALSE and it will toggle between using the System git and agent Git versions.

**Comment by TingluoHuang** [comment]
@mjring if you check your agent diag log under `_diag` folder of your agent root directory, the first few lines should tells you the Git Commit SHA the agent is built from, can you share that?

**Comment by mjring** [comment]
> @mjring if you check your agent diag log under `_diag` folder of your agent root directory, the first few lines should tells you the Git Commit SHA the agent is built from, can you share that?

@TingluoHuang On our private agent, this is the newest commit that I see for the Agent log: 0cf7b2e90c2258027f198114885ce8d9f9f3497e
