### ISSUE TITLE
Allow trigger options with path filtering to be defined in the .vsts-ci.yml

### ISSUE THREAD

**Issue by TerrapinStation** [Microsoft/vsts-agent#1419]

**Comment by bryanmacfarlane** [comment]
It's coming in the next sprint.  Already coded.

Here's the design: https://github.com/Microsoft/vsts-agent/pull/1383/files

**Comment by ericsciple** [comment]
@TerrapinStation is your repo in VSTS or GitHub. Right now we only have path filtering for repositories in VSTS.

**Comment by ericsciple** [comment]
@TerrapinStation thanks for confirming

**Comment by shtratos** [comment]
For posterity, there's uservoice item to support path filters for Github:
https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/15140571-enable-continuous-integration-path-filters-for-git

**Comment by bryanmacfarlane** [comment]
@shtratos - Thanks for including
