### ISSUE TITLE
Add to troubleshooting section?

### ISSUE THREAD

**Issue by dbeattie71** [Microsoft/vsts-agent#142]
When trying to start the svc via ssh and get "Could not find domain for"

good info here: http://www.egeek.me/2015/02/14/jenkins-in-osx-guest-in-virtualbox-for-ios-jobs-full-setup-guide/

**Comment by bryanmacfarlane** [comment]
I added a troubleshooting section.  Feel free to create PRs for anything else you would like to see in it.
