### ISSUE TITLE
Parseable download URL via api.github.com

### ISSUE THREAD

**Issue by angrox** [Microsoft/vsts-agent#1423]
It is not possible anymore to find the download url in an parsable form via api.github.com:

<pre> 
 # curl -s https://api.github.com/repos/Microsoft/vsts-agent/releases/latest
 
[...]
  "assets": [ 
 ],
 "tarball_url": "https://api.github.com/repos/Microsoft/vsts-agent/tarball/v2.129.0",
 "zipball_url": "https://api.github.com/repos/Microsoft/vsts-agent/zipball/v2.129.0",
 "body": "## Features\r\n  - use SChannel for git during get source. #1377\r\n  - enable process force clean by default. #1372\r\n  - ordered test support in trx reader #1361\r\n## Bugs\r\n  - fix cancellation race condition. #1352\r\n  - skip most of the web console lines for last run. #1364\r\n  - fixed issue where autologon was not working with .\\username #1343\r\n  - update Xamarin.Android capability on macOS #1342\r\n## Misc\r\n  N/A\r\n\r\n## Agent Downloads  \r\n\r\n|         | Package                                                                                                       |\r\n| ------- | ----------------------------------------------------------------------------------------------------------- |\r\n| Windows | [vsts-agent-win-x64-2.129.0.zip](https://vstsagentpackage.azureedge.net/agent/2.129.0/vsts-agent-win-x64-2.129.0.zip)      |\r\n| macOS   | [vsts-agent-osx-x64-2.129.0.tar.gz](https://vstsagentpackage.azureedge.net/agent/2.129.0/vsts-agent-osx-x64-2.129.0.tar.gz)   |\r\n| Linux   | [vsts-agent-linux-x64-2.129.0.tar.gz](https://vstsagentpackage.azureedge.net/agent/2.129.0/vsts-agent-linux-x64-2.129.0.tar.gz) |\r\n\r\nAfter Download:  \r\n\r\n## Windows\r\n\r\n``` bash\r\nC:\\> mkdir myagent && cd myagent\r\nC:\\myagent> Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory(\"$HOME\\Downloads\\vsts-agent-win-x64-2.129.0.zip\", \"$PWD\")\r\n```\r\n\r\n## OSX\r\n\r\n``` bash\r\n~/$ mkdir myagent && cd myagent\r\n~/myagent$ tar xzf ~/Downloads/vsts-agent-osx-x64-2.129.0.tar.gz\r\n```\r\n\r\n## Linux\r\n\r\n``` bash\r\n~/$ mkdir myagent && cd myagent\r\n~/myagent$ tar xzf ~/Downloads/vsts-agent-linux-x64-2.129.0.tar.gz\r\n```\r\n"
} 
</pre>

Could you change the releases that the download url is available as key-value pair in the assets tag and we do not need to parse the body of the request?

**Comment by bryanmacfarlane** [comment]
There's plenty of libraries to parse an url.  Can you explain why you need to parse the url?  The point of the url is it's an opaque url to do a get against.

**Comment by angrox** [comment]
I do not want to parse the url, I want to get the download URL for the vsts-agent tgz file. In the past that was easy using the following command against the API of github:
`curl -s https://api.github.com/repos/Microsoft/vsts-agent/releases/latest | jq -r .assets[].browser_download_url`

Now you changed something in the releases so the download url is not in the assets[] in the returned JSON object from the Github API.

**Comment by TingluoHuang** [comment]
#1644

**Comment by angrox** [comment]
Thanks a lot @TingluoHuang. Closing this issue with fix in #1644
