### ISSUE TITLE
line bigger than 1024 chars are truncated, can we split the line in to sublines and send in livelogs

### ISSUE THREAD

**Issue by madhuv-msft** [Microsoft/vsts-agent#1425]
in this file
https://raw.githubusercontent.com/Microsoft/vsts-agent/573c9699eb478b41deda0195dcae24cc5be2128d/src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs

if line length is bigger than 1024 we are truncating it, rather can we split the line in to 1024 length lines?

if (!string.IsNullOrEmpty(line) && line.Length > 1024)
                    {
                        Trace.Verbose("Web console line is more than 1024 chars, truncate to first 1024 chars");
                        line = $"{line.Substring(0, 1024)}...";
                    }

**Comment by bryanmacfarlane** [comment]
It's only truncated in the live console log which flies by.  The persisted log does not truncate anything.
