### ISSUE TITLE
Running electron-builder with NSIS on a VSTS Agent fails

### ISSUE THREAD

**Issue by DiedB** [Microsoft/vsts-agent#1427]
## Agent version and platform
2.129.1, Hosted VS 2017 (Windows)

## VSTS type and version
VisualStudio.com

## What's not working?
Running electron-builder through a VSTS task (both using the NPM task or a PowerShell script) fails. Making an NSIS installer for the Electron package does not work because the command line input is not given correctly.

This is not an issue with electron-builder itself, or with the specific task. I've tried rolling out an agent myself which has the same environment. Logging into this agent and starting this process through PowerShell works and results in a succesful build, but running the same set of tasks through VSTS results in the same error that was seen on the Hosted VS2017 Agent.

## Agent and Worker's diag log
```Error: C:\Windows\ServiceProfiles\NetworkService\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe exited with code 1
Error output:
Error: invalid VIProductVersion format, should be X.X.X.X
Error - aborting creation process
    at ChildProcess.childProcess.once.code (C:\Agent\_work\1\s\node_modules\electron-builder\node_modules\builder-util\src\util.ts:248:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)```

VIProductVersion is a variable passed through stdin.

**Comment by ericsciple** [comment]
are you passing anything to stdin of the tool?

**Comment by DiedB** [comment]
Debugged it with Procmon and discovered that the environment variable Build.BuildNumber gets injected by VSTS, which in turn is used by Electron Builder in the product version number. It expects a number there and crashes, since our build number format does not consist of only digits.
