### ISSUE TITLE
assets list does not contain binary packages

### ISSUE THREAD

**Issue by Ingo-Siegel** [Microsoft/vsts-agent#1433]
VSTS-Team,

we are using the Github Rest API to automate the Installation of vsts-agent Software. Up to release v.2.124.0 you always added the rest assets list data of the packages containers (tar.gz/zip) but it is no longer included except than in the pre-releases.

**We are missing:**
Browser: https://api.github.com/repos/Microsoft/vsts-agent/releases/latest
{
  "url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/9354534",
  "assets_url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/9354534/assets",
 ...
  "html_url": "https://github.com/Microsoft/vsts-agent/releases/tag/v2.129.0",
  "id": 9354534,
  "tag_name": "v2.129.0",
  ...
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2018-01-23T17:21:16Z",
  "published_at": "2018-01-23T18:58:40Z",
  "assets": [
**here missing assets list data**
  ],
...
}

**What we want:**
Browser: https://api.github.com/repos/Microsoft/vsts-agent/releases/8203057
{
  "url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/8203057",
  "assets_url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/8203057/assets",
 ...
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2017-10-20T20:16:34Z",
  "published_at": "2017-10-20T21:01:13Z",
  "assets": [
    {
      **"url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/assets/5124214",
      "id": 5124214,
      "name": "vsts-agent-osx.10.11-x64-2.124.0.tar.gz",**
...
        "type": "User",
        "site_admin": false
      },
...
    },
    {
      "url": "https://api.github.com/repos/Microsoft/vsts-agent/releases/assets/5124213",
      "id": 5124213,
      "name": "vsts-agent-rhel.7.2-x64-2.124.0.tar.gz",
...
}

**Comment by bryanmacfarlane** [comment]
The VSTS backend for your account has the url where to download the agent (that API drives the download agent button in our web UI).  Open up fiddler or browser dev tools to see the rest api requests.

We did it that way so we could change the actual url where it's stored at anytime.  We always had plans to move it to our own CDN (which we did).

A more durable automation would query the rest api in the VSTS backend, retrieve the opaque url and download from that.

We still create the release in github for tracking and relating a release to commits etc...

**Comment by Ingo-Siegel** [comment]
thanks for your Support!

**Comment by Ingo-Siegel** [comment]
Hi @bryanmacfarlane, we wish to use the filename attribute within the VSTS backend REST API - currently the field is empty. 

What we get:
Browser: https://<account>/_apis/distributedtask/packages/agent?$top=1&%24top=1
[packages_agent_top1.txt](https://github.com/Microsoft/vsts-agent/files/1780338/packages_agent_top1.txt)

What we want:
...
{
         "type":"agent",
         "platform":"osx-x64",
         "createdOn":"2018-02-26T16:29:19.003Z",
         "version":{
            "major":2,
            "minor":129,
            "patch":1
         },
         "downloadUrl":"https://vstsagentpackage.azureedge.net/agent/2.129.1/vsts-agent-osx-x64-2.129.1.tar.gz",
         "infoUrl":"https://go.microsoft.com/fwlink/?LinkId=798199",
         "filename":**"vsts-agent-osx-x64-2.129.1.tar.gz"**
      },
...
