### ISSUE TITLE
VSO Log items not shown in step tree or logs.

### ISSUE THREAD

**Issue by redshiftz** [Microsoft/vsts-agent#1434]
## Have you try trouble shooting doc?
Yes.

## Agent version and platform
Version of your agent? 
TFS 2015 - 1.95.3/14.102.25423.0
TFS 2017 - 2.122.1/15.117.27024.0

OS of the machine running the agent? 
Windows

## VSTS type and version
On-Prem TFS

If On-Prem TFS, which release?
2015 U3
2017 U3 RTM

## What's not working?
When running the following code in a powershell file, the log items coded as ##vso[task.logdetail don't show in the step list in the UI nor in the log files.
I have tried both "build" and "release" as the type in the initial statement. For 2015, it briefly shows up in the Step tree before disappearing. It never
shows in 2017 in the step tree. It never shows in the log files for either.

param()
$VerbosePreference = "Continue"
$projectName = "MyProject"

$newBaseGuid = [guid]::NewGuid()
$newDetailGuid = [guid]::NewGuid()

Write-Verbose "VSO Log - Starting"
Write-Verbose "ProjectName: '$($projectName)'"
Write-Verbose "BaseGuid: '$($newBaseGuid)'"
Write-Verbose "DetailGuid: '$($newDetailGuid)'"
$firstLogItem = "##vso[task.logdetail id=$($newBaseGuid);name=$($projectName);type=build;order=1;state=Initialized;]"
Write-Verbose "Attempting Log: '$($firstLogItem)'"
write-host "$($firstLogItem)"

$secondLogItem = "##vso[task.logdetail id=$($newBaseGuid);state=InProgress;]Hello World"
Write-Verbose "Attempting Log: '$($secondLogItem)'"
write-host "$($secondLogItem)"

$thirdLogItem = "##vso[task.logdetail id=$($newBaseGuid);progress=100;state=Completed;result=Succeeded;]Hello World2"
Write-Verbose "Attempting Log: '$($thirdLogItem)'"
write-host "$($thirdLogItem)"

Write-Verbose "VSO Log - Complete"

## Agent and Worker's diag log
[Agent_TFS2015_1_Initialize.log](https://github.com/Microsoft/vsts-agent/files/1768986/Agent_TFS2015_1_Initialize.log)
[Agent_TFS2015_1_Release.log](https://github.com/Microsoft/vsts-agent/files/1768987/Agent_TFS2015_1_Release.log)
[Agent_TFS2015_2_Download artifacts.log](https://github.com/Microsoft/vsts-agent/files/1768988/Agent_TFS2015_2_Download.artifacts.log)
[Agent_TFS2015_3_Powershell test.ps1.log](https://github.com/Microsoft/vsts-agent/files/1768989/Agent_TFS2015_3_Powershell.test.ps1.log)
[Worker_TFS2015_diag.log](https://github.com/Microsoft/vsts-agent/files/1768990/Worker_TFS2015_diag.log)
[Agent_TFS2017_1_Initialize Job.log](https://github.com/Microsoft/vsts-agent/files/1768991/Agent_TFS2017_1_Initialize.Job.log)
[Agent_TFS2017_1_Release.log](https://github.com/Microsoft/vsts-agent/files/1768992/Agent_TFS2017_1_Release.log)
[Agent_TFS2017_2_Download artifacts.log](https://github.com/Microsoft/vsts-agent/files/1768993/Agent_TFS2017_2_Download.artifacts.log)
[Agent_TFS2017_3_Powershell test.ps1.log](https://github.com/Microsoft/vsts-agent/files/1768994/Agent_TFS2017_3_Powershell.test.ps1.log)
[Worker_TFS2017_diag.log](https://github.com/Microsoft/vsts-agent/files/1768995/Worker_TFS2017_diag.log)

**Comment by TingluoHuang** [comment]
##vso[task.logdetail] suppose create detail timeline record on the `timeline` tab of your task
like this:

![image](https://user-images.githubusercontent.com/1750815/37120131-8699d2ca-2227-11e8-8a3b-48ef70ad1537.png)

**Comment by redshiftz** [comment]
Your image above shows the build. I need it to work on the release as well. Everything I've been able to find on it says it should.

Should it not show in this tree?
![image](https://user-images.githubusercontent.com/20643813/37357258-eee376be-26b5-11e8-8212-357e984211f1.png)

**Comment by TingluoHuang** [comment]
@redshiftz I don't think release UI ever render those information.
@GitHubSriramB FYI,

**Comment by GitHubSriramB** [comment]
@redshiftz - Release never supported timeline tab

**Comment by TingluoHuang** [comment]
close as Release not support this.
