### ISSUE TITLE
sudo: ./svc.sh: command not found

### ISSUE THREAD

**Issue by Amethi** [Microsoft/vsts-agent#1435]
Hi, I've just executed the command given by the VSTS deployment group page  to execute the agent on my Ubuntu 16.04.4 LTS server (via su root) and received the following error at the end. Is this a problem?

```
...
./run.sh
Must not run with sudo
sudo: ./svc.sh: command not found
sudo: ./svc.sh: command not found
```

The command given by VSTS on the https://tenant.visualstudio.com/project_name/_machinegroup?view=MachineGroupView&mgid=47&tab=Details URL was:

```
mkdir vstsagent;cd vstsagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.129.1/vsts-agent-linux-x64-2.129.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "$(command -v systemctl)" ]; then ./config.sh --deploymentgroup --deploymentgroupname "Staging" --acceptteeeula --agent $HOSTNAME --url https://<snipped_tenant>.visualstudio.com/ --work _work --projectname '<snipped_project>' --auth PAT --token <sniped_token>--runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --deploymentgroup --deploymentgroupname "Staging" --acceptteeeula --agent $HOSTNAME --url https://<snipped_tenant>.visualstudio.com/ --work _work --projectname '<snipped_project>' --auth PAT --token <snipped_token>; ./run.sh; fi
```

Looks like `svc.sh ` script doesn't exist in the agent.

**Comment by Amethi** [comment]
**Update:** it didn't like root. I added my normal user to sudo group and it's happier, but still failing on `sudo: ./svc.sh: command not found`

**Comment by Amethi** [comment]
**Update:** okay, after running the `vstsagent/installdependencies.sh` script and nuking the agent folder and re-running it worked.

So the commands given on visualstudio.com might need updating to include the dependencies script?

**Comment by jespersh** [comment]
Did you run the commands here: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envubuntu.md ?

I initially missed these instructions and got the same errors as you. I rm -rf'd the vstsagent folder and redid the lengthy command and it succeeded. 

I am however on 16.04.3 LTS instead of .4

**Comment by Amethi** [comment]
No, because the user journey is you start from Azure Portal, run the command it tells you to, and that fails. That script needs fixing and then the pre-reqs here are irrelevant. You shouldn't have to know to come here and find the pre-reqs that you don't know you need.

**Comment by jespersh** [comment]
Ah, okay. We're using TFS and the deployment groups page has this link: https://aka.ms/vstsagentubuntusystem I am unfamiliar with what VSTS has here.

![TFS](https://user-images.githubusercontent.com/1004198/36968975-6a2bce64-2064-11e8-8ed0-e5ac11dd37d5.png)

**Comment by Amethi** [comment]
Ah, I'm an idiot. I didn't see that. I got too eager with the big command :)

**Comment by TingluoHuang** [comment]
looks like everyone is happy now, i am going to close the issue, please reopen if more help needed. :D

**Comment by bibichuan** [comment]
I commented out the following code in the config.sh file.This is helpful.
`# we want to snapshot the environment of the config user
# if [ $user_id -eq 0 -a -z "$AGENT_ALLOW_RUNASROOT" ] && [ "${ALLOW_RUNASROOT:-default_value}" == "default_value" ]; then
#    echo "Must not run with sudo"
#    exit 1
#fi
`
