### ISSUE TITLE
Subversion using Agent-configured proxy

### ISSUE THREAD

**Issue by bownie** [Microsoft/vsts-agent#1441]
## Agent version and platform
Windows 7/10 64bit 
Agent version 2.129.1

## VSTS type and version
https://nn-solaris.visualstudio.com

## What's not working?
We've configured an on-premise agent to run behind a proxy using  command line args to config.cmd and then configured a build to connect to on-prem SVN repo.  The agent connects to VSTS ok, we can queue the build on the agent but when the svn command runs it includes the proxy setting which therefore makes the checkout fail.  In the below error message I've changed the URLS for the svn server and the proxy server.

Exit code 1 returned from process: file name '<C:\Program Files\TortoiseSVN\bin\svn.EXE>', arguments 'info https://our.svn.url/trunk --depth empty --revision HEAD --xml --username ******** --password ******** --no-auth-cache --non-interactive --config-option servers:global:http-proxy-host=ourproxy.biz --config-option servers:global:http-proxy-port=8080'. 

How do we configure subversion not to take the vsts proxy?  There are no HTTP_PROXY/HTTP_PROXY environment variables set on the agent so we're at a loss as to where this is coming from.

## Agent and Worker's diag log
I don't have access to this at this time.

**Comment by bryanmacfarlane** [comment]
See the docs
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows#specify-proxy-bypass-urls

**Comment by bownie** [comment]
Perfect, thanks!
