### ISSUE TITLE
Agent should back off  when polling when server throttles

### ISSUE THREAD

**Issue by yaananth** [Microsoft/vsts-agent#1455]
@TingluoHuang  has the context here.
The agent will keep polling when it gets some exceptions.
For throttling exceptions, we should handle it and back off to stop hammering the server more

**Comment by TingluoHuang** [comment]
https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.0
https://github.com/Microsoft/vsts-agent/pull/1264

the problem has already been fixed in 2.125.0
