### ISSUE TITLE
Need Variable for "LastBuildDirectoryNumber"

### ISSUE THREAD

**Issue by cbfrank** [Microsoft/vsts-agent#1457]
Hi
I can get the Build.ArtifactStagingDirectory, but the final build output files are in the folder such as:
D:\agent\_work\2\a\Archive\Content\D_C\agent\_work\2\s\**projectname**\obj\Release\Package\PackageTmp
the second 2 is hard to get from the existing viaraibles.

Thanks

**Comment by TingluoHuang** [comment]
@cbfrank 
try `$(AGENT.BUILDDIRECTORY)`, it should point to the directory you want.
`2018-03-13T18:15:22.9884500Z AGENT_BUILDDIRECTORY=c:\vsts-agent\_layout\_work\2`

**Comment by cbfrank** [comment]
@TingluoHuang 
Thank you for the suggestion, but I think it can resolve my problem, as I can get "D:\agent_work\2\a" from "Build.ArtifactStagingDirectory" which include the value of LastBuildDirectoryNumber (in this case, it is 2).
But the problem is: I need the path something like D:\agent\_work\2\a\_Archive\Content\D_C_\agent\_work\2\_s\MyWebProj\obj\Release\Package\PackageTmp_ 
The italic part are constant string, but the other parts are related to the enviroment, and can't get by combine any existing default enviroment variables, the variables such as $(AGENT.BUILDDIRECTORY) including the disk letter, I can't combine two times of them in a path string

**Comment by cbfrank** [comment]
I closed this issue by mistake clicking on the button. Sorry, I opened it again

**Comment by TingluoHuang** [comment]
i am going to close the issue, i don't think we want to add a variable for the LastBuildDirectoryNumber
