### ISSUE TITLE
Unable to configure VSTS agent on MAC- Getting error at the run of /config.sh

### ISSUE THREAD

**Issue by 199219921992** [Microsoft/vsts-agent#1458]
@TingluoHuang @bryanmacfarlane I am configuring VSTS agent on MAC machine and itseems like the config.sh is failing with error below.

phl-dev-macbook:vstsagent mobilebuildepicor.onmicrosoft.com$ ./config.sh
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/mobilebuildepicor.onmicrosoft.com/VSTSAgent/bin/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/mobilebuildepicor.onmicrosoft.com/VSTSAgent/bin/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

./config.sh: line 86: 37574 Trace/BPT trap: 5       ./bin/Agent.Listener configure "$@"
phl-dev-macbook:vstsagent mobilebuildepicor.onmicrosoft.com$ cd /usr/local/lib

Let me know if i am missing any thing here I follow below document.
https://www.wintellect.com/installing-macos-vsts-build-agent/

Agent Version:2.129.1
Mac OSX Version: 10.11.6 (OS X EI Capitan)

**Comment by bryanmacfarlane** [comment]
Can you update the issue and fill out the template with the agent version and mac osx version you are installing onto?

**Comment by 199219921992** [comment]
@bryanmacfarlane  OS and MAC agent version at my previous comment

**Comment by bryanmacfarlane** [comment]
This is osx 10.11.  I believe net core 2.0 only supports osx 10.12 and forward.  Correct @TingluoHuang ?

**Comment by TingluoHuang** [comment]
yes, net core 2.0 only support 10.12+

**Comment by TingluoHuang** [comment]
you have to use https://github.com/Microsoft/vsts-agent/releases/tag/v2.124.0 for osx 10.11-

**Comment by TingluoHuang** [comment]
i am going to close the issue, please reopen if 2.124.0 agent doesn't work.
