### ISSUE TITLE
Agent container support: Docker pull needs retry logic

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/vsts-agent#1466]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Yes

## Agent version and platform
Version of your agent? 2.131.0

OS of the machine running the agent? Linux...

## VSTS type and version
VisualStudio.com 

If VisualStudio.com, what is your account name? http://devdiv.visualstudio.com

## What's not working?
When using `_PREVIEW_VSTS_DOCKER_IMAGE`, and the `docker pull` fails, the VSTS agent needs to retry the pull.  `docker pull` doesn't have retry logic built-in itself.  And Docker Hub can be unstable.

Docker Hub appears to be having issues today, and it is failing my build.  Apparently the recommendation is to use retry logic when pulling the image.

## Agent and Worker's diag log
https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1497371&_a=summary&tab=summary

/cc @michaelsimons @chcosta

**Comment by bansalaseem** [comment]
Since this is an enhancement request for docker task, can you please report the issue in tasks repo (https://github.com/Microsoft/vsts-tasks).

**Comment by eerhardt** [comment]
I can do that, but it isn't obvious that this is handled by a task in vsts-tasks.  I searched for `_PREVIEW_VSTS_DOCKER_IMAGE` in https://github.com/Microsoft/vsts-tasks and there are no hits in that repo.

However, when I search for it in this repo, I find:

https://github.com/Microsoft/vsts-agent/blob/f6977295a556cc0a4b898c703bc1e66a660e71f4/src/Agent.Worker/ExecutionContext.cs#L370-L381

Which appears to be the code that handles getting this property.

And then searching a bit more, it appears the code to actually pull the docker file is also in this repo:

https://github.com/Microsoft/vsts-agent/blob/0a76ddf67a8be88cc5840c47396781afcc5e85a4/src/Agent.Worker/ContainerOperationProvider.cs#L96-L101

So I guess I don't completely understand why this should move to a different repo, when the code is in this repo.

**Comment by bryanmacfarlane** [comment]
This feature isn't even in preview yet.  It's still under development.  But we will consider this request

**Comment by chcosta** [comment]
We're continuing to see this (https://dotnet.visualstudio.com/public/_build/results?buildId=10151&view=logs).  Not stating that anything needs to be done explicitly here, but highlighting that we're looking forward to the official feature and hope that some of the reliability issues we're seeing with the preview feature are addressed.

**Comment by TingluoHuang** [comment]
close as the fix has been released in recent version agent.
