### ISSUE TITLE
OSX Service: can't copy to LaunchAgents

### ISSUE THREAD

**Issue by simmdan** [Microsoft/vsts-agent#147]
I've been running the 0.7 release successfully (not as a service) on a mac for a month or so.  Yesterday I upgraded to v2.100.0, and while I'm able to run it the way I was before (not as a service), if I try to configure it to run as a service I get this result:

Enter work folder (press enter for _work) >
Enter run agent as service? (Y/N) (press enter for N) > Y
Creating launch agent in /Users/prose/Library/LaunchAgents/vsts.agent.msdata.prose-mac-test-2.plist
creating /Users/prose/Library/Logs/vsts.agent.msdata.prose-mac-test-2
cp: /Users/prose/Library/LaunchAgents/vsts.agent.msdata.prose-mac-test-2.plist: No such file or directory
svc.sh: line 40: failed to copy plist: command not found
Cannot start the service. Check the logs for more details.
An error occured.  Exit code 127 returned from process: file name '/bin/bash', arguments 'svc.sh install'.

Here's the log file from the _diag folder:
[Agent_20160510-165044-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/257696/Agent_20160510-165044-utc.log.txt)

Suggestions?

**Comment by bryanmacfarlane** [comment]
That might mean ~/Library/LaunchAgents doesn't exist.  That's a core built in core OSX directory.  I've seen osx reports of some installs having it missing.

**Comment by simmdan** [comment]
So the first user I logged onto the machine with when I received the new machine does have that directory, but I later decided I wanted to interact with the machine under a different, standardized user name.  So I created a new user and made it admin and have since been logging on with that user name.  It does not have that directory.

I just now created the directory and reran and everything seems to be working fine as a service.

Thanks!

Might be worthwhile to handle this in the configuration script or add to troubleshooting docs or something.

**Comment by simmdan** [comment]
Now I'm having a different issue trying to run as a service on my second mac.  On this machine I did already have a ~/Library/LaunchAgents directory, and when I deleted the .Agent file and reran run.sh so that I could reconfigure to run as a service, it gets a little farther.  The agent is setup in the queue, but I get this error message:

```
Enter run agent as service? (Y/N) (press enter for N) > Y
Creating launch agent in /Users/prose/Library/LaunchAgents/vsts.agent.msdata.prose-mac-test-1.plist
creating /Users/prose/Library/Logs/vsts.agent.msdata.prose-mac-test-1
Service vsts.agent.msdata.prose-mac-test-1 successfully configured
Could not find domain for
svc.sh: line 45: failed to load /Users/prose/Library/LaunchAgents/vsts.agent.msdata.prose-mac-test-1.plist: No such file or directory
/Users/prose/Library/LaunchAgents/vsts.agent.msdata.prose-mac-test-1.plist
Stopped
Agent is configured to run as service vsts.agent.msdata.prose-mac-test-1
```

Here's the diag log file.
[Agent_20160510-175052-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/257799/Agent_20160510-175052-utc.log.txt)

I can't seem to figure out what's different in the configuration between the two machines.  The other one is working fine as a service, but this one only works when I run it not as a service.

**Comment by bryanmacfarlane** [comment]
Deleting .Agent isn't enough (we are adding an unconfigure command).

Does it work if you go to another directory, create a new agent, and choose a different agent name?

**Comment by bryanmacfarlane** [comment]
I changed the scripts to detect that directory is missing (the original issue).

I just releases 2.100.1 @ https://github.com/Microsoft/vsts-agent/releases

Other service fixes and features added.  Follow docs: https://github.com/Microsoft/vsts-agent/blob/master/README.md

Configure a completely new agent via docs since it's generating different scripts now

**Comment by mrmojo666** [comment]
Hi,

I have this problem too,

yesterday I installed vsts-agent-osx.10.11-x64-2.102.0

when i tried to install as service i got this error:
```
mc-110:myagentTfs2015 tfsservice$ sudo ./svc.sh install
Password:
Creating launch agent in /Users/tfsservice/Library/LaunchAgents/vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1.plist
Failed: /Users/tfsservice/Library/LaunchAgents does not exist.  OSX system dir expected

```
so i created the LaunchAgents folder 

then i was able to install as service

```
mc-110:myagentTfs2015 tfsservice$ sudo ./svc.sh install
Password:
Creating launch agent in /Users/tfsservice/Library/LaunchAgents/vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1.plist
Creating /Users/tfsservice/Library/Logs/vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1
Creating /Users/tfsservice/Library/LaunchAgents/vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1.plist
Creating runsvc.sh
Creating .service
svc install complete
```

then i started 

```
mc-110:myagentTfs2015 tfsservice$ sudo ./svc.sh start
starting vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1
status vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1:

/Users/tfsservice/Library/LaunchAgents/vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1.plist

Started:
1973 0 vsts.agent.alm.D3alm.mc-110.InternationalMarkets.TFS2015.OSX.Agent1

```
but it seems the is not starting anything 

```
mc-110:myagentTfs2015 tfsservice$ ps aux | grep Agent.Listener
tfsservice        2015   0.0  0.0  2444056    796 s000  S+    9:17AM   0:00.00 grep Agent.Listener

```
If i uninstall the service and start it as normal task it works perfectly:
```
mc-110:myagentTfs2015 tfsservice$ ./run.sh
Scanning for tool capabilities.
Connecting to the server.
2016-06-23 07:33:31Z: Listening for Jobs
2016-06-23 07:44:09Z: Running job: Build
```

so seems that i'm affected from this issue and also this one 
[](https://github.com/Microsoft/vsts-agent/issues/306)

I've already tried to reconfigure, reinstall , change agent name ...but nothing changes, any ideas ?

thank you 

PS: 
System Version:	OS X 10.11.5 (15F34)
  Kernel Version:	Darwin 15.5.0

**Comment by bryanmacfarlane** [comment]
@mrmojo666 see https://github.com/Microsoft/vsts-agent/issues/317

**Comment by mrmojo666** [comment]
sorry, maybe i didn't get correctly, but here if i start service without sudo, it gives same results as with sudo. are you meaning that I have to wait for RC2 release to get this service working ?
Thank you

**Comment by bryanmacfarlane** [comment]
No, it works without sudo per #317 - that customer, many others and our services are running per sudo.

Start again and after configure, run this sequence of commands and paste output here:

(no sudo)
```bash
./svc.sh install
./svc.sh start
./svc.sh status
```

**Comment by bryanmacfarlane** [comment]
#317 is a doc bug to remove sudo from docs

**Comment by mrmojo666** [comment]
WOW, thank you it worked.

**Comment by issafram** [comment]
Being a non Mac user, can someone tell me the proper way to create the LaunchAgents folder?  The error message seems to state that its a System Directory, so is MKDIR good enough or is there an official way to do this?

**Comment by cocowalla** [comment]
@simmdan I've got the same issue with the `Could not find domain for` message - did you ever figure out how to get the Agent to start?

**Comment by simmdan** [comment]
@cocowalla.  Sorry, honestly I gave up trying to run as a service quite some time ago.  I don't have many mac machines and the ones I do have are used for nothing but build agents, and they are rarely rebooted.  When they do get rebooted I just log into them and manually start the agent under `screen` so that I can detach from the console and leave the agent running.  Someday I'll try to get them running as a service again, but this has been stable enough that I just haven't bothered.

**Comment by lavahot** [comment]
Anybody find a way to fix the `Could not find domain for` issue? Running as a service is essentially broken on mac.

**Comment by TingluoHuang** [comment]
@lavahot can you share a full log of what you are seeing?

**Comment by lavahot** [comment]
```
macmini01:agents builder$ ./svc.sh start
starting vsts.agent.mytfs.macmini01
Could not find domain for
Failed: failed to load /Users/Builder/Library/LaunchAgents/vsts.agent.mytfs.macmini01.plist
```
Running 10.12.5 and connected via SSH. I've done a little bit of research and it seems like there's some sort of permissions issue with running launchctl (which is what svc.sh is doing) over SSH if the plist is owned by a non-root user or something. Not really sure how to solve it. builder owns all of the agent files at `/usr/local/bin/agents` (inclusive) and `~/Library/LaunchAgents/vsts.agent.mytfs.macmini01.plist`. I'm also trying to run `./svc.sh start` as builder. Any thoughts?

**Comment by lavahot** [comment]
So it's `launchctl` that is emitting the `Could not find domain for`. The error code returned is 112. `launchctl error 112` reveals `112: Could not find specified domain`. I have no idea what this means. AFAIK, the plist generated by `./svc.sh install` doesn't specify a domain, but this might just be my ignorance of how launchd works. I went through and verified that all permissions were correct. I had an issue where the user was incorrect, but that's fixed now and I'm still getting the error. I suspect that it has something to do with the user not being logged in on the desktop, but I'm not certain. I'm going to dig into the docs and see if that helps.
