### ISSUE TITLE
TFS 2017 Upgrade - Build agent service failing

### ISSUE THREAD

**Issue by cschroll** [Microsoft/vsts-agent#1472]
## Agent Version and Platform
Version of your agent? 2.122.1

OS of the machine running the agent? Windows 7 Professional SP1

## VSTS Type and Version
On-Prem TFS 2017

If On-Prem TFS, which release? TFS 2017 15.117.27024.0 Update 3

## What's not working?
We upgraded from TFS 2012 to TFS 2017.  We initially had issues connecting from Visual Studio 2017 right after the upgrade - basically it would timeout after trying to connect and say that the TFS server was offline.  We then turned off Anonymous Authentication on the tfs website, and everything has been working fine.  

I then tried to set up a new build agent so we could use gated check-ins and take advantage of the new features in C#.  I created the build agent on our build server and set it to run as a service.  Everything installed correctly, but the service wouldn't start.  After researching, it is related to Anonymous Authentication not being turned on within the tfs website.  So, I turned on anonymous auth, and the build agent service works perfectly.  But, now the developers can't connect anymore to TFS using VS 2017.

Not sure what to do.  Toggling anonymous fixes one thing, but then breaks another.  Any help would be appreciated.

## Agent and Worker's Diagnostic Logs
[Agent_20180326-131750-utc.log](https://github.com/Microsoft/vsts-agent/files/1848008/Agent_20180326-131750-utc.log)

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting?view=vsts#config-fails-while-testing-agent-connection-on-premises-tfs-only

Anonymous access should be on by default for TFS2017, the build agent need to use one of the anonymous endpoint to exchange access token.

I would suggest report your issue at https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by derrickstolee** [comment]
Please do report your issue at the link provided above, but we will also need some more information in order to diagnose this issue.

What is your Visual Studio version?
You seem to be using TFVC. Does the command-line "tf.exe" tool work when Anonymous Access is on?
Please collect Fiddler traces for each connection attempt from Visual Studio (Anonymous Access enabled and disabled).

Fiddler traces contain sensitive information, so please create an issue on the developer community link; you will then have a way to privately send the Fiddler traces to us and our support team for investigation.

**Comment by cschroll** [comment]
I will report the issue on the Developer Community site. It looks like similar issues have been reported, and some are pointing to anti-virus software interfering with the connection. We use AVG, so I'm going to add devenv.exe as an exclusion to see if it makes a difference. 

Yes, we are using TFVC with Visual Studio 2017, v15.6.4. I'll turn anonymous back on tonight so it doesn't interfere with the developers. Then I can check to see if tf.exe works as well as the effect of excluding devenv.exe from AVG.  

Thank you for your help.

**Comment by TingluoHuang** [comment]
I am going to close this issue for now, since it's not related to the agent.
