### ISSUE TITLE
Build agent failed to install msi

### ISSUE THREAD

**Issue by MengYunfan** [Microsoft/vsts-agent#1475]
Error message.
> The Temp folder is on a drive that is full or is inaccessible. Free up space on the drive or verify that you have write permission on the Temp folder.

I can not use the nuget version of MicrosoftStoreServicesSDK, so i install MicrosoftStoreServicesSDK.msi in my local machine, but on vsts build agent  MicrosoftStoreServicesSDK installation was failed.

😂😂😂😂😂

**Comment by TingluoHuang** [comment]
@MengYunfan can you fill out the issue template? i can't understand which issue you run into, the agent is delivered as a self-contained `.zip`, there is no `MSI` at all.

**Comment by MengYunfan** [comment]
@TingluoHuang not private agent,  I use the vsts host build agent.
This is msi version of [MicrosoftStoreServicesSDK](https://marketplace.visualstudio.com/items?itemName=AdMediator.MicrosoftStoreServicesSDK) .

and this is my install script's content.
```ps
# install MicrsoftStoreServicesSDK
cd $PSScriptRoot

msiexec /i MicrosoftStoreServicesSDK.msi /quiet
```

**Comment by TingluoHuang** [comment]
@MengYunfan i would suggest you report at:
[Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool.

the issue your run into seems related to the machine itself.

**Comment by MengYunfan** [comment]
@TingluoHuang Thanks 😁😁😁😁
