### ISSUE TITLE
YAML Build Timeout Setting

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-agent#1479]
I can't find how to set the build controller timeout setting when using YAML builds.

When you use YAML builds the "options" section of the build configuration disappears.  This is where the build job timeout setting is.  How can I set this in YAML?

As an aside, the "View YAML" feature against a non YAML build does not include this property.

**Comment by gregpakes** [comment]
I think i've found the setting:

> queue:
>     name: Hosted VS2017
>     timeoutInMinutes: 90

I'm testing it now.

**Comment by ericsciple** [comment]
yep that should work, fyi it's also documented here under phase options: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-phase.md#job-timeout-applies-to-queue-server
