### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#148]
1) If the options are specified on the command line, then prompting is omitted. The problem is when validation fails on the group of inputs, then the while loop is tried again. However, since the values were already supplied on the command line, validation on the group of inputs is performed on the same incorrect values...in a while loop. The second time through any of the input while loops, we should force prompting - the value supplied on the command line should be the default.
~~2) Agent exits if --nostart is specified on the command line.~~
3) Should error out early if unknown command line parameter (i.e. typo)

**Comment by bryanmacfarlane** [comment]
If you error, it should print help.
