### ISSUE TITLE
VSTS shallow cloning does not shallowly clone submodules and clones all branches

### ISSUE THREAD

**Issue by Therzok** [Microsoft/vsts-agent#1487]
## Agent Version and Platform
2.115.0

OS X and Windows

## VSTS Type and Version
visualstudio.com
maungu

## What's not working?
Everything works, just not efficiently. 3 excerpts below

```
2018-04-02T14:51:32.8066258Z ##[command]git remote add origin $url
```

```
2018-04-02T14:51:32.9933327Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ********" fetch --tags --prune --progress --no-recurse-submodules --depth=1 origin
```

```
2018-04-02T14:52:14.9899144Z ##[command]git -c http.https://github.com.extraheader="AUTHORIZATION: basic ********" submodule update --init --force --recursive
```

These two commands do a lot more work than needed:
a) Cloning does not clone a single branch, so all the objects for refs alive in the remote are cloned. In the case of a repository with remote branches which were not deleted, it'll pull in more objects than needed. The branch name can be specified after the remote like so
```
git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin master
```

Another option is to add the remote via:
`git remote add -t $branch origin $url`

b) `--tags` is supplied instead of `--no-tags`, which causes fetching of tags.

c) submodules are not shallowly cloned in the depth=1 version. This should work always with git > 2.8.

**Comment by TingluoHuang** [comment]
@Therzok 
a) `branch` is not required for queuing a build, you can provide either a `branch` or a `commint hash`, so the client has to fetch `origin` in case the there is no `branch` been provided.

b) we support build a given tag, so the client has to fetch tags.

c) thanks for let me know this, i will fix this later. :)

**Comment by Therzok** [comment]
I see.

Tag names could be supplied too at the end of the fetch parameter or as a specific ref to grab. Regardless it seems there is a way to actually just fetch a single commit, but it is computationally expensive to actually look for the commit and grab only that (has to traverse the ref until it reaches the commit itself), and it seems to time out on github on my test case.

So yeah, it seems better to grab all the branches. Thank you for looking into this!

**Comment by TingluoHuang** [comment]
#1594

**Comment by TingluoHuang** [comment]
i will close this issue, the next agent release will pass fetch depth to `git submodule udpate`
