### ISSUE TITLE
BuildNumber that is updated during build does not update name in agent queue list

### ISSUE THREAD

**Issue by Kollibri** [Microsoft/vsts-agent#1493]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Version of your agent? Not sure, I will update once I know.

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

## VSTS Type and Version
On-Prem TFS 2018 - Version 16.122.27102.1

## What's not working?
When the buildnumber of a build is updated during the build process by a task, the buildnumber shows the updated value when looking at the build summary page, but the buildnumber still shows the unupdated/original value in the list of builds on the agent queue page.
![tfsagentqueuelist](https://user-images.githubusercontent.com/533377/38307015-56fe7bfa-37e0-11e8-850d-ee2a2c3cb03d.jpg)
In this example, the original buildnumber was set to the value of a variable called "$(GitVersion_NuGetVersionV2)" which is not defined when the build first starts, but the value is updated with a real value later on in the build tasks.  The build summary page will show the updated buildnumber, but the buildnumber is not updated when looking at the list of builds on the agent queue page.

## Agent and Worker's Diagnostic Logs
I don't have these now, let me know if you still need them and I will work to get them.

**Comment by Kollibri** [comment]
@TingluoHuang is there a way I can force the request queue page to be updated?

**Comment by TingluoHuang** [comment]
@Kollibri not from what i know, the string is stored in a different SQL table and we never update that table after the data got insert.

**Comment by Kollibri** [comment]
@TingluoHuang If I changed to use YAML builds, would the value be set early enough in the build that it would be correct?

**Comment by TingluoHuang** [comment]
@Kollibri i am not sure, the agent request queue page only shows the most recent builds which may not be interesting to fix.

**Comment by japj** [comment]
Having the agent request queue correctly show the version number will greatly help with analyzing and knowing which actual build has run at what time on a certain agent.

After the retention policy has kicked in for a build, the request queue could still have the correct version value even though the build details are gone.

I have wondered about this several times while doing post-mortem build failure analysis.

**Comment by TingluoHuang** [comment]
i would suggest report the problem at https://developercommunity.visualstudio.com/spaces/21/index.html since this is more like a server side improvement instead of agent issue.
