### ISSUE TITLE
VSTS ARM Agent Extension doesn't support Build/Release Agents.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/vsts-agent#1494]
The current extension is only for Deployment groups. I've been scouring the web and there doesn't seem to be a good automation story around standing up build/release agents. No ARM extension, no DSC resource, and the [quick-start template](https://github.com/Azure/azure-quickstart-templates/tree/master/visual-studio-vstsbuildagent-vm) has some custom script for installing it.

I'm about to go put together a DSC resource for this - think this repo would be a good place for that functionality?

**Comment by TingluoHuang** [comment]
@chshrikh for Azure ARM extension question.

**Comment by jwittner** [comment]
I've got an internal repo providing this API:

```powershell
Find-VSTSAgent - Searches the vsts-agent release list on GitHub.
Get-VSTSAgent - Finds installed VSTS Agents.
Install-VSTSAgent - Installs new VSTS Agents..
Uninstall-VSTSAgent - Uninstall existing VSTS Agents.
Start-VSTSAgent  - Start existing VSTS Agents.
Stop-VSTSAgent - Stop existing VSTS Agents.
```
and providing this DSC Resource:

```powershell
# Ensure that a VSTS Agent is installed and running.
 xVSTSAgent VSTSAgent {
	Name              = $Name
	Pool              = $Pool
	Account           = $Account
	AccountCredential = $AccountCredential
	LogonCredential   = $LogonCredential
	AgentDirectory    = $AgentDirectory
	Ensure            = $Ensure
}
```

I'm intending to create a new repo at Microsoft/vstsagent.powershell analogous to my other OSS project [Microsoft/unitysetup.powershell](https://github.com/Microsoft/unitysetup.powershell).

**Comment by RoopeshNair** [comment]
@jwittner. sure, a new repo is a right option. you can publish the DSC resource/module PS gallery
