### ISSUE TITLE
OutputVariables not present in next phase

### ISSUE THREAD

**Issue by iyerusad** [Microsoft/vsts-agent#1496]
VSTS, hosted linux agent. 

Attempting to use [Output Variables](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md) feature. I understand its in preview, was wondering if the lack of persistence through phases is current state (documentation unclear).

## What's not working?

**AgentPhase1,Task 1:**
`Write-Host "##vso[task.setvariable variable=foo;isSecret=false;isOutput=true;]bar"`

Manually set the output variables reference name to `test1`

**AgentPhase1,Task 2:**
`echo $TEST1_FOO` = Returns expected "bar"

**AgentPhase2,Task 1:**
New phase, not seeing the variable (either by running `set` or `echo $TEST1_FOO`)

## Expectation:

Output variables pass between tasks AND phases, i.e.:
`PHASE1_TASK1_FOO=bar`

**Comment by bryanmacfarlane** [comment]
It works in yaml (and therefore the agent): https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-phases.md#output-variables 

There's an experience missing in the designer (phase level variables).

**Comment by bryanmacfarlane** [comment]
I'm following up on the designer.  A developer community issue might be better for the service side designer issue.  Will update

**Comment by bryanmacfarlane** [comment]
Followed up with designer team - it's on the backlog but at least a couple sprints out.  use yaml
