### ISSUE TITLE
Document yaml build interaction with task groups

### ISSUE THREAD

**Issue by jrr** [Microsoft/vsts-agent#1498]
I can't seem to find any documentation on how _yaml builds_ interact with _task groups_.

Can yaml builds reference existing task groups? Can task groups exist as .yaml files?

Are there other mechanisms for sharing code between multiple yaml definitions?

I'm excited to use yaml, but I'd like to be able to learn a little more about it before turning on the preview feature and diving in.

Here's where I looked:

https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml?view=vsts
https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

**Comment by ericsciple** [comment]
Template files are the reuse mechanism in a yaml definition: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md

**Comment by jrr** [comment]
Oh, cool, this is new. Does it exist today in the preview? Will it be available in the version of yaml builds that graduates from preview later this quarter? (is that's what meant by "coming in April"?)

Maybe a better direction to take this issue would be a migration guide.

**Comment by ericsciple** [comment]
It's rolling out with the current sprint's payload. It will finish rolling out over the next few weeks.

**Comment by ericsciple** [comment]
For migration, it doesn't look like the editor in a designer-based build definition supports task groups when clicking the "View YAML" link. I don't know offhand where that feature is on the backlog. A workaround, other than by hand, would be to inspect the task group JSON and convert it to YAML. I think the structure would be very similar. You can hit the URL https://ACCOUNT.visualstudio.com/TEAMPROJECT/_apis/distributedtask/taskgroups to see the JSON

**Comment by ivanrusso** [comment]
We have Agent.Version 1.33.3 but template is not supported yet
![image](https://user-images.githubusercontent.com/2790090/39470938-b9572b9c-4d40-11e8-9f3b-7ea0a705927d.png)

**Comment by anh-duc-le** [comment]
@ivanrusso See commit "_Update templates ETA_" 12fffd179e7beb26c7b5d360760c49ddf80c5f2d

```
-# YAML getting started - Templates (coming in April)
+# YAML getting started - Templates (coming in May)
```

```
-## Phase reuse (coming in May)
+## Phase reuse
```

**Comment by ericsciple** [comment]
@vtbassmatt fyi, we should make sure this is clear in the docs on microsoft.com that task groups are not supported for yaml definitions and templates are the equivalent

**Comment by somanchirajasekhar** [comment]
@ericsciple: - I could see that define task groups in build yaml definition is not supported yet, but I hope that there is some kind of a workaround except of expanding the task group into tasks.
