### ISSUE TITLE
TF400813: Resource not available for anonymous access when creating a build agent.

### ISSUE THREAD

**Issue by gdodd1977** [Microsoft/vsts-agent#1500]
I'm running .\config.cmd to create a build agent on my build server, but I'm getting TFS400813 error.  See attached screenshot of the PowerShell command and full error message.

I'm on Windows Server 2016. I'm logged into the server as the user whos PAT I'm using to create the build agent. 

This is a new server, but on our previous build server I was able to do this with this same PAT and user with no issues. Is there some security setting on the server that allows this to move forward?

![tf400813error](https://user-images.githubusercontent.com/29410398/38679665-4fac8b14-3e32-11e8-8592-f434948367cf.jpg)

**Comment by TingluoHuang** [comment]
@gdodd1977 does your PAT expired? the default is valid for 90 days. try create a new one.

**Comment by gdodd1977** [comment]
I'm using VSTS.

**Comment by gdodd1977** [comment]
SSI_TFS_Build

**Comment by gdodd1977** [comment]
Sorry. Try https://app.vsaex.visualstudio.com

**Comment by TingluoHuang** [comment]
@gdodd1977 not the `app.vsaex` service url, the real account url, the url that has your git repository.

**Comment by TingluoHuang** [comment]
@gdodd1977 can you share your agent config log? it's under `_diag` folder under agent root.

**Comment by gdodd1977** [comment]
[Agent_Log.txt](https://github.com/Microsoft/vsts-agent/files/1903742/Agent_Log.txt)

**Comment by TingluoHuang** [comment]
@gdodd1977 are you able to use that PAT to fetch git repository?
i am not able to find any detail trace indicate what's wrong with your PAT, the service just decide return 401 when you make request.

**Comment by gdodd1977** [comment]
I don't have git on my build server. 

Since it's giving 401, it seems to be indicating that it can't authenticate the user from the build server. Is there some command in Powershell to run to get that? Or is it something that needs to be changed directly on the server?

**Comment by TingluoHuang** [comment]
@gdodd1977 make sure the PAT you generate is for the right account.
![image](https://user-images.githubusercontent.com/1750815/38691532-1a7cbdb6-3e4f-11e8-8c80-d16e6871c63a.png)

**Comment by gdodd1977** [comment]
I figured out the issue. The place that was storing my PATs was capitalizing letters, thus messing up the PAT.

Thanks for your time.

**Comment by TingluoHuang** [comment]
@gdodd1977 how did you get into this situation? the web UI should shows the PAT in lowercase.

**Comment by gdodd1977** [comment]
Because the app that I store the PAT in for reference was capitalizing them when I pasted them in for some reason.
