### ISSUE TITLE
Variable substitution not working for nested JSON tokens

### ISSUE THREAD

**Issue by vigneshmsft** [Microsoft/vsts-agent#1504]
I have the below JSON schema in my appsettings.json
![image](https://user-images.githubusercontent.com/10269434/38724140-2f4ef5cc-3efb-11e8-89f2-43e1670d5ca9.png)

and the below variable in my release variable set in VSTS

![image](https://user-images.githubusercontent.com/10269434/38724229-7a32d612-3efb-11e8-8f1d-a1b921cd6fbc.png)

If you are unable to view the image, I have values set for
Api.Income.url & Api.PersonalInformation.url in release scope.

But once the deployment is complete, I can only see the variable getting substituted for
Api.PersonalInformation.url and not the next element.

Is this is a bug or am I doing something wrong?

Also I would like to access the variables in the sameway as I do it from code,
for example in code I would access these variables using the path
["Api:Income:Url"], ["Api:PersonalInformation.Url"] and this is also case insensitive
and this also allows me to have a dot(.) in the JSON token
for example I could have the below structure

![image](https://user-images.githubusercontent.com/10269434/38724624-b6da2f56-3efc-11e8-8ef2-e1873d986956.png)

But this won't work with VSTS variable substitution as VSTS looks at dot (.) as an element separator.

Thanks

**Comment by bryanmacfarlane** [comment]
Please create an issue in vsts-tasks repo.  the agent is just a task runner ...
