### ISSUE TITLE
Variable Build.SourceBranchName is empty with TFS-RestAPI

### ISSUE THREAD

**Issue by anonymmynona** [Microsoft/vsts-agent#1509]
## Agent Version and Platform
Agent version: 2.122.2
OS: Windows

## VSTS Type and Version
On-premise TFS 2018 Update 1

## What's not working?
If you queue a git build with the TFS-RestAPI via the build id, the variable $(Build.SourceBranchName) is empty. If you queue the build with web access, it works fine.

**Comment by TingluoHuang** [comment]
@anonymmynona i would suggest you to report this problem to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), since it sounds like a problem with the server. $(Build.SourceBranchName) is a variable provided by the VSTS Server.

**Comment by anonymmynona** [comment]
Okay I'll try. Thanks you.
