### ISSUE TITLE
Inject agent system capabilities as environment variables for tasks to use

### ISSUE THREAD

**Issue by gravufo** [Microsoft/vsts-agent#151]
Hi,

It would be **very** useful to be able to access system capabilities as variables inside tasks.

That way, I could simply lookup the variable "MSBuild" using tl.getVariable("MSBuild) and get the path to msbuild.exe without having to either hard code it or insert it in the PATH.

This was expected to work that way, but I was disappointed to learn that it only works for build definitions' demands.

Thanks

**Comment by bryanmacfarlane** [comment]
We are going to round out the concepts of capabilities with tools - both scanning and acquiring.  Including pulling dynamically if supported.  

https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md

That's future work.  For right now, capabilties are simply used to meet demands for agent selection
