### ISSUE TITLE
Linux agent - unattended install: Dependencies check and systemctl status

### ISSUE THREAD

**Issue by NickMRamirez** [Microsoft/vsts-agent#1520]
To enable unattended install of the VSTS agent on Linux, e.g. installing as a script into a new VM created in Azure:

### Dependencies check
The Linux agent script checks if .NET Core 2.x is installed, as described here: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envlinux.md

If they aren't installed, a message is printed telling you to run `sudo ./bin/installdependencies.sh`.

Can this check be run by default to aid unattended installation? 

### Systemctl status

Also, for an unattended installation, the part of the script that starts the agent using systemctl hangs because the script invokes a function called `status`, which does not exit. Can this call be removed from the following code block in *svc.sh*?

```
function start()
{
    systemctl start ${SVC_NAME} || failed "failed to start ${SVC_NAME}"
    status # <--- Can this be removed? It causes the script to hang.
}
```

**Comment by TingluoHuang** [comment]
@NickMRamirez 
we do have dependencies check for configure linux agent.
https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutroot/config.sh#L11

status is a function to 
```sh
function status()
{
    if [ -f "${UNIT_PATH}" ]; then
        echo
        echo "${UNIT_PATH}"
    else
        echo
        echo "not installed"
        echo
        return
    fi

    systemctl status ${SVC_NAME}
}
```
i am not sure which part is hanging, can you run `systemctl status` manually on your machine?

**Comment by TingluoHuang** [comment]
@NickMRamirez any updates?

**Comment by NickMRamirez** [comment]
Thank you @TingluoHuang, but this doesn't answer my questions. What I was wondering is two things (maybe it should be different issues?):

### 1. .NET Core Dependency Check
Although there *is* a dependency check for .NET Core, is there any reason not to automatically download the .NET Core installer and install it rather than only printing a message? Currently, the following message is printed:

```
Dependencies is missing for Dotnet Core 2.0
Execute ./bin/installdependencies.sh to install any missing Dotnet Core 2.0 dependencies.
```

Any reason that the install script can not execute `./bin/installdependencies.sh` itself? This would simplify the installation process.

### 2. Call to systemctl status 
The second question is about the call to `systemctl status`. This command is a blocking call. You mentioned some code in `config.sh`, but the problem I'm seeing is in `svc.sh`.  The last command called in the install script is `sudo ./svc.sh start`. This blocks on a call to `systemctl status`, which gives output like the following and then blocks waiting for the user to type `q` or `Ctrl + C`:

Output of `systemctl status`:
```
/etc/systemd/system/vsts.agent.nickmramirez.ubuntu-xenial.service
● vsts.agent.nickmramirez.ubuntu-xenial.service - VSTS Agent (nickmramirez.ubuntu-xenial)
   Loaded: loaded (/etc/systemd/system/vsts.agent.nickmramirez.ubuntu-xenial.service; enabled
   Active: active (running) since Wed 2018-06-20 02:27:43 UTC; 41ms ago
 Main PID: 2703 (runsvc.sh)
    Tasks: 7
   Memory: 3.5M
      CPU: 37ms
   CGroup: /system.slice/vsts.agent.nickmramirez.ubuntu-xenial.service
           ├─2703 /bin/bash /home/vagrant/vstsagent/vstsagent/runsvc.sh
           └─2706 ./externals/node/bin/node ./bin/AgentService.js

Jun 20 02:27:43 ubuntu-xenial systemd[1]: Started VSTS Agent (nickmramirez.ubuntu-xenial).
Jun 20 02:27:43 ubuntu-xenial runsvc.sh[2703]: .path=/home/vagrant/bin:/home/vagrant/.local/b
lines 1-13/13 (END)
```

Having this block means it can't be a completely unattended install. I dont know if there's much value in calling status? Can it be removed?

**Comment by bryanmacfarlane** [comment]
@NickMRamirez - the agent is a self encapsulated net core binary (carries net core) since it updates itself.  This isn't about downloading net core dependency, it's about the OS dependencies of net core.

> Any reason that the install script can not execute script?

Yes, it installing requires sudo and config is done by the user. 

> blocking on systemctl status

That shouldn't happen.  It doesn't happen on our systems.  It's not a blocking cli.  Not sure why it's blocking on your machine.  man page doesn't refer to it being blocking either: https://manpages.debian.org/jessie/systemd/systemctl.1.en.html

You can remove but the intent of the status line was to apply an action and then print the current to the user as a confirmation the action was applied.

**Comment by bryanmacfarlane** [comment]
I think the next step is to figure out why systemctl status is hanging on your machine.

**Comment by NickMRamirez** [comment]
It was happening for me (the blocking call to status) on Ubuntu Xenial. Maybe it’s different from CentOS?

**Comment by dakale** [comment]
I think the SO link by @NickMRamirez covers the fix needed. @TingluoHuang to take a quick look, should be a one liner

**Comment by TingluoHuang** [comment]
#1635 i will test it before merge.

**Comment by TingluoHuang** [comment]
I am going to close this issue as the PR has been merged. 
Thanks for reporting this.
