### ISSUE TITLE
VSTS build agent setup failing with timeout while testing connection

### ISSUE THREAD

**Issue by paul-lucas** [Microsoft/vsts-agent#1522]
## Agent Version and Platform
Version of your agent? vsts-agent-win-x64-2.131.0

OS of the machine running the agent? Windows Server 2012 R2

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? VSTS

If VisualStudio.com, what is your account name? http://intelia.visualstudio.com

## What's not working?
Downloaded agent, config failing with HTTP timeout error:
- PS C:\agent> .\config.cmd
- 
- >> Connect:
- 
- Enter server URL > https://intelia.visualstudio.com
- Enter authentication type (press enter for PAT) >
- Enter personal access token > ****************************************************
- Connecting to server ...
- An error occurred while sending the request.
- Failed to connect.  Try again or ctrl-c to quit

Tested connections using TELNET, all OK:
- telnet login.microsoftonline.com 443	OK
- telnet app.vssps.visualstudio.com 443	OK
- telnet intelia.visualstudio.com 443	OK
- telnet intelia.vsrm.visualstudio.com 443	OK
- telnet intelia.pkgs.visualstudio.com 443	OK
- telnet intelia.vssps.visualstudio.com 443	OK

## Agent and Worker's Diagnostic Logs
[2018-04-23 00:56:03Z INFO Terminal] WRITE LINE: Connecting to server ...
[2018-04-23 00:56:03Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-23 00:56:14Z WARN VisualStudioServices] Attempt 1 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 11.052 seconds.
[2018-04-23 00:56:35Z WARN VisualStudioServices] Attempt 2 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 13.057 seconds.
[2018-04-23 00:57:07Z WARN VisualStudioServices] Attempt 3 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 17.182 seconds.
[2018-04-23 00:57:35Z WARN VisualStudioServices] Attempt 4 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 24.775 seconds.
[2018-04-23 00:58:10Z WARN VisualStudioServices] Attempt 5 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 42.054 seconds.
[2018-04-23 00:59:02Z ERR  VisualStudioServices] Attempt 6 of GET request to https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The maximum number of attempts has been reached.
[2018-04-23 00:59:02Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-23 00:59:02Z INFO AgentServer] Catch exception during connect. 4 attemp left.
[2018-04-23 00:59:03Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

**Comment by TingluoHuang** [comment]
@paul-lucas do you have anything between your build machine and the internet, proxy/firewall?

**Comment by paul-lucas** [comment]
Windows Firewall on the server, now disabled but issue persists. No proxy server that I can see, IE settings don't indicate any proxy, we've got a bit of a non-responsive IT department....

**Comment by bryanmacfarlane** [comment]
As a troubleshooting step, have you tried an agent on an azure VM (or outside your network)?  Just to make sure ...

**Comment by TingluoHuang** [comment]
@paul-lucas can you try hit that url in IE?
https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1

**Comment by paul-lucas** [comment]
Yep that URL in IE on the server returns a JSON message, all looks ok.
@bryanmacfarlane yes I installed an agent for the same pool on my PC at home, all worked ok.

**Comment by TingluoHuang** [comment]
@paul-lucas what about `invoke-webrequest` from powershell to that url?
i guess your IT department has some firewall rule base on request's `user-agent`.

**Comment by paul-lucas** [comment]
PS C:\agent> invoke-webrequest "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&l
astChangeId64=-1"


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           :

                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">




                    <html lang="en-US">
                    <head><title>

                                Visual Studio Team...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    X-TFS-ProcessId: 87c4bcbe-b84f-4999-9093-6f5dc512557d
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    ActivityId: 04a3368...
Forms             : {}
Headers           : {[Pragma, no-cache], [X-TFS-ProcessId, 87c4bcbe-b84f-4999-9093-6f5dc512557d],
                    [Strict-Transport-Security, max-age=31536000; includeSubDomains], [ActivityId,
                    04a3368a-755c-4366-bf0f-73e56a56318b]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" value="
                    xJSDiPAgpAC9rgm7MQ0jGbsKpWh5Liu_d09gBjeJudMnLC5HdtMmGsltG298RcJKZeolStKuZFnf94_wO7frUT49PJk1">;
                    outerText=; tagName=INPUT; name=__RequestVerificationToken; type=hidden; value=xJSDiPAgpAC9rgm7MQ0j
                    GbsKpWh5Liu_d09gBjeJudMnLC5HdtMmGsltG298RcJKZeolStKuZFnf94_wO7frUT49PJk1}, @{innerHTML=;
                    innerText=; outerHTML=<input name="__RequestVerificationToken2" type="hidden"
                    value="__RequestVerificationToken21c8c69a2-95a1-434a-b362-7ff42dff5937">; outerText=;
                    tagName=INPUT; name=__RequestVerificationToken2; type=hidden;
                    value=__RequestVerificationToken21c8c69a2-95a1-434a-b362-7ff42dff5937}}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 14409

**Comment by TingluoHuang** [comment]
@paul-lucas try add `-UserAgent something` when call `invoke-webrequest`

**Comment by paul-lucas** [comment]
OK:

PS C:\Windows\system32> Invoke-WebRequest -Uri "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1" -UserAgent ([Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer)


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           : 
                    
                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                    
                        
                        
                    
                    <html lang="en-US">
                    <head><title>
                        
                                Visual Studio Team...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    X-TFS-ProcessId: 7958c32f-794b-43ce-9652-c147c9bde324
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    ActivityId: 7d9dbae...
Forms             : {}
Headers           : {[Pragma, no-cache], [X-TFS-ProcessId, 7958c32f-794b-43ce-9652-c147c9bde324], [Strict-Transport-Security, max-age=31536000; includeSubDomains], [ActivityId, 
                    7d9dbaee-5e40-43bb-87c8-03800cb086d3]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" 
                    value="mHy4mJ2kKVjjvyzOBdecxYHpn0rfy36BCaQ27voRfs00V2XgRVNV-6iJ8oCPh5N9hoj_PZPi5EcLrt1vpMn6MM2NJ1M1">; outerText=; tagName=INPUT; name=__RequestVerificationToken; 
                    type=hidden; value=mHy4mJ2kKVjjvyzOBdecxYHpn0rfy36BCaQ27voRfs00V2XgRVNV-6iJ8oCPh5N9hoj_PZPi5EcLrt1vpMn6MM2NJ1M1}, @{innerHTML=; innerText=; outerHTML=<input 
                    name="__RequestVerificationToken2" type="hidden" value="__RequestVerificationToken2b501ba04-c1dd-47f1-8acf-67d1c0f8f6b3">; outerText=; tagName=INPUT; 
                    name=__RequestVerificationToken2; type=hidden; value=__RequestVerificationToken2b501ba04-c1dd-47f1-8acf-67d1c0f8f6b3}}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 14365

**Comment by TingluoHuang** [comment]
@paul-lucas don't use `IE` as user agent, use some random string, like `TestingUserAgent`

**Comment by paul-lucas** [comment]
OK:

PS C:\Windows\system32> Invoke-WebRequest -Uri "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1" -UserAgent "TestUserAgent"


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           : 
                    
                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                    
                        
                        
                    
                    <html lang="en-US">
                    <head><title>
                        
                                Visual Studio Team...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    X-TFS-ProcessId: b8f4cfad-b3c0-4560-b426-024616b51083
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    ActivityId: c19c5aa...
Forms             : {}
Headers           : {[Pragma, no-cache], [X-TFS-ProcessId, b8f4cfad-b3c0-4560-b426-024616b51083], [Strict-Transport-Security, max-age=31536000; includeSubDomains], [ActivityId, 
                    c19c5aa7-a27f-4346-a850-9fd1f8e64c51]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" 
                    value="obSOQn6ZaVh-BgKuVFzIXeBS9vl3BK_oydgrQ1cEcEk_qh9zj8ckEC1h1szPdb5OstsWOZ0XgcMvohpyLMoJhudMH_g1">; outerText=; tagName=INPUT; name=__RequestVerificationToken; 
                    type=hidden; value=obSOQn6ZaVh-BgKuVFzIXeBS9vl3BK_oydgrQ1cEcEk_qh9zj8ckEC1h1szPdb5OstsWOZ0XgcMvohpyLMoJhudMH_g1}, @{innerHTML=; innerText=; outerHTML=<input 
                    name="__RequestVerificationToken2" type="hidden" value="__RequestVerificationToken2de813584-627b-4465-8469-c1d3137536b6">; outerText=; tagName=INPUT; 
                    name=__RequestVerificationToken2; type=hidden; value=__RequestVerificationToken2de813584-627b-4465-8469-c1d3137536b6}}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 14409

**Comment by TingluoHuang** [comment]
@paul-lucas what about:
$bytes = [System.Text.Encoding]::ASCII.GetBytes("vsts:PASTEYOURPATHERE")
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
Invoke-WebRequest  -Uri "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1" -Headers @{ Authorization = $basicAuthValue } -useragent "vstsagentcore"

**Comment by paul-lucas** [comment]
Excuse my ignorance but wasn't too sure what you wanted me to put as 'vsts:PASTEYOURPATHERE', tried it as follows:
PS C:\Windows\system32> $bytes = [System.Text.Encoding]::ASCII.GetBytes("vsts:https://intelia.visualstudio.com")
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
Invoke-WebRequest -Uri "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1" -Headers @{ Authorization = $basicAuthValue } -useragent "vstsagentcore"


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           : 
                    
                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                    
                        
                        
                    
                    <html lang="en-US">
                    <head><title>
                        
                                Visual Studio Team...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    X-TFS-ProcessId: 3659f28d-a2a7-41ba-a426-840074c6276f
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    ActivityId: 9d69626...
Forms             : {}
Headers           : {[Pragma, no-cache], [X-TFS-ProcessId, 3659f28d-a2a7-41ba-a426-840074c6276f], [Strict-Transport-Security, max-age=31536000; includeSubDomains], [ActivityId, 
                    9d696269-4100-4ed1-9ae0-42050facaae3]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" 
                    value="rEadYlTMOLXaBvbR98f4GSoinCZ7EcoQpTvk-cgTrd4O0LId9EC6UnyMuI_AEBbIzFox17xg_StbV1gVTuCt3YR-RbY1">; outerText=; tagName=INPUT; name=__RequestVerificationToken; 
                    type=hidden; value=rEadYlTMOLXaBvbR98f4GSoinCZ7EcoQpTvk-cgTrd4O0LId9EC6UnyMuI_AEBbIzFox17xg_StbV1gVTuCt3YR-RbY1}, @{innerHTML=; innerText=; outerHTML=<input 
                    name="__RequestVerificationToken2" type="hidden" value="__RequestVerificationToken2390e32ac-75db-48fe-8cb5-f369daa51d1d">; outerText=; tagName=INPUT; 
                    name=__RequestVerificationToken2; type=hidden; value=__RequestVerificationToken2390e32ac-75db-48fe-8cb5-f369daa51d1d}}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 14409

**Comment by TingluoHuang** [comment]
@paul-lucas the token you used when you configure the agent.
PS C:\agent> .\config.cmd
Connect:

Enter server URL > https://intelia.visualstudio.com
Enter authentication type (press enter for `PAT`) >
- Enter personal access token > `****************************************************`

**Comment by paul-lucas** [comment]
Ah - I'd parsed that as 'PATH' :)

PS C:\Windows\system32> $bytes = [System.Text.Encoding]::ASCII.GetBytes("vsts:**********************************************************")
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
Invoke-WebRequest -Uri "https://intelia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1" -Headers @{ Authorization = $basicAuthValue } -useragent "vstsagentcore"


StatusCode        : 200
StatusDescription : OK
Content           : {"authenticatedUser":{"id":"42c6485d-2616-6b75-9481-51b56ee5d1b2","descriptor":"Microsoft.IdentityModel.Claims.ClaimsIdentity;6ee502f0-ffb4-46d8-a0a7-711fa97ef456\\paul.l
                    ucas@intelia.com.au","subjectD...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    X-TFS-ProcessId: 2fdc5286-f5c9-4fcc-aec3-56601b85ae48
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    ActivityId: f7e19ff8-56de-4fd2-8b72-91273ef0d8...
Forms             : {}
Headers           : {[Pragma, no-cache], [X-TFS-ProcessId, 2fdc5286-f5c9-4fcc-aec3-56601b85ae48], [Strict-Transport-Security, max-age=31536000; includeSubDomains], [ActivityId, 
                    f7e19ff8-56de-4fd2-8b72-91273ef0d89a]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 311278

**Comment by TingluoHuang** [comment]
@paul-lucas at the point the only difference between powershell and the agent is PowerShell will following IE proxy setting.
try add `-noproxy` to `Invoke-WebRequest`.
Can you share a screenshot of your IE proxy setting?

**Comment by paul-lucas** [comment]
OK with NoProxy:

PS C:\> $bytes = [System.Text.Encoding]::ASCII.GetBytes("vsts:********************"); $base64 = [System.Convert]::ToBase64String
($bytes); $basicAuthValue = "Basic $base64"; Invoke-WebRequest -Uri "https://int
elia.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&last
ChangeId64=-1" -Headers @{ Authorization = $basicAuthValue } -useragent "vstsage
ntcore" -NoProxy
Invoke-WebRequest : The operation timed out
At line:1 char:198
+ ... c $base64"; Invoke-WebRequest -Uri "https://intelia.visualstudio.com/ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...stsagentcore
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Com
mands.InvokeWebRequestCommand

IE proxy settings:
![image](https://user-images.githubusercontent.com/38638837/39109024-6db7d16a-470e-11e8-971e-2b54efbdf92a.png)

**Comment by TingluoHuang** [comment]
@paul-lucas ok, this definitely means there is a proxy server in your network that block the traffic, you might want to ask your IT department what's the proxy server url, and configure the agent to use that proxy, [DOC](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?view=vsts)

I am not sure how you can find the proxy server without help from IT department, but maybe worth for a shut.
check regiestry: [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]

**Comment by TingluoHuang** [comment]
@paul-lucas or try this one.
https://superuser.com/questions/33588/how-to-view-internet-explorer-auto-detected-proxy-settings

**Comment by paul-lucas** [comment]
Righto that did the trick! Managed to get proxy details out of IT, re-ran config with --proxyurl and installed all ok. Thanks very much for your help.

**Comment by TingluoHuang** [comment]
Cool. :)
