### ISSUE TITLE
Agent not pumping all logs to console

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vsts-agent#1525]
Link to build: https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9259381&_a=summary

Agent Diag Logs: 
[Build 9258646_Msn.Web.LifeStyle.Tests.dll_MSN.Service.Web.Prime-Test.UnitTests.1-Phase 1.zip](https://github.com/Microsoft/vsts-agent/files/1941003/Build.9258646_Msn.Web.LifeStyle.Tests.dll_MSN.Service.Web.Prime-Test.UnitTests.1-Phase.1.zip)

Task log: 
[7_VsTest Platform Installer Diagnostic Version.txt](https://github.com/Microsoft/vsts-agent/files/1941004/7_VsTest.Platform.Installer.Diagnostic.Version.txt)

Log file written to disk by task:
[8_VsTestToolInstallerDiagLog.txt](https://github.com/Microsoft/vsts-agent/files/1941068/8_VsTestToolInstallerDiagLog.txt)

Complete logs zip:
[DiagLogs.zip](https://github.com/Microsoft/vsts-agent/files/1941008/DiagLogs.zip)

The console logs of the task are incomplete. The logs written to disk by the task show that the task has run to completion successfully. But the subsequent task (VsTest task) fails because it is unable to find a particular variable that the vstest platform tool installer task sets.

In the logs written to disk it is evident that the task executed the set variable command but since this was never parsed by the agent (or never reached the agent) the variable did not get set and the functionality of the task was hampered.

Link to [original issue](https://github.com/Microsoft/vsts-agent/issues/1492) for more context

**Comment by ShreyasRmsft** [comment]
List of failures with agent diag logs and logs written to disk and uploaded. All of these failures occurred in the span of the last 12 hours.

https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9259381&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9260358&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9259772&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9259952&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9260365&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9262155&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9262177&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9261703&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9262162&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9264946&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9269889&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9269308&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9269698&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9271171&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9271366&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9274120&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9275257&_a=summary&tab=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=9275260&_a=summary&tab=summary

**Comment by TingluoHuang** [comment]
@ShreyasRmsft looks like the agent didn't get all STDOUT from your task. what's so special to your task that cause redirect STDOUT not working properly?
Can you try write a dotnet console app and call node.exe <your task.js> and redirect stdout?
Run 100 times, see whether the number of lines you redirected are same.

**Comment by ShreyasRmsft** [comment]
@TingluoHuang the task simply uses the debug warning functions present in the task-lib and apart from that has console.log for output.

There's nothing special.

**Comment by ShreyasRmsft** [comment]
@TingluoHuang this only repros on agents used by the Microsoft UST team. These are slow-ish machines. It has occurred over a 100 times in the last 2-3 weeks. 

Also when exactly do you want me to call this console app? At the beginning of the task code?

**Comment by TingluoHuang** [comment]
@ShreyasRmsft run the console app in your machine, then ask UST people to run the same console app on their machine.
i want to see whether we can get a repro without the agent.

**Comment by bryanmacfarlane** [comment]
The output is not coming out of the task.  Per the _diag logs, the agent pumps what comes out of the task.  The issue is the task is not writing all of it's output.  And it's only that task.
