### ISSUE TITLE
Add Files to Build Log

### ISSUE THREAD

**Issue by DSakura1987** [Microsoft/vsts-agent#1529]
## Agent Version and Platform
Version 2.122.1

Windows

## VSTS Type and Version
On-Prem TFS

TFS 2018

## What's not working?
I use Cake and [MSBuild Binary Log](https://github.com/Microsoft/msbuild/wiki/Binary-Log). Currently the agent captures all console output and upload it to the server, but I also want to upload binary logs to the server. Is there a way to add a file to build log? 

[JobServerQueue.cs#L189](https://github.com/Microsoft/vsts-agent/blob/0bc2022d397d68863e407201a18d0783828e4da0/src/Microsoft.VisualStudio.Services.Agent/JobServerQueue.cs#L189) seems to be the method used by agent, but I don't know how I can use it.

**Comment by TingluoHuang** [comment]
@DSakura1987 try use the `##vso` command from following doc
 https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

`##vso[task.uploadfile]local file path`
