### ISSUE TITLE
Segmentation fault ./bin/Agent.Listener configure "$@"

### ISSUE THREAD

**Issue by mingalsuo** [Microsoft/vsts-agent#1536]
## Have you tried trouble shooting?
Yes, issue is more fundamental though.

## Agent Version and Platform
2.133.3
Debian 9 (Stretch) amd64

## VSTS Type and Version
On-Prem

## What's not working?
config.sh: line 86: 30231 Segmentation fault ./bin/Agent.Listener configure "$@"

## Agent and Worker's Diagnostic Logs
Last line in _diag -log:
VisualStudioServices] Starting operation Location.GetConnectionData

Configuration fails with a segmentation fault straight after entering authentication credentials on Debian 9.

Thanks and regards,
mingalsuo

**Comment by TingluoHuang** [comment]
Cool, glad you unblock, i will close the issue.

**Comment by gigi81** [comment]
I have the exact same identical issue but I have no trace of libssl 1.0.0 on my system so the workaround doesn't work for me.
Any idea of what could be the problem or how I can diagnose it?

[root:/azp] # find / -name libssl*
/var/lib/dpkg/info/libssl1.1:amd64.postrm
/var/lib/dpkg/info/libssl1.0.2:amd64.postinst
/var/lib/dpkg/info/libssl1.0.2:amd64.templates
/var/lib/dpkg/info/libssl1.0.2:amd64.md5sums
/var/lib/dpkg/info/libssl1.1:amd64.triggers
/var/lib/dpkg/info/libssl1.0.2:amd64.shlibs
/var/lib/dpkg/info/libssl1.0.2:amd64.triggers
/var/lib/dpkg/info/libssl1.0.2:amd64.postrm
/var/lib/dpkg/info/libssl1.1:amd64.postinst
/var/lib/dpkg/info/libssl1.1:amd64.templates
/var/lib/dpkg/info/libssl1.1:amd64.shlibs
/var/lib/dpkg/info/libssl1.0.2:amd64.symbols
/var/lib/dpkg/info/libssl1.1:amd64.list
/var/lib/dpkg/info/libssl1.0.2:amd64.list
/var/lib/dpkg/info/libssl1.1:amd64.md5sums
/var/lib/dpkg/info/libssl1.1:amd64.symbols
/usr/local/ssl/lib/pkgconfig/libssl.pc
/usr/local/ssl/lib/libssl.a
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/share/doc/libssl1.1
/usr/share/doc/libssl1.0.2

apt --installed
libssl1.0.2/stable,stable,now 1.0.2r-1~deb9u1 amd64 [installed,automatic]
libssl1.1/stable,stable,now 1.1.0j-1~deb9u1 amd64 [installed,automatic]
