### ISSUE TITLE
Powershell unattended config for Build Agent install error VS30063

### ISSUE THREAD

**Issue by peckhamm** [Microsoft/vsts-agent#1538]
I have tried running it many different ways including calling a CMD.exe from powershell.  I have checked IIS Manager on the TFS server and both "Team Foundation Server" and "tfs" have anonymous authentication enabled (as I found in another thread on here).

## Agent Version and Platform
2.129.21 & 2.133.3
Windows Server 2008 R2

## VSTS Type and Version
On-Prem TFS 2017.3

## What's not working?
Trying to run a powershell script to "config remove" and then "config" to setup the build agent.
This is the line that stops it.
.\config.cmd --unattended --url $TFSServerURL --auth integrated --userName $SA_Username --password $SA_Password --pool $AgentPool --agent $BuildAgent --runAsService --windowsLogonAccount $SA_Username -windowsLogonPassword $SA_Password

Not sure if it was needed but I added --userName and --Password in an attempt to trouble shoot.  I have also removed the variable TFSServerURL and replaced it with that actual path of the server which has :8080/tfs at the end, but the error just shows the :8080.

PS D:\TFS_RM_Scripts> .\TFS_BuildAgent_00-Reinstall_Local.ps1
Enter Password for som\PeckhamM: ***********
Connecting to "Build Server Name".
Press Enter to continue...:
Configure VSBuild3 on "Build Server Name".

>> Connect:

VS30063: You are not authorized to access http://<TFS Server Name>:8080.
    + CategoryInfo          : NotSpecified: (VS30063: You ar..."Only the last 9 characters of our TFS Server Name":8080.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : "Build Server Name"

Just FYI: I replaced the actual server names with "TFS Server Name" and "Build Server Name".  Also in categoryInfo it only showed the last 9 characters of the TFS Server Name, they are normally 15 characters long.

**Comment by bryanmacfarlane** [comment]
you script is trying to register with an empty host name

VS30063: You are not authorized to access http://:8080

I don't believe that's a product issue.

**Comment by peckhamm** [comment]
Hey Bryan, I tried to actually redact the information for security reasons.  

The actual line is http://HCS123TFS901:8080/tfs and it's showing
VS30063: You are not authorized to access http://HCS123TFS901:8080.

Sorry for the confusion, I thought I had done a better job of redacting.

**Comment by TingluoHuang** [comment]
@peckhamm why you feed in username and password while using `--auth integrated` auth? integrate auth will use the current process run as user's windows credential.

**Comment by bryanmacfarlane** [comment]
Ahhh - you may want to replace with {redacted}.  I'll do that now.

**Comment by bryanmacfarlane** [comment]
@TingluoHuang comment is correct.  Do not use user and pass if integrated

**Comment by peckhamm** [comment]
@TingluoHuang I understand that user / pass issue, I was trying anything to get it to work.  Then I found another article that you had helped solve and it was anonymous authentication but we have that enabled in IIS.

**Comment by peckhamm** [comment]
Thank you @bryanmacfarlane.

**Comment by TingluoHuang** [comment]
@peckhamm can you share your agent diag log? it's under `_diag` folder in your agent root directory.

**Comment by peckhamm** [comment]
Sure, I have 21 of them.  I'm posting the last one in a hope that it helps.  If you need more information please just let me know and I'll get you another.

[AgentLog-001.txt](https://github.com/Microsoft/vsts-agent/files/1969401/AgentLog-001.txt)

**Comment by TingluoHuang** [comment]
@peckhamm i am wonder your long on user don't have permission to your TFS. have you try access your TFS server as that user in IE?
also, you are confident about the username/password, you can set --auth "negotiate" instead of `integrate`

**Comment by peckhamm** [comment]
@TingluoHuang I'll try the "negotiate" instead of integrate tomorrow.  But as for the access question, when I run the command from a command line and answer the questions manually it does work.  That account has elevated access on that server and in TFS.  

Would the script I'm attempting to execute help?
Would you like me to run it manually and send you the log from that?

**Comment by TingluoHuang** [comment]
@peckhamm Interactive works means when "you" run the config.cmd, you have permission to access your TFS server. However, when your script run, it doesn't run as "you", so it fail to authenticate. how did you run your script? remote powershell? or log on to the box run from powershell.exe?

**Comment by peckhamm** [comment]
I hope that seeing the script helps a bit and clarifies what I'm trying to do.  It resides on our TFS server, which is also where our Release Agent is.  Thank you @bryanmacfarlane and @TingluoHuang.  Now this version of the script is designed to run outside of the Release part of TFS so I can get data back on what its doing or not doing.

**Comment by TingluoHuang** [comment]
in your script `$session =New-PSSession -Computername $TargetServer`, can you add `-Credential som\PeckhamM` to `New-PSSession`? it will make the session run as `som\PeckhamM`

**Comment by TingluoHuang** [comment]
you can also call `whoami` in your powershell script to print out what's the current run as user.

**Comment by peckhamm** [comment]
@TingluoHuang thank you for that suggestion, I ran it with the -Credential part added in.  The first time it kicked me an error about how it was already configured so I went and config removed and ran it again.  VS30063 again.

I hope the logs below might help...
[AgentLog-002a.txt](https://github.com/Microsoft/vsts-agent/files/1969500/AgentLog-002a.txt)
[AgentLog-002b.txt](https://github.com/Microsoft/vsts-agent/files/1969501/AgentLog-002b.txt)

**Comment by TingluoHuang** [comment]
the config remove succeed in your 002a.txt log file, how did you run it? run as part of the script-tfs-local or running interactively.
can you print out the output from execute `whoami` to show what's the current running user?

**Comment by peckhamm** [comment]
I ran remove interactively.

PS D:\TFS_RM_Scripts> .\TFS_BuildAgent_00-Reinstall_Local.ps1
Enter Password for som\PeckhamM: ***********
whoami
som\peckhamm
Connecting to REDACTED.
som\peckhamm
Configure VSBuild3 on REDACTED.

>> Connect:

VS30063: You are not authorized to access http://REDACTED:8080.
    + CategoryInfo          : NotSpecified: (VS30063: You ar...ltfspa901:8080.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : REDACTED

PS D:\TFS_RM_Scripts>

**Comment by TingluoHuang** [comment]
can you run `whoami` directly from the powershell console? since you are using integrated auth, i would not expect you to get prompt for credential.
is there anyway i can have a skype meeting with you and you can share your screen?

**Comment by peckhamm** [comment]
@TingluoHuang sorry, I got pulled away on something else and am just now getting time to circle back to this.  Yes I am more than open to a skype meeting for you to see it but I have some new information.

First, the way it was running was a powershell script housed on our TFS server where the Release Agent was.  It was calling an invoke command, which started a new session on the TFS Build Server (where the build agents are).  I changed this.  I moved the script itself to the TFS Build Server and am using "Run Powershell script on a remote server" now to execute it there.  I would honestly say there was something with the invoke command that was breaking it.  It is now connecting to the correct http URL with /tfs at the end of it. 

But now it's bombing out on the Agent Pool, so I'm playing with that.  But I hope that might give you something to look into with that invoke command.  So now the config -remove unattended...  <vars> appears to be working.

I hope to have more shortly as I check log files.

**Comment by TingluoHuang** [comment]
@peckhamm any updates? i didn't receive email from you for a well.

**Comment by peckhamm** [comment]
@TingluoHuang thank you for the help.  The Auth document is very helpful in understanding how that works and the --replace addition is perfect.  Everything is working now.  So for anyone else having an issue similar to this check the Roles on the Agent Pools.

**Comment by peckhamm** [comment]
@TingluoHuang First, thank you for the help earlier today.  The --replace I think is going to be a great start.  Now the bad news, I started getting another error...  I'm wondering if you have a trick up your sleeve that might help.

##[error]System.Management.Automation.RuntimeException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item D:\TFSBuilds\VSBuild3\bin\Agent.Listener.dll: Access to the path 'Agent.Listener.dll' is denied. ---> System.Management.Automation.RuntimeException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item D:\TFSBuilds\VSBuild3\bin\Agent.Listener.dll: Access to the path 'Agent.Listener.dll' is denied.

Is there a way you suggest to 'stop' the agent.  At first I thought it was related to security but when I try to manually delete it I get an error that it's open in another window.
"The action can't be completed because the file is open in Agent.Listener.exe.  Close the file and try again."

**Comment by TingluoHuang** [comment]
@peckhamm you should be able to stop the agent windows service using `SC.exe stop <servicename>`

**Comment by peckhamm** [comment]
Perfect!  Thank you, I'll give it a shot.

**Comment by peckhamm** [comment]
@TingluoHuang that worked!  Exactly what I needed.  Thank you and I believe this issue can be closed.

**Comment by TingluoHuang** [comment]
@peckhamm cool, i am going to close this issue.

**Comment by pm141088** [comment]
@peckhamm - This thread has been really useful, I was wondering if you could kindly share the final script you put together to install the VSTS agents on your servers remotely. I've read through the comments a few times but it's not obvious to me how the issue was resolved in the end. Appreciate any help here. thanks!
