### ISSUE TITLE
When Clean Sources = True, allow "/diff" argument for "tf vc scorch" command to be optional

### ISSUE THREAD

**Issue by BrettJaner** [Microsoft/vsts-agent#1540]
I'm attempting to tune the build definition for my extra large tfvc legacy repository.  After some testing I've found that I can shave 15+ minutes off my build time if I was able to remove the "/diff" argument from the "tf vc scorch" command.  I'm wondering if having finer grain control over the cleaning process, would be entertained as a possible enhancement.  There seems to be other issues still opened regarding how "scorching" works.  I'm willing to dedicate some time to help if required.

Thanks,
Brett J

**Comment by ericsciple** [comment]
@daveVSTS  fyi

@BrettJaner it should be possible to uncheck clean and script the `tf scorch` command yourself. If you check Allow scripts access to OAuth token, you can execute the command line yourself and use $(system.accessToken) in place of `***`

Would that work?

**Comment by BrettJaner** [comment]
That does usually work and has been what I've done in the past.  Only problem with that solution is when I need to delete a project from source control.  When I delete a project from source control, the build errors on GetSources, saying "Unable to delete directory because directory is not empty."  I'm guessing this is because GetSources runs before the tf scorch and there are left over binaries in the directory or subdirectories from a previous build.  Only way for me to delete a project from source control is to require the next build to do a full clean by deleting the sourcesDirectory.  Maybe if I run tf scorch as part of build clean up?  I'll play with that and report back.

**Comment by BrettJaner** [comment]
I moved the `tf vc scorch` script to the end of the build definition and set it to run even if previous task has failed or build was canceled.  I've been running it like this on multiple build definitions for the past couple of days with no issues.  I can now delete whole project directories from source control again.  Thanks @ericsciple!  Closing the issue.
