### ISSUE TITLE
Agents updated to disallow multiline secrets before KeyVault task was updated to set exception variable.

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/vsts-agent#1541]
## Agent Version and Platform
2.133.3 

**OS of the machine running the agent?**
Linux

## VSTS Type and Version
VisualStudio.com

**If VisualStudio.com, what is your account name?**
http://dialearn.visualstudio.com

## What's not working?
The actual issue with agents and key vault tasks has already been fixed with task 1.0.18, but this is more about asking questions about what I can do as user of Hosted Agents to prevent this from occurring again or provoking process change on the teams that release these changes to agents.

We are using the Hosted Linux Preview agents and also using a Azure Key Vault build tasks to download a cert into a build variable.

There is a order of operations issue where the Agents were updated to disallow multiline secret variables before the KeyVault task was updated to set the SYSTEM_UNSAFEALLOWMULTILINESECRET variable.

This caused hours of downtime as we try to debug and understand how the build was passing before and now is broken.

![image](https://user-images.githubusercontent.com/2856501/39554445-b4ef6f28-4e27-11e8-9d3d-a1544dede743.png)

![image](https://user-images.githubusercontent.com/2856501/39554462-c9d391b2-4e27-11e8-82cc-e3b25008d686.png)

We found this change on the agents:
https://github.com/Microsoft/vsts-agent/pull/1511/commits/c307d84885dd6a02a29fc55c9b36f2bca4c2a908?utf8=%E2%9C%93&diff=split

And then this fix in the KeyVault task:
https://github.com/Microsoft/vsts-tasks/commit/6d1b8ee03e044059960ad39c9d950e318346f054#diff-22c46e2b1798c388f50afaddd64844f0

There are multiple issues here that could be improved.

**1. How do we subscribe to these list of breaking changes to agents?**
Or was this not known to be breaking?

**2. Is there a better process so that the agent only updates if the tasks it requires are also updated?**
E.g. Our agent should have ran with 1.0.18 of KeyVault but it was not available yet.  Only 1.0.16 was available so we had to manually set the SYSTEM_UNSAFEALLOWMULTILINESECRET variable to fix.

**Is there a way to lock the version of a hosted agent?**
Perhaps I can set a build demand variable that restricts hosted agent version? I assume this could cause a lot of fragmentation while the point of hosted is to always be up to date, but perhaps there is compromise solution that does the best of both like windows fast ring vs slow ring.

I understand that these hosted agents are in preview, but the nature of this issue is worrisome.  It seems like the changes across vsts-tasks and vsts-agents repos would need to be synchronized somehow.

See other issue here:
https://developercommunity.visualstudio.com/content/problem/244260/keyvault-cert-download-vsts-task-fails-on-hosted-l.html

**Comment by mattmazzola** [comment]
Also, slightly related question.

The build variable is prefixed with **UNSAFE** (SYSTEM_UNSAFEALLOWMULTILINESECRET) which makes me think there was some security/risk with allowing multi-line secret variable.

If this KeyVault task is setting the build variable to allow this unsafe practice does it stay enabled for the rest of the build or does it only exist for duration of task?

Since I was digging around in the code I was expecting the UNSAFEALLOW to be set at the beginning and removed at the end so only the variables set by this task are exempt. but other later tasks still can have error.

**Comment by bryanmacfarlane** [comment]
Log issue in vsts-tasks repo for azure key vault task
