### ISSUE TITLE
 401 Unauthorized Error Consuming vsts Extension with Certificate

### ISSUE THREAD

**Issue by andreinfra** [Microsoft/vsts-agent#1545]
Good morning everyone!

I'm having trouble getting the extension created for the vsts using the certificate generated by the extension.  By the official documentation to which the link refers https://docs.microsoft.com/en-us/vsts/extend/develop/auth?view=vsts the same does not work because the version of the System.IdentityModel.Tokens.Jwt is using version 4.0.2.206221351 and with the advent now the minimum acceptable to download the package is 5.1.4 however in this case the method var validationParameters = new TokenValidationParameters () if it contains the parameters the item IssuerSigningTokens no longer exists.  
Someone has some example that I can base to be able to access my api using authorization without getting a code 401. It is developed the api in dotnet core 2.0

**Comment by TingluoHuang** [comment]
@andreinfra i don't think the question you ask is scope to this repository, i would like to suggest you ask the question at https://developercommunity.visualstudio.com/spaces/21/index.html
