### ISSUE TITLE
Git lfs exit code 2 - on second git lfs fetch

### ISSUE THREAD

**Issue by matthid** [Microsoft/vsts-agent#1548]
## Have you tried trouble shooting?

Yes, in fact I found another bug that when you set `GIT_TRACE` globally the agent will crash.

## Agent Version and Platform

Version of your agent: `2.131.0`
Version of git: `2.16.1.windows.4`
Version of git-lfs: `git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73`

Running on Windows 7

## VSTS Type and Version

On-Prem TFS 2017.3 (15.117.27414.0)?

## What's not working?

Basically the problem is the following:

- We have a git project with lfs files
- We have a build
- After clearing the source directory (ie .git folder in the agent for the build) the build always works fine
- The build works fine for the same git-"branch"
- When running the build for a different git-branch we get the following output (domain and project name changed):

```
Fetch LFS objects for git repository at: C:\TFS\work\2\s remote: origin.

git -c http.http://tfs.<domain>:8080.extraheader="AUTHORIZATION: bearer ***" lfs fetch origin <sha1>
Fetching <sha1>

batch response: Git credentials for http://tfs.<domain>:8080/tfs/<teamproject>/_git/<project> not found.
batch response: Git credentials for http://tfs.<domain>:8080/tfs/<teamproject>/_git/<project> not found.
Git LFS: (0 of 128 files) 0 B / 888.38 MB                                      
error: failed to fetch some objects from 'http://tfs.<domain>:8080/tfs/<teamproject>/_git/<project>.git/info/lfs'

Get git-lfs logs.

git lfs logs last
No logs to show

Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.

System.InvalidOperationException: Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

The log is already the most verbose setting I could figure out (and I even tried to compile the agent myself and "hack-in" GIT_TRACE support).

## Agent and Worker's Diagnostic Logs

See above

## Related Repositories

I guess this is the correct place.

## Questions:

- Any idea how to further diagnose this?
- Running locally on the agent works (ie git is asking for password) so I'd assume it is related to the "token"
- I'd assume it has to do with how we have different lfs files across the branches (ie. the same file might be a lfs file in one branch and checked-in directly in another one or not exist at all)

**Comment by TingluoHuang** [comment]
@matthid looks like the build service identity (the OAuth token's identity) don't have permission on LFS files in your other branch? 
Btw, set GIT_Trace shouldn't crash the agent, i thought the agent will remove GIT_Trace env before running any git command.

**Comment by TingluoHuang** [comment]
@matthid sorry for late reply, i was out for conference. do you have lfs object in the branch that `git lfs fetch` not working? 
let's say:
1. you queue a build in master branch, and everything works.
2. you queue a build in feature branch, and lfs report error.
3. if you queue a new build to master branch again, does everything still working for master?

**Comment by matthid** [comment]
> if you queue a new build to master branch again, does everything still working for master?

@TingluoHuang Yes this is what we see in our system.

**Comment by TingluoHuang** [comment]
@matthid does your other branch has git lfs object at all?

**Comment by matthid** [comment]
Just to make it clear: The other way around works as well:


0. Cleanup everything on the agent (ie clear .git directory)
1. you queue a build in feature branch, and everything works.
2. you queue a build in master branch, and lfs report error.
3. if you queue a new build to feature branch again, does everything still working for feature? -> yes

This hopefully clarifies your next question as well (where the answer is yes)

**Comment by matthid** [comment]
We basically report this here because we have no more ideas on how we can debug this further than what we have already figured out above.

**Comment by TingluoHuang** [comment]
@matthid i understand, it looks weird to me, but i will try to help you out.
https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

can you set GIT_TRACE=/somepath/log.txt ?

base on the doc, it will print all trace log to a file if the value of that env start with `/` :D

**Comment by matthid** [comment]
@TingluoHuang Ok retrieving the logs now.
Something I noticed in the mean time It's not actually related to switching branches. More generally: It's just that the initial clone+lfs fetch works and as soon as new lfs files arrive it fails. This actually makes a lot more sense.

**Comment by matthid** [comment]
@TingluoHuang Thanks for the trace idea. We tried several different versions. We have this problem since upgrading TFS from I believe 2017.1.

I think with the trace logs I could figure out the reason. Basically we have a `.lfsconfig` with the following contents:

```
[lfs "http://<domain>:8080/tfs/<teamproject>/_git/<project>/info/lfs"]
       access = basic
```

With the logs I realized that the difference between the working and non working version was:

broken: `trace git-lfs: run_command: 'git' config -l -f C:\TFS\work\2\s\.lfsconfig` BEFORE `git lfs fetch`
working: the call is made AFTER `git lfs fetch`

Obviously - before we even started to debug into this - the first thing we tried is to remove the `.lfsconfig` file. However this is not working (or at least in our tests), because of how the vsts agent works.

It first executes `git clean -fdx` from the PREVIOUS state. This means it does restore the state from the previous build (and for us basically restored ".lfsconfig")!

I believe we have the `.lfsconfig` in place to workaround some client side issues. Is there a way for vsts-agent to ignore the config? Otherwise we might need to find a different way or check if we still actually need it.

I think vsts-agent should work even with `.lfsconfig` in place.

**Comment by TingluoHuang** [comment]
@matthid thank you so much on your detail analyze!
I am still think this is a bug in git-lfs, i would except `git -c http.extraheader lfs fetch` always overwrite whatever in your config file.
I will create an issue in git-lfs and get thought from them.

**Comment by matthid** [comment]
@TingluoHuang Ah yes, you are correct. Still it feels a bit strange to use the "old" `.lfsconfig` but I guess that's just how it works.

**Comment by matthid** [comment]
@TingluoHuang Ok we discussed this internally and we need the `.lfsconfig` file because of client side issues. Can you think of any other workaround? The point is it apparently worked before the TFS upgrade (we upgraded the agents at this point) so it worked with an older vsts-agent version?

Should we try to downgrade to old vsts-agent version? Also please feel free to link the lfs-issue (if it is public)

**Comment by matthid** [comment]
We actually verified that an older version fixes the problem

**Comment by TingluoHuang** [comment]
@matthid which version you use?

**Comment by matthid** [comment]
Ahhh wait we tested this on a different machine which might have credentials in the credentials manager. This issue is really tricky to track down, sorry

**Comment by matthid** [comment]
but this might be our workaround just add it to the credential manager ...

**Comment by matthid** [comment]
They apparently already released a version with the fix. We will update our agents and report back.

**Comment by TingluoHuang** [comment]
https://github.com/git-lfs/git-lfs/releases/tag/v2.4.1

Thanks!

**Comment by TingluoHuang** [comment]
close the issue as git-lfs release a newer version with the fix.

**Comment by milbrandt** [comment]
As announced by @matthid we upgraded our build servers to git 2.17.0 and git-lfs 2.4.1 this morning. Up to now the issue seems to be fixed. Thx.

**Comment by rswarnka-cg** [comment]
Facing this issue #4901 ... still unable to get a fix for this.
