### ISSUE TITLE
On prem TFS 2017 still pointing at version 2.122.1  Ok to dl latest version?

### ISSUE THREAD

**Issue by Larswa** [Microsoft/vsts-agent#1550]
Quick question. 

Our on prem TFS is pointing at 2.122.1 agent and our infosec department is screaming at us to upgrade the agents GIT to a higher. I'd love to just deploy the latest agent

Is it safe to "just" manually upgrade the agent to the latest version, whenever one comes out, is stuck on TFS 2017?

And why is the on prem version of tfs not pointing to "the latest" version of the agent?

**Comment by bryanmacfarlane** [comment]
Yes, we support latest

**Comment by Larswa** [comment]
Thanks Bryan
