### ISSUE TITLE
Capturing Performance counters from Agent machines

### ISSUE THREAD

**Issue by Praveen1im** [Microsoft/vsts-agent#1554]
## VSTS Type and Version
VisualStudio.com

If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

If VisualStudio.com, what is your account name? http://1id.visualstudio.com

## What's not working?
We are using Visual studio 2017 Cloud load test and self provisioned rig for running our load tests and we configured some vm's as agents under the self provisioned rig and running the load test using cloud but we are not able to capture the counters from the server machines.

Virtual machines which are acting as agents and the server machines from which we need to capture the counters are in different domain and vsts and visual studio are in different domain.

![image](https://user-images.githubusercontent.com/39156811/39867093-eabdadc8-5470-11e8-9e3f-538299d417c6.png)

![image](https://user-images.githubusercontent.com/39156811/39867140-23591190-5471-11e8-8563-6c0b15f63703.png)

So please let us know how capture the performance counters from the server machines when we run the load test using Visual studio cloud load test.

**Comment by bryanmacfarlane** [comment]
This doesn't appear to be a bug or issue in the application in this repo.  You might want to try developercommunity
