### ISSUE TITLE
Cannot Run Yaml Builds on Private Agent

### ISSUE THREAD

**Issue by wsmckenz** [Microsoft/vsts-agent#1556]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 

2.133.3

OS of the machine running the agent? 

Linux

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://chevron.visualstudio.com

## What's not working?
Yaml builds wont use private agents. Permissions are correct, but jobs just sit in the queue saying "Waiting for an enabled agent. All possible agents are disabled." I can only make yaml build work on Hosted Agents

## Agent and Worker's Diagnostic Logs
No useful logs, since an agent is never selected.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by wsmckenz** [comment]
I don't have any agent demands. My yml is really simple to start.

resources:
- repo: self
steps:
- bash: 'env'

**Comment by TingluoHuang** [comment]
@wsmckenz can you share an url to the build?

**Comment by wsmckenz** [comment]
I dont think you can get to our url, based on required authentication.

**Comment by wsmckenz** [comment]
Is there something I can post that would help

**Comment by TingluoHuang** [comment]
@wsmckenz i don't need to access the page in your VSTS account, base on the url, i can find the buildid and query backend database to see what might causing this.
i think it's fine to post here. :)

**Comment by wsmckenz** [comment]
Build: https://chevron.visualstudio.com/AnsibleRoles/AnsibleRoles%20Team/_build/index?buildId=6068&_a=summary

Definition: https://chevron.visualstudio.com/AnsibleRoles/AnsibleRoles%20Team/_build/index?definitionId=286&_a=completed

**Comment by wsmckenz** [comment]
Hmm, I updated to latest, and it looked like it successfully updated all the agents to 2.133.3, but when I look at capabilties, they all say 

2.131.0
--

**Comment by TingluoHuang** [comment]
can you zip one of the agent's _diag folder from the agent that didn't update successfully?

**Comment by TingluoHuang** [comment]
@wsmckenz looks like all agent updates are failed in your account, we need agent diag log from those machine.
you can find them under `_diag` folder of each agent's root directory.
zip it up and send to `tihuang @ microsoft.com`

**Comment by TingluoHuang** [comment]
@wsmckenz base on your log, the agent is getting SSL error when try to download agent package from Azure blob storage.

```
[2018-05-11 16:48:36Z ERR  AgentProcess] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.<DownloadLatestAgent>d__10.MoveNext()
```

Can you try hit the endpoint of package download manually using `curl` or `wget` from your box?
`https://vstsagentpackage.azureedge.net/agent/2.133.3/vsts-agent-linux-x64-2.133.3.tar.gz`

I am wonder whether there is some network issue in your environment, like a proxy/firewall in your corp net.

**Comment by wsmckenz** [comment]
yes, it fails. it is a firewall issue. do you know if we can change the url
the agent uses for download? I could load the files into our on-prem
artifactory and they could pull from there.

**Comment by TingluoHuang** [comment]
Sorry you can't, the url is stored at VSTS server side, can your IT department add that url to write list?

**Comment by wsmckenz** [comment]
Yes, I can start the work on that. Just takes a week :-)

Are there instructions somewhere to manually upgrade the agent?

Thanks for the help.

BTW, is there any way for me to see in VSTS what agent capabilities are
being requested by a job? when the job is accepted, I can see in the agent
log what version of the agent was requested, but I cant find a way to see
that for a queued job.

**Comment by TingluoHuang** [comment]
1. stop the agent service. (svc.sh stop) i can't remember clearly about the args.
2. rename /bin -> /bin.old
3. rename /external ->/external.old
4. copy /bin from https://vstsagentpackage.azureedge.net/agent/2.133.3/vsts-agent-linux-x64-2.133.3.tar.gz
5. copy /external from https://vstsagentpackage.azureedge.net/agent/2.133.3/vsts-agent-linux-x64-2.133.3.tar.gz
6. delete those renamed folder.
7. svc.sh start.

**Comment by wsmckenz** [comment]
great, thanks

**Comment by TingluoHuang** [comment]
@wsmckenz i am going to close this issue, since it's a network (firewall) issue within your environment.
please reopen if you need more help.

**Comment by TingluoHuang** [comment]
the full picture:
Run yaml builds require latest version agent.
Customer's agent fail to update due to firewall.
