### ISSUE TITLE
Can not run task inside container on hosted agent

### ISSUE THREAD

**Issue by Davis10733** [Microsoft/vsts-agent#1557]
## Agent Version and Platform
Hosted Linux Preview

## VSTS Type and Version
http://kpmg-taiwan-blockchain-lab.visualstudio.com

## What's not working?
I try to run a task inside container. It worked before April. But after that it has broken. The error message is on the following paragraph. It seems like docker version on the hosted agent is not compatible with docker host. Is something has changed ? 

```
##[command]/usr/local/bin/docker version --format '{{.Server.Version}}'
'17.09.0-ce'
Docker daemon version: '17.09.0-ce'
##[command]/usr/local/bin/docker version --format '{{.Client.Version}}'
'17.12.0-ce'
Docker client version: '17.12.0-ce'
##[error]Min required docker server version is '17.12', your docker ('/usr/local/bin/docker') server version is '17.9.0'
```

vsts.ci.yaml

```
queue: Hosted Linux Preview
variables:
  _PREVIEW_VSTS_DOCKER_IMAGE: "jermysu/docker-vsts-ci:0.10"

steps:
- script:
    ...
```

**Comment by TingluoHuang** [comment]
@Davis10733 thanks for reporting this issue. @thechrisjohnson is going to fix this soon.

**Comment by thechrisjohnson** [comment]
We're currently updating the underlying host os image, and will start rolling this change out in the beginning of next week (May 21st).

**Comment by thechrisjohnson** [comment]
The update has been pushed to all rings. Please try your scenario again, and let us know if you see any issues!
