### ISSUE TITLE
Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://tfs.yourserver.com/tfs/DefaultCollection/" -jwt:*** -noprompt'.

### ISSUE THREAD

**Issue by Krishnd** [Microsoft/vsts-agent#1564]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.133.3
OS of the machine running the agent? OSX
## VSTS Type and Version
On-Prem TFS. 

If On-Prem TFS, which release? 2017
If VisualStudio.com, what is your account name? http://account.visualstudio.com

## What's not working?
I have installed and configured the latest MAC OS x build agent in the system and configured it to run it as service and installed the TEE-CLC .But when tried to run the build definition I am getting the following error.
Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://tfs.yourserver.com/tfs/DefaultCollection/" -jwt:*** -noprompt'.
Please help me to fix this issue as I am not so familiar with MAC OS x. Please find the log files attached.
[logs_189757.zip](https://github.com/Microsoft/vsts-agent/files/2012109/logs_189757.zip)

The latest version of Java was installed in it and also I tried adding the certificate to the Java key store to fix those issue. But still no luck.

Also after installing the agent I couldn't access TFS link from safari. But I could access it from other browsers like Mozilla.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@Krishnd can you try run `/Users/tfsbuild/myagent/externals/tee/tf workspaces -format:xml "-collection:https://tfs.gmgcolor.com/tfs/DefaultCollection/"` and see what you get?

**Comment by Krishnd** [comment]
I am getting the following error when I run the command locally
An error occurred: Access denied connecting to TFS server https://tfs.myserver.com/ (authenticating with TFS service credentials).
If I remove the switches (-jwt:*** -noprompt) it works fine from the command line.

**Comment by Krishnd** [comment]
It works fine from the command line 

<?xml version="1.0" encoding="utf-8"?><workspaces>
  <workspace name="CS" owner="e22f4921-76f6-4a92-b8d0-54e55540a6b1" owner-display-name="TFSBUILD" computer="MACDETUSD2" comment="" server="https://tfs.myserver.com/tfs/defaultcollection/">
    <working-folder server-item="$/My-Software/Products/CS/Main" local-item="/Users/Meera/Documents/_s/MyCollection" type="map" depth="full"/>
  </workspace>
  <workspace name="CS1" owner="e22f4921-76f6-4a92-b8d0-54e55540a6b1" owner-display-name="TFSBUILD" computer="MACDETUSD2" comment="" server="https://tfs.myserver.com/tfs/defaultcollection/">
    <working-folder server-item="$/My-Software/Products/CS/Main" local-item="/Users/tfsbuild/Documents/Build/_s" type="map" depth="full"/>
  </workspace>
</workspaces>
MACDETUSD20:tee tfsbuild$ 

But if I include the switches (-jwt:*** -noprompt) in the command, it returns the following error:- 
An error occurred: Access denied connecting to TFS server https://tfs.myserver.com/ (authenticating with TFS service credentials)

**Comment by Krishnd** [comment]
Thank you so much for your quick response.
It works fine from the command line (I edited the original server names for privacy below)
<?xml version="1.0" encoding="utf-8"?><workspaces>
  <workspace name="CS" owner="e22f4921-76f6-4a92-b8d0-54e55540a6b1" owner-display-name="TFSBUILD" computer="MACDETUSD2" comment="" server="https://tfs.myserver.com/tfs/defaultcollection/">
    <working-folder server-item="$/My-Software/Products/CS/Main" local-item="/Users/Meera/Documents/_s/MyCollection" type="map" depth="full"/>
  </workspace>
  <workspace name="CS1" owner="e22f4921-76f6-4a92-b8d0-54e55540a6b1" owner-display-name="TFSBUILD" computer="MACDETUSD2" comment="" server="https://tfs.myserver.com/tfs/defaultcollection/">
    <working-folder server-item="$/My-Software/Products/CS/Main" local-item="/Users/tfsbuild/Documents/Build/_s" type="map" depth="full"/>
  </workspace>
</workspaces>

If I added the switch ( -jwt:*** -noprompt) to the command line , I will get the following error
An error occurred: Access denied connecting to TFS server https://tfs.myserver.com/ (authenticating with TFS service credentials)

**Comment by Krishnd** [comment]
Any solution updates on this issue?

**Comment by Krishnd** [comment]
After changing the user permission, I could access the tfs link from safari. But still the issue from build exists. It works fine manually from the command line. Please help me on this. We need to get it fixed urgently.

**Comment by TingluoHuang** [comment]
@Krishnd you don't need to install TEE-CLC yourself, the agent has a copy of TEE with it under `/Users/tfsbuild/myagent/externals/tee`. I am not expert in TEE, i need to find someone to help you out.

**Comment by whoisj** [comment]
@Krishnd by "The latest version of Java was installed", which version of Java are you referring to? I am not certain CLC has ever been tested against Java 9 or later.

@AlexRukhlin could you lend your wisdom and provide any insights here?

**Comment by Krishnd** [comment]
@TingluoHuang @whoisj  Finally I could fix the issue. I had manually installed the TEE-CLC in the system before. Today I  removed it and also deleted and configured the build agent(with latest version) again. After that I couldn't access the tfs link from safari and from the terminal window also , if we type 'tf' nothing happens. But it was working fine with the manually downloaded TEE-CLC. So I used a copy of the manually downloaded TEE-CLC in the build agent directory and it works fine after that. So I think the TEE-CLC version with the agent has the issue.
Thank you all for your help :)

**Comment by TingluoHuang** [comment]
@Krishnd what's the version of TEE do you get? and where do you get them from, like URL?

**Comment by Krishnd** [comment]
@TingluoHuang I used the TEE version 14.123.1. I got it from https://github.com/Microsoft/team-explorer-everywhere/releases

**Comment by TingluoHuang** [comment]
@Krishnd that's odd, the agent should use the same version of TEE as you.

**Comment by TingluoHuang** [comment]
@Krishnd Ok, i need to bump it to at latest 14.122.0 or above. :( i don't remember why i am missing that.

**Comment by Krishnd** [comment]
@TingluoHuang  ok.Thank you.

**Comment by TingluoHuang** [comment]
i am going to close the issue, the next agent release will contains latest tf.exe
