### ISSUE TITLE
VSTS online‘s Hosted Agent sometimes doesn't run even there no queue ahead

### ISSUE THREAD

**Issue by ToMakeSense** [Microsoft/vsts-agent#1567]
**Queue a new build**
![image](https://user-images.githubusercontent.com/6244148/40180613-d0fbdb2c-5a19-11e8-9690-853eef2de4d0.png)

**The build task rank the first(Red mark)**
![image](https://user-images.githubusercontent.com/6244148/40178908-715a8956-5a15-11e8-9e04-eacaae6399ca.png)

**Do not run for a long time(#3198 is the same situation  as #3202, I canceled it, then #3201 could run successfully)**
![image](https://user-images.githubusercontent.com/6244148/40180350-2e603e30-5a19-11e8-9ecb-4be51cff40cb.png)

**Comment by bryanmacfarlane** [comment]
It's blocked waiting on concurrency (purchased concurrency).  At the point you're looking at, no agent has even started up.  It's waiting on the service for purchased concurrency to free up.  The UI does not make that clear and there's an effort underway to fix that and make it more obvious what it's waiting on.

**Comment by ToMakeSense** [comment]
![image](https://user-images.githubusercontent.com/6244148/40181080-d62d31b2-5a1a-11e8-8513-041d65f64f23.png)

**Comment by bryanmacfarlane** [comment]
Thanks for adding that error message to the issue.  That particular error is a service side bug that was is race timing issue during cancel.  That's a known issue we're fixing now.  But it's a knock on effect of the cancel after blocking on purchased concurrent jobs.  Neither are agent application bugs (this repo).  If you want you can create a developer community issue and we can track it there as the improvements I mentioned are rolled out.

**Comment by ToMakeSense** [comment]
@bryanmacfarlane  sorry, I am doing enterprise development, I can't share you the account information.
