### ISSUE TITLE
Environment variable's value passed to spawn processes are truncate at 'equal' character

### ISSUE THREAD

**Issue by lukka** [Microsoft/vsts-agent#1568]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
2.126.0 

OS of the machine running the agent? OSX/Windows/Linux/...
WIndows 10

## VSTS Type and Version
VSTS

## What's not working?
Environment variables are truncate if the value contains a '=' character.

The bug is clearly at these lines:

[var keyValuePair = envStr.Split('=', 2);](
https://github.com/Microsoft/vsts-agent/blob/1ee38f4be6d695ca3eaa1ad150672587546ae0fa/src/Microsoft.VisualStudio.Services.Agent/ProcessExtensions.cs#L270)

and 

[string[] env = envString.Split("=", 2);](https://github.com/Microsoft/vsts-agent/blob/1ee38f4be6d695ca3eaa1ad150672587546ae0fa/src/Microsoft.VisualStudio.Services.Agent/ProcessExtensions.cs#L146)

as they do not take into account that there could be an equal character in the environment variable.

**Comment by TingluoHuang** [comment]
@lukka the 2 files your referenced is used by the agent process to read environment variable from given process on the machine, it shouldn't affect how agent spawns child process.
also, since you are in 2.126.0, i don't believe your agent binary has those 2 files.

can you share an example or log about the issue you run into?

**Comment by lukka** [comment]
i experienced the problem in a powershell script that runs vstest.console.exe assembly.dll.
In the code of assembly.dll the environment variables are truncate at '='.

I got around it encoding the values of variables as URL, so it is not really important, it might be a bug in vstest.console.exe too.
