### ISSUE TITLE
yaml Pipeline Build -  timeoutInMinutes cannot be set with a $(variable)

### ISSUE THREAD

**Issue by paul-green** [Microsoft/vsts-agent#1571]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
2.133.3

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

## VSTS Type and Version
VisualStudio.com 

If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

If VisualStudio.com, what is your account name? http://account.visualstudio.com
recreo.visualstudio.com

## What's not working?
Setting the queue timeoutInMinutes to a build $(variable) creates a syntax/parse error. The variable is set to an integer in the Variables section of the build settings.

If I set the value to a literal value - e.g. 90 - it is fine. Seems this setting doesn't understand variables

**YAML Pipline:**
![image](https://user-images.githubusercontent.com/4505378/40343757-cfe44cba-5dd4-11e8-970c-6650599647d4.png)

**Build Variable**
![image](https://user-images.githubusercontent.com/4505378/40343776-f3b4924e-5dd4-11e8-846a-036db34c1167.png)

**Error**
![image](https://user-images.githubusercontent.com/4505378/40343740-b963a440-5dd4-11e8-974b-04d3c232dc2b.png)

When set to a literal value it works OK;
![image](https://user-images.githubusercontent.com/4505378/40343814-26693a78-5dd5-11e8-865f-c20a6762fbc3.png)

## Agent and Worker's Diagnostic Logs
No logs - build can't start

**Comment by ericsciple** [comment]
`$( )` macro syntax isn't currently supported for that field. You can use a pipeline expression in that field, for example `$[ variables['Build.TimeoutMins'] ]` 

we have work to do, to clean up consistency here and add a doc that talks about variables/macros/expressions.

**Comment by paul-green** [comment]
Thanks for the tip!

**Comment by bew** [comment]
I just hit this issue when setting a timeout for a job & a task (required for the [`ManualValidation` task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines)).

Why is it not supported for this field specifically, even though variable are supported just fine for other fields at job/task level? 🤔

**Comment by elninoisback** [comment]
> I just hit this issue when setting a timeout for a job & a task (required for the [`ManualValidation` task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines)). The suggested solution works at job-level, but not at task-level ><
> 
> 👉 Why is it not supported for this field specifically, even though variables are supported just fine for other fields at job/task level?

I also could not find how to set a runtime variable value to the timeoutInMinutes in ManualValidation task. I need to set a computed value here and apparently, nothing worked.
