### ISSUE TITLE
Exit Code 100 on Get Sources: 'tf shelve ...' - The option collection is not allowed

### ISSUE THREAD

**Issue by Blackbaud-TyriekeMorton** [Microsoft/vsts-agent#1572]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.134

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? https://blackbaud.visualstudio.com

## What's not working?
On the Get Sources step of our Gated Check-ins, we are receiving this error: 

The option collection is not allowed.
Exit code 100 returned from process: file name 'tf', arguments 'vc shelve /saved /replace /recursive /comment:@C:\Users\VssAdministrator\AppData\Local\Temp\tmp44BC.tmp _Build_508985 D:\a\44\s /collection:https://blackbaud.visualstudio.com/ /loginType:OAuth /login:.,*** /noprompt'

I've also tried the command locally and received the same error. 

We'd really like to get this problem fixed because at the moment it has the potential to stop us from releasing updates. 

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
#1573

**Comment by Blackbaud-TyriekeMorton** [comment]
@TingluoHuang thank you! When could we expect these changes to be rolled out / reflected in our following builds?

**Comment by TingluoHuang** [comment]
@Blackbaud-TyriekeMorton i am pushing the release right now, for safe deployment i need run basic validation before i push the release out to hosted agent, and the deployment will be rolled ring by ring.
So, ETA 2-3 hours to hit all rings that got affected today.

**Comment by TingluoHuang** [comment]
i am going to close the issue since the agent with the fix has been released. 2.134.2
