### ISSUE TITLE
Download Secure File task fail

### ISSUE THREAD

**Issue by Prashanth-PS** [Microsoft/vsts-agent#1574]
The Download Secure file task works fine on the Hosted agent but the same task gets failed on a Private Agent with the below error. 
##[error]Error: connect ETIMEDOUT 13.107.6.175:443

Please let us know what feature needs to be enabled/set under the private agent to download the Certificates to a target machine from VSTS Library

**Comment by TingluoHuang** [comment]
@Prashanth-PS please log an issue in VSTS-Tasks repository for task related question. :)
