### ISSUE TITLE
Error CS2012

### ISSUE THREAD

**Issue by Claytonator** [Microsoft/vsts-agent#1577]
Hi, randomly I get this error when queue the building with /m option

We have a TFS 2017 and privated hosted agents pool. The versión of the hosted agents are  2.122.1

How we can avoid this problema, running the build in multicpu option.

Thanks so much.

Error:

  CSC (0, 0)  
 
CSC(0,0): Error CS2012: Cannot open 'D:\Builds\1\2\s\Units\Utilities\Source\UnitTesting\obj\Debug\Example.Comit.Utilities.UnitTesting.dll' for writing -- 'Access to the path 'D:\Builds\1\2\s\Units\Utilities\Source\UnitTesting\obj\Debug\Example.Comit.Utilities.UnitTesting.dll' is denied.'
 


 
Process 'msbuild.exe' exited with code '1'.

**Comment by TingluoHuang** [comment]
@Claytonator i don't think your issue has any thing to do with the build agent, the agent just invoke msbuild.exe with the arguments you provide. From what i can tell, `/m` option in msbuild is a little bit tricky. you might want to ask your question to Msbuild repository. https://github.com/Microsoft/msbuild
