### ISSUE TITLE
Enable anchors in YAML builds

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/vsts-agent#1580]
##Agent Version and Platform  
Windows | Linux  

##VSTS Type and Version  
VisualStudio.com  

##If VisualStudio.com, what is your account name?  
http://msdata.visualstudio.com

##What's not working?
I would love it if I could use anchors in my yml file to enable some code reuse.  For example:
```
&REPEATED_TASK { displayName: foo, inputs: bar }
...
- task:
  <<: *REPEATED_TASK
```

Thanks!

**Comment by ericsciple** [comment]
I agree. It's something we want to enable.

Note templates are currently supported and allow for code reuse.

It's interesting that in your example you used `...` are you suggesting to allow for a separate document where you can define anchors, and then your process document where you can reference the anchors defined in the separate document?

**Comment by montebhoover** [comment]
Thanks for the tip on the templates - I wasn't aware of them and they are in fact a better fit for my needs: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md

The `...` just referred to space in the same .vsts-ci.yml document.  Thanks again!

**Comment by felixfbecker** [comment]
Could this be reopened? I just set up VSTS for the first time and was very surprised they don't work. They work in every other CI provider I've used before (Travis, Circle, Buildkite). Having to write an extra template file with parameters just to reuse simple structures/values is cumbersome, and with the parameterization it's harder to typecheck against a schema in an editor. It's also a bad first user experience because you don't find out they are not supported until you committed the YAML and triggered another build - too many of these failed builds because of invalid config cause frustration.

I really wonder _why_ they are not supported? What YAML parser does not support them?

**Comment by mjuric** [comment]
Just to chime in that supporting anchors would be very useful and allow for quick and elegant solutions to simple problems. [Here](https://github.com/mjuric/conda-pyslalib/blob/2a22a06467ffce944736e17fdabff9f89ec54545/azure-pipelines.yml) is an example of a simple definition that runs the same steps+matrix on Linux and MacOS. This is also possible with templates, but requires an additional file (plus learning about the template feature, which seems a bit of an overkill for many common cases where plain YAML would suffice).

**Comment by samuel-begin** [comment]
it would also be very useful for things other than tasks and jobs (which templates support)
```
dependencies: &dependencies
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - src/App1/
    - src/App2/
    - src/SharedCodebase1/
    - src/SharedCodebase2/

trigger:
  batch: true
  <<: *dependencies
  pr:
    <<: *dependencies
```

**Comment by Pr0methean** [comment]
@samuel-begin I worked around that by creating a job that depends on all of them, specifies `pool: server` so that it won't waste time spinning up an agent, and is depended on in place of the list.

**Comment by ahoereth** [comment]
Are there any plans for enabling anchors and references in azure pipeline yaml configuration files?

**Comment by cristobal** [comment]
Is this one the plan anywhere in the future?

Would be nice to use it in the pipeline template.
I know that one can use the `- template: filename.yaml` for stages, but would be nice to have this feature e.g. reuse of variables references across stages.

Also would be handy in cases where one needs to set the same values for the `include.paths` in the `pr` and `trigger` sections of the azure pipeline template especially in mono repos where one has multiple apps in the same repo with complex include paths across the repository to trigger on.

Hard to think that this is not supported when most YAML parsers these days support anchors, this has been in the spec for a while now https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases. Is there some special reason that this is not supported?

**Comment by asdkant** [comment]
+1 to having this. I know it overlaps with templates, but I believe there is value in having these extra YAML features (and it wouldn't have much maintenance overhead).

**Comment by renepupil** [comment]
@montebhoover Can you reopen this issue?

**Comment by CodingBricked** [comment]
Yaml anchors will never ever be supported because they've already decided you should use templates.

**Comment by vaspoz** [comment]
we
Want
ANCHORS!
