### ISSUE TITLE
Unable to download agents from vstsagentpackage.azureedge.net

### ISSUE THREAD

**Issue by gusarov** [Microsoft/vsts-agent#1585]
## Agent Version and Platform
Windows | vsts-agent-win-x64-2.134.2.zip

## VSTS Type and Version
VisualStudio.com

## What's not working?
IE11 and Chrome no longer able to download new agent zip due to RC4 in TLS:
![image](https://user-images.githubusercontent.com/1462777/40590327-8bdfc5e6-6205-11e8-9ec3-2f6464c94f43.png)

**Comment by gusarov** [comment]
Wow... just realized that it is blocked in Rissia
http://isitblockedinrussia.com/?host=vstsagentpackage.azureedge.net
Works via proxy

**Comment by TingluoHuang** [comment]
![image](https://user-images.githubusercontent.com/1750815/41601387-5078e2aa-73a6-11e8-9611-fa670f9699df.png)

I think the problem has been fixed, i am going to close this issue. :D
