### ISSUE TITLE
Insecure git version (before 2.17.1) regarding git vulnerability CVE 2018-11235 

### ISSUE THREAD

**Issue by Shahyads** [Microsoft/vsts-agent#1590]
Based on
https://blogs.msdn.microsoft.com/devops/2018/05/29/announcing-the-may-2018-git-security-vulnerability/
It is needed to replace externals\git folder with the latest version of git for the next release otherwise it doesn't work alongside VSTS or TFS2018 update 3

**Comment by bryanmacfarlane** [comment]
Yes, the next agent release will include that git.  You can use latest agent with previous on prem >= 2017 for windows (only one that carries git as a convenience). Note that you can always configure a definition to prefer git in the path and not the one the agent carries as well if you don't want to wait.
