### ISSUE TITLE
config.sh dies looking for apphost

### ISSUE THREAD

**Issue by denzuko** [Microsoft/vsts-agent#1591]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

Linux

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?

Azure VM

mrcooper.visualstudio.com

## What's not working?

Executing config.sh to start the installation after doing a git clone of this repository results in
```

....

dspencer1/myagent/bin/System.Private.CoreLib.dll:
Property NATIVE_DLL_SEARCH_DIRECTORIES = /home/dspencer1/myagent/bin:
Property PLATFORM_RESOURCE_ROOTS =
Property AppDomainCompatSwitch = UseLatestBehaviorWhenTFMNotSpecified
Property APP_CONTEXT_BASE_DIRECTORY = /home/dspencer1/myagent/bin/
Property APP_CONTEXT_DEPS_FILES = /home/dspencer1/myagent/bin/Agent.Listener.deps.json;
Property FX_DEPS_FILE =
Property PROBING_DIRECTORIES =
Property JIT_PATH = /home/dspencer1/myagent/bin/libclrjit.so
Failed to initialize CoreCLR, HRESULT: 0x80004005

Failed to initialize CoreCLR, HRESULT: 0x80004005
```
## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@denzuko make sure you have all dependencies that dotnet core requires, you can install then by run `installdependencies.sh` under "\src\Misc\layoutbin\installdependencies.sh". Btw, which commit are your on?

**Comment by denzuko** [comment]
I already ran that previously. I'm on commit e46b26f1fda0eae4cf8cda6442a813939d4b2639.

I'm even seeing this also in the tarball version: vsts-agent-linux-x64-2.125.0.tar.gz

**Comment by TingluoHuang** [comment]
@denzuko what's your linux flavor/version?

**Comment by denzuko** [comment]
```
 cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Red Hat Enterprise Linux Server release 7.5 (Maipo)

```

**Comment by TingluoHuang** [comment]
when you build then agent from source code, the agent will pull down a copy of dotnet sdk. the sdk should under `vsts-agent\_dotnetsdk\2.1.200\dotnet`, can you try run `mkdir testdir; cd testdir; ./vsts-agent\_dotnetsdk\2.1.200\dotnet new console; ./vsts-agent\_dotnetsdk\2.1.200\dotnet run`

**Comment by TingluoHuang** [comment]
i am wonder dotnet is having issue with your OS.

**Comment by denzuko** [comment]
@TingluoHuang don't thing that's the issue:

```
 ./dev.sh b
~/vsts-agent/src ~/vsts-agent/src
Prepend /home/dspencer1/vsts-agent/src/../_dotnetsdk/2.1.200 to %PATH%


-----------------------------------------
Dotnet SDK Version
-----------------------------------------
Failed to initialize CoreCLR, HRESULT: 0x80004005


-----------------------------------------
Pre-cache external resources for linux platform ...
-----------------------------------------
Download exists: TEE-CLC-14.134.0.zip
Download exists: vso-task-lib.tar.gz
Download exists: node-v6.10.3-linux-x64.tar.gz


-----------------------------------------
Building ...
-----------------------------------------
Failed to initialize CoreCLR, HRESULT: 0x80004005
Failed: build
~/vsts-agent/src
[dspencer1@CRVSDDCLNXUAT01 src]$ echo $PATH
/home/dspencer1/vsts-agent/_dotnetsdk/2.1.200/:.:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/dspencer1/.local/bin:/home/dspencer1/bin

````

Core of the problem seems to be related to what ever is causing the `Failed to initialize CoreCLR, HRESULT: 0x80004005` error.

**Comment by TingluoHuang** [comment]
yes, seems like dotnet sdk 2.1.200 is not working for your platform at all.
```
-----------------------------------------
Dotnet SDK Version
-----------------------------------------
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
we try to print out the SDK version by just run `dotnet version` and that failed as well.

Can you try reboot?

**Comment by denzuko** [comment]
Reboot a linux server? It can be tried but got to know first:

   - Is there any daemon or long running process that's running which we're trying to reload?
   - Is there a kernel module of some sort that's needing to be reloaded?

**Comment by TingluoHuang** [comment]
@denzuko 
- i don't think there is any daemon process, the dotnet sdk is just a console app
- possible, but i can't confirm, since the SDK is a separate project at https://github.com/dotnet/cli

You can also post the issue to them about why 2.1.200 SDK return `Failed to initialize CoreCLR, HRESULT: 0x80004005`

**Comment by denzuko** [comment]
I'll look tomorrow when I get back in the office but its sounding like a reboot would not be needed.

**Comment by denzuko** [comment]
@TingluoHuang Finished checking, there's nothing of the sort to require a reboot for Linux/Unix based systems.

**Comment by TingluoHuang** [comment]
@denzuko ok, i will wait for dotnet people provide further guide.

**Comment by denzuko** [comment]
Resolved, please update the documentation to set selinux to permissive, instead of enforcing.
