### ISSUE TITLE
Update tag/release description for 2.122.1 to include TFS 2017.3

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vsts-agent#1592]
This is just a meta issue about updating the description/title for https://github.com/Microsoft/vsts-agent/releases/tag/v2.122.1 since it is also the agent shipped with 2017.3.
Maybe "v2.122.1 (TFS 2018 RTW and TFS2017 QU3)"

**Comment by TingluoHuang** [comment]
@nschonni the agent is always back compat, you can use latest version agent from github and it should works with even TFS 2017 (Win) Tfs2015 (Linux/OSX).
the release tag is us to remember which version of agent is packaged with which On-Prem TFS release. :)

**Comment by nschonni** [comment]
Yup, I was asking the description to be updated because it is the version that shipped with on-prem 2017.3/3.1 (as well as TFS 2018 RTW) :wink:

**Comment by bryanmacfarlane** [comment]
No agent ships with on-prem - there's just a default one it pointed to for the download button.  

I'm fine with adding a table on the front page of TFS release to sprint / release branch.

**Comment by nschonni** [comment]
Sorry, I forgot to link to https://github.com/MicrosoftDocs/vsts-docs/issues/924 where someone flagged that the version table was out of date. I've put in a PR to fix that part already.

> No agent ships with on-prem - there's just a default one it pointed to for the download button.

Right, I'm just using the wrong terms today 😝

**Comment by TingluoHuang** [comment]
I update the release to include TFS 2017 Qu3 info.
https://github.com/Microsoft/vsts-agent/releases/tag/v2.122.1
