### ISSUE TITLE
PublishSymbols@2 Warning: symbolServerType input is required

### ISSUE THREAD

**Issue by vicioussn** [Microsoft/vsts-agent#1593]
Hi!

There is an issue in YAML builds.

- task: PublishSymbols@2
  displayName: Publish symbols path
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    publishSymbols: false
  continueOnError: true

This task will generate warning with the following message: "symbolServerType input is required". However at https://docs.microsoft.com/en-us/vsts/pipelines/tasks/build/index-sources-publish-symbols?view=vsts defined that this input is not required when publishSymbols == false (that's my case).

This task definition will work instead:

- task: PublishSymbols@2
  displayName: Publish symbols path
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    **publishSymbols: false
    symbolServerType: teamServices**
  continueOnError: true

**Comment by bryanmacfarlane** [comment]
The condition is only on visibility.  

The input is required: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishSymbolsV2/task.json#L63

**Comment by bryanmacfarlane** [comment]
I would log an issue in the tasks repo.  That can cause an issue even in UI designer builds where it's not visible, has no value but is required.

**Comment by bryanmacfarlane** [comment]
let them know the docs are wrong
