### ISSUE TITLE
Switching the agent from http to https conenctionstring

### ISSUE THREAD

**Issue by MagnusTim** [Microsoft/vsts-agent#1599]
## Agent Version and Platform
Version of your agent? 2.120.2

OS of the machine running the agent:  Windows 2016

If On-Prem TFS: TFS 2018.2

## What's not working?
We are switching from http to https on our TFS, is there a way to change the agent connection string without reinstalling the agent?

**Comment by TingluoHuang** [comment]
@MagnusTim i am not 100% sure, there are 2 hidden files under your agent root directory.
![image](https://user-images.githubusercontent.com/1750815/40877061-3cbb1810-6649-11e8-9e05-b245308f2114.png)
change Url in both file, see whether that works.

**Comment by MagnusTim** [comment]
Hi,
When I change the first file the agent works fine, when changing both the agent does not turn green because of this I am unsure what to do.

Could it be enough to just change the .agent file?

/Magnus

**Comment by TingluoHuang** [comment]
@MagnusTim ok, then i think change .agent file should be enough.

**Comment by MagnusTim** [comment]
It works, thanks!
