### ISSUE TITLE
Upgrading agent behind firewall

### ISSUE THREAD

**Issue by MagnusTim** [Microsoft/vsts-agent#1600]
## Agent Version and Platform
Version of your agent? 2.120.2

OS of the machine running the agent:  Windows 2016

If On-Prem TFS: TFS 2018.2

## What's not working?
Our TFS and build servers are behind a firewall with no connection to the internet. I have downloaded the latest agent version from GitHub. Is there a way to upgrade the agent without reinstalling in (the same way TFS does when it has access to the internet maybe)

**Comment by TingluoHuang** [comment]
#1451 
Close as Duplicate
