### ISSUE TITLE
"Cannot find CodeCoverage.exe" on self-hosted agent

### ISSUE THREAD

**Issue by SeriousM** [Microsoft/vsts-agent#1605]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
yes

## Agent Version and Platform
Version of your agent? 2.134.2

OS of the machine running the agent? Windows 10, 1803

The agent-machine has VS2017 Professional installed.

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://scan2lead.visualstudio.com

## What's not working?

I use "Visual Studio Test Platform Installer (Preview)" and "Visual Studio Test (v2)" to run my tests. I enabled Code Coverage for them.
The codecoverage.exe files are located at 
```
C:\vstsAgent\_work\_tool\VsTest\15.8.0-preview-20180510-03\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe
C:\vstsAgent\_work\_tool\VsTest\15.8.0-preview-20180510-03\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\amd64\CodeCoverage.exe
```
but the logs tell me
```
...
2018-06-05T07:45:52.4833619Z Data collection : Logging DataCollector Diagnostics in file: C:\vstsAgent\_work\_temp\6de4f490-6894-11e8-a094-f7e855a114e8.datacollector.18-06-05_09-45-49_54108_5.txt
2018-06-05T07:45:52.4834750Z Data collector 'Code Coverage' message: Cannot find CodeCoverage.exe..
...
```

If I run the same tasks on a VSTS Hosted Agent the coverage works.

## Agent and Worker's Diagnostic Logs
[Agent_20180530-071436-utc.log](https://github.com/Microsoft/vsts-agent/files/2071345/Agent_20180530-071436-utc.log)
[Worker_20180605-074323-utc.log](https://github.com/Microsoft/vsts-agent/files/2071346/Worker_20180605-074323-utc.log)

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@SeriousM please log an issue at the Tasks repository https://github.com/microsoft/vsts-tasks
this seems like to be a task issue instead of an agent issue.

**Comment by SeriousM** [comment]
thanks!
