### ISSUE TITLE
Python not recognised on Windows Server 2016

### ISSUE THREAD

**Issue by fmanea** [Microsoft/vsts-agent#1606]
## Agent Version and Platform
2.112.0 

##OS of the machine running the agent?
Windows Server 2016

## What's not working?
"python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Process completed with exit code 0 and had 1 error(s) written to the error stream."

Altough python 3.6.2 was installed in the default path: C:\Users\MyUser\AppData\Local\Programs\Python\Python36-32
And Environment variables weres set to point to that location 

How can i solve my issue?
I can point that from the local Powershell in recognisez python without any problems,
What else should I do to fix my issue?

**Comment by fmanea** [comment]
Something weird is happening:
If I do ($env:Path).Replace(';',"`n"), from a local powershell that is placed where the agent is installed, I can see that Python is added to the Environment variable PATH
But if I do the same from a in-line powershell task within VSTS, Python is missing

**Comment by TingluoHuang** [comment]
@fmanea did you restart the agent after you install python?

**Comment by fmanea** [comment]
Didn't, that was the problem, sorry
