### ISSUE TITLE
Demand LFS missing

### ISSUE THREAD

**Issue by milbrandt** [Microsoft/vsts-agent#1607]
## Agent Version and Platform
Version of your agent? 2.123.0

OS of the machine running the agent? Windows

## VSTS Type and Version
TFS 2017 Update 3 15.117.27414.0

## What's not working?
Git checkout lfs failed as no git-lfs installed on the build Agent
(Build Definition was a draft)

## Agent and Worker's Diagnostic Logs
2018-06-05T08:41:32.9941727Z ##[section]Starting: Get Sources
2018-06-05T08:41:33.0254225Z Syncing repository: XXX (TfsGit)
2018-06-05T08:41:33.0254225Z Prepending Path environment variable with directory containing 'git.exe'.
2018-06-05T08:41:33.0410474Z ##[command]git version
2018-06-05T08:41:33.1191719Z git version 2.12.2.windows.3
2018-06-05T08:41:33.1347968Z ##[error]Value cannot be null.
Parameter name: _gitLfsPath
2018-06-05T08:41:33.1347968Z ##[section]Finishing: Get Sources

![lfs](https://user-images.githubusercontent.com/26173245/40972798-6abd47b4-68b1-11e8-8b1e-a5368df52a9c.png)

## Expected behaviour
Only build agents where git lfs is installed will get the job. Automatically adding a corresponding depand to the build Definition.

**Comment by bryanmacfarlane** [comment]
If you're using LFS, why wouldn't you just install LFS on all the agents in the pool?  We could add a demand but that would break existing customers that have running agents without the capability.

If you can't do that for some reason, then there's custom capabilities on the agent web UI and custom demands on the definitions that target those.

Also the latest version of git bundles lfs with it.

**Comment by milbrandt** [comment]
Unfortunately in our enterprise the build servers are located at several subsidaries. Not everywhere I am authorizied to log in and install git-lfs. Why don't you bundle git-lfs with the build agents as you already do with git? Even in the latest 2.134.2 in git-lfs is not included `externals\git\`  in the agent bundle.

For builds we can work around and set manually a demand `GIT_LFS_PATH`` but unfortunately for definition of build drafts the demand frame is not available in the TFS on-premise 15.117.27414.0.

**Comment by TingluoHuang** [comment]
@milbrandt we don't have legal approval to ship git-lfs with the agent.

**Comment by TingluoHuang** [comment]
I am going to close this issue since we can't add LFS demand at this point, it will break all existing customer who is using LFS in their build since the capability scan is done during agent process startup.
If we want to add the LFS demand, we need update all agents to latest version (with git-lfs capability scan script) to prevent not breaking existing customer.

**Comment by milbrandt** [comment]
Would be fine for me if you could consider this demand in a nearby agent release and later on (eg with an TFS on-premise release) also in the Get Sources task. Thx.
