### ISSUE TITLE
Question: Can a release agent be used offline?

### ISSUE THREAD

**Issue by marco-gallinari** [Microsoft/vsts-agent#1620]
We have a release pipeline up and running for our enterprise products, deploying them on Azure VMs and on-premise machines.

One of our new on-premise customers is not willing to open firewall for http/s traffic, so we're not able to add a fully functional on-premise agent to their network.

This would mean a huge step back in product delivery for us, and we are trying to find a solution to avoid handcrafted deployments.

Would it be possible for us to keep using the pipeline automation, even in this "detached" environment?
Something like: 
- copy tasks and release definition from a "live" agent
- copy build artifacts
- run the release definition locally on the "offline" agent machine, skipping artifacts download step

**Comment by bryanmacfarlane** [comment]
No, if they don't allow internet access, they can't use an internet exposed cloud service.  However we do offer an on premise TFS product that is the full build / release code base.  TFS is the disconnected internet solution.

**Comment by bryanmacfarlane** [comment]
Just a little backgroud - the workflow actually runs on the server / service and dishes out work to agents.

**Comment by marco-gallinari** [comment]
Thank you for your explanation!

Unfortunately, on-prem TFS installation has already been discussed and is out of scope for our customers, as we are developing our product on our own and selling it to various enterprise companies that do not have or want an on-prem installation.

I guess powershell scripting is our best option then.

Thanks
