### ISSUE TITLE
VSTS Build Agents does not pick a enqueued Build

### ISSUE THREAD

**Issue by victorperez2911** [Microsoft/vsts-agent#1629]
Environment
Server - VSTS
Account Name - portalprocfit.visualstudio.com
Agent - Private:
Agent Version - 2.131.0/2.134.2
Running On Windows 10 Pro - 1709

## Issue Description

As of today, none of our agents pay build queued.

How do I diagnose this problem?

Things I've tried/checked

1) demands-although we do not make any changes regarding the demands of the build's definitions, much less in the demands of the agents, we validate them, and everything is correct.

2) I created new builds.

3) I added a new Agent with the version 2.134.2

4) I created builds of other definitions.

![image](https://user-images.githubusercontent.com/11770654/41607249-f7cb9bbe-73bb-11e8-8c70-bd5d02d2858e.png)

**Comment by TingluoHuang** [comment]
@victorperez2911 thanks for reporting this. i have asked our service team to take a look.
are those builds failed eventually (20 mins)? or it hanging there forever?

**Comment by victorperez2911** [comment]
Yes @michVSTS and @TingluoHuang 

Apparently everything works now.

Tks

**Comment by TingluoHuang** [comment]
cool. i am going to close the issue.
