### ISSUE TITLE
Build agent incorrectly selects Build Tools folder for vstest tasks when Build Tools is on the same or greater version than VS Pro

### ISSUE THREAD

**Issue by tompatib** [Microsoft/vsts-agent#1634]
Hi,

I'm using TFS 2017 U3 with Build Agent 2.112.1. I have installed VS Professional 15.7.4 on build servers, also I have Build Tools installed (I had to go for VS Pro due to the VsTest for 2017 was not supported in Build Tools). Lately I have updated the Build Tools to the same 15.7.4 version and since my VsTest tasks started to fail with the message: 

> VisualStudio version selected for test execution : 15.0
[command]powershell -NonInteractive -ExecutionPolicy Unrestricted -file 
> D:\TfsBuildAgent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.55\vs15Helper.ps1
> Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"
>    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools</S>
> Objs
> [command]wmic datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
> No Instance(s) Available.

![1](https://user-images.githubusercontent.com/16067575/41661538-48a21412-749f-11e8-9f10-f9d45e7d53c1.png)

After some troubleshooting it turned out that the vswhere.exe gives back the correct location of VS, selecting the Professional one but the vs15Helper.ps1 takes the first one when found more for the same version and due to the path the Build Tools is preferred but that doesn't have the vstest.console.exe.

![2](https://user-images.githubusercontent.com/16067575/41661540-48c6ac0a-749f-11e8-9766-5fac11816a83.png)

![3](https://user-images.githubusercontent.com/16067575/41661970-45ba3db4-74a0-11e8-9176-19b2c441c17b.png)

I think this should somehow considered, for now I have excluded that from the PS file as it won't support it:

```

return $instances |

            Where-Object { $_.Version.Major -eq 15 -and $_.Path -notlike "*BuildTools"} |

            Sort-Object -Descending -Property Version |

            Select-Object -First 1 
``` 
![4](https://user-images.githubusercontent.com/16067575/41662080-94dc22ea-74a0-11e8-9f81-82de1415d727.png)

Thanks,
Tibor Tompa

**Comment by TingluoHuang** [comment]
@tompatib thanks for reporting this, i think this is task not a agent problem, can you log an issue at https://github.com/microsoft/vsts-tasks?

**Comment by tompatib** [comment]
Sure, thanks.
