### ISSUE TITLE
Xcode build task fails for Subproject

### ISSUE THREAD

**Issue by kannanprasad87** [Microsoft/vsts-agent#1641]
Hi Team,

I am working on VSTS builds and Hosted macOS Preview for implementing CI/CD pipeline for iOS native project.
This iOS Project is having custom frameworks added as subproject, which doesn’t require any provisioning profiles while signing, and it is mentioned in the project setting also. But while running Xcode Build task with manual provisioning profile settings, these sub projects also getting applied with provisioning profile and the build job getting failed. With the same configuration app is able to build in local machine. 

How can I solve this issue ? Is this an issue with new Xcode task ?

Thanks

**Comment by TingluoHuang** [comment]
@kannanprasad87 please log issue to task repo for help.
https://github.com/microsoft/vsts-tasks
