### ISSUE TITLE
Agent.JobName for Builds changed from "Build" to "Release"

### ISSUE THREAD

**Issue by DerGary** [Microsoft/vsts-agent#1648]
## Agent Version and Platform
Version of your agent? 2.134.2

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://dev-fg.visualstudio.com

## What's not working?
Agent.JobName for Builds is now somehow "Release" instead of "Build", we didn't change anything. The Problem first appeard today with agent version 2.133.1 and did not change after updating to 2.134.2.

## Agent and Worker's Diagnostic Logs
the UI seems to know that it is a Build:
![image](https://user-images.githubusercontent.com/4302467/41961527-fe71ab6a-79f2-11e8-9c82-9f3363a0b5ec.png)

but the logs say that it is a Release Job, which it isn't
[logs_5757.zip](https://github.com/Microsoft/vsts-agent/files/2140329/logs_5757.zip)

Greetings Gary

**Comment by TingluoHuang** [comment]
@DerGary 
why you are using ##vso[release.updatereleasename] in a build?
```
2018-06-27T08:09:36.5808182Z ##[error]release commands are not supported for Build flow. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

2018-06-27T08:09:36.5824226Z ##vso[release.updatereleasename]Release-3.1.0.0
```

**Comment by DerGary** [comment]
I have the following code in my build task, and until now it worked as expected. And we didn't change the build definition it always used the multi config with release as Build Configuration.

```
var jobname = tl.getVariable("Agent.JobName");
        if (jobname != null && jobname.toLowerCase() == "release") {
            console.log("##vso[release.updatereleasename]Release-" + buildNumber);
        } else {
            console.log("##vso[build.updatebuildnumber]" + buildNumber);
        }
```

**Comment by TingluoHuang** [comment]
@DerGary you should use `SYSTEM.HOSTTYPE` = Release/Build to branch your logic, Agent.JobName can be anything you set on the UI.

**Comment by DerGary** [comment]
Ok I will use this variable now but agent.jobname worked until now.

**Comment by TingluoHuang** [comment]
@DerGary are you doing multi-configuration build before?

**Comment by DerGary** [comment]
yes i didn't change anything
