### ISSUE TITLE
Branch Policy Exemption for Build Agent not working

### ISSUE THREAD

**Issue by Ryanman** [Microsoft/vsts-agent#1651]
## Have you tried trouble shooting?
Yes, a huge amount

## Agent Version and Platform
1.105.6 , OS = Windows

## VSTS Type and Version
TFS 2017 R2

## What's not working?
As part of a TFS 2017 R2 CI build definition, I'm trying to merge commits from one branch to another. If you can imagine a bugfix in a test environment being added, then as part of the build def I run some git commands to merge that change down to a dev environment/branch and push them.

The branches have policies enabled that require pull requests for commits. In order for this flow to work, I will need to exempt the build agent from branch policies so that it can push these commits outside the context of a Pull Request.

My build def is a single powershell script that runs "whoami" and then a git merge and then a git push. The Whoami returns a user:

    domain\adminAccount

The admin account has the following permission properties:

* Collection Level: Member of a Service Account Group
* Team Project Level: The service account group is a member of the Build Administrators group
* Repository Level: The Build Administrators group has the "Exempt from Policy Enforcement" permission set to allow.
* Individual Level: If I add this user and trace their Exempt from policy enforcement permissions, they show "inherited allow". See image below.

![image](https://user-images.githubusercontent.com/1376624/41987745-1cd4f11a-7a08-11e8-9d15-7832f123d80a.png)

However, when I try to push commits to a branch, I get the TFS error:

    TF402455: Pushes to this branch are not permitted; you must use a pull request to update this branch.

If these account permissions are correct, and when I execute these scripts they show this account as being used, what am I missing? Is there some black box logic about what account is actually executing this that I need to exempt from policy enforcement?

The only thing I can think of is in Capabilities for the agent I see the Key Value Pair of:

    USERNAME    SYSTEM

Is this the name of the user *actually* running these build tasks or something? If so, how do I change it?

**Comment by TingluoHuang** [comment]
@Ryanman why you are using `1.105.6` agent? it would be super easy to archive your goal with 2.x agent, which is agent we released with TFS 2017 RTM.

**Comment by Ryanman** [comment]
@TingluoHuang , this is the version number specified in the Capabilities view on the Agent pool. However these agents would not be able to be connected to TFS2017 correct? I may have misrepresented the version number. Where is the correct one?

Are there any significant changes in which accounts an agent uses or how it handles AD/TFS Permissions between the versions?

**Comment by TingluoHuang** [comment]
https://docs.microsoft.com/en-us/vsts/pipelines/scripts/git-commands?view=vsts

**Comment by TingluoHuang** [comment]
Auth flow for 2017 or above with 2.x agent.
https://github.com/Microsoft/vsts-agent/blob/master/docs/design/auth.md

**Comment by Ryanman** [comment]
Those links are helpful, and what I used as a basis for trying to get this to work.

Some notes about the solution to the problem:

- The user that powershell scripts/build agents are executing as is a fairly useless piece of information. Instead, you want to use the command "git config user.name" to see what _git credentials_ are being used.
- The reason is that regardless of what user is executing the build scripts, the build process will either use the user's git credentials (viewable in credential manager in the Ctrl Panel) *or* just the "nearest" git credentials. In our case, a user who was _also_  an admin on the Build Agent VM.
- My gut feeling is that branch policies are enforced in TFS by intercepting a git command, looking at the git credentials, and then trying to correlate that to an AD account, then checking for policy exemptions.
- Finally, Double check group membership for whatever account is executing the build processes on the agent, as this is ultimately what decides their ability to be exempted from branch policies. Even if you add that user in TFS and exempt them, if a group they belong to is even just "Not Set" for policy exclusion it could be blocking them!
