### ISSUE TITLE
Yaml build fails if missing variable with wrong error message

### ISSUE THREAD

**Issue by vovikdrg** [Microsoft/vsts-agent#1655]
## VSTS Type and Version
VisualStudio.com 

## What's not working?
Create new build and point to build.yml
`steps:
- task: PublishBuildArtifacts@1
  displayName: Publish ArmTemplate
  inputs:
    PathtoPublish: '$(UndefinedVariable)\net461'
    ArtifactName: Arm
`

If UndefinedVariable is not added to build variables it will fail with exception

**Could not find a queue with id ID. The queue does not exist or has not been authorized for use.**

I would expect to see an proper error message.

**Comment by TingluoHuang** [comment]
@vovikdrg you must have some syntax error before and you fixed it in your yaml file. However the definition is not reflect the latest change, so you get that weird error.
try make a meaningless edit to your definition and save it (like change `system.debug` to true).
this should unblock you, we are working on a fix for this issue.

**Comment by vovikdrg** [comment]
@TingluoHuang Sorry if forgot to mention that i've fixed that simply by adding variables. But I spend some time because of wrong error message which was saying nonsense.

**Comment by ericsciple** [comment]
thanks for confirmation. we're working on a fix
