### ISSUE TITLE
Badge for Github repo, with YAML

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-agent#1656]
I cannot find the badge link for github, with YAML.
However, it seems your repo support that badge.
How do i enable it for my own repo ?

**Comment by ericsciple** [comment]
@moswald

**Comment by moswald** [comment]
We are adding the UX to expose the badge links in the next sprint, but for now you can generate it yourself:

`https://<your account>.visualstudio.com/<your project>/_apis/build/status/<path/to/definition>&branchName=optionalBranchName`

The path to your definition is optional, it's only necessary if you have definitions with the same name in different folders. You can also use the definition's ID instead, if you happen to know it.

**Comment by guolinke** [comment]
Thanks, I can generate the badge now.
However, that is only a icon, can I get the link to the build log for that icon ?

**Comment by moswald** [comment]
Yes:
https://<your account>.visualstudio.com/<your project>/_build/latest?definitionId=<id>

Unfortunately, you have to use the definition's ID for this, but this is an oversight we'll address in a future release.

**Comment by isuruf** [comment]
@moswald, is there a way to get the link without the definition ID now?

**Comment by moswald** [comment]
Not yet. I'll see if I can carve out a little time next week and sneak it into the release, though. Thanks for the reminder.

**Comment by moswald** [comment]
Ok, I just merged a PR into the Azure DevOps service that will allow you to use a url formatted the same way as the status endpoint. It will be available sometime next week or the week after, depending on our deployment schedule and where your account is hosted.

```
dev.azure.com/<your account>/_build/latest?definitionId=<definition id>
dev.azure.com/<your account>/_build/latest/<definition id>
dev.azure.com/<your account>/_build/latest/path/to/your/definition name
dev.azure.com/<your account>/_build/latest/unique definition name
```

As before, `&branchName=branch name` is an optional query parameter.
