### ISSUE TITLE
freeze when calling conda install in Linux agent

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-agent#1658]
when I run ```conda install numpy nose scipy scikit-learn pandas matplotlib pytest``` in Linux agent (already set conda environment), the build stuck, and then being killed due to time-out (1 hour).

Switching to `pip` has not such a problem.

**Comment by TingluoHuang** [comment]
similar to the other issue, try find the argument to do unattended installation.
https://stackoverflow.com/questions/34644612/conda-silently-installing-a-package

looks like also add `-y`

**Comment by guolinke** [comment]
Thanks, it is working now !
