### ISSUE TITLE
freeze when calling ``sudo apt-get install libboost-all-dev``

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-agent#1659]
the same as #1658 .
![image](https://user-images.githubusercontent.com/16040950/42079696-ef02bdd8-7bb2-11e8-985f-1e833eb93053.png)

**Comment by TingluoHuang** [comment]
@guolinke add  `-y` to your `apt install`, you are getting prompt for `Do you want to continue? [Y/n]`

**Comment by guolinke** [comment]
Thanks very much ! I didn't notice that since `Do you want to continue? [Y/n]` is shown after cancelling.
