### ISSUE TITLE
Any reliable supported/long-term way to take advantage of AGENT_ALLOWALLSECUREFILES?

### ISSUE THREAD

**Issue by DuncanMillard** [Microsoft/vsts-agent#1660]
## Agent Version and Platform
Version of your agent? 2.134.2
OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com
If VisualStudio.com, what is your account name? http://easplatform.visualstudio.com

## What's not working?
I'm trying to create a custom deployment task that will let me download an arbitrary secure file at run time, rather than having to select it from the UI at design time. Scenario is a task group that we use to onboard a new customer, which includes the deployment of an environment- and customer-specific certificate from VSTS Secure Files.

In my custom task I am only able to download the secure file if I first select it using a ui control type of secureFile. Unfortunately this is the scenario I'm trying to avoid :-) See more details of the code I'm using and the success/failure scenarios in [this VSTS Task SDK comment](https://github.com/Microsoft/vsts-task-lib/issues/280#issuecomment-401075198))

Looking through the source for the agent, I see reference to AGENT_ALLOWALLSECUREFILES environment var and agent.AllowAllSecureFiles (configuration setting?) which look like they would expose all the secure files to the agent and hence to my task. However there's a note in the code saying it'll be removed ~sprint 121.

So two questions:

1) In the short term, where do I need to configure AGENT_ALLOWALLSECUREFILES so that it exposes the secure files tokens to the agent and hence to my task? I tried a process-level variable set to 'True', which didn't seem to have any impact.

2) Is there a longer term, supported way to do this that won't disappear some time around sprint 121?

I have a less elegant workaround in mind, which will be to add a 'download secure file' task to my task group for each one of my secure files, and to put a conditional execution statement on each one to check the scenario we're running, but this means modifying the task group every time we onboard a new customer, which I'd rather avoid, and it obviously doesn't scale too well.

## Agent and Worker's Diagnostic Logs
not available for releases according to [the troubleshooting guide](https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts#get-logs-to-diagnose-problems)

**Comment by TingluoHuang** [comment]
@DuncanMillard we won't support AGENT_ALLOWALLSECUREFILES in the future, for security reason we don't allow any task to access secret information it doesn't reference to.

**Comment by DuncanMillard** [comment]
Completely understandable, @TingluoHuang . It would be great if there was a way to request a specific secure file being available in the agent... not having to select from a UI at run time, but being able to specify something like SSL_$(CustomerName)_Certificate.pfx - but I guess that's not part of the Agent codebase so not an issue for this repo.

Thanks for the reply.
