### ISSUE TITLE
Using YAML build definition, have the ability to set build number format

### ISSUE THREAD

**Issue by tomaszgawlik** [Microsoft/vsts-agent#1666]
## Agent Version and Platform
Hosted VS2017 Windows. But I suspect that this request is for every agent type.

## VSTS Type and Version
VisualStudio.com

##Issue 
While creating the build definition manually, I have an option to set build number format using Option tab: 
![image](https://user-images.githubusercontent.com/12712794/42324529-59a6c22c-805b-11e8-82c7-6c4fa9269060.png)

Currently, in YAML build definition, I'm not able to set that. Also after the build definition is created, I'm unable to manually set that option (Options tab is gone if I'm using YAML ).
My question is: is it possible to achieve this right now?

**Comment by tomaszgawlik** [comment]
@simonvane yes that did the trick. thank you for your quick response!

**Comment by cpoDesign** [comment]
@simonvane the link no longer works:(

**Comment by ericsciple** [comment]
the docs moved. This doc contains links to the new and old docs: https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/yamlgettingstarted.md

Here was the old doc: https://github.com/Microsoft/azure-pipelines-agent/blob/3d39fca3cac2bf54c16600e0a3b9e7972d4c5ef3/docs/preview/yamlgettingstarted-name.md

**Comment by Fisher-Joe** [comment]
https://github.com/Microsoft/azure-pipelines-agent/blob/3d39fca3cac2bf54c16600e0a3b9e7972d4c5ef3/docs/preview/yamlgettingstarted-name.md

**Comment by cristianbanarescu** [comment]
@simonvane Thanks man! It really helped me!

**Comment by MisinformedDNA** [comment]
This no longer seems to work:

```
name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)
```

![image](https://user-images.githubusercontent.com/1784452/66774616-950a8100-ee87-11e9-94e0-84041e5e416a.png)
