### ISSUE TITLE
Auto Release to "GitHub Release"

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-agent#1669]
Both Travis and Appveory support to release back to github: https://docs.travis-ci.com/user/deployment/releases/

However, I cannot find this feature in vsts-ci, from the document.
Is this feature available ?

**Comment by TingluoHuang** [comment]
here are few github extensions i found in market place, i guess some of them can handle create github release.
https://marketplace.visualstudio.com/search?term=github&target=VSTS&category=All%20categories&sortBy=Relevance

**Comment by guolinke** [comment]
Thanks so much! one more question: can yaml use these packages?

**Comment by TingluoHuang** [comment]
you can, as long as the task has installed to your VSTS account.

**Comment by TingluoHuang** [comment]
are we good on close this issue?

**Comment by guolinke** [comment]
yeah, sure.
