### ISSUE TITLE
YAML resources documentation is unclear

### ISSUE THREAD

**Issue by simonvane** [Microsoft/vsts-agent#1672]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com 

## What's not working?
When build definition is exported using "View YAML" the following is included:

```
resources:
- repo: self
  clean: true
```

This does not match what is described in https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-resources.md

Additional, it is unclear whether the "Get sources" part of the build is effected by this. The values in the UI don't change when clear is set to false for example.  All in all, this part of the YAML build definition is difficult to understand.

**Comment by ericsciple** [comment]
I agree. We are currently working through changes around checkout and repositories.

In short, use the [checkout options](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-checkout.md) to control whether to `clean`
