### ISSUE TITLE
Exported YAML does not work with process parameters.

### ISSUE THREAD

**Issue by simonvane** [Microsoft/vsts-agent#1678]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com 

https://1id.visualstudio.com

## What's not working?
When build definition is exported using "View YAML" and the build uses Process Parameters comments like the following are included. It is unclear what the best course of action is:

```
#Your build pipeline references an undefined variable named ‘Parameters.ArtifactName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
```

**Comment by TingluoHuang** [comment]
@mireillehanna

**Comment by ericsciple** [comment]
you will need to define the value in a different way. process parameters don't work with yaml. we have a different plan for the yaml-equivalent for process parameters

**Comment by simonvane** [comment]
Hi @ericsciple,

Thanks for the update but I don't think this should be closed.

My basic expectation is that exported YAML should be usable to create a working build. I should never get invalid or incomplete YAML. 

It's fine that  process parameters are not supported  in YAML. An alternative to exporting broken YAML might be to create variables for each of the process parameters. They could have a comment next to them explaining that they are replacing process parameters and the user needs to decide if that's OK. At least then I could create a working build from the exported YAML.

Cheers.

**Comment by ericsciple** [comment]
@vijayma @mireillehanna regarding process parameter feedback

**Comment by ericsciple** [comment]
I've sent an email to Vijay and Mireille also. Export to yaml is performed by the server side, so closing the issue here. I believe the current behavior is how it was intentionally designed. I'll defer to Vijay/Mireille to consider the feedback.

**Comment by vijayma** [comment]
Thanks for the feedback. We will look into this.

**Comment by dfoulk** [comment]
@ericsciple @vijayma The generated YAML referenced here still does not produce a usable pipeline. Parameters seem to be available in YAML now (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops). Can you point me to the "server side" issues board so I can re-open this?

People like me are trying to use the generated YAML as a starting point while we learn how to create YAML Pipelines. The current YAML that's generated by the classic editor is not very useful.
