### ISSUE TITLE
Add temp directory and variable

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#168]
Agent.TempDirectory set to _work\_temp. Best effort delete at the beginning/end of each build.

**Comment by TingluoHuang** [comment]
#824 Overwrite %temp% on Windows, %tempdir% on linux/osx

**Comment by riezebosch** [comment]
But that's shell or os specific and prevents me from creating an agent agnostic build 😢

**Comment by marscher** [comment]
this variable is unset on Linux and OSX containers...

**Comment by rfennell** [comment]
If you use the code snippit 

```
var env = process.env;
Object.keys(env).forEach(function(key) {
      agentApi.logDebug(`export ${key}=${env[key]}`);
});
```

you can dump all the available environment variables. It does show the TempDirectory is not set, as expected. However, you can build it with

```
// cannot use process.env.Agent_TempDirectory as only set on Windows agent, so build it up from the agent base
// Note that the name is case sensitive on Mac and Linux
var tmpFolder = `${process.env.AGENT_WORKFOLDER}/_temp`;
```
