### ISSUE TITLE
Execute bit lost on tf

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#169]
I verified this isn't a problem related to how it's unzipped now, versus how it used to be unzipped. I think the problem is somewhere in the process of how we're now putting the file on blob storage. The expedient solution might be to switch back to pulling this from the previous location.

Linking to the issue where this was originally discovered: https://github.com/Microsoft/vso-agent/issues/303

**Comment by bryanmacfarlane** [comment]
tar preserves permissions.  I don't believe zip does.  

Two options:
- switch to a tar.  would need on win build
- make the build process do chmod u+x on it.  The build ultimately produces a tar so it would then be preserved.

**Comment by ericsciple** [comment]
fyi - The [old version of the script](https://github.com/Microsoft/vsts-agent/blob/c7d9a6844e1183401166889fd01ccf71a78a9ce6/src/Misc/externals.sh#LC91) did not chmod. It just unzipped.

**Comment by bryanmacfarlane** [comment]
Perhaps the zip given to us from java team is the issue.  They did provide us with an updated one.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, May 18, 2016 at 7:53 PM -0700, "ericsciple" <notifications@github.com<mailto:notifications@github.com>> wrote:


fyi - The old version of the script<https://github.com/Microsoft/vsts-agent/blob/c7d9a6844e1183401166889fd01ccf71a78a9ce6/src/Misc/externals.sh#LC91> did not chmod. It just unzipped.

-
