### ISSUE TITLE
VSTS, agent as docker image and ACR

### ISSUE THREAD

**Issue by cmacduff-sb** [Microsoft/vsts-agent#1695]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Hosted Linux Preview

## VSTS Type and Version
VisualStudio.com 

martech-development

## What's not working?
I'm not sure how to use  _PREVIEW_VSTS_DOCKER_IMAGE (https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/runtaskindocker.md) with an image from ACR. It's working perfectly fine for public docker images, however ACR requires authentication to pull the image (or I haven't figured out how to let images in ACR be public yet). I tried using the "Add a docker registry endpoint" in the project settings to add authentication to the request, but that more seemed for uploading an image not for using an image as the agent.

## Agent and Worker's Diagnostic Logs
Is this needed? the agent can't pull the image at all.

## Related Repositories

I seem to be in the right place? The below don't seem to apply.

Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@cmacduff-sb the official support for running phase inside container is coming, you can check our YAML doc, it will support image from private registry.

**Comment by cmacduff-sb** [comment]
@TingluoHuang Awesome, just wanted to make sure this use case was taken into account. Do you have an idea on the timeline for this functionality? I'm engineering around this at the moment, but it'd be nice to know how long I need to be doing it this way.

Will it also incorporate using a service endpoint for a private docker registry? Though that might get into a different feature request as it might be nice if there was a service endpoint specifically for ACR.

**Comment by TingluoHuang** [comment]
@cmacduff-sb base on which region your VSTS account is located, the time frame might be different, we rolls out new feature ring by ring to prevent unwanted break.
For the service endpoint, i would assume you will use the docker registry endpoint to point to your ACR.
![image](https://user-images.githubusercontent.com/1750815/42772269-efb4891c-88f7-11e8-9327-fa892518691f.png)

**Comment by bryanmacfarlane** [comment]
@cmacduff-sb - reactivate of log another issue if this didn't address questions.
