### ISSUE TITLE
GitHub Pull Request status cannot be updated when manually rebuild

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-agent#1699]
Refer to https://github.com/Microsoft/LightGBM/pull/1497 
The homebrew was down for a while and caused osx build failed. 
After that, I rebuild the PR manually successfully, but the status is still shown failed in GitHub.
![image](https://user-images.githubusercontent.com/16040950/42606244-06946824-85af-11e8-9505-0868952eab55.png)

**Comment by bryanmacfarlane** [comment]
Hi @guolinke - this repo is for tracking issues with the agent app.  You should probably go to developer community for service issues or feedback.  I'll forward this as FYI to the team however.

**Comment by guolinke** [comment]
Thanks @bryanmacfarlane so much.
Which team/repo can I report for these issues ? 
I met another problem:

The VSTS doesn't check the PR from forks, like this one https://github.com/Microsoft/LightGBM/pull/1501 and this one:  https://github.com/Microsoft/LightGBM/pull/1511

Since most github contributions are from forks, I think it is a big problem.
