### ISSUE TITLE
Requested registry access is not allowed

### ISSUE THREAD

**Issue by mblaschke** [Microsoft/vsts-agent#1707]
## Have you tried trouble shooting?
Workaround possible, but not very nice

## Agent Version and Platform
Agent: 2.133.3
OS: Windows 10.0.14393

VSTS agent running inside an Azure VM

## VSTS Type and Version
VisualStudio.com

## What's not working?
If a security application (eg. qualys) is installed some registry keys (uses registry as credential storage) are not readable by `NETWORK SERVICE` user and vsts agent failed to run tasks. The tasks are already failing in the setup phase (before running the user task) where the agent wants to list the installed software.

Affected registry keys are under:
- HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
- HKEY_LOCAL_MACHINE\SOFTWARE

The task fails with a "Requested registry access is not allowed." exception and prevents any build.

As the registry permissions are a windows feature the agent should be able to deal with locked registry keys and should be able to proceed.

## "Workarounds"
- Allow `NETWORK SERVICE` to read these keys (security credentials are readable by all vsts users!)
- Uninstall security software

**Comment by TingluoHuang** [comment]
@mblaschke `NETWORK SERVICE` is the default account we prompt during agent config, you can choose to run your agent service as a domain account, then manage permission for that domain account.

**Comment by TingluoHuang** [comment]
i don't think there is anything to with the agent for your issue, you choose the agent to run as `NetworkService`, you need to manage permission for `NetworkService` yourself. 
I am going to close this issue, let me know if you need more help. :D

**Comment by mblaschke** [comment]
@TingluoHuang 

We don't want that the VSTS agent can access the secret.
But the VSTS agent is failing due to an exception and will fails for EVERY deployment if there is a registry key which he cannot access so i would say this is a VSTS agent bug as this permission feature is a common windows feature.

The "workaround" to make a secret public to all vsts agent users is nothing that we want but as the agent is failing the only way to keep our deployments running.
It's a secret for a reason and we don't want that another tool can read it because.. hey, it's a secret, right?

So please open it again.

**Comment by TingluoHuang** [comment]
@mblaschke which build/release task are you using that need to access to those registry? what are failing? is the agent not able to start or your build/release failed due to some task error?

**Comment by TingluoHuang** [comment]
@mblaschke 
i think that means Azure PowerShell may require its run as user have permission to those registry.
What i want to say is the vsts-agent is just a tool invoker, it runs all different tools you choose to use in your build/release definition and report return code.
The agent doesn't control what requirements each tool needs, like Azure PowerShell want permission to read your registry.

**Comment by mblaschke** [comment]
@TingluoHuang 
These registry keys are only accesable by an administrator for security reasons.

Who is responsible for the startup phase of eg. the "Azure Powershell" task? It's not user content, the deployment powershell script was not executed, the exception thrown before the user content was executed.

We just run the Azure VM with an VSTS agent on it using hosted VisualStudio account and we don't see any point where we can modify these "hardcoded" commands.

Currently this is a very big blocker for big companies who are forced to use eg. Qualys.

Running the users task as admin would also solve this issue, but to be honest, a big security violation cannot be a solution ;)

**Comment by mblaschke** [comment]
Thanks, will open a new ticket :)
