### ISSUE TITLE
Vsts-agent on Windows 10 Invoke-MsBuild error

### ISSUE THREAD

**Issue by richardwoollcott** [Microsoft/vsts-agent#171]
Hi I'm trying to build a Xamarin.Android project using the vets agent on Windows 10 with Visual Studio 2015 Professional Update 2 installed and am experiencing the error below:-

Executing the powershell script: C:\windowsagent\_work\_tasks\XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285\1.0.13\XamarinAndroid.ps1
Microsoft.PowerShell.Commands.WriteErrorException: **A parameter cannot be found that matches parameter name 'LogFile'.**
Microsoft.PowerShell.Commands.WriteErrorException: See http://go.microsoft.com/fwlink/?LinkId=760847
PowerShell script completed with 2 errors.

It looks like it's the Invoke-MSBuild  command with the parameter -LogFile thats the problem.

```
foreach ($pf in $projectFiles)
{
    try {
        Invoke-MSBuild $pf -LogFile "$pf.log" -ToolLocation $msBuildLocation -CommandLineArgs $args
    }
    catch [System.Exception] {
        Write-Error $error[0]
        $exitCode = 1
    }
}
```

I've experimented with trying to install Invoke-MsBuild, first using chocolatey then in Powershell using the command Install-Module -Name Invoke-MsBuild -Force could this be I'm using the wrong version of Invoke-MsBuild?

When I use Get-InstalledModule in powershell it's reporting version 1.6.3 for Invoke-MsBuild.

Regards,
Richard

**Comment by ericsciple** [comment]
@TingluoHuang Was the Invoke-MSBuild ported to the version of the legacy task lib that is pulled into the Core CLR agent? If not, it looks like the ps implementation for this task would be really easy to port to the ps3 task handler.

**Comment by TingluoHuang** [comment]
@ericsciple Looks like I didn't port it. I didn't realize it been used by task other than msbuild...

**Comment by TingluoHuang** [comment]
@richardwoollcott I will fix it in next preview.

**Comment by richardwoollcott** [comment]
Thats great thanks

**Comment by TingluoHuang** [comment]
#198 should fix this.

**Comment by richardwoollcott** [comment]
Thanks for fixing this.
