### ISSUE TITLE
Get sources: Git fetch - the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by chcosta** [Microsoft/vsts-agent#1711]
## Agent Version and Platform
Version of your agent? 2.136.1
OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? VisualStudio.com

If VisualStudio.com, what is your account name? http://dotnet.visualstudio.com

## What's not working?
2018-07-14T00:01:00.3572284Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=5 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/303/merge:refs/remotes/pull/303/merge
2018-07-14T00:01:08.3263472Z fatal: The remote end hung up unexpectedly
2018-07-14T00:01:11.0106851Z ##[error]Git fetch failed with exit code: 128

## Agent and Worker's Diagnostic Logs
Unavailable (not sure how to connect to a Hosted agent)

We've seen this issue a handful of times (it's not frequent but it does occur).  The error looks slightly different from what was reported in https://github.com/Microsoft/vsts-agent/issues/1474.  Is this something that a retry could help with?

**Comment by TingluoHuang** [comment]
@chcosta 
#1474 is calling VSTS git repository, in your case, you are calling github.com.
you might want to ask github.com why they are hung up.

**Comment by chcosta** [comment]
Sure, I can follow up with them.  

My point in filing this issue was to highlight that network / other issues are common (particularly when depending on an external provider), and that it might be helpful to add some retry logic here depending on the error code.  We don't have much control over the "Get sources" step so we can't do anything (that I know of) on our end to improve reliability and thus we depend on the agent to be rock solid.  One off failures aren't a terribly big deal, until they are, like when you're spinning an escrow build and 4 PM's are asking you for build status.

I know there's some other work in this area for improving reliability of VSTS builds, but catching this particularly type of issue at the source might prevent wasting a lot of resources.

**Comment by vtbassmatt** [comment]
Fetching sources seems like it should be idempotent and thus safe to offer a retry or 2. Probably not by default, but as an option for complex builds. @TingluoHuang would that be problematic? (I'm only asking about the semantics of retrying the fetch. Scheduling work to add this feature is an entirely different question.)

**Comment by TingluoHuang** [comment]
@vtbassmatt i think adding retry is fine, it wouldn't make the problem worst, i think we need to run `git reset --hard` before retry git fetch.

**Comment by bryanmacfarlane** [comment]
closing since it's merged.
