### ISSUE TITLE
Feature Request - keep the source code of build.yaml and application source code in separate repositories 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1715]
Hi vsts developers! I wonder if it is possible now? Keeping build.yaml in the same repository of the source code to build works fine for simple scenarios but getting tedious to maintain if we have multiple branches.

I'd like the idea of keeping  build logic   as separate repository not interfered with application source code to build ...

**Comment by ericsciple** [comment]
done: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-reusefromrepo.md

**Comment by ericsciple** [comment]
@melezhik

**Comment by melezhik** [comment]
Hi @ericsciple , it's close, but probably not exactly what I was looking for, ideally I would like to see this hypothetical scenario:


```

# This is a repository containing build logic ( build.yaml ) and helper script ( script.bat ):

$ ls -1

build.yaml
script.bat 

# Helper script 

$ cat script.bat

REM this script will do something with application source code 
REM which is loaded later 
REM and will be accessible
REM at w1 working folder
 

# Build logic

$ cat build.yaml

resources:
  repositories:
    type: git
    name: apps/app1 # Application source code 
    working_copy : w1 # the local path where source code from apps/app1 would be checked out 
steps:

- task: BatchScript@1
  displayName: Run script
  inputs:
    filename: 'script.bat'

```


Original Idea with [templates](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-reusefromrepo.md) imho is kinda limited.  Course you only reusing YAML code there, while in the suggested scenario you are reusing everything comes from repository ( both build.yaml and script.bat )
