### ISSUE TITLE
Support ~ in the workFolder on Linux

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/vsts-agent#1724]
## Agent Version and Platform
Version of your agent? 2.136.1

OS of the machine running the agent? Linux

## What's not working?
The config.sh script accepts a path for the `workFolder` starting with `~/`, but interprets it as an actual folder named `~` relative to the agent folder instead of the user's HOME directory. While this is certainly a valid configuration, it then broke my Yocto build and most importantly is not what I was trying to configure :)

**Comment by ericsciple** [comment]
did you pass it on the command line or during a prompt? on the command line I would expect bash it expand it, otherwise I would not expect it to be expanded

**Comment by Tragetaschen** [comment]
You are correct, it was on the prompt.

**Comment by TingluoHuang** [comment]
@Tragetaschen i am going to close this issue, since `~` is a bash shortcut. please reopen if you need more help.
