### ISSUE TITLE
Deployment groups and Agent Phase groups

### ISSUE THREAD

**Issue by IbrahimUmar** [Microsoft/vsts-agent#1726]
What is difference between agent phase and deployment group phase in Release definition of TFS 2018.

**Comment by TingluoHuang** [comment]
@IbrahimUmar this is repository for VSTS builld/release agent, it's for reporting issue with the agent itself, you might want to use other channel to seek help from general VSTS question.
Like: 
https://visualstudio.microsoft.com/team-services/support/
https://docs.microsoft.com/en-us/vsts/index?view=vsts
https://developercommunity.visualstudio.com/spaces/21/index.html

i am going to close this issue for now.
