### ISSUE TITLE
Unable to refresh agent capab without restart // ##vso[agent.capability

### ISSUE THREAD

**Issue by carct** [Microsoft/vsts-agent#1732]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
Agent.Version | 2.136.1

OS of the machine running the agent? OSX/Windows/Linux/...
Agent.OSVersion | 10.0.14393
Private agent.

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?
VSTS
If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

## What's not working?
Please include error messages and screenshots.
**Write-Host "##vso[agent.capability name="myCapab"]myValue"**

_"##[warning]Can't find command extension for ##vso[agent.command]. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)"_

Hi,
Noticed that in the initial setup of the agents you guys use the above VSO Command. 
E.g. of usage: https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutbin/powershell/CapabilityHelpers/CapabilityFunctions.ps1

We'd like to use this command to change the value of the capability of the current agent that is running the build, but we get the error:
"##[warning]Can't find command extension for ##vso[agent.command]. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)"

Have also tried to add the below lines prior to the VSO command:
Import-Module -Name 'Microsoft.PowerShell.Management'
Import-Module -Name 'Microsoft.PowerShell.Utility'

Noticed the usage of _PowerShellCapabilitiesProvider_ (https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Capabilities/PowerShellCapabilitiesProvider.cs) which seems to be the thing to import, but not really sure if this is it and how to do that since it's the source code. 
Should be compiled in "Microsoft.VisualStudio.Services.Agent.dll" and therefore the VSO command be available for the agent, no ?!

Any suggestion on how to do the above or to update the capabilities without having to restart service or VM ? In Linux agent there is that env.sh that seems to handle this quite fine.

Very much appreciate your input on the matter!

Thank you,
Andrei

**Comment by TingluoHuang** [comment]
@carct 
`##vso[agent.capability]` is not mean to use by user. `http://go.microsoft.com/fwlink/?LinkId=817296` shows the supported `##vso` commands.

What's your scenarios? why you want to change the agent capability while it's running a Build/Release?

I think you can also create a `.env` file even fro windows agent.

You can always make REST api call to update agent capabilities.

**Comment by carct** [comment]
yeaa i checked that webpage with the available commands, but got excited when i saw in your initial scripts the other one that you use  :))

we wanted to make a demand for a phase and make sure that once that phase is finished that specific agent will not be accepting any new build that could exist in the queue and basically we'd destroy it at some point and re-create so that each time it accepts a build it is in a fresh state

now i'm working on getting the agent to put himself offline (unregister basically) as the last task in the phase (see my post from issue #1730 )

i checked the available API endpoints and couldn't find anything related to the agents (maybe deployment groups and some other testing stuff), would you please point me to the documentation?

also, would you have a better idea on how to ensure that the agent is not picking up any other build once it finishes the initial one ?

thanks!

**Comment by TingluoHuang** [comment]
@carct you can disable the agent once it start running job. we don't have any doc around the agent, but you can figure it out in F12 tool from browser. 
![image](https://user-images.githubusercontent.com/1750815/43270519-38e090ea-90c3-11e8-9e76-3534046cc564.png)

**Comment by carct** [comment]
ok, the API is indeed an option and i'll keep in on my list if not pleased with the current approach

regarding the .env file, i tried creating one but the agents' capabilities don't get refreshed automatically.. previously i was referring to the 'env.sh' script available on the linux agent that is able to refresh the capabilities, although i'm not 100% sure if it need a a stop/start to publish the new capab. to VSTS ...

thanks for the input

**Comment by TingluoHuang** [comment]
capabilities updates only happen during agent start up, i am pretty sure after you run `env.sh` you need restart the agent process. :)

**Comment by carct** [comment]
ah, alright, thought that it also published it or at least the agent would pick it up from the .env file

may i suggest that the .env file be scanned periodically by the agent and publish any changes ?
maybe VSTS can trigger this periodically (and also on-demand through some api call) so that it can compare for any changes

anyways, thank you ! i don't think any other options are available to handle this...

**Comment by TingluoHuang** [comment]
Sure, we can consider that, i think i am going to close this issue for now. let me know if you need more help.
