### ISSUE TITLE
Options tab is not accessible for YAML based pipelines

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1734]
Hi! Any ideas why **options tab** is not accessible for yaml build definitions, what I normally does for GUI based build?

Build options in GUI based build definition:
  
![build-options](https://raw.githubusercontent.com/melezhik/images/master/build-options.png)

Build options in YAML based build definition:

![build-options](https://raw.githubusercontent.com/melezhik/images/master/build-options-yaml.png)

**Comment by ericsciple** [comment]
It is intentionally not available on yaml definitions. @melezhik which setting are you looking for on the options tab?

**Comment by melezhik** [comment]
Hi @ericsciple , it is "Build number format".

**Comment by ericsciple** [comment]
@melezhik I was hoping you would say that one! Here is the yaml way of defining the build number: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-name.md

**Comment by melezhik** [comment]
👍

**Comment by melezhik** [comment]
thanks @ericsciple , will try that one
