### ISSUE TITLE
VSTS Package feed not always finding upstream source

### ISSUE THREAD

**Issue by jmiddour** [Microsoft/vsts-agent#1735]
## VSTS Type and Version
VisualStudio.com

## What's not working?
I have a package cache feed to serve as a clearing house for all packages used during builds.
I have 4 upstream sources for that feed -- NPM, Nuget.org, local NPM feed, local nuget feed.
When the local nuget feed is 4th in priority, it does not find the new version of the packages and bring them over to the cache.  When I move it up in priority, it does find the package and brings it over.

This may be by design - but I would have expected it to exhaust all sources before reporting back as a failure.

**Comment by TingluoHuang** [comment]
@jmiddour you might want to report this problem to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) 
this is the repository for tracking build/release agent issue.

**Comment by TingluoHuang** [comment]
i am going to close this issue, since it's not scope to this repository.
