### ISSUE TITLE
Inconsistent behavior of 'Hosted Ubuntu 1604' Host image

### ISSUE THREAD

**Issue by carct** [Microsoft/vsts-agent#1744]
## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
Agent.Name | **Hosted Agent**
Agent.Version | **2.136.1**

OS of the machine running the agent? OSX/Windows/Linux/...
pool "**Hosted Ubuntu 1604**"

## VSTS Type and Version
**VSTS**

## What's not working?
Please include error messages and screenshots.
Running task 'Bash' (Run a Bash script on macOS, Linux, or Windows // Version: 3.136.0) with the following in-line script:
_sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get -y install ansible
sudo pip install --upgrade pip
sudo pip install ansible[azure]
sudo pip install pywinrm
ansible --version_

**Sometimes** i get the following message:
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
..................
The directory '/home/vsts/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vsts/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

I can see that advice regarding -H flag, but the troubling thing is that the above behavior is totally inconsistent as the above happens only sometimes, most of the other times it works just fine with the exact same in-line script. 
This makes me think that maybe the mentioned flag is not actually the issue as in the logs of the successful execution i don't see the first part of the message related to the 'dpkg lock / resource temp unavailable', but i still see the second part that advises me to use -H flag to sudo and, once again, everything works just fine.

What are your thoughts on the matter ?

Thank you,
Andrei

**Comment by TingluoHuang** [comment]
@carct thanks for reporting this, I would suggest you report this problem to [ImageGeneration](https://github.com/Microsoft/vsts-image-generation), that is the repository about how that Ubuntu 1604 image got built.

I don't think the problem you run into is an agent issue, so I am going to close this issue for now.
