### ISSUE TITLE
vsts agent is running on network user instead of admin windows user

### ISSUE THREAD

**Issue by AmitDaniel-wsc** [Microsoft/vsts-agent#1746]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.127.0

OS of the machine running the agent? OSX/Windows/Linux/...
Windows server 2016 

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? VisualStudio.com

If VisualStudio.com, what is your account name? http://wsc-zoomin.visualstudio.com

## What's not working?
Please include error messages and screenshots.

I'm trying to install the vsts agent using VMSS extension using powershell custom script .
and i saw that the the vsts agent service is running using network service instead of ad admin user.
The command to setup the agent is : 

```
$hostname=hostname
config.cmd --unattended  --url https://wsc-zoomin.visualstudio.com --auth pat --token <TOKEN> --agent $hostname --pool default --runAsService --windowsLogonAccount '.\<USERNAME>' --acceptTeeEula --windowslogonpassword '<PASSWORD>'
```
![screen shot 2018-08-06 at 9 27 45](https://user-images.githubusercontent.com/40730680/43701072-9c869d04-995d-11e8-9f3f-f04abd519bcc.png)

And in this case i can't run docker commands cause i'm getting the following errors : 

`2018-08-06T06:21:37.6062354Z ##[error]error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/json?all=1: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

## Agent and Worker's Diagnostic Logs
Let me know if you need logs - maybe it's just a command issue 

Thanks , 
Amit

**Comment by TingluoHuang** [comment]
@AmitDaniel-wsc the command line seems right, what is `VMSS extension`?
you might want to attach the log, the log should shows what arguments the agent get while config

**Comment by AmitDaniel-wsc** [comment]
@TingluoHuang Thanks . 
Vmss extension is virtual machine scale set - and once you're scaling up / down the instances you can run a custom script ( Powershell script ) that will install the agent / clone repository or do whatever you want once the server is starting . 

Which logs should i attach ?

**Comment by TingluoHuang** [comment]
@AmitDaniel-wsc everything under `_diag` folder of agent root directory.

**Comment by TingluoHuang** [comment]
@AmitDaniel-wsc seems like a escaping problem.
`'.\<USERNAME>'`
[2018-08-06 14:14:12Z INFO CommandSettings] Arg 'windowslogonaccount': ''.\wscadmin''
[2018-08-06 14:14:12Z INFO CommandSettings] Arg is invalid.

Can you try pass ``.\<USERNAME>`` or ``".\<USERNAME>"`` instead of using single quote?

**Comment by AmitDaniel-wsc** [comment]
Sure . Updating the script now . 
I'll send the logs again if something will fail again . 

Thanks @TingluoHuang

**Comment by AmitDaniel-wsc** [comment]
@TingluoHuang King of the world !!!!
it works like a charm !!!!!! 
Thank you so much !

**Comment by TingluoHuang** [comment]
@AmitDaniel-wsc cool, glad you unblocked.
