### ISSUE TITLE
Better supported-handler-not-found message

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#175]
Add the list of handlers that the task supports to the supported-handler-not-found message from task runner when an appropriate handler can't be found for the current platform.

**Comment by bryanmacfarlane** [comment]
Note it's not the list it supports.  The key is including the handler it couldn't handle to the error message

**Comment by ericsciple** [comment]
The reported issue was for the Node agent. This agent already reports a message (`Supported task execution handler not found.`), it just doesn't include the unsupported handler name(s).

Agreed, the list it supports does not need to be included in the error message. However, it still could be *a list* that needs to be included in the error message (since tasks can carry more than one implementation).

**Comment by TingluoHuang** [comment]
#790
