### ISSUE TITLE
***NO_CI*** commit message flag not being honored

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-agent#1760]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes, but n/a

## Agent Version and Platform
Version of your agent? 1.136.1 

OS of the machine running the agent? OSX/Windows/Linux/…
All 

## VSTS Type and Version
VSTS

If VisualStudio.com, what is your account name? multiple

## What's not working?
The `***NO_CI***` commit message flag is no longer being honored, resulting in endlessly recursive builds. This was working just fine until very recently. I'm guessing the root cause may be a change on the VSTS side but not sure

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

**Comment by TingluoHuang** [comment]
@calebcartwright there is a regression on the server side @MireilleHanna fixed today, the deployment will deploy the fix on Monday.

sorry for the inconvenience!

**Comment by lifesoccult** [comment]
@TingluoHuang I am still experiencing this issue with builds inside my team's VSTS account. Can you confirm this regression is fixed across the board? If not, when will the rollout be finished? TIA.

**Comment by TingluoHuang** [comment]
@lifesoccult the deployment that contains the fix has start rolling, it might take in total 3-4 days to hit all VSTS deployment rings (0 -> 5), what's your VSTS account name? i can help you check which ring your VSTS account belongs to. :D

**Comment by calebcartwright** [comment]
Thanks for the update @TingluoHuang . Is there an email address we can use to share account info/names with you offline to determine their ring placement?

**Comment by lifesoccult** [comment]
@TingluoHuang I will email you directly. Thanks.

**Comment by TingluoHuang** [comment]
Updates:
The deployment has finished on Ring 0/1/2.
Ring 3 is deploying right now.

**Comment by Kp0c** [comment]
Thanks for the update @TingluoHuang. Could you say what're the estimates for rings 4..5?

**Comment by TingluoHuang** [comment]
Ring 3 finished.
Ring 4 will start in an hour.

**Comment by lifesoccult** [comment]
@TingluoHuang has Ring 4 finished? Problem is still persistent.

**Comment by TingluoHuang** [comment]
@lifesoccult  Ring 4 is still running...

**Comment by TingluoHuang** [comment]
Ring 4 is almost done, other than South India region.

**Comment by TingluoHuang** [comment]
Ring 4 has completed.

**Comment by calebcartwright** [comment]
Thanks @TingluoHuang!

**Comment by garyjohnson** [comment]
Having the same issue, appeared to start yesterday or the day before. Was still happening early this morning. Is there any workaround while we wait for a fix?

**Comment by TingluoHuang** [comment]
Ring 5 is still deploying, but most accounts should get the fix already. if you are still seeing this issue, share your VSTS account name with me, i can help you double check.

**Comment by TingluoHuang** [comment]
The fix has finished deployed to all VSTS account, sorry for the break and thanks for your patience.
I am going to close this issue.  please re-open if anything still busted.
