### ISSUE TITLE
Build Failure - ##[error]Value cannot be null. Parameter name: version

### ISSUE THREAD

**Issue by victorperez2911** [Microsoft/vsts-agent#1763]
Environment
Server - VSTS
Account Name - portalprocfit.visualstudio.com
Agent - Private:
Agent Version - 2.131.0/2.134.2
Running On Windows 10 Pro - 1709
Issue Description

Hello

One of our build definitions (Gated Checkin) has now been error in the "Get sources" process of all agents.

The mistake is.

# # [ERROR] Value cannot be null. Parameter Name: Version

![image](https://user-images.githubusercontent.com/11770654/44072300-651a72ac-9f64-11e8-991e-7b0ca7d57a65.png)

Nothing in the agents has been changed.

Victor Perez

**Comment by TingluoHuang** [comment]
@victorperez2911 the fix has been deployed, can you try your build again and confirm whether it is fixed or not? thanks.

**Comment by victorperez2911** [comment]
fixed now.tks.
