### ISSUE TITLE
YAML - How to test YAML locally before commit

### ISSUE THREAD

**Issue by jhgoodwin** [Microsoft/vsts-agent#1764]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes - I tried reading the docs available, getting started guides, looking through the logs with debug enabled, but I did not see a way to run, or rerun a yaml build at the command line.

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
image: microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce-standard

OS of the machine running the agent? OSX/Windows/Linux/...
Linux docker image:
image: microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce-standard

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? https://metabolondev.visualstudio.com

## What's not working?
Unable to find out how to test YAML files locally before committing.

## Agent and Worker's Diagnostic Logs
n/a

**Comment by TingluoHuang** [comment]
@jhgoodwin what kind of testing you are trying to do? just validate syntax or verify the function?

**Comment by bryanmacfarlane** [comment]
We have a few stories on our backlog to address these scenarios starting with linting, then preview what if, and then finally a private buddy build you can run before committing the yaml (run locally but cooperates with the service - not offline).

I'm going to close since this is a multi-stage set of work and it's not an issue.  rest assured it's something we want to and will solve.  It's just not ready yet.

**Comment by jhgoodwin** [comment]
@bryanmacfarlane what feed is most likely to have the updates related to this work announced? I'd be glad to try it when it's available.

**Comment by another-guy** [comment]
This increases the development cycle and prevents fast experimental changes to Build pipelines. :|

The issue is closed as "multi-stage set of work" but not a single related issue was linked to this one (so that users can subscribe). :(

**Comment by medmin** [comment]
I have to say, it would be  game changing  if Azure Pipeline does provide such feature. 

A use case is that sometimes it's not the ymal file that has issues, but still the CI or CD gets failed. Just like this issue on Vuejs:

https://github.com/vuejs/vue-cli/issues/2404

This issue has been bothering me and many others for a very long time, but nobody can give a proper answer because sometimes it's ymal file, sometimes it's the OS environment, and sometimes it's vuejs. 

So, a more important issue is whether we can test the whole CI or CD process locally.  We cannot just commit something and hope this time it would work. That's painful.

**Comment by jhgoodwin** [comment]
@bryanmacfarlane Perhaps I'm just failing to do something simple, but how do I find the docs you are referring to? I checked in that folder, but after a long time, there are no changes. I tried searching for branches with `yaml` in the name, but still not seeing anything. From what you are saying, it seems like I must be missing something obvious.

**Comment by bryanmacfarlane** [comment]
Since that early post, yaml stuff was moved to here:
https://github.com/Microsoft/azure-pipelines-yaml/tree/master/design

The documentation since then was integrated into the official docs, e.g.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml

**Comment by DaveSneddon** [comment]
Now that YAML pipelines have been made the default, how about giving us the opportunity to test them locally.  The "create, run, inevitable failure, hand hack, fail, try to guess what the issue is, hand hack fail" cycle is much slower than the previous, very easy to understand GUI driven system.

**Comment by ReddingScriptars** [comment]
Makes me want to keep my career from getting sucked into more of that stuff

**Comment by bryanmacfarlane** [comment]
Note that test before commit does not necessarily mean run them locally.  The former is much more valuable in finding issues early.

**Comment by MPiwowarski** [comment]
The only workaround for now is just to use [cakebuild.net ](https://cakebuild.net/) It would be so nice if the M$ give us a solution to run the build locally based on the yaml.

**Comment by another-guy** [comment]
@bryanmacfarlane how would I test before commit without running them locally, however?

**Comment by dariuszparys** [comment]
Is there a way to reopen this @bryanmacfarlane?

**Comment by jhgoodwin** [comment]
It is my understanding many of the Azure DevOps contributors have been retasked to GitHub related assignments. Unless there's a big change in priority, the chance of this getting work is all but zero. The thing that baffles me is how they iterated on the pipeline w/o this. Whether tasks or pipelines, I can't conceive why anyone would want to add/commit/push every time they try to change the system. I'm starting to think I need to have my team use Fake and Paket scripts w/ defined stages where auth happens when leveraging the build agent. The pain and suffering of defining build yaml is just too high as is.

**Comment by MichaKnoe** [comment]
I totally aggree, that this is very painfull.
But I fear we need to consider the requested issue to be a new maybe quite complex feature.
Here I found a similar feature request:
https://developercommunity.visualstudio.com/content/idea/366517/ability-to-test-yaml-builds-locally.html --> please upvote it.

**Comment by ScottLangham** [comment]
I used to define my entire build with msbuild. IT aquired nugets+dependencies, build solutions, signed files, build installers, packed and pushed nugets and artifacts. The world was happy and I could run it on my machine and on the build machine.

I never really understood why there were all the other pipeline tasks!
Recently though this is becoming hard to maintain! Its seems that new functionality we want to use in builds is only supported in pipeline tasks and I can't call it directly from msbuild.

Cry.

It is very wrong to have to define a build that I want to do the exact same thing in two different ways to be able to run it locally and on build machines!!!!!!!!!

Architectural fail. :)

**Comment by jaapcrezee** [comment]
> We have a few stories on our backlog to address these scenarios starting with linting, then preview what if, and then finally a private buddy build you can run before committing the yaml (run locally but cooperates with the service - not offline).
> 
> I'm going to close since this is a multi-stage set of work and it's not an issue. rest assured it's something we want to and will solve. It's just not ready yet.

Any update on this? It would be useful to run this on a local machine; until that is arranged, azure pipelines are practically useless for me and probably many other Linux CLI guys...

**Comment by jhgoodwin** [comment]
@jaapcrezee Don't hold your breath. If you don't like azure pipelines for dev/test cycles, I'd work out some alternate arrangement and just use pipelines as a way to kick it off on another computer, but put all the tasks and such inside your own code.

Doing it this way would also make your platform easier to port to another provider should the need arise.

**Comment by Nirav-Bhadradiya** [comment]
> > We have a few stories on our backlog to address these scenarios starting with linting, then preview what if, and then finally a private buddy build you can run before committing the yaml (run locally but cooperates with the service - not offline).
> > 
> > I'm going to close since this is a multi-stage set of work and it's not an issue. rest assured it's something we want to and will solve. It's just not ready yet.
> 
> Any update on this? It would be useful to run this on a local machine; until that is arranged, azure pipelines are practically useless for me and probably many other Linux CLI guys...

Check this out - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline

**Comment by PureKrome** [comment]
> Check this out - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline

OOOoo! So they now have an API exposed for this ... and just need to add some entrypoint into their website UI. Nice -- nearly there, now.

Aside: it's also lol that this issue was closed in 2018 and in 2020 we're all still talking in it.... 🤔 🤔

**Comment by gunnerr91** [comment]
> > > We have a few stories on our backlog to address these scenarios starting with linting, then preview what if, and then finally a private buddy build you can run before committing the yaml (run locally but cooperates with the service - not offline).
> > > I'm going to close since this is a multi-stage set of work and it's not an issue. rest assured it's something we want to and will solve. It's just not ready yet.
> > 
> > 
> > Any update on this? It would be useful to run this on a local machine; until that is arranged, azure pipelines are practically useless for me and probably many other Linux CLI guys...
> 
> Check this out - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline

Hi guys, I have tried using the api, but I keep getting a timeout error, it would be nice to see other experiences (hopefully successful ones), perhaps I am missing something, not a lot in the doc.

**Comment by gunnerr91** [comment]
> > Check this out - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline
> 
> OOOoo! So they now have an API exposed for this ... and just need to add some entrypoint into their website UI. Nice -- nearly there, now.
> 
> Aside: it's also lol that this issue was closed in 2018 and in 2020 we're all still talking in it.... 🤔 🤔

Just noticed that this is actually closed lol I don't think this issue is resolved yet!

**Comment by TechnicallyJoe** [comment]
Does anyone know if this is planned to be added into the vscode addon? - Could be awesome to be able to test your pipeline directly in vscode.

Also - We use a lot of templates, how would one upload those to the api?

**Comment by viveksi** [comment]
i am deploying .net core app on Azure container Registry and fixing the failure with each commit is just mind-boggling

**Comment by gwendalbroudinpro** [comment]
It's been 2 years since, and nothing has been announced? Could we at least reopen the issue to track the request, or at least open a new one?

**Comment by runemoennike** [comment]
Can we please reopen this?

**Comment by jhgoodwin** [comment]
The contributors are too busy working on the github actions which seems to have this. My advice would be to use that, or else to move away from using tasks and instead use local make-style builds, only using the actions to invoke them.

It's absurd that incremental, local testing is so foreign to Microsoft, but it is what it is.

**Comment by runemoennike** [comment]
The speed at which we are supposed to rewrite our projects to suit the latest flavour is ridiculous.

**Comment by anatolybolshakov** [comment]
Hi everyone, please feel free to create an issue in https://github.com/Microsoft/azure-pipelines-yaml to get right eyes on it. This repo is mostly for pipeline tasks, so it could be more forward way to track progress regarding this feature.

**Comment by tapika** [comment]
Raised a ticket on issue in here:

https://developercommunity.visualstudio.com/idea/1302759/yaml-how-to-test-yaml-locally-before-commit.html

**Comment by kasajian** [comment]
> This increases the development cycle and prevents fast experimental changes to Build pipelines. :|
> 
> The issue is closed as "multi-stage set of work" but not a single related issue was linked to this one (so that users can subscribe). :(

Dude, it's always been like this.  Xml builds, "new scriptable builds" now yaml builds.   You'd think the company that started with interpreted BASIC REPL would understand that developers want to get stuff working on their own computer first before putting on the server.   It honestly boggles the mind.   It's a cultural issue that I don't see changing unfortunately.

**Comment by v-kydela** [comment]
I think the concept of running a YAML pipeline locally is getting conflated with the concept of testing a YAML pipeline before committing it.

The ability to run a pipeline locally is not only a much larger feature to implement, it's also less desirable because your local machine won't be able to give an accurate impression of whether the pipeline will run on the cloud. It's also irrelevant to me because I always edit YAML pipelines directly in DevOps where I'm going to run them. The feature of just getting to test a pipeline before committing it seems like it would be as easy to implement as adding a "run" button that's the same as "save and run" without the save. DevOps can already run your pipeline for you, so how hard can it be to let you run a pipeline that hasn't been committed yet?

Because it would be a better feature and a more likely one to get implemented, I think we should focus our efforts on just asking for a way to test pipelines before committing rather than a way to run pipelines locally.

**Comment by kasajian** [comment]
What is needed is to do all this work locally on your computer without using azure pipelines.  Just like I can build a visual studio solution locally or in pipeline.   The fact that Microsoft build systems never provided a way of running the scripts locally, whether it was xaml based, then vNext, and now yml is just a perpetuation of a bad decision made a long time ago.

Fundamental tenet of any system on the cloud or build system is that the developer ought to be able to run it locally, unless there is some kind of technical reason such as it being impossible... special hardware, etc.  And even those should be able to provisionable as needed.

The solution right now is to decouple from the yaml system as much as possible, placing as much of the logic as possible in poweshell scripts which can be run in any container.   That way when the build system changes again, majority of the logic that's on powershell scripts doesn't have to get rewritten. 

Issue can be closed.

**Comment by tapika** [comment]
At the moment we actively use powershell scripts as a "replacement" for yaml, but unfortunately - yaml cannot be completely replaced with powershell - there are always native yaml mistakes, like forgetting amount of tabs, spaces inconsistency, incorrect variables / parameters usage.

We have also build system which takes quite long time to execute (for example over 1 hour), and then testing yaml syntax gets crazy if you need to fix it on same place multiple times. Luckily we've invented nooperation for powershell script - build system would just print what it about to do. But then need to run yaml with special parameter turned on.

I guess best approach would be that yaml would always execute powershell script with "-noop" command line argument first, and after that without that parameter. "-noop" would just verify that everything that was scheduled to be executed, will be executed.

Suspect it would be useful to have this interop yaml - powershell by default on, with built-in check box (like "verify execution flow" or "no operation")

**Comment by v-kydela** [comment]
> What is needed is to do all this work locally on your computer without using azure pipelines. Just like I can build a visual studio solution locally or in pipeline. The fact that Microsoft build systems never provided a way of running the scripts locally, whether it was xaml based, then vNext, and now yml is just a perpetuation of a bad decision made a long time ago.
> 
> Fundamental tenet of any system on the cloud or build system is that the developer ought to be able to run it locally, unless there is some kind of technical reason such as it being impossible... special hardware, etc. And even those should be able to provisionable as needed.
> 
> The solution right now is to decouple from the yaml system as much as possible, placing as much of the logic as possible in poweshell scripts which can be run in any container. That way when the build system changes again, majority of the logic that's on powershell scripts doesn't have to get rewritten.
> 
> Issue can be closed.

Was this in response to what I said? I'm not sure I understand what you're saying and why. The issue has been closed for a long time
