### ISSUE TITLE
Binaries do not reflect real versioning.

### ISSUE THREAD

**Issue by duaneking** [Microsoft/vsts-agent#1766]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Version of your agent? 2.134.2

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com with on-prem build agent.

## What's not working?
The binaries that get installed do not have version data set correctly.  If you look in the properties of the binary on the file system by selecting the nstalled binaries and right clicking them to get the properties of the file,  you just see "version 1.0.0.0.0" listed as the file version even with version 2.134.2 of the agent

**Comment by bryanmacfarlane** [comment]
You can run cli with --version to get version.

**Comment by TingluoHuang** [comment]
![image](https://user-images.githubusercontent.com/1750815/44871439-c5319900-ac60-11e8-8dd8-18134da53190.png)
fixed with latest version agent.
