### ISSUE TITLE
VSTS Nuget restore -- Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by wangfeng19890** [Microsoft/vsts-agent#1767]
## Agent Version and Platform
Version is 2.102.0

OS of the machine running the agent?  **Windows**

## VSTS Type and Version
VisualStudio.com

## What's not working?
Nuget step failed:
Error Message: getaddrinfo ENOTFOUND xxxx.visualstudio.com xxxx.visualstudio.com:443

**Comment by TingluoHuang** [comment]
@wangfeng19890 can you sure more info with about your issue, like a full build log?

**Comment by bryanmacfarlane** [comment]
also, create on vsts-tasks repo if you get the full log
