### ISSUE TITLE
[YAML] Cannot set environment variable in reusable step

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/vsts-agent#1770]
In YAML you can set environment variables using scripts easily but if you try to do the same thing in a reusable step then the changes are ignored in the original YAML script. So you cannot create reusable steps that will do any sort of calculations that must be used in later (reusable) steps.

A typical YAML scenario.

```yaml
- script: echo ##vso[task.setvariable variable=SomeVariable]true
```

Trying to clean up the build by using reusable steps.

```yaml
- template: steps/variable-set.yml@templates
  parameters:
     name: SomeVariable
     value: SomeValue


# variable-set.yaml
parameters:
  name: ''
  value: ''
  
steps:
- script: echo ##vso[task.setvariable variable=${{parameters.name}}]${{parameters.value}}
```

Note that this is just an example to test whether it can be done. The actual reusable step would be doing common calculations that all builds would need.

## Have you tried trouble shooting?
Tried all variants I could think of. I tried marking the variables as output and that didn't change anything. I tried declaring the variables in the root YAML file and then setting their value later. The original value was used. I tried using both echo and powershell to set the values. Neither worked.

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? VSTS

If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

If VisualStudio.com, what is your account name? http://fsmb.visualstudio.com

## What's not working?
No errors. The variables just aren't set. If they already exist then the values aren't changed. If they don't already exist then the variables aren't created.

Fundamentally what I need to do is be able to get data from a reusable step back to the root YAML file without having to go through a hacky solution like saving a file temporarily or something.

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by kenkuo** [comment]
You can try using the format function (poorly) described here: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templateexpressions.md
In your example it would be:
`- script: ${{ format('echo ##vso[task.setvariable variable={0}]{1}', parameters.name, parameters.value) }}`

**Comment by CoolDadTx** [comment]
Thanks but the issue isn't that the build doesn't like the command. It executes the command and no errors occur in the output. It just doesn't have any impact on the parent YAML definition.

I'm not sure what your example code is doing that is different than the direct call I'm making. Irrelevant it fails at runtime because it doesn't like the template expression.

**Comment by CoolDadTx** [comment]
Arg!! template expressions and whatnot are flaky. I really wish the documentation and/or samples could be updated to make all the (non-intuitive) rules (e.g. template expressions, variable references, scripts, etc) clear with examples. Using single quotes seems needed in some cases but in others double quotes, sometimes expressions eval and sometimes they don't. The list goes on.

I have another (shared) template that is properly setting env vars.

```yaml
steps:
- powershell: Write-Host "##vso[task.setvariable variable=My_BuildVersion]$buildVersion"
```
I really think the issue is related to the template expression because earlier in this script it is trying to use the parameters to set a PowerShell variable and it isn't substituting anything.

**Comment by bryanmacfarlane** [comment]
@CoolDadTx - agreed.  we're updating docs as we progress through the preview.  @ericsciple is back on Monday and he can take a look at this.

**Comment by 4c74356b41** [comment]
@ericsciple hey, dont know how to reach you in any other way, any ETA on yaml release (not build) pipelines?

**Comment by ericsciple** [comment]
Regarding your original question, template expressions (i.e. `${{ this syntax }}`) are expanded during pipeline initialization. Macros (i.e. `$(thisSyntax)`) are expanded at runtime. So I think in your scenario, you want to pass `$(SomeVariable)`.

**Comment by ericsciple** [comment]
@chrisrpatterson regarding ETA for yaml release

**Comment by 4c74356b41** [comment]
@chrisrpatterson hello? :)

**Comment by ericsciple** [comment]
`parameters` is just a templating construct. You need to map the parameter into your process. So either:

```yaml
parameters:
  someVariable: 1
steps:
- powershell: |
    ${{ format('$temp = {0}', parameters.someVariable) }}
```

or

```yaml
parameters:
  someVariable: 1
jobs:
- job: myJob
  variables:
    someVariable: ${{ parameters.someVariable }}
  steps:
  - powershell: |
      $temp = $(someVariable)
```

Note, `variables` exists at the root of the pipeline, or on a job.

**Comment by CoolDadTx** [comment]
Does the ${{ work for you in a PowerShell step? I tried the following variants and they all failed with error: Use `{ instead of { in variable names.

```yaml
"${{ format('$temp= "{0}"', parameters.someVariable) }}"
$temp = ${`{ format('{0}', parameters.someVariable) }`}
$temp = "${{ format('{0}', parameters.someVariable) }}"  
```
In the debug logs the ${{ is not getting replaced in the PS script. What PS is trying to run includes ${{ so PS fails it.

I'm not sure how jobs work in regards to reusable steps. I'm trying to get this to work in a step that is being referenced by my main YAML build file so that I can reuse this step in the 60+ build definitions we have. This would equivalent to creating a task group in the normal build definition.

**Comment by CoolDadTx** [comment]
How is this code usable from the original sample I provided? This is using AzurePowerShell@3 whereas I'm using the Powershell shell within a step, Are you saying the Powershell shell in a step won't work at all and you have to use the Powershell task?

**Comment by ericsciple** [comment]
I think @4c74356b41 might have the answer: "no, it wont work like that. it has to start with ${{ for it to work."

When we parse the DOM, if the value starts with `${{` and ends with `}}` then we treat it as a template expression. Otherwise we don't. Today we don't support template expressions embedded as a substring within - we want to add support for that but it is not supported today.

**Comment by CoolDadTx** [comment]
So when parsing the line, the very first set of tokens after the - powershell : text must be the template expression otherwise it ignores it completely? So a multi-line powershell like I posted couldn't use a template expression for one line and a regular command for another because the parser sees all the lines as a single string?

**Comment by ericsciple** [comment]
That's correct. When using `|` for multi-line, it is all a single string (single node in the post-parse yaml dom).

**Comment by CoolDadTx** [comment]
Ok, I'll try the updated YAML and see. Thanks.

**Comment by CoolDadTx** [comment]
I'm going to consider this issue closed as it seems to be the way to go right now and there is already another issue tracking the request for getting template expressions in strings to work.

**Comment by roofiq** [comment]
> You can try using the format function (poorly) described here: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templateexpressions.md
> In your example it would be:
> `- script: ${{ format('echo ##vso[task.setvariable variable={0}]{1}', parameters.name, parameters.value) }}`

Hello, any update on this method? Is there any 'better' solution for passing objects as outputs?

Thanks :)
