### ISSUE TITLE
Hosted agent in MacOs throws error when Xamarin.iOS pipline runs

### ISSUE THREAD

**Issue by Gold14388** [Microsoft/vsts-agent#1771]
## Agent Version and Platform
Agent Version: 2.136.1
MacOS high Sierra  version : 10.13.4

## VSTS Type and Version
VisualStudio.com

## What's not working?
I created a CI pipeline using Xamarin.iOS template.
I hosted an agent in MacOS and referenced this agent in my CI pipeline.
When I run the pipeline, it throws me an error as described below:

_##[Error 1]
No agent found in pool MacbookAir Pool which satisfies the specified demands:
     Xamarin.iOS
     Agent.Version -gtVersion 2.115.0_ 

## Agent and Worker's Diagnostic Logs
[logs_532.zip](https://github.com/Microsoft/vsts-agent/files/2295363/logs_532.zip)

**Comment by bryanmacfarlane** [comment]
And is there an agent in that pool with the Xamarion.iOS capability?  Does it have that capability if you restart the agent? (it scans on startup) . What if you manually add that capability to an agent in the admin web UI?

**Comment by Gold14388** [comment]
Can you direct me to the link where i can learn about adding manually that capability to an agent in admin web UI?
Also can you tell me how do i confirm if there is Xamarin.iOS in my macOs because i donwloaded Visual studio for mac in MacOs i am did try to select Xamarin.iOS while installingt

**Comment by bryanmacfarlane** [comment]
If it's not installed then you wouldn't want to manually create the capability.

https://docs.microsoft.com/en-us/xamarin/ios/

Restart the agent.

The error is correct if it's not installed ...

Reactivate if it still doesn't work.  Make sure you can build a xamarin.ios app locally as a dev first on the machine.

hth
