### ISSUE TITLE
Can't create/configure a Linux Build Agent with TFS

### ISSUE THREAD

**Issue by cwelde** [Microsoft/vsts-agent#1776]
I'm trying to follow https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts
We are using TFS2017, ubuntu linux server 16.04, but our TFS is not set with https yet due to issues.

I'm unable to configure the agent to connect to TFS
PAT - this is out of the question, we don't have https
Integrated - Not Supported for linux
Alternate - Only works with https, is there a work around? A colleague was able to connect to other Microsoft tools like TFX Cli with Basic auth, but I'm not allowed to do that with this tool?

Which leaves my only option of Negotiate, however, after entering the username and password, I am getting a GSSAPI Operation failed with error - An invalid status code was supplied (unknown error). I think it might have something to do with our corp proxy. 

For anyone who is behind one, how did you configure it to work with a proxy? I have an endpoint available.

**Comment by TingluoHuang** [comment]
@cwelde Negotiate should work for you, try pass your proxy information while configure the agent.
https://docs.microsoft.com/en-us/vsts/pipelines/agents/proxy?view=vsts&tabs=windows

**Comment by cwelde** [comment]
Sorry, I seem to have misunderstood my original issue. The ubuntu server is configured work with our proxy already. I can't connect via Negotiate to our server, all I get is a "No Such device or address error"

![issue1](https://user-images.githubusercontent.com/28943926/44431875-9a568f00-a554-11e8-989b-24c8a519e955.PNG)

**Comment by cwelde** [comment]
And then I tried it again with a different name for the server we use and receive this error:
![issue3](https://user-images.githubusercontent.com/28943926/44432361-a17e9c80-a556-11e8-8320-27ac93415183.PNG)

**Comment by TingluoHuang** [comment]
@cwelde when you configure your agent, which command you run?
i assume your run `./config.sh`
in order to pass proxy info to the agent you need to run following when configure the agent
`./config.sh --proxyurl http://127.0.0.1:8888 --proxyusername "1" --proxypassword "1"`

the agent doesn't read proxy setting from your OS.

**Comment by cwelde** [comment]
I'm sorry, I recreated a VM and reran everything and got it to work. Not sure why that is, but for now everything is good. Going to close this and sorry for wasting your time.
