### ISSUE TITLE
Get Sources Git Submodules needs option to pull latest commits

### ISSUE THREAD

**Issue by trevorNgo** [Microsoft/vsts-agent#1777]
I have been scrounging the web for a workaround to this issue. 
During the CI build "Get Sources" step, I need latest commit from remote repository from Git Submodule to be pulled; not the (potentially outdated) SHA-1 commit hash indicated by .gitmodules in the index.

In the logs, submodules are being updated through this command:
_##[command]git -c http.https://[url].visualstudio.com.extraheader="AUTHORIZATION: bearer ***" submodule update --init --force --recursive_

I need to add the flag _--remote --merge_ else it will pull from whatever SHA-1 committed in .gitmodules

It would be nice to have a checkbox to prompt users for latest remote submodule commit-update.
![image](https://user-images.githubusercontent.com/23327878/44475845-1bb92a80-a604-11e8-8b88-744cf511bebc.png)

Here is a similar blog:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a889120b-6710-4fcb-972d-8e370a7b722a/update-submodules-from-remote-via-script-during-build?forum=tfsbuild

**Comment by TingluoHuang** [comment]
@trevorNgo you can always don't check the "checkout submudules" options and add a command line task to run any git command you want.

**Comment by TingluoHuang** [comment]
@trevorNgo i am sure `--remote` is a good choice for CI system, the CI system only track which commit get build from your Main repository. So, with `--remote` when you queue 2 builds against the same commit in your Main repository, the build artifact might be different if there is any changes to your submodules.

**Comment by trevorNgo** [comment]
Unfortunately I've tried this and for my company, build servers has a tight IE SEC, meaning I cannot add login.microsoftonline.com to trusted sites. This prevents any git push/pull/ submodule update commandlines to run.

**Comment by TingluoHuang** [comment]
add a commit line task and run:
`git -c http.https://[url].visualstudio.com.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" submodule update --init --force --recursive --remote --merge`

**Comment by trevorNgo** [comment]
Thanks Tingluo, but I still am looking for another work around. I am certain Command-line hangs (to infinity) because of IE SEC. 

![image](https://user-images.githubusercontent.com/23327878/44486537-db68a500-a621-11e8-810d-6614ad72c006.png)

![image](https://user-images.githubusercontent.com/23327878/44486296-2f26be80-a621-11e8-913f-32c2e43955e7.png)

![image](https://user-images.githubusercontent.com/23327878/44486179-da834380-a620-11e8-81df-c673ab2cf0ee.png)

**Comment by trevorNgo** [comment]
![image](https://user-images.githubusercontent.com/23327878/44486604-0d7a0700-a622-11e8-8e24-b77a46b4ed8c.png)

**Comment by TingluoHuang** [comment]
![image](https://user-images.githubusercontent.com/1750815/44486757-7bbec980-a622-11e8-8e21-4b4e03ddef12.png)

**Comment by TingluoHuang** [comment]
make sure that is checked, otherwise you can't use $(System.AccessToken) in script.
the build is stuck because it's waiting for console input.

**Comment by trevorNgo** [comment]
Wow, you're a genius, Tingluo! It works! Thanks for your help!
