### ISSUE TITLE
Change my build results page to the old interface

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1794]
Hi! Any chance to change my build results page to the old interface? I like it better than current one ;))

![https://raw.githubusercontent.com/melezhik/images/master/vsts-features-disabled.png](https://raw.githubusercontent.com/melezhik/images/master/vsts-features-disabled.png)

**Comment by melezhik** [comment]
I can't do so, as this setting is disabled in my account.

**Comment by yaananth** [comment]
New build page will be the default view going forward, this is where we get new features and updates. Old page is deprecated.
We are listening for feedback, could you explain bit more on why you like the previous one better?

**Comment by melezhik** [comment]
Yeah.

1. First of all it hangs right now - ![https://github.com/melezhik/images/blob/master/vsts-build-log-hangs.png](https://github.com/melezhik/images/blob/master/vsts-build-log-hangs.png)

2. Copy of text is pretty unconvenient, at least at my browser ( chromium ) -  copy submenu ( when I select text to copy ) is almost unseen, sorry  can't make screen shot right now cause log view is not working at the moment

3. I find it is unconvenient not to see all the log at one screen, now log entries are splited by sections ( Get source code, tasks, publish artifacts , so on ), which are only browserable one by one . 
As a practical point, you can't now just copy and paste the whole log.


4. I find these lines at most right  from the log view of executed tasks pretty award especially when there are too many log lines, sorry again can't do screenshot right now.

5, in old version I could only not tailing last N lines of current log during build process , but also old lines , I can't do so with new build layout, I need to wait till build finishes to see all the log lines ( executed tasks ).


The only advantage I can see so far in comparison with old version is that horizontal links tab "log, summary, so on" is pretty handy.

**Comment by melezhik** [comment]
updated previous comment, so that my screenshot could be seen.

**Comment by bryanmacfarlane** [comment]
Not an agent issue.  You can create something on developer community if you wish.

**Comment by melezhik** [comment]
That log view is not accessible right now, which issue this is?

**Comment by yaananth** [comment]
please report it here https://developercommunity.visualstudio.com/content/problem/post.html?space=21

**Comment by melezhik** [comment]
Ok. I hope you have taken my remarks with regards to usability into consideration.

**Comment by yaananth** [comment]
We will traige/investigate once you report the problem, you can track it there as well.
Thanks for the feedback!

**Comment by melezhik** [comment]
Thank you @yaananth !
