### ISSUE TITLE
Dashboard for my projects/builds/agents for the last X minutes 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1797]
Sorry ahead of time if it is wring place to post.

I am looking for a dashboard/VSTS plugin to show me my last Project/Builds/Agents for the last X minutes. With information per project - how many builds succeeded ,  now many failed and links to the builds.

Any information would be appreciated ( vsts plugins / extension or may be out of the box functionality of VSTS which I am not aware  )

Thank you

**Comment by TingluoHuang** [comment]
https://developercommunity.visualstudio.com/spaces/21/index.html seems to be better place for this kind of question.

what about this extension?
https://marketplace.visualstudio.com/items?itemName=ms-devlabs.TeamProjectHealth

**Comment by melezhik** [comment]
Thanks @TingluoHuang 

> what about this extension?
https://marketplace.visualstudio.com/items?itemName=ms-devlabs.TeamProjectHealth


It is only for project not ALL projects

**Comment by melezhik** [comment]
FYI - https://developercommunity.visualstudio.com/content/problem/325111/dashboard-for-all-my-projectsbuildsagents-for-the.html
