### ISSUE TITLE
NO_PROXY environment variable ignored by node.js when run through VSTS agent

### ISSUE THREAD

**Issue by kaufmd** [Microsoft/vsts-agent#1800]
Issue can be reproduced on Windows and Linux platform!

## Agent Version and Platform
Windows:2.131.0
Linux: 2.139.1

## VSTS Type and Version
VisualStudio.com

## If VisualStudio.com, what is your account name? 
https://schwarzit.visualstudio.com

## What's not working?
We have set up the VSTS agent in our internal network to work with a proxy to be able to connect to the visualstudio.com instance. We also defined a .proxybapass file in the root of the VSTS agent directory to ignore this proxy for certain addresses. The rules in this file are disregarded for the node.js task though apparently. I pasted an excerpt from the VSTS debug logs beneath. As you can see we're still bouncing at the proxy server.
To rule out that node.js is the culprit I used the same call that the SonarQube plugin uses in a small JS program which I ran through a standalone node.js instance and this one worked like a charme. Side note: I had to set the environment variable NO_PROXY for this to work correctly or else I bounced at the proxy too. When running SonarQube plugin in the VSTS Agent context though this environment variable (NO_PROXY) is totally disregarded.

Reasoning on this I think there are two options why that is:
1. The VSTS Agent is overwriting/overriding some of the node.js proxy mechanisms leading to this error. It might even be because the .proxybypass file has a different format than the one node.js expects.
2. node.js is disregarding the NO_PROXY environment variable when being called with proxy parameters from the VSTS agent.

Please check if either is the case and help us resolve the issue so we can get our static code analysis to run.

`2018-08-31T12:32:12.7388666Z ##[debug]Agent.ProxyUrl=[ProxyURL:Port]
2018-08-31T12:32:12.7389207Z ##[debug]Agent.ProxyUsername=undefined
2018-08-31T12:32:12.7389618Z ##[debug]Agent.ProxyPassword=undefined
2018-08-31T12:32:12.7390019Z ##[debug]Agent.ProxyBypassList=["my.url"]
2018-08-31T12:32:12.7390440Z ##[debug]expose agent proxy configuration.
2018-08-31T12:32:12.7390843Z ##[debug]Agent.CAInfo=undefined
2018-08-31T12:32:12.7391232Z ##[debug]Agent.ClientCert=undefined
2018-08-31T12:32:12.7391640Z ##[debug]Agent.SkipCertValidation=undefined
2018-08-31T12:32:12.7392209Z ##[debug]SonarQube=a874a7fc-6e35-4660-bd3d-c97ca7d9d871
2018-08-31T12:32:12.7392858Z ##[debug]a874a7fc-6e35-4660-bd3d-c97ca7d9d871=https://sonar.internal/sonar
2018-08-31T12:32:12.7393307Z ##[debug]a874a7fc-6e35-4660-bd3d-c97ca7d9d871 auth param apitoken = null
2018-08-31T12:32:12.7393956Z ##[debug]a874a7fc-6e35-4660-bd3d-c97ca7d9d871 auth param username = ********
2018-08-31T12:32:12.7394448Z ##[debug]a874a7fc-6e35-4660-bd3d-c97ca7d9d871 auth param password = null
2018-08-31T12:32:12.7394870Z ##[debug]organization=null
2018-08-31T12:32:12.7395247Z ##[debug]scannerMode=MSBuild
2018-08-31T12:32:12.7395662Z ##[debug]projectKey=Com.Organization.ProjectName
2018-08-31T12:32:12.7396077Z ##[debug]projectName=ProjectName
2018-08-31T12:32:12.7396478Z ##[debug]projectVersion=1.0
2018-08-31T12:32:12.7396988Z ##[debug][SQ] API GET: '/api/server/version' with query "undefined"
2018-08-31T12:32:12.7398359Z ##[debug]Response: 403 Body: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

## Agent and Worker's Diagnostic Logs
Too much to blank out. This log file is giving URLs and information about internal projects. Can't do that publicly.

**Comment by TingluoHuang** [comment]
@kaufmd the agent is not using any of those linux proxy variables, the agent use different variable to expose its proxy setting with task, AGENT_PROXYURL/Username/Password/Bypasslist, in the log you shared looks like the task get those info, `Agent.ProxyBypassList=["my.url"]`, make sure you author your bypass file right, entry in that file should be regex, so consider escaping.

**Comment by kaufmd** [comment]
Following your hint I came up with the following RegEx - but still to no avail.

RegEx: ^(https?:\/\/)sonar\.internal/sonar.*$
URL: https://sonar.internal/sonar

Any further ideas?

**Comment by kaufmd** [comment]
Following your hint I came up with the following RegEx - but still to no avail.

RegEx: ^(https?:\/\/)sonar\.internal.*$
URL: https://sonar.internal/sonar

The debug log tells me the following: 2018-09-06T06:53:07.5451518Z ##[debug]Agent.ProxyBypassList=["^(https?:\\/\\/)sonar\\.internal.*$"]

Any further ideas?

**Comment by TingluoHuang** [comment]
@kaufmd that makes me feel the task is not doing the right thing, can you share the task you are using? we may want to contact the task author.

**Comment by kaufmd** [comment]
I'm trying to use the task "Prepare analysis on SonarQube" which is part of this project: https://github.com/SonarSource/sonar-scanner-vsts

I digged into their code base and it seems that the culprit might be here: https://github.com/SonarSource/sonar-scanner-vsts/blob/master/common/ts/helpers/request.ts

That is where the actual call is being made. Are you suspecting they're not paying attention to the bypass list? This actually would explain a lot...

**Comment by TingluoHuang** [comment]
@kaufmd the weird thing is their task seems like never check proxy setting, isn't it?

**Comment by kaufmd** [comment]
@TingluoHuang I think they're relying on the Node environment variables instead of using the agent's settings. Like I said: if I strip their `get` function to the absolutely necessary parts and execute it in a stand-alone node.js environment it works. It's not unlikely they never tested their plugin in an environment that requires a proxy.

**Comment by TingluoHuang** [comment]
@kaufmd agree, i would suggest you log an issue with them, since they are authoring a VSTS task which mean they need to follow how the rest of VSTS task handle proxy config. does this make sense to you?

**Comment by kaufmd** [comment]
As their JIRA is not allowing to open tickets directly I filed a report in the following post: https://community.sonarsource.com/t/vsts-prepare-analysis-ignores-proxybypass-list/2398

**Comment by TingluoHuang** [comment]
i am going to close this issue for now, since it doesn't seems like an agent issue, please re-open if you need more help on this.
