### ISSUE TITLE
Linux agent: run as service but not as root

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/vsts-agent#1804]
On my private Linux agent I want to run the agent as service (so it starts automatically) but not as root (to secure the pipelines).

The config help states this as 'Windows only' options:

Startup options (Windows only): | &nbsp;
---------------------------------|---------
--runAsService | Configure the agent to run as a Windows service. Requires administrator permission.
--runAsAutoLogon | Configure auto logon and run the agent on startup. Requires administrator permission.
--windowsLogonAccount <account> | Used with --runAsService or --runAsAutoLogon. Specify the Windows user name in the format: domain\userName or userName@domain.com
--windowsLogonPassword <password> | Used with --runAsService or --runAsAutoLogon. Windows logon password.
--overwriteAutoLogon | Used with --runAsAutoLogon. Overwrite any existing auto logon on the machine.
--noRestart | Used with --runAsAutoLogon. Do not restart after configuration completes.

But the template suggests a user can be specified: https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutbin/systemd.svc.sh.template#L54-L55

I will try to dig into the scripts & templates but it seems like this is an un(der)documented feature.

**Comment by bryanmacfarlane** [comment]
When you tried it what uid was the systemd svc run as?  It shouldn't have been root which fits your requirements.

**Comment by bryanmacfarlane** [comment]
The command line help you're looking at is for windows config.  Per the docs your supposed to run svc.sh

https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-linux?view=vsts#run-as-a-systemd-service

If you run usage on that, you will see it does allow you to specify user:
https://github.com/Microsoft/vsts-agent/blame/master/src/Misc/layoutbin/systemd.svc.sh.template#L125

**Comment by riezebosch** [comment]
Thanks! On to the Windows install you specify it on the configure command whereas on Linux when running the svc.sh. That's where the confusion (or the oversight) came from. Probably worth mentioning on the docs that you cited.
