### ISSUE TITLE
Jenkins Queue Job -task, unable to verify the first certificate

### ISSUE THREAD

**Issue by mingalsuo** [Microsoft/vsts-agent#1805]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes.

## Agent Version and Platform
2.139.1 on Debian GNU/Linux 8 "Jessie"
2.129.0 on Windows Server 2012 R2

## VSTS Type and Version
Microsoft Visual Studio Team Foundation Server
Version 15.117.26714.0

## What's not working?
2018-09-04T11:17:34.6207657Z Task         : Jenkins Queue Job
2018-09-04T11:17:34.6221891Z Description  : Queue a job on a Jenkins server
2018-09-04T11:17:34.6235751Z Version      : 1.117.2
2018-09-04T11:17:34.6252309Z Author       : Microsoft
----
2018-09-04T11:17:35.0984013Z Error: unable to verify the first certificate

## Agent and Worker's Diagnostic Logs
There seem to be no other info than that the step failed.

## Related Repositories
N/A?
----------------------

Hi!

Is something (NodeJs?) once again using internal OpenSSL or other library instead of SChannel? We have to enable not validating certificates in endpoint-settings used by the Queue Jenkins Job -task to be able to call Jenkins-instances that use more or less self signed certifactes that are trusted by both OS's built in crypto provider.

I'd really like to not have to bypass validation since it might be frowned upon in this organisation. Is there a way to configure this or do I make this a feature request?

Thanks and regards,
Markus

**Comment by TingluoHuang** [comment]
@mingalsuo looks like a task issue to me, you might want to create the issue at https://github.com/microsoft/vsts-tasks

**Comment by TingluoHuang** [comment]
i am going to close this issue for now, please re-open if you not get response on the task repo.
