### ISSUE TITLE
How to rename an installed agent?

### ISSUE THREAD

**Issue by cocowalla** [Microsoft/vsts-agent#1807]
I have 2 Agents running as Windows services on the same server, but one of them was named incorrectly, so the name is wrong in the Windows services list and of course in VSTS too.

To change the name visible in VSTS, , can I just change the `agentName` property in the `.agent` file?

To change the name in the Windows services list, can I just use `sc`?

I think this should work, but I want to check if there is an 'official' before I potentially break things!

**Comment by TingluoHuang** [comment]
@cocowalla you have to re-config in order to change the agent name, the agent name is a primary key in the backend.

**Comment by cocowalla** [comment]
@TingluoHuang so I just run `config.cmd` again, as if I was deploying a new Agent from scratch? Does that also take care of removing the existing Windows service registration and VSTS Agent registration too?

Thanks!

**Comment by cocowalla** [comment]
Excellent, and thanks for the super quick responses - I'll give this a go tomorrow and update/close as needed!

**Comment by TingluoHuang** [comment]
i am going to close this issue for now, please re-open if you need more help on this.
