### ISSUE TITLE
Release queued indefinitely

### ISSUE THREAD

**Issue by mcm-ham** [Microsoft/vsts-agent#181]
If I create a release even with no build steps and no capability checks I'm finding it saying "Agent: not allocated" and "The release has been queued and is waiting to start..." though it is listed under a build agent as in progress.
![screenshot from 2016-05-20 12 12 58](https://cloud.githubusercontent.com/assets/8325692/15417085/b82c9456-1e84-11e6-86af-066b6398ad19.png)
![screenshot from 2016-05-20 12 14 38](https://cloud.githubusercontent.com/assets/8325692/15417086/b82c8916-1e84-11e6-92f0-66120dea3a7a.png)

Build works fine, and release works fine using the [old agent](https://github.com/Microsoft/vso-agent), this is on a Mac.

**Comment by bryanmacfarlane** [comment]
You have the wrong repo.  This is the repo for the next version of the agent.  Not the RM service.

Send a mail to RM_Customer_Queries at microsoft dot com for RM questions/issues.
