### ISSUE TITLE
Unable to access project collection endpoint from ps1 handler 

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#1814]
I'm getting multiple reports from users of my tfvc tasks that VSTS is reporting that it doesn't have an endpoint for the Project Collection when I'm trying to connect to the tfvc repository. 

The code for this hadn't changed in a year. 

See also:
https://github.com/jessehouwing/vsts-tfvc-tasks/issues/68

**Comment by jessehouwing** [comment]
The code that fails is:

```
$serviceEndpoint = Get-ServiceEndpoint -Context $distributedTaskContext -Name $env:BUILD_REPOSITORY_NAME

            $tfsClientCredentials = Get-TfsClientCredentials -ServiceEndpoint $serviceEndpoint


```

**Comment by TingluoHuang** [comment]
make sure they are on latest version agent. there was a bug in the agent cause the legacy endpoint not populate correctly.
