### ISSUE TITLE
Scheduled builds need "build only if something has changed since previous build"

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vsts-agent#194]
This is the inverse of what is gen2 build definitions but either way, I want to set up our nightly "complete" builds to only run if there has been a commit since the last build.

**Comment by bryanmacfarlane** [comment]
This repo is tracking the agent and issues with the agent.  For features in the service, please use user voice.

**Comment by bryanmacfarlane** [comment]
And yes, we know of this request and we will do this soon.  it's high on our backlog.
