### ISSUE TITLE
Support TfsVC/TEE with on-prem TFS2015

### ISSUE THREAD

**Issue by drolevar** [Microsoft/vsts-agent#199]
I have managed to install the current version of the agent and register it with the TFS.
However, when it tries to pull sources, it fails, because in TeeTFCommandManager::FormatArguments only access token (PAT) is supported. However, on-prem server does not support PAT authentication and build fails.

**Comment by bryanmacfarlane** [comment]
This preview doesn't support on-prem yet.

From the readme:
What's missing from the preview? On-prem NTLM support is in the works so preview with Team Services.

The next preview will.  Can you confirm which version you are running?

**Comment by bryanmacfarlane** [comment]
I will ensure TEE is part of the test pass for the next preview.  Should be this week.  Look for >= 2.101.0

**Comment by drolevar** [comment]
@bryanmacfarlane I'm running v.2.100.1.
Is there any sense to try to contribute a patch? Or is it already in the works?
I've tried compiling sources under ubuntu 16.04, but it doesn't work, cannot restore the runtime for ubuntu 16.04 and then fails building:
`./dev.sh b


-----------------------------------------
publish
-----------------------------------------
-c Debug

-- Running: dotnet publish Microsoft.VisualStudio.Services.Agent --

Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'ubuntu.16.04-x64'. Possible causes:
1. The project has not been restored or restore failed - run 'dotnet restore'
2. The project does not list one of 'ubuntu.16.04-x64' in the 'runtimes' section.
`

**Comment by bryanmacfarlane** [comment]
We welcome patches.  However the work you're referring to has already been done.  Mostly testing is left.

See here for setup in ur constributions guide: https://github.com/Microsoft/vsts-agent/blob/master/docs/dev/netcore.md

**Comment by drolevar** [comment]
Is the work you mention available in one of the branches?
25 мая 2016 г. 11:59 пользователь "Bryan MacFarlane" <
notifications@github.com> написал:

**Comment by bryanmacfarlane** [comment]
It's in master.

To be clear, the work isn't to support PAT on-prem.  The work is for NTLM support for OSX/Linux against on-prem server.  The agent uses the provided NTLM credentials to register the agent and listen to the queue.  We will recommend creating a specific local account to avoid using your domain creds (persisted).  So the other part of the work is to document.

Once a build occurs the server generates an OAuth token (jawt) per build which is time bombed.  TEE and other interactions with the server will use that token.

In the next major release of TFS, it will only use your credentials to interactively register the agent.  The server will exchange a token even for listening to the queue.  That will avoid persisting domain or local account credentials.  https://github.com/Microsoft/vsts-agent/pull/97

**Comment by drolevar** [comment]
@bryanmacfarlane Ok, so the OAuth token you mention is the one being used as AccessToken in TEE command manager, right?
I wonder, if it's supported in the latest Update 2.1, because that's what I get:

```
An error occurred: Access denied connecting to TFS server http://server:8090/ (authenticating as _)
An error occurred: Access denied connecting to TFS server http://server:8090/ (authenticating as _)
Exit code 100 returned from process: file name '/home/user/LinuxAgentN/externals/tee/tf', arguments 'workspaces -format:xml -collection:http://server:8090/tfs/Collection/ -login:_,******** -noprompt'.
Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 100 returned from process: file name '/home/user/LinuxAgentN/externals/tee/tf', arguments 'workspaces -format:xml -collection:http://server/tfs/Collection/ -login:_,******** -noprompt'.
```

**Comment by bryanmacfarlane** [comment]
I don't know what 2.1 is.  Let's wait till we finish the testing and docs for on-prem.  As I said above, it's in the next preview which we're currently finishing up, doc'ing and testing.  Until then, on-prem is not supported with this agent.

**Comment by bryanmacfarlane** [comment]
OK - we just dropped 2.101.0 and it supports on-prem but only for git.  We understand the issue with TEE against on-prem and we're fixing now.

**Comment by drolevar** [comment]
Works for me with Preview 6.
