### ISSUE TITLE
TEE workspace deleted every build when computer name exceeds 34 characters

### ISSUE THREAD

**Issue by andrewtechhelp** [Microsoft/vsts-agent#203]
The current stable TFBuild agent on Windows by default does a 'tf get' when doing a TFVC build. This can be configured using the $(Build.Clean) variable to delete the sources directory on each build if needed.

However, on Mac OS X, this agent runs 'tf workspace -delete' each time a TFVC build is started and I can't seem to get it to not do this, despite what I set the $(Build.Clean) variable to.

Is this by design or is it just a bug? It really slows down builds when the build agent is download all of the source code each time a build is started

**Comment by ericsciple** [comment]
Check the repo tab of your build definition. Is the Clean option set to true?

**Comment by andrewtechhelp** [comment]
Clean is set to False on the Repository tab.

**Comment by ericsciple** [comment]
@andrewtechhelp Can you send ersciple the worker log (at microsoft.com)?

**Comment by ericsciple** [comment]
...from the _diag folder.

**Comment by andrewtechhelp** [comment]
@ericsciple Logs have been sent :)

**Comment by ericsciple** [comment]
@AlexRukhlin any thoughts on this one? It looks like the computer name persisted in the workspace info is truncated when the computer name exceeds 34 characters?

**Comment by AlexRukhlin** [comment]
The "Computer" field in the "Workspaces" SQL database table on the TFS server is defined as NVARCHAR(31). So, the answer is - this is by design. Sorry for inconvenience.

**Comment by bryanmacfarlane** [comment]
Is that because windows computer name sizes?  In other words, should VC react and change in recognition of xplat clients?

**Comment by AlexRukhlin** [comment]
If I remember well the Windows computer name limit is 15 characters. On Linux it's 64.
You can change the host name from command line.
Mac: sudo scutil --set HostName _new-name_
Linux: sudo sysctl kernel.hostname=_new-name_

Also I've found on interned the following additional restrictions that might affect the limit used by TFS:

- Hostnames used for server TLS/SSL certificates should not exceed 64 bytes as a fully qualified domain name
- Hostnames used for e-mail addresses in OpenSSL-generated certificates should not exceed 31 bytes (for traditional 8 character username limit) as a fully qualified domain name (usernames longer than 8 reduce this limit)

**Comment by ericsciple** [comment]
Tracking in the above referenced issue.
