### ISSUE TITLE
git-core templates not found when using bundled git

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#204]
I'm running the latest release 2.101.0 on centos7 and am getting this warning re templates when using `git` bundled with the VSTS agent:

```
git version
git init "/home/vsoagent/_work/1/s"
warning: templates not found /home/vagrant/projects/gitwinout/share/git-core/templates
Initialized empty Git repository in /home/vsoagent/_work/1/s/.git/
```

Everything seems to work though, so probably harmless. Reporting this in case someone thinks it might cause issues.

There is a docker image where you can reproduce this: `docker pull ppanyukov/vsts-agent-auto:centos7-preview-2.101.0`, also here: https://hub.docker.com/r/ppanyukov/vsts-agent-auto/tags/

**Comment by stiliev** [comment]
It looks we need to set GIT_TEMPLATE_DIR environment variable to the correct location. From https://www.kernel.org/pub/software/scm/git/docs/git-init.html:
TEMPLATE DIRECTORY

The template directory contains files and directories that will be copied to the $GIT_DIR after it is created.

The template directory will be one of the following (in order):

    the argument given with the --template option;

    the contents of the $GIT_TEMPLATE_DIR environment variable;

    the init.templateDir configuration variable; or

    the default template directory: /usr/share/git-core/templates.

The default template directory includes some directory structure, suggested "exclude patterns" (see gitignore(5)), and sample hook files (see githooks(5)).

**Comment by bryanmacfarlane** [comment]
OK.  Go ahead and fix it.

**Comment by stiliev** [comment]
The issue is fixed.
