### ISSUE TITLE
HockeyApp task fails to upload ipa and dSYM on OSX

### ISSUE THREAD

**Issue by frankbuckley** [Microsoft/vsts-agent#205]
We have the [HockeyApp task](https://marketplace.visualstudio.com/items?itemName=ms.hockeyapp) configured to upload ipa and dSYM files from a Xamarin.iOS build in Visual Studio Team Services.

The build completes fine, but the HockeyApp task always results in:

`##[error]Failed to upload the package. Status code = 404, err =
`

We are using the latest vsts-agent version 2.101.0.

Have triple checked API key, etc. Logs indicate ipa and dSYM located OK.

Not sure if this is a HockeyApp or VSTS issue.

[Has been suggested this is a VSTS issue in the past](https://support.hockeyapp.net/discussions/problems/52717-404-error-after-vsts-upload).

**Comment by bryanmacfarlane** [comment]
Can you report in the vsts-tasks repo?  I'll get it routed ASAP

https://github.com/Microsoft/vsts-tasks/issues

**Comment by frankbuckley** [comment]
https://github.com/Microsoft/vsts-tasks/issues/1797

Also reported to HockeyApp: https://support.hockeyapp.net/discussions/problems/57383-vsts-hockeyapp-task-fails-with-404-error-uploading-ipa-and-dsym

**Comment by frankbuckley** [comment]
I have also checked with a Xamarin.Android project and get exactly the same error uploading the apk file.

**Comment by frankbuckley** [comment]
Resolved - it turns out I was specifying Bundle/Package IDs where a HockeyApp App ID was required.

**Comment by pratyush-19** [comment]
Thanks Franc, you saved my day
