### ISSUE TITLE
Agent does not run as a service on Ubuntu (14.04?) without systemd

### ISSUE THREAD

**Issue by rusergeev** [Microsoft/vsts-agent#208]
Hi there,

Subj

user@buildvm:~/agent3$ ./config.sh

```
>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/user/agent3/externals/tee/license.html

Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > Y

>> Connect:

Enter server URL > https://tfs.company.com/tfs/
Connecting to server ...
Saving credentials...

>> Register Agent:

Enter agent pool (press enter for default) > Simulators
Enter agent name (press enter for buildvm) > agent_buildvm_3
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Enter work folder (press enter for _work) >
2016-05-27 00:53:51Z: Settings Saved.
Enter run agent as service? (Y/N) (press enter for N) > Y
Systemd does not exist, if you are having init.d or any other init system you can manually configure it

```

user@buildvm:~/agent3$ cat .Agent
```
{
  "AcceptTeeEula": true,
  "AgentId": 310,
  "AgentName": "agent_buildvm_3",
  "PoolId": 6,
  "PoolName": "Simulators",
  "ServerUrl": "https://tfs.company.com/tfs/",
  "WorkFolder": "_work"
}
```

**Comment by bryanmacfarlane** [comment]
From the output:

```
Systemd does not exist, if you are having init.d or any other init system you can manually configure it
```

**Comment by bryanmacfarlane** [comment]
From the docs: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/startubuntu.md

NOTE: Prefer Ubuntu 16.04 LTS. We configure as a service using systemd and it's not in 14.04.

**Comment by rusergeev** [comment]
Thanks. No need in logs, i suppose.

**Comment by bryanmacfarlane** [comment]
Not really.  Unless you're on Ubuntu 16 which supports systemd - then very interested :)

I added those docs I pointed to last night to help out.

The error message could be better.  But what it's trying to say is systemd is the "new" service management system common to new linux versions (same as redhat etc..).  We configure for that.  Since it isn't present on your system, you can always manually configure a service in the old alternate methods init.d etc... (we just create a file for you).

If you have suggestions on better error messages or docs, all ears.  Perhaps the error message should point to an url??  Did the message not stand out enough??

**Comment by rusergeev** [comment]
The error message in deed very clear. I just did not realize the systemd is a new service. I heard about something similar quite a while ago. I am just not very experienced Linux admin. 

I specially downgraded from Ubuntu 16.04 to 14.04 to have your vets-agent, so far the configuration includes SSL root certificates for in-house LDAP and for TFS (OnPrem of course), several admins for the company build engineers, they will install compilers and stuff, and the final diamond - vets-agent. 

While the vets-agent does not fully works, we are on hold.

This issue is not on critical path. I am running several agents (2.99, 2.100, 2.101) with in background.

What is really does not work is the getting task from ifs server.
I will submit a separate issue on that.

We have premium MS support as a last resort.

**Comment by bryanmacfarlane** [comment]
OK.  File a separate issue for getting tasks.  Include name resolution details and server notification url (in admin console).

Closing this since svc on 14.04 isn't supported.  I also added more docs for on-prem this morning.
