### ISSUE TITLE
Agent not able to download tasks from TFS 2015.1 and TFS 2015

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/vsts-agent#209]
This is because of we move task from deployment level resource to collection level resource.
@bryanmacfarlane do we want to support this?

**Comment by bryanmacfarlane** [comment]
What does it look like with our http client and this agent?  With node it wasn't a big deal.

I would like to support .1 but if it's not feasible, we can require QU2.

**Comment by bryanmacfarlane** [comment]
Dupe of #138
