### ISSUE TITLE
"git init" fails on windows when running as a service with "Local Service" account

### ISSUE THREAD

**Issue by stiliev** [Microsoft/vsts-agent#210]
"git init" fails on windows when running as a service with "Local Service" account. If I run with a different account or interactive, then the build works normally. Below is a console output from the error:

git init "D:\prj\vsts-agent2\_layout\_work\1\s"
error: unable to create directory for D:/prj/vsts-agent2/_layout/_work/1/s/.git/HEAD
Unable to use git.exe init repository under D:\prj\vsts-agent2\_layout\_work\1\s, 'git init' failed with exit code: 1
System.InvalidOperationException: Unable to use git.exe init repository under D:\prj\vsts-agent2\_layout\_work\1\s, 'git init' failed with exit code: 1

**Comment by bryanmacfarlane** [comment]
And this is independent of rtm coreclr drop?  You can repro with 2.101.0?

**Comment by stiliev** [comment]
Yes, this is independent of rtm coreclr drop. I can repro with latest on master (may be a few PRs newer than 2.101.0)

**Comment by bryanmacfarlane** [comment]
OK - good news for rtm core clr.

**Comment by stiliev** [comment]
Yesterday I was able to run one build when running as a service with "Local Service" account, but from a different folder on my drive. Need to do more research to narrow down when the issue happens.

**Comment by stiliev** [comment]
I hit another issue https://github.com/Microsoft/vsts-agent/issues/254 which gets on the way of this use case.
As per our talk with @patrickcarnahan and @TingluoHuang we will change the default windows service account during config to "Network Service" instead of "Local Service".

**Comment by bryanmacfarlane** [comment]
Isn't it really all the same issue?

**Comment by stiliev** [comment]
Talked with @patrickcarnahan about it. It seems to be because we store a key with an API in User specific storage. Then when we try to extract it, this API throws:
CngKey.Open(keyName, CngProvider.MicrosoftSoftwareKeyStorageProvider, CngKeyOpenOptions.UserKey)
Patrick mentioned he will try to fix it.

**Comment by stiliev** [comment]
It turned out this is a permission issue with the folder that I used to run the agent. I had to add a permission for the service account to read and execute and the issue was fixed. Permission should be set for all parent folders as well.
