### ISSUE TITLE
Disabled agent on server not handled correctly on agent

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#212]
Case 1:
Disabled in web admin UI (unchecked).
When I start the agent:
$ ./run.sh 
Scanning for tool capabilities.
Connecting to the server.
**The agent no longer exists on the server**. Please reconfigure the agent.
Failed to create session.

I think there's other cases where the agent exists but disabled and you configure a new agent.  Will try

**Comment by bryanmacfarlane** [comment]
Did it prompt you to replace the agent since it existed but in a disabled state?

**Comment by stiliev** [comment]
No, it did not prompt me. It just started the agent and there was no difference weather it is disabled or not.

**Comment by bryanmacfarlane** [comment]
I'll do some testing

**Comment by bryanmacfarlane** [comment]
Can't repro
