### ISSUE TITLE
Agent PER account

### ISSUE THREAD

**Issue by Mittchel** [Microsoft/vsts-agent#213]
Is the scope of the new vsts-agent on account level on Mac? So basically for each client I can create a different use account on the mac thus seperating the builds?

**Comment by bryanmacfarlane** [comment]
You can setup an agent per account or multiple agents on the same account in different directories.  It's self contained and xcopy bits.  The account is a security boundary - we store everything within that agent and account.  Even the credentials will be stored encrypted within the account once this PR comes in: https://github.com/Microsoft/vsts-agent/pull/97

Of course a machine boundary is even a better security boundary :)

Considerations are running as a service.  We run as LaunchAgents so even that is per account.  But you need to auto logon (and lock) - see service instructions.  We configure the service plist file (we create as a convenience) to run as the logged on user.  You could also create multiple agents in different directories under the same accounts logon but the plist says to run as a different user.  To do that you would have to create the plist, specify the user and ACL/chown the files and dirs.  

What are you after here?  What are your goals.
