### ISSUE TITLE
Handling SIGTERM on Linux

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#215]
I am running the agent in a docker container in unattended mode and it does not seem to respond to `SIGTERM` signal.  

The negative impact of this:

- default `docker stop` does not work well: takes longer to stop the container, eventually stopped by `SIGKILL`.

- when not using workaround, the `SIGKILL` leaves the agent in "zombie available state" for a while in VSTS which causes queuing issues.

- the workaround exists though a bit awkward and may not play well with container-based clusters (e.g. ACS, marathon etc).

### Details

This is what runs in docker container:

```
    # This saves the configuration in a file.
    echo "Configuring VSTS agent..."
    ./bin/Agent.Listener \
        configure \
        --unattended \
        --nostart \
        --agent ${VSTS_AGENT_NAME} \
        --auth ${VSTS_AUTH_TYPE} \
        --token ${VSTS_AUTH_TOKEN} \
        --pool ${VSTS_POOL} \
        --url ${VSTS_URL} \
        --acceptteeeula Y

    # This actually runs the agent.
    echo "Running VSTS agent..."
    exec ./bin/Agent.Listener \
        --unattended 
```

This is how I launch the container:

```
docker run \
    -d \
    --restart=on-failure:3 \
    -e VSTS_AGENT_NAME_PREFIX="some_prefix" \
    -e VSTS_AUTH_TYPE="PAT" \
    -e VSTS_AUTH_TOKEN="secret secret" \
    -e VSTS_POOL="some-pool" \
    -e VSTS_URL="https://company.visualstudio.com" \
    ${IMAGE_TAG}
```

This is the list of processes in the container, as you can see the agent is `PID 1` so all looks good:

```
UID        PID  PPID  C STIME TTY          TIME CMD
vsoagent     1     0  4 16:49 ?        00:00:01 ./bin/Agent.Listener --unattended
```

### Workaround

The agent seems to respond to `SIGQUIT` and `SIGINT`, shuts down gracefully and communicates to VSTS that it's offline.

For docker the workaround is to specify `--stop-signal=SIGQUIT` when launching the container, e.g:

```
docker run \
    --stop-signal=SIGQUIT \
    -d \
    --restart=on-failure:3 \
    -e VSTS_AGENT_NAME_PREFIX="some_prefix" \
    -e VSTS_AUTH_TYPE="PAT" \
    -e VSTS_AUTH_TOKEN="secret secret" \
    -e VSTS_POOL="some-pool" \
    -e VSTS_URL="https://company.visualstudio.com" \
    ${IMAGE_TAG}
```

**Comment by bryanmacfarlane** [comment]
Stan - should he be calling the host js file like our service does?

**Comment by stiliev** [comment]
Last time I checked SIGTERM could not be handled by .Net core app, but this may have changed with the latest corefx libraries that we use. There is a workaround we have: the root Linux service process is a bash process "runsvc.sh" (and not Agent.Listener), which converts SIGTERM signal to SIGINT.

**Comment by stiliev** [comment]
It looks .Net core handles SIGTERM, so we can add support in our agent
https://github.com/dotnet/coreclr/issues/2688

**Comment by stiliev** [comment]
I added code to handle SIGTERM on Linux in Agent.Listener and exit gracefully. PR is merged https://github.com/Microsoft/vsts-agent/pull/242
