### ISSUE TITLE
Enable non interactive configuration

### ISSUE THREAD

**Issue by giggio** [Microsoft/vsts-agent#221]
Right now the only way to configure the agent is interactively, with a human interacting with the console.
We need to be able to configure the agent by passing command line arguments.
The use of environment variables should also be allowed, so, for instance, if a variable, say, `AGENT_PAT` is set, you should use it (of course you would name such variables), and configuration should work without human interaction.

**Comment by giggio** [comment]
Right now, the only way to solve the problem is to use `expect`. I'd post a sample configuration script here, but there are special characters that would not translate. Even though this works, it is fragile, as it would break with any update to any message, etc. This issue still needs fixing.

**Comment by bryanmacfarlane** [comment]
Can you let us know what command line you attempted to run which did not work?

**Comment by giggio** [comment]
The script works. I would like to run `./configure.sh` without needing user interaction. For example (incomplete, just to get an idea):

````bash
./configure.sh --url https://foo.visualstudio.com --auth pat:adsflfsdjklasdjkldsafljk --interactive
````

Also, support for environment variables would be good. This would enable us to pass in the `PAT` without needing to type it on the terminal, which gets recorded into bash history. So, if a variable `AGENT_PAT` exists, there would be no need for `--auth`. But this is less important.

Also, please use the standard way of setting up command line options. See [docopt](http://docopt.org/) for more info.

The reason I am asking for this is for automatically provisioning agents.

**Comment by bryanmacfarlane** [comment]
The command line above isn't the right per the help.   --auth is for just the type, you need the token, --interactive is not an option and you need to pass the pool and agent name

Try 
```bash
./config.sh --help
````
or 

```bash
./bin/Agent.Listener --help
```

You will see
```bash
...
Unattend configuration.  Remember to check return codes
bin/Agent.Listener configure --url https://myaccount.visualstudio.com --agent myagent --pool default --nostart --auth PAT --token o4u5...

bin/Agent.Listener run
```

**Comment by giggio** [comment]
Ok, I was not aware I could pass arguments to it. It was what I was asking for. Tks, I will close the issue.

**Comment by bryanmacfarlane** [comment]
Great.  Let me know if you hit snags with unattended install.  It's one of the key things we wanted to be better at with this agent.
