### ISSUE TITLE
Config using loc key instead of messages ( Prompt0Default1 )

### ISSUE THREAD

**Issue by giggio** [Microsoft/vsts-agent#225]
The current release (v2.101.1 Preview) is generating several errors, making it impossible to configure.
Here is the output when configuring with args, unattended:

````
agentuser@6566cd252050:/agent$ ./bin/Agent.Listener configure --url https://uniobuild.visualstudio.com --pool Foo --auth PAT --token $AGENT_PAT --agent $(hostname) --unattended

>> EulasSectionHeader:

TeeEula


>> ConnectSectionHeader:

ConnectingToServer
The value cannot be null or empty.
Parameter name: value
````

This worked with the previous release.

If you try to configure manually, there are prompt errors, so one is not able to understand what to input. Here is the output:

````
agentuser@6566cd252050:/agent$ ./config.sh

>> EulasSectionHeader:

TeeEula

Prompt0Default1 >
````

What is `Prompt0Default1`?

The `--help` is also not working. Here is the output:

````
agentuser@6566cd252050:/agent$ ./config.sh --help
ListenerHelp
````

This is when running on Ubuntu 16.04, with all prerequisites installed as directed.

**Comment by bryanmacfarlane** [comment]
That looks like a loc key.  Eric?

**Comment by ericsciple** [comment]
@giggio can you check a few things (I chatted with @stiliev and got a few more ideas):
1) Can you confirm you followed [these steps](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/latebreaking.md#-ubuntu-1604) to install libicu52?
2) Can you verify you have the file `bin/en-US/strings.json` under your agent directory? and that it is not empty.
3) Can you tell me how your language environment variables are setup? `printenv|sort` and check GDM_LANG, LANG, LANGUAGE, LC_*. I'm not sure which one exactly CoreCLR is using, but we may have a problem with our fallback logic. I'll try and repro your exact scenario.

**Comment by abhimanyusinghal** [comment]
Facing same issue while using OSX Agent. When I try to configure I get following: 

```
>> EulasSectionHeader:

TeeEula

[Prompt0Default1 >

```

**Comment by bryanmacfarlane** [comment]
What's your language settings?

**Comment by giggio** [comment]
Hello there, @ericsciple 
1) Yes, I did.
2) Yes, it is there, and has lots of values.
3) Here is the output (removed some sensitive info):

````bash
$ printenv | sort
HOME=/home/agentuser
HOSTNAME=19f3102b6d01
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/agent
SHLVL=1
TERM=xterm
_=/usr/bin/printenv
````

As you can see, I don't have any of those `GDM_LANG, LANG, LANGUAGE, LC_*`.

**Comment by ericsciple** [comment]
@giggio Great! I was able to repro by unsetting my LANG env var.

As a workaround, can you try `export LANG=en_US.UTF-8` then `./config.sh`?

**Comment by giggio** [comment]
@ericsciple Yes, setting `LANG` fixes the issue.

**Comment by ericsciple** [comment]
@giggio thanks, for confirmation. I'll get a fix in for the next release drop. I'll leave this issue open for now so others can find the workaround.

If you still have other issues with unattended install, lets work through them on a separate issue. Thanks again for your help.

**Comment by bryanmacfarlane** [comment]
Fixed with https://github.com/Microsoft/vsts-agent/pull/230
