### ISSUE TITLE
Publish task does not preserve links

### ISSUE THREAD

**Issue by j0tt** [Microsoft/vsts-agent#229]
This is a bit obscure, so bear with me:

When using the publish task to copy an .app with a framework reference from a mac agent, symbolic links are lost (I believe). This manifests when downloading the .app artifact from VSTS and attempting to sign it with:

`codesign --force --sign [THUMBPRINT] --deep myapp.app`

This returns `bundle format is ambiguous (could be app or framework) in subcomponent: /path/to/dependent.framework`

We have worked around this issue by using our own copy task that calls a .sh which mounts a share, and then copies the artifacts with:
`cp -R folder/to/copy/to location/of/myapp.app`

According to http://www.delorie.com/gnu/docs/fileutils/fileutils_38.html -R verses -r:
"Copy directories recursively, _preserving non-directories_"

Note: when we used `copy -r` we had the same issue as the using the publish task.

Using the capital `R` argument allows me to sign the .app using codesign.

I believe using the `-a` argument would work as well, but I have not verified.

**Comment by ericsciple** [comment]
@j0tt Can you log an issue on the tasks repo? https://github.com/Microsoft/vsts-tasks/issues

**Comment by j0tt** [comment]
Done. Sorry about that.
