### ISSUE TITLE
Git repository does not exist or you do not have permissions

### ISSUE THREAD

**Issue by louisfischer** [Microsoft/vsts-agent#249]
We recently updated our TFS 2015 OnPrem instance to update 2. As a result, our build agents (on a separate build server) are no longer able to connect to the TFS instance. After further investigation, we discovered that the agents now use a new authentication module (FrameworkOAuthS2SAuthenticationModule) to connect to the server to download the git repository.

On a Windows Build Agent, this was the error messages:
2016-06-01T21:31:40.3462949Z ##[error]Response status code does not indicate success: 404 (Not Found).

On a OSX Build Agent, this was the error message:
06-06T02:01:52.4022550Z ##[command] git config gc.auto 0 2016-06-06T02:01:52.5159110Z ##[command] git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
remote: TF401019: The Git repository with name or identifier [Git Repository] does not exist or you do not have permissions for the operation you are attempting.

Before the upgrade, they agents connected using Windows authentication which worked flawlessly and the Cross-Platform agents used Basic authentication to connect. The vso-agent is being deprecated and no longer supports Basic Authentication.

The only way we have been able to get the agents to connect is to commit out the FrameworkOAuthS2SAuthenticationModule module. The new vsts-agent is replacing the vso-agent and needs that module in order to work.

**Comment by TingluoHuang** [comment]
@louisfischer have you ever modified the permission for "Project Collection Build Service" account?
![image](https://cloud.githubusercontent.com/assets/1750815/15810313/1b7d5c82-2b6b-11e6-8b85-280662dca294.png)
make sure that identity has read permission on the repository you are building.

**Comment by louisfischer** [comment]
@TingluoHuang Yes. That was one of the first things I checked. It just seems that the build agents cannot find the repository to clone the contents. I have been able to clone it outside of tfs using other git clients so I it can be accessed.

 i looked at the agents log and this is what I see

[2016-06-06 01:58:08Z ERR  Program] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()

**Comment by TingluoHuang** [comment]
@louisfischer are you able to give a Fiddler trace?

**Comment by TingluoHuang** [comment]
@louisfischer also please confirm your agent version?

**Comment by louisfischer** [comment]
@TingluoHuang we are using the latest preview...vsts-agent-win7-x64-2.101.1

**Comment by louisfischer** [comment]
Is there any plans to support Basic Authentication in the new Agent?
That would be one work around for this. The only vso-agent supported it and works.

**Comment by bryanmacfarlane** [comment]
If you do not have permissions, you will get the error message (does not exist - 404) for non disclosure.

Note this isn't an authentication issue.  It looks like you're authenticating fine.  After authenticating you it says you do not have permission (does not exist).

**Comment by TingluoHuang** [comment]
@louisfischer are you using vsts-agent-win7-x64-2.101.1 on a OSX build machine? it's a agent package for windows.

**Comment by louisfischer** [comment]
@bryanmacfarlane 	 You are right. The agent can listen for requests just fine.

It is when the build process starts and it is fetching the repository that is the problem.
It uses the Bearer token to as the authorization....
For some reason, the agent cannot download the repository using bearer token Authorization Header.

Here is the latest build log snipit

2016-06-06T13:53:27.4436140Z ##[command]git init "/Users/web/vsts-agent/_work/1/s" 
2016-06-06T13:53:27.4786380Z Initialized empty Git repository in /Users/web/vsts-agent/_work/1/s/.git/ 
2016-06-06T13:53:27.5575280Z ##[command]git remote add origin [Url to repository] 
2016-06-06T13:53:27.6731290Z ##[command]git config gc.auto 0 
2016-06-06T13:53:27.7961960Z ##[command]**git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin** 
2016-06-06T13:53:27.8518410Z remote: **TF401019: The Git repository with name or identifier [MyApplication] does not exist or you do not have permissions for the operation you are attempting.** 
2016-06-06T13:53:27.8527790Z **fatal: repository '[Url to repository]' not found**
016-06-06T13:53:27.9081080Z ##[error]Git fetch failed with exit code: 128
2016-06-06T13:53:27.9382310Z Cleaning extra http auth header from repository: [TfsGit] (TfsGit)


@TingluoHuang I have tried the vsts-agent-osx.10.11-x64-2.101.1.tar.gz on OSX and the vsts-agent-win7-x64-2.101.1.zip on Windows.... They both produce the same results in regards in not being able to download the repository Source Files.

**Comment by TingluoHuang** [comment]
@louisfischer can you show me your TFS admin version control setting's page? the one i pasted early, select the repository your build trying to clone instead of the root repositories.

**Comment by louisfischer** [comment]
Here is the sreenshots for the Root:  
The user is in that group highlighted..

![tfsrootcollection](https://cloud.githubusercontent.com/assets/1905010/15825617/2391a68a-2bca-11e6-9d2e-c7a813a77b2f.png)  
![tfsrepositorysettings](https://cloud.githubusercontent.com/assets/1905010/15825645/3c243a00-2bca-11e6-901f-68b46a653f89.png)

**Comment by TingluoHuang** [comment]
@louisfischer  not the group, but the user called "Project Collection Build Service (TeanFoundation)"

**Comment by louisfischer** [comment]
I do not see a user with that name in our tfs instance....

I do, however, see a user called "Project Collection Build Service" without the Team Foundation in parentheses. 

It seems that none of the "Project Build Service" Accounts and the "Project Collection Build Service" were in the "Project Collection Build Service Account" group. It through me off because of the GUID ids and the "Build\" domain. Once all the individual project service accounts were added, the agents were able to download the git source repository without any issue. 

![tfs build service accounts](https://cloud.githubusercontent.com/assets/1905010/15829631/237f6460-2bda-11e6-8030-7e66ec20f9a9.png)  

I'll close the issue. Thanks for the help..

**Comment by bryanmacfarlane** [comment]
I'll forward to a doc team to see if we can improve this.

**Comment by Chakri1082-2021** [comment]
Hi All, I am facing the same issue. I have provided the service connection in ADO pipelines but I still get the error 

remote: TF401019: The Git repository with name or identifier [my application] does not exist or you do not have permissions for the operation you are attempting.

I have also provided permissions under user setting as well. Still facing the issue

**Comment by CurlyBytes** [comment]
I Agree to @Chakri1082-2021  , the setup is self hosted vmss is not working on cloning the wiki in azure devops
