### ISSUE TITLE
Link to get latest release 

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#251]
There should be dedicated latest release links for each OS.
If anyone wants to install latest agent, they should just "wget link" to get latest release instead of "copying the link from releases"

**Comment by bryanmacfarlane** [comment]
We have this in the new acquisition experience in VSTS (download agent).  They just click a download button.  And in that case, it's not latest, it's approved stable version

**Comment by nigurr** [comment]
I would like to download through `cURL`, it's not possible to download right. A simple automation use case.

**Comment by bryanmacfarlane** [comment]
You can download through curl.  GitHub also has a rest api which is the correct way to discover all the releases.

**Comment by bryanmacfarlane** [comment]
https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by bryanmacfarlane** [comment]
https://api.github.com/repos/Microsoft/vsts-agent/releases

**Comment by nigurr** [comment]
Thanks
