### ISSUE TITLE
Behavior for command errors

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#275]
- Should command not found be a warning or an error?
- Should an incorrect value passed to a command be a warning or an error? e.g. ##set result "some unknown result value"
  - Current consensus is that it should result in a fatal error. And is the current implemented behavior in this agent.
- Should command failure result in an error, or only partially succeeded? e.g. upload file, upload test results, etc.
  - Should some commands be critical failure, and others be non-critical? i.e. hard-coded into each command.
  - Another option is that it could be driven by a parameter passed to the command. E.g. test task exposes a flag that indicates whether uploading the artifact is a critical failure.
  - A third option is to take a hard approach that all command failures are critical (current implemented behavior).

**Comment by bryanmacfarlane** [comment]
Actually, we discussed and we're not doing anything here.  My main two scenarios (logs, issues, etc...) are already best effort with retries and don't contribute to task result.  Test results to TCM would be the only other one and not worth complicating for that.  That can be task level option.
