### ISSUE TITLE
AndroidSigning task fails on Windows agent version 2.101.1 with TypeError: Path must be a string (but succeeds on VSTS hosted agent 1.100.4)

### ISSUE THREAD

**Issue by frankbuckley** [Microsoft/vsts-agent#288]
Using VSTS hosted agent, the task runs OK.

When run on a Windows machine with agent version 2.101.1, task fails with:

```
2016-06-11T13:22:10.1819897Z ##[section]Starting: Signing and aligning APK file(s) **\App.Android\bin\Release\*.apk
2016-06-11T13:22:13.4475916Z ##[error]TypeError: Path must be a string. Received undefined
2016-06-11T13:22:13.4475916Z ##[error]Return code: 1
2016-06-11T13:22:13.4475916Z ##[section]Finishing: Signing and aligning APK file(s) **\App.Android\bin\Release\*.apk
```

**Comment by bryanmacfarlane** [comment]
Very interesting.  Task is likely doing something fragile.  New agent is stricter about boundaries with out of proc etc

**Comment by bryanmacfarlane** [comment]
We will fix

**Comment by frankbuckley** [comment]
Turns out JAVA_HOME and ANDROID_HOME were not defined on the build server, but AndroidSigning requires them.

Thanks.

**Comment by bryanmacfarlane** [comment]
Thanks.  In the preview that's about to drop anyday (2.102.0) when you run as a service, I snapshot interesting env vars like those into a file and the service loads when it runs.  As long as they were defined in your interactive console when you configured, it would be good.

I also think there's a bug here.  If those aren't defined then the task should output a helpful message.  Can you log an issue in the vsts-tasks repo?

**Comment by frankbuckley** [comment]
Looks like error messages have been improved in recent changes: https://github.com/Microsoft/vsts-tasks/pull/1741 (the version of AndroidSigning we are getting in production is 1.0.19).

**Comment by bryanmacfarlane** [comment]
Great.  Thanks for confirming.
