### ISSUE TITLE
Add ability to download specific artifacts per environment

### ISSUE THREAD

**Issue by 501st-alpha1** [Microsoft/vsts-agent#291]
I have a VSTS build that produces 2 artifacts, each of which are destined for a different release environment. However, I have noticed that **both** artifacts are downloaded in every environment, which obviously slows down my release build.

I looked through the options (and even a bit of [the source code](//github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Release/ReleaseJobExtension.cs#L118)), and it looks like there is only an option to disable the downloading of **all** artifacts on a given environment.

Can an option be added to allow us to specify which assets should be downloaded to a given release environment?

**Comment by bryanmacfarlane** [comment]
Not specifically an agent issue (although agent would have to react to server support).  Assigning to Sriram for RM consideration.  Will shoot a mail to RM team

**Comment by GitHubSriramB** [comment]
Thanks for the suggestion. We have this feature request in our backlog. Will let you know once we have this support in place.

**Comment by cryptomatt** [comment]
Has there been any progress on this ? Multiple artifacts being downloaded when not required for that particular phase is causing the build to slow down especially for on premise build agents

**Comment by GitHubSriramB** [comment]
@cryptomatt - No. We have not added this support to the product yet. Apologies for the delay.
