### ISSUE TITLE
Wrong collection url when trying to run build with TfsVersionControl

### ISSUE THREAD

**Issue by PawelKm** [Microsoft/vsts-agent#297]
Collection url seems to be damageded at the start of build when using tf.
Using:

- Ubuntu 14.04
- TFS 2015 update 2.1
- vsts-agent 2.102.0

I have server at adderss similar to http://my-server-ngi-tfs.country.company.com:8080/tfs
When running build it results in exception:
Unknown host my-server-ngi-tfs

[Here](https://github.com/Microsoft/vsts-agent/files/314277/log.txt) you have full log.

Please notice significant difference between http://my-server-ngi-tfs:8080/tfs and http://my-server-ngi-tfs.country.company.com:8080/tfs. 
Noticed that in file SourceFolder.json this address is wrong as well.

**Comment by ericsciple** [comment]
@PawelKm if you log on one of the TFS AT machines and launch TFS Mgmt Wizard, what is the notification URL configured as?

**Comment by bryanmacfarlane** [comment]
@PawelKm - can you get to Eric's question?

**Comment by PawelKm** [comment]
Sorry for such late response! 

Notification url is: 
http://my-server-ngi-tfs:8080/tfs

I've changed it to:
http://my-server-ngi-tfs.country.company.com:8080/tfs

and now it doesn't even produce log, build fails right a way. 

Maybe my setup is somewhere damaged cause I've had configured this agent with different tfs server and it works ok.

**Comment by ericsciple** [comment]
@PawelKm can you check the _diag folder of the agent. Is a worker diag log produced for the job? e.g. Worker_20160623-220848-utc.log

If not, check the agent log to see if it's actually getting the job message when you queue the build or if it's failing server-side before it ever reaches the agent. (agent listens for jobs, spawns a worker process to handle the job)

**Comment by PawelKm** [comment]
Log says now: 
VS30063: You are not authorized to access

It is surprising because both tfs servers are using the same AD authentication and I use for both the same credentials. Checked that in both servers account that I am using is added as pool administrator and pool service account. I think that this is configuration issue now rather than issue with agent itself cause I've managed to get it working with different server. I will try to reconfigure it.

**Comment by bryanmacfarlane** [comment]
I would recommend creating a clean directory with a clean new agent (2.102.1 just dropped).

**Comment by ericsciple** [comment]
I talked with @TingluoHuang, we have an idea how to avoid this issue in the future. However, I have some concerns, I want to discuss with other folks as well.

**Comment by TingluoHuang** [comment]
#357 will fix this issue.
