### ISSUE TITLE
Update to value of variable is not honored for release definition

### ISSUE THREAD

**Issue by mthalman-msft** [Microsoft/vsts-agent#299]
Any task that has an input which makes use of a user-defined variable always gets the initial value of the variable when it was originally defined.  If the user makes a change to the variable's value and deploys a new release, that new value is not used; it always uses the original value.  This only affects release definitions, not build definitions.

Repro:
1. Create a new release definition.
2. Define a new variable named "Cmd" with a value of "c:\boo.exe".
3. Add a "Command Line" task to the definition.
4. For the task's Tool input value, use the value "$(Cmd)".
5. Save the definition.
6. Create a release.
7. Go back to the variable and change its value to "c:\boo2.exe".  Save.
8. Create another release.
9. Look at log of the release and notice the output mentions "c:\boo.exe" instead of "c:\boo2.exe".

**Comment by bryanmacfarlane** [comment]
Is this an agent issue?  Does it only repro with this new agent?

**Comment by ericsciple** [comment]
pinging Sriram/Kalyan on email..

**Comment by ericsciple** [comment]
@mthalman-msft did you repro on this agent (2.x version) or on the old Windows agent (1.x version)?

**Comment by GitHubSriramB** [comment]
When a release is created, a snapshot of all the variables available in the Release Definition is taken. From then on, any changes to variables in the release definition would not affect the variables in the release.

If you need to change value of variable in a release, you would need to create release in draft & then change the variable. This change will be applicable only for the particular release.

**Comment by mthalman-msft** [comment]
Huh, this appears to no longer repro.
