### ISSUE TITLE
'Failed to create session' error

### ISSUE THREAD

**Issue by tomlee** [Microsoft/vsts-agent#300]
Hello

Whenever I execute run.cmd, the error "`Failed to create session.`" occurs. When I re-run it, this error always occurs; I cannot replace it because the error occurs before asking me to replace. I need to delete the whole directory and re-setup the agent.

Please check if it's a bug or my mis-configuration.

Thomas

```
PS C:\myagent> .\run.cmd

>> Connect:

Enter server URL > https://xyz.visualstudio.com
Enter authentication type (press enter for PAT) >
Enter personal access token > ****************************************************
Connecting to server ...
Saving credentials...

>> Register Agent:

Enter agent pool (press enter for default) > OnPrem
Enter agent name (press enter for XYZAGENT) >
Scanning for tool capabilities.
Connecting to the server.
Enter replace? (Y/N) (press enter for N) > y
Successfully replaced the agent
Enter work folder (press enter for _work) >
2016-06-15 15:15:02Z: Settings Saved.
Enter run agent as service? (Y/N) (press enter for N) > n
Scanning for tool capabilities.
Connecting to the server.
Failed to create session.
PS C:\myagent>
```

**Comment by TingluoHuang** [comment]
@tomlee what's your agent version? can you send us your agent diag log? those log are located at _diag folder of the agent.
BTW, base on the snapshot you past, you are able to replace the agent.
`Enter replace? (Y/N) (press enter for N) > y`
`Successfully replaced the agent`

**Comment by tomlee** [comment]
I was able to replace it only after I had deleted the whole directory c:\myagent and set it up again. Otherwise, the " Enter replace?" wouldn't come out when I reran run.cmd because the "Failed to create session" stopped the command before the prompt occurred. How should I send you the log file? Does it contain sensitive info? Is it okay attach the file here?

**Comment by TingluoHuang** [comment]
@tomlee all sensitive info should already be masked out, you can double check before you past here. :)

**Comment by tomlee** [comment]
Attached please find the log file for your investigation. Thank you.

[Agent_20160615-151402-utc.zip](https://github.com/Microsoft/vsts-agent/files/316498/Agent_20160615-151402-utc.zip)

**Comment by TingluoHuang** [comment]
@tomlee you are using a older preview version of the agent, please try the latest version 2.102.0.

**Comment by bryanmacfarlane** [comment]
Should use >= 2.102.0

**Comment by tomlee** [comment]
I downloaded the package at the link on VisualStudio.com. Does it point to the old version?

Thomas

![image](https://cloud.githubusercontent.com/assets/227776/16120772/4ed8d402-3413-11e6-8dbb-33c94208c478.png)

**Comment by tomlee** [comment]
Anyway, I switched back to use the original closed source version. 

Thomas

**Comment by bryanmacfarlane** [comment]
It just points to here:  https://github.com/Microsoft/vsts-agent/releases 

Get it there.
 
It would be great if you could try out 2.102.0 so we can close on whether there's a bug here.  We would appreciate it!

**Comment by tomlee** [comment]
It seems not. I clicked the download button again and the browser downloaded vsts-agent-win7-x64-2.100.1.zip. You may need to fix this link.

I'll try out the new version later when I have time. (I have already de-registered and deleted this preview agent.)

![image](https://cloud.githubusercontent.com/assets/227776/16121328/6b5e7120-3415-11e6-952d-80f675ead62c.png)

**Comment by bryanmacfarlane** [comment]
Right, you don't have this sprints rollout.  Per above, go here: It just points to here: https://github.com/Microsoft/vsts-agent/releases

**Comment by bryanmacfarlane** [comment]
We can't repro this.  Please reactivate if you can repro with >= 102 and add logs
