### ISSUE TITLE
Agent Shows "Red" on Agent Pools screen ONLY when running as service (runs fine interactively)

### ISSUE THREAD

**Issue by chrispont** [Microsoft/vsts-agent#306]
If I run the agent using ./run.sh the agent shows in the portal as green.
If I run ./svc.sh install to install the service and then run ./svc.sh to ensure the service is running, the agent still shows in the portal as red.

I've installed this agent on a few machines and never had this issue before.

**Comment by TingluoHuang** [comment]
@chrispont can you run `ps` print out all running process?

**Comment by bryanmacfarlane** [comment]
Also, which OS are you using?  Both options to run as a service (plist launchagent on OSX, systemd unit file on Linux) have logs which you should check.  The .service file has the location of those files and those files specify where the logs are.

A typical cause is if two instances of the agent are running with the same name - one will 409 conflicts until the other one stops.

Can help 
```bash
ps aux | grep Agent.Listener 
```

**Comment by chrispont** [comment]
Thanks for your help!

Output from the above gives me the following...

`admin            17664   0.0  0.0  2434840    764 s000  S+    8:21PM   0:00.00 grep AgentListener`

It's running on Mac OSX (El Capitan). If I check the directory from the launchagent plist (StandardOutPath and StandardErrorPath) it's actually empty. There's no log files or anything.

Anything else I can check?

**Comment by chrispont** [comment]
OK, problem solved. I removed the old agent, installed a new one with a different name (I did try and replace the old agent under the same name and this didn't solve the problem) and suddenly theres a green mark next to the new agent name. 

Thanks for your help anyway.

**Comment by bryanmacfarlane** [comment]
Thanks
