### ISSUE TITLE
OSX LaunchAgent: security: cert import failed: write permissions error

### ISSUE THREAD

**Issue by candril** [Microsoft/vsts-agent#308]
As described here https://github.com/Microsoft/vso-agent/issues/269 without a `<key>SessionCreate</key>` in the plist of the launch agent, identies cannot be imported to the key chain. PR #301 removes the flag from the plist file.

Is there another way to configure the agent to support access to the key chain?

**Comment by bryanmacfarlane** [comment]
Did you try it with this agent?

It was removed because we did a lot of testing and it introduced problems in testing and with at least El Capitan and above, it's not needed for signing and the key chaining.  This agent is only configured as LaunchAgent (not LaunchDaemon) so it's not needed - you have to be logged on with a session.

**Comment by candril** [comment]
Yes, I've tried it with the "new" agent (v2.102.0) and experiencing this issue.
In the build step I'm referencing the certification as p12 file.

**Comment by JKennedy24** [comment]
Would this bug also affect my Xamarin.iOS build. I am getting "User interaction is not allowed" for my build. It looks to be access to the keychain and after trying everything from [this stackoverflow post](http://stackoverflow.com/questions/20205162/user-interaction-is-not-allowed-trying-to-sign-an-osx-app-using-codesign) I still cant get it to work. I'm guessing its linked to this?

**Comment by bryanmacfarlane** [comment]
@candril and @JKennedy24 - please list versions of OSX and Xcode along with any other details you can think of to ensure @madhurig can repro

We've had a mix of needs sessioncreate and sessioncreate breaks.  So, I want to make sure we're crisp

**Comment by JKennedy24** [comment]
@bryanmacfarlane I'm not sure whether it is linked to this issue but it seems it may be. I am trying to build my `Xamarin.iOS` application on my physical mac machine using:
Build agent version RC v2.102.0 
Mac running OSx
Xcode version is 7.3.1
Xamarin version is the latest. 

I am getting "User interation not allowed" when trying to run my build definition and my build logs are 
[here](http://www.filedropper.com/4buildxamariniossolutionfieldstrikefieldstrikemovefieldstrikemovesln)

StackOverflow post is [here](http://stackoverflow.com/q/37946136/2987066)

**Comment by JKennedy24** [comment]
Note: from the stackOverflow post it was suggested I try running the build agent in interactive mode instead of as a service and this worked! not sure what the root cause / bug is there though

**Comment by candril** [comment]
Build agent version: v2.102.0
OSX version: El Capitan 10.11.5 (15F34)
XCode version: Version 7.3.1 (7D1014)

Running in interactive mode resolves the issue for me too.

**Comment by chrisrpatterson** [comment]
You can also unlock the key chain.

**Comment by chrisrpatterson** [comment]
@JKennedy24 this is not a bug it is a feature of how OSX works.  You either have to be interactive or unlock the keychain.

**Comment by JKennedy24** [comment]
I tried to unlock the keychain. and I'm pretty sure I did but it still wouldn't work. Although I'm not a Mac expert so possibly could have done it wrong

**Comment by madhurig** [comment]
@candril: Can you please send me the debug log from your build failure (you can email me at madhurig at Microsoft dot com)? I have same version of agent, OSX, Xcode and can run my agent as service without the errors you are seeing. Do you see any popup when you are running the agent interactive or as a service?

**Comment by bryanmacfarlane** [comment]
@candril Any update on @madhurig request?
