### ISSUE TITLE
Unsure of authentication credential format

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-agent#310]
**Agent version and platform**
Agent version: vsts-agent-osx.10.11-x64-2.102.0.tar.gz
Agent OS: OS X El Capitan
<br>
**VSTS type and version**
visualstudio.com
<br>
**What's not working?** 
I'm unsure of the required format of the credentials required for the Negotiate authentication type. I'm seeing the following:
```
Connecting to server...
Moved Permanently
Failed to connect. Try again or ctrl-c to quit
```
I've tried:
DOMAIN\user
DOMAIN\user@domain.com
user@domain.com
user

None of those combinations seem to work
<br>
**Agent and Worker's diag log**
No log. Config issue.

**Comment by TingluoHuang** [comment]
@jsauvexamarin You can't use Negotiate for VisualStudio.com account, PAT is the only support authentication way.

**Comment by TingluoHuang** [comment]
DOC: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/configvsts.md

**Comment by jsauvexamarin** [comment]
The newest version (v2.102.0 Release Candidate 1) prompts for Negotiate as the default authentication method. The docs ought to be updated to reflect this for newcomers, particularly for those who are using hosted VSTS.
