### ISSUE TITLE
Documentation - Need sudo to install service on *NIX

### ISSUE THREAD

**Issue by steji113** [Microsoft/vsts-agent#311]
**Agent version and platform**
1. version of your agent? 2.102.0 RC 1
2. OS of the machine running the agent? OSX
<br>
**VSTS type and version**
1. visualstudio.com or On-Prem TFS? On-Prem TFS
2. if On-Prem TFS, which release, 2015 RTM/QU1/QU2? 2015 QU2
<br>
**What's not working?**
On the NIX service install docs (docs/start/nixsvc.md), sudo seems to be necessary to run the following command properly and get the directory permissions set correctly:
`./svc.sh install`

**Comment by bryanmacfarlane** [comment]
It says that at the top of the page under key points

**Comment by steji113** [comment]
I saw that, but it also says "OSX does not." This doesn't seem consistent with the behavior I saw. It seems sudo is required for all operations, so it may be helpful to just include sudo before the ./svc.sh install command to help people who simply copy and paste these items.

**Comment by bryanmacfarlane** [comment]
OSX should not be run as sudo.  It creates a LaunchAgent which is scoped to the user (~/Library/LaunchAgents).
