### ISSUE TITLE
Auto-update resiliency on Windows

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#315]
Auto-update on Windows can fail to move downloaded dir due to anti-virus.

Reported by a customer who worked with CSS to diagnose. The failure was correlated to anti-virus.
>During the unsuccessful update test, the  ProcMon logs show a lot of mcshield.exe entries accessing items in the “D:\\Agent\\_work\\_download\\\*.\*” path.  
During the successful update test, the  ProcMon logs show no mcshield.exe entries accessing items in the “D:\\Agent\\_work\\_download\\\*.\*” path.

Relevant excerpt from _update._20160610-135207-135200_1.log:
```
Waiting for vsoAgent.exe (6028) to complete 
Copying files 
move "D:\agent\agent" "D:\agent\agent.old" 
        1 dir(s) moved.
move "D:\agent\_work\_download\agent" "D:\agent\agent" 
Access is denied.
        0 dir(s) moved.
Can't move "D:\agent\_work\_download\agent" to "D:\agent\agent"  
```

This was reported on the old Windows agent, but the problem likely (almost certainly) exists in this repo as well.

I discussed with @TingluoHuang. It sounds like we're under a time constraint, so falling back to copy (given the current constraint) is out of the question. That leaves a couple options:
1) Retry the move (probably wouldn't help).
2) Replace `bin` folder (was `agent` in the old Windows agent) with a junction point to wherever the new binaries are extracted (e.g. could be `bin-2.102.0`).
3) Use transactional file system API, if it fails then can retry next time. If the download folder is skipped if it already exists, by the time it runs again, the anti-virus program would likely be finished scanning the files.

A workaround exists: add an anti-virus exclusion on the folder.

**Comment by bryanmacfarlane** [comment]
It's a good point to add virus exception for not only the work folder but also the agent folder.  I'll remember that for my other next steps issue

**Comment by ericsciple** [comment]
Closing. Duplicate of https://github.com/Microsoft/vsts-agent/issues/384
