### ISSUE TITLE
Cannot run agent as Service on Mac - "Path had bad ownership/permissions"

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#317]
## **Agent version and platform**
Mac RC v2.102.0
OSX..
## **VSTS type and version**
On Prem TFS
If On-Prem TFS, which release, 2015 RTM/QU1/QU2? - Not Sure
http://gmpsoftware.visualstudio.com
## **What's not working?** 
Cannot run the agent as a service on Mac.
I can run `./svc.sh install`
but when i call `./svc.sh start` it get an error message saying:
> Path had bad ownership/permissions

![a](https://cloud.githubusercontent.com/assets/9284438/16225791/49ffbafa-37a0-11e6-9919-d140985cfb38.png)

**Comment by bryanmacfarlane** [comment]
sudo ./svc.sh start is the issue.

Per docs: SystemD requires sudo so all scripts below must be called with sudo. OSX does not.

yesterday I checked in changes that will block sudo on OSX.

**Comment by JKennedy24** [comment]
@bryanmacfarlane Thanks bryan. You are correct running the script without sudo worked

**Comment by bryanmacfarlane** [comment]
Great thanks for confirming.  Next drop will have better guidance.

**Comment by bryanmacfarlane** [comment]
Opening until I fix the docs.  I have a branch and I'm waiting on .1 to drop very soon

**Comment by bryanmacfarlane** [comment]
2.102.1 drooped and docs updated

**Comment by georgeslegros** [comment]
Hi there,

Sorry to re-open this but I get the exact same issue even when I do not use sudo.
Any other reasons that might cause this?

Thanks,
