### ISSUE TITLE
Old powershell task fails if working folder is set to `$(Build.SourcesDirectory)`

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#331]
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>

All my TFVC tasks are giving me: 
 
![image](https://cloud.githubusercontent.com/assets/4173387/16345980/320a1542-3a45-11e6-9f31-e99b08f80869.png)

It seems to do so even before reaching my own code. 

I suspect this line is causing it:
https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/vsts-tfvc-checkin/task.json#L190

Removing the offending line seems to solve the issue.

## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[Worker_20160624-174728-utc.txt](https://github.com/Microsoft/vsts-agent/files/332231/Worker_20160624-174728-utc.txt)

**Comment by bryanmacfarlane** [comment]
This is interesting ... shouldn't fail.  Never liked the working folder in json but we shouldn't fail on it

**Comment by jessehouwing** [comment]
It seems that certain things work just fine, like $(currentDirectory), but this variable fails in an interesting way.

What's the recommended alternative?

**Comment by TingluoHuang** [comment]
#347 will fix this.
