### ISSUE TITLE
VSTS returns Access Denied when connecting back to VSTS using Client Object Model

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#332]
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? Win10
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots

My TFVC tasks use the Client Object Model to connect back to VSTS. They use the following code to retrieve the credentials:
https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/vsts-tfvc-shared/vsts-tfvc-shared.psm1#L118

This has worked until now. It doesn't in the new agent and instead returns:

![image](https://cloud.githubusercontent.com/assets/4173387/16346085/d7361ffc-3a45-11e6-9066-b16f4ef0ceef.png)

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 
[Worker_20160624-174728-utc.txt](https://github.com/Microsoft/vsts-agent/files/332243/Worker_20160624-174728-utc.txt)

**Comment by jessehouwing** [comment]
Enabling Oauth token access doesn't improve things.

**Comment by jessehouwing** [comment]
As per @ericsciple, this works as a workaround (confirmed)
```
    $tfsClientCredentials = New-Object Microsoft.TeamFoundation.Client.TfsClientCredentials($false)
    $tfsClientCredentials.AllowInteractive = $false
    $tfsClientCredentials.Federated = (New-Object Microsoft.TeamFoundation.Client.OAuthTokenCredential([string]$endpoint.Authorization.Parameters['AccessToken']))
```

**Comment by bryanmacfarlane** [comment]
Great - we'll fix the cmdlet in the next drop

**Comment by jessehouwing** [comment]
Still not entirely sure if this code works against an on premise TFS server. Or why it does. Will it fall back to ntlm if that still available?

**Comment by bryanmacfarlane** [comment]
In Dev15, ntlm is only for config/registering the agent.  After that we get an oauth token which is used to listen to the queue and each build generates an oauth token.  the account the agent/service runs as should largely be irrelevant with one exception - publish/cleaning up UNC shares.

**Comment by ericsciple** [comment]
@jessehouwing - fyi - NTLM isn't required for the build identity in on-prem for the extended client, even in Dev14 (I confirmed in on Dev 14 U2, haven't tried on RTM). The OAuth token is for the built-in Project Collection Build Service / Project Build Service account. It uses a Bearer authentication header.

**Comment by jessehouwing** [comment]
Just out of pure curiosity... is it that it sends the bearer token without prompting that IIS is able to skip the whole NTLM business?

**Comment by ericsciple** [comment]
Sorry, I'm not sure why IIS allows it through without initiating an NTLM challenge (even with anonymous disabled). My guess is the same as yours - because an auth header is present.

**Comment by chrisrpatterson** [comment]
From the perspective of IIS this request is already authorized so it passes it through to the application.

**Comment by ericsciple** [comment]
Fixed https://github.com/Microsoft/vsts-agent/pull/363
