### ISSUE TITLE
Debug logging is hard to read due to the meta-debug-logging

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#334]
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? Win10
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>

Due to the fact that the Write-Vststask[Debug|Warning|verbose|etc] each log a bunch of lines themselves, the logs are very hard to read. It'd be very helpful when the standard logging functions wouldn't be as verbose as they are at the moment:

![image](https://cloud.githubusercontent.com/assets/4173387/16351059/1e80dee8-3a63-11e6-84f4-92126a1655af.png)

The lines in red don't add to the understanding of the logs for me as a user.

## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@jessehouwing  If you set system.debug=false, you would not get those debug trace anymore.

**Comment by bryanmacfarlane** [comment]
Agreed.  Those lines seem like tracing in the _diag logs.

**Comment by jessehouwing** [comment]
@TingluoHuang agreed, but then I wouldn't see my own Write-VSTSTaskDebug / Write-Debug lines either, right?

**Comment by TingluoHuang** [comment]
@bryanmacfarlane I prefer still keep one line of tracing, currently there are 2 lines, i will remove one of them. We used to have customer complains about they have no idea of whether their ##vso command been executed or not in the old windows agent.

**Comment by bryanmacfarlane** [comment]
@TingluoHuang - that's fine.
