### ISSUE TITLE
Agents no longer working after upgrade from 1.95.0 to 1.95.3 (TFS 2015 Update 3)

### ISSUE THREAD

**Issue by michielrutting** [Microsoft/vsts-agent#345]
## **Agent version and platform**
Version of your agent? 1.95.3
<br>
OS of the machine running the agent? Windows Server 2012 R2
<br>
## **VSTS type and version**
On-Prem
<br>
Team Foundation Server 2015 Update 3
<br>
## **What's not working?** 
Agents are no longer running builds and releases after updating TFS from Update 2 to Update 3. 
The agent is now version 1.95.3. The previous version was 1.95.0. 
The build fails before it has done any work. Worker log is no longer generated. (Re-)Configuration via ConfigureAgent.cmd registers the agent fine and doesn't result in any errors. The agent is running under a domain account that has the nescessary rights in TFS. 
<br>
## **Agent and Worker's diag log**

I've attached a redacted agent log, but looking at it the most likely cause seems to be this error:
13:38:09.433482 JobInfo.ctor
13:38:09.433482 JobInfo.ctor - leave
13:38:09.433482 JobManager.StartJob - calling JobWriter.StartJob
13:38:09.433482 JobWriter.StartJob - enter
13:38:09.433482 JobWriter.StartJob - (SKIPPING)first renew
13:38:09.667136 JobWriter.StartJob - start continual renewing
13:38:09.667136 AuthorizationType : OAuth
13:38:09.713970 ---------------------------------------------------------------------------
13:38:09.713970 Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found

13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)

13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__79.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__76`1.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ConnectionHelper.GetConnection(Uri serverUri, VssCredentials credentials)

13:38:09.713970    at Microsoft.TeamFoundation.DistributedTask.Agent.JobWriter.StartJob()
13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)

13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__79.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__76`1.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()

13:38:09.713970 --- End of stack trace from previous location where exception was thrown ---

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

13:38:09.713970    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

13:38:09.713970    at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ConnectionHelper.GetConnection(Uri serverUri, VssCredentials credentials)

13:38:09.713970    at Microsoft.TeamFoundation.DistributedTask.Agent.JobWriter.StartJob()
13:38:09.713970 ---------------------------------------------------------------------------
13:38:09.713970 Process logging event with context handler.
13:38:09.713970 BaseLogger.LogConsoleMessage(scope.JobId = c532af07-8d69-4510-b654-c07c09ec1756, message = ##[error]The Agent failed to start this job. Error: Not Found)
13:38:09.713970 JobManager.LogConsoleMessage (scope.JobId = c532af07-8d69-4510-b654-c07c09ec1756, message = ##[error]The Agent failed to start this job. Error: Not Found)
13:38:09.713970 JobManager.LogConsoleMessage - message enqueued
13:38:09.713970 [90899c62-f2d3-47a1-b38c-fe7abe9bff34][c532af07-8d69-4510-b654-c07c09ec1756]##[error]The Agent failed to start this job. Error: Not Found
13:38:09.713970 JobManager.FinishJob(jobId = c532af07-8d69-4510-b654-c07c09ec1756, result = Failed)
[agent_20160629-124411-utc.txt](https://github.com/Microsoft/vsts-agent/files/339426/agent_20160629-124411-utc.txt)

**Comment by TingluoHuang** [comment]
@michielrutting Can you send us a Fiddler trace while you hitting this error?
and provide me more detail information.
1. are you upgrade form 2015 update 2 or update 2.1?
2. where did you get the update 3 build? since we haven't release it? is that a preview or RC?

**Comment by michielrutting** [comment]
Hello Ting,

1. We upgraded from Update 2.
2. We downloaded the update from MSDN subscriber downloads (iso version). As far as I can tell it was actually released 2 days ago. See [https://www.visualstudio.com/news/releasenotes/tfs2015-update3-vs](url)

I will try to get a Fiddler trace tomorrow morning (am in Europe). I'll have to see how to set proxy variable as it's running as a service.

If there is a proper support channel for the version of the agent we are using I'd be happy to file an issue there as well.

**Comment by ericsciple** [comment]
Can you check the notification URL? See *Team Foundation Administration Console*, *Application Tier*.

The agent listens to the message queue using the URL that it was configured with. However, when a job message is pulled from the queue, a job connection is initialized using the notification URL.

**Comment by michielrutting** [comment]
Thanks Eric, that pointed me in the right direction. 

Our tfs and build server are in an extranet domain. The notification URL (http://vstfs.ourcompany.com) is different from the urls servers use within the extranet (http://vstfs.extranet.local). All requests from outside the extranet to the tfs server using the notification url pass through a TMG server which then sends the request to the correct server using the extranet.local name. 

However, the build server also being inside the extranet can't resolve vstfs.ourcompany.com and the tfs server only accepts requests on vstfs.extranet.local. So in order to get everything working we had to teach the build server where find the notification url by adding an entry to the hosts file and we had to add a binding in IIS on the TFS server so it would accept requests the notification url.

Upgrading the TFS server has removed the added binding and the TFS server was no longer accepting requests on the notification URL.

If we'd change the notification to vstfs.extranet.local (instead of using the hosts file and binding) the build server would be able to start the job, but then subsequently fail when trying to get files from the repository, because when the build template was created using the web interface using the vstfs.ourcompany.com url it will try to find the repository on that url. If you'd create the build template from within the extranet (f.ex. by remoting into the build server and using a browser and navigating to vstfs.extranet.local/tfs) the build would work. But having to remote into a server create and edit working build templates doesn't feel right.

I'm interested in finding out if there's a better solution, given the network setup we have. If you know a place where I can report our situation and issues to the appropriate people I'd be happy to do so.

**Comment by bryanmacfarlane** [comment]
One piece of good news is that the agent in this repo will replace the one you are using in the TFS.vnext release.  We made changes in this agent to ensure you don't have to connect via the notification URL.  It's does matter what the agent knows the server by.  As long as it resolves and it can reach the server, it will work.  We basically use the hostnane you use to config with the server for further communication

**Comment by ericsciple** [comment]
Closing this issue. It sounds like you're unblocked. The same solution you applied prior to update 3 sounds like the best option for now. As Bryan mentioned, we're fixing this in the next agent.
