### ISSUE TITLE
Should be able to switch between running as a service and interactively easily

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#349]

**Comment by ericsciple** [comment]
For troubleshooting, should be able to switch between running as a service and running interactively.

Anything preventing that - aside from the explicit validation check which needs to be removed - should be addressed. For example, need to verify no file-owner issues stand in the way.

**Comment by bryanmacfarlane** [comment]
On all platforms, it's typical to have an issue when running as a service.  Our first question is, does it work interactively?  Well, that should be easy.  Stop service, start interactive.  Shouldn't not block and require reconfigure.  409 conflict will already prevent scenario where you try and run two instances for an agent.
