### ISSUE TITLE
Domain Joined Linux agent, clean under the repository tab has not effect

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-agent#351]
## **Agent version and platform**
Version of your agent? 2.102.1
<br>
OS of the machine running the agent? CentOS 7.2
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? On-Prem
<br>
If On-Prem TFS, which release? 2015 QU3

<br>
## **What's not working?** 
Under the repository tab when clean is set to false,  on Windows only changes are downloaded.  On Linux, however, this setting appears to do nothing.  No matter what, the workspace is deleted and all source code is redownloaded and everything must be rebuilt.
<br>

**Comment by TingluoHuang** [comment]
@bbusacker is your repository a TFVC or GIT?

**Comment by bbusacker** [comment]
TFVC

**Comment by bryanmacfarlane** [comment]
clean on the repo tab should do scorch

**Comment by bbusacker** [comment]
When clean is turned off it still does   Scorch when interfacing with the Linux agent.

Sent from my iPhone

On Jun 30, 2016, at 3:50 PM, Bryan MacFarlane <notifications@github.com<mailto:notifications@github.com>> wrote:


clean on the repo tab should do scorch

-

**Comment by ericsciple** [comment]
Can you send ersciple the worker log from the _diag directory at the root of your agent (at microsoft com)?

**Comment by bryanmacfarlane** [comment]
@bbusacker - any update here?

**Comment by ericsciple** [comment]
I forgot to update the thread here with context (got sidetracked). From what I can tell from the worker logs, it *looks* like @bbusacker is domain-joined and TEE is associating the fully-qualified machine name with the workspace. The agent is comparing against the unqualified machine name, finding it not to match, deleting the workspace, and creating a new workspace every time.

I'm waiting to hear confirmation that what I'm interpreting from the worker diag log sounds accurate. If so, there are a couple different ways this could be fixed.

**Comment by bbusacker** [comment]
Yes, the machine is joined to a domain through LDAP.

**Comment by ericsciple** [comment]
From TEE source code, it looks like you can set this environment variable before running the agent: `export JAVA_TOOL_OPTIONS=-DcomputerName="MYCOMPNAME"`

Replace `MYCOMPNAME` with your unqualified machine name to match how the agent is expecting it when performing the comparisons. It passes a system property to Java, and the workspace command checks for that system property before falling back to other mechanisms. I played around with it a bit, it seems to be what you're looking for.

You'll probably run into a workspace conflict if you don't first manually clean up the existing workspaces (`tf workspace -delete` and delete the _work/<N>/s directory). An easier option might be to just unconfigure your agent and setup a new agent in a different directory to avoid the collision. The agent ID goes into the the workspace name, so if you choose "REPLACE" during configure then the ID won't change and then still chance of collision even though different directory.

I have a PR out to improve the resiliency of the agent when syncing TFVC sources and computer name changes. Although I think I just found another place where it could be more resilient.

The TEE workspace command is using [this code](https://github.com/Microsoft/team-explorer-everywhere/blob/30ce5c33e8259e25fa19368aaee4d632ff41df83/source/com.microsoft.tfs.jni/tests/com/microsoft/tfs/jni/internal/platformmisc/UnixExecPlatformMisc.java#L90) to resolve the computer name. Which platform are you on? Which hostname command is TEE running for you?

**Comment by bbusacker** [comment]
@ericsciple   I tried the JAVA_TOOL_OPTIONS workaround but it appears to have no effect.  I am running this on CentOS 7.1.   How can I tell what hostname command TEE is running?

**Comment by bbusacker** [comment]
After deleting _work thouroughly JAVA_TOOL_OPTIONS worked.  I'm still not clear where the fully qualified hostname is coming from?  Is tf build based on the tee open source project in GitHub or does is it still developed internally?
