### ISSUE TITLE
Azure / AzureRM capabilities not detected after installation

### ISSUE THREAD

**Issue by tebeco** [Microsoft/vsts-agent#353]
## **Agent version and platform**
Agent : 2.102.1
OS : Windows 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
There are issues with the release definition that may prevent deployment of releaseIssues with Environment 'DevCi'
No agents could be found that match the following demands (queue: 'Default'): azureps
Do you want to queue the release anyway?
<br>
## **Agent and Worker's diag log**
[Logs.zip](https://github.com/Microsoft/vsts-agent/files/340991/Logs.zip)

Line 132 is the begining of : Add-AzurePowerShellCapabilities.ps1

At line 138 to 150 there's a PowerShell Exception

FYI I did try this manually :

> Get-Module -Name Azure -ListAvailable
Result :
 Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
Manifest   1.5.1      Azure                               {Get-AzureAutomationCertificate, Get-Azu

So it found something, but :

> Get-Module -Name AzureRM -ListAvailable
>

It returns nothing for AzureRM

based on :

> $null = (Get-FromModulePath -Classic:$false) -or
>    (Get-FromSdkPath -Classic:$false) -or
>    (Get-FromModulePath -Classic:$true) -or
>    (Get-FromSdkPath -Classic:$true)

It should have return true but I guess the error block the process ?

**Comment by tebeco** [comment]
I think the fix is on line 61 to change :

> Write-Host "Get-Module -Name $path"
to
> Write-Host "Get-Module -Name $path" -ListAvailable

**Comment by tebeco** [comment]
see PR : https://github.com/Microsoft/vsts-agent/pull/354
I'm not sure about the
> Get-Object -First 1

But this is how it behave in first function so ...

**Comment by ericsciple** [comment]
Fixed: https://github.com/Microsoft/vsts-agent/pull/360
