### ISSUE TITLE
Visual Studio Build task tries to invoke NuGet.exe from old layout

### ISSUE THREAD

**Issue by SDxKeeper** [Microsoft/vsts-agent#366]
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
On-Prem TFS 2015 Update 2
<br>
If On-Prem TFS, which release - 2015 QU2
<br>
If VisualStudio.com, what is your account name? N/A
<br>
## **What's not working?** 
When trying to build solution with checkbox "Restore NuGet Packages"
I recieve following error in the log:
2016-07-04T14:46:33.5850444Z ##[error]Leaf path not found: 'C:\vNextAgentPreview\Agent\Worker\Tools\NuGet.exe'
<br>
## **Agent and Worker's diag log**
too much sensitive info in the logs.

Main problem is that Visual Studio build task tries to invoke NuGet.exe from layout of the old style agent.

**Comment by TingluoHuang** [comment]
@SDxKeeper Base on the Doc, https://github.com/Microsoft/vsts-agent#preview-support
We currently don't support this coreclr agent on windows machine configure against TFS 2015.

**Comment by SDxKeeper** [comment]
@TingluoHuang I've read the doc and got understanding that this is supported scenario because I use vNext build definitions and it's mentioned as "Yes" in the line:
 **TFS.vNext (onprem)** 	Yes 	Yes

**Comment by TingluoHuang** [comment]
@SDxKeeper `TFS.vNext (onprem)` means TFS 2016 RTM, which will coming later this year.

**Comment by SDxKeeper** [comment]
@TingluoHuang OK, got it.
Than I'll continue to use old agent.
