### ISSUE TITLE
No agent found in pool 3 which satisfies the specified demands

### ISSUE THREAD

**Issue by escamoteur** [Microsoft/vsts-agent#367]
[Agent_20160706-142123-utc.txt](https://github.com/Microsoft/vsts-agent/files/350089/Agent_20160706-142123-utc.txt)

## **Agent version and platform**
Version of your agent? 2.102.0.
<br>
OS of the machine running the agent? OSX
<br>
## **VSTS type and version**
VisualStudio.com 
<br>
If VisualStudio.com, what is your account name? http://escamoteur.visualstudio.com
<br>
## **What's not working?** 
I installed the build agent on my mac. It connects to the server and is displayed in it's pool as online and idle.

But when I try to built a project on it (here a xamarin ios project) I get this error:

No agent found in pool 3 which satisfies the specified demands:
msbuild
Cmd
Cmd
Agent.Version -gtVersion 1.98.1

Any idea?

**Comment by TingluoHuang** [comment]
@escamoteur the tasks in your build definition require msbuild and cmd available on the build agent in order to queue a build, since you are on OSX, i don't you will have both. Can you check doc and make sure you definition/task are able to run on OSX.

**Comment by escamoteur** [comment]
which task should I use if I want to build a iOS library? I only found a Task for iOS Apps.

**Comment by TingluoHuang** [comment]
@madhurig adding iOS expert for help.
what tasks do you have in your definition?

**Comment by escamoteur** [comment]
NuGet restore
MSBuild
Nuget Packager
NuGet Publisher

Same es I do for Android builds

**Comment by escamoteur** [comment]
I tried to replace MsBUild with the Xamarin.iOS Task, but stil no luck

**Comment by escamoteur** [comment]
Ah, after disabling the Nuget Tasks too it starts building

**Comment by madhurig** [comment]
@escamoteur : For Xamarin iOS we have a template that I would recommend starting with. The Xamarin iOS task will also use xbuild (msbuild equivalent on Mac) but will give you more options to generate .ipa etc.

**Comment by escamoteur** [comment]
@madhurig THanks fort coming back. I managed to build an iOS App, that's not a problem.
The problem is how to build a ios dll and then a nuget package as I do for Android.

For Android I have

NuGet restore
MSBuild
Nuget Packager
NuGet Publisher

And the nuget is saved to my VSTS nuget feed. Works great.

For iOS I cannot add the nuget tasks as they are not supported by the mac agent.

Any Idea how to deal with that?

P.S:: Perhaps we should continue this in my other issue so it will be easier to find from others with the same problem

**Comment by escamoteur** [comment]
Got it working. I was missleaded by thinking I need a MAC to build an iOS lib.
