### ISSUE TITLE
Windows 7 dependencies

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vsts-agent#375]
When running on Windows 7, it appears the following are prerequisites for the agent (although the System Requirements document says there are none)
- A version of Windows PowerShell which supports the [Unblock-File](https://technet.microsoft.com/en-us/library/hh849924%28v=wps.620%29.aspx) command - so 3.0 or higher, Windows 7 ships with 2.0
- The [Universal C Runtime](https://support.microsoft.com/en-us/kb/2999226)

It would be good if the Requirements document could list this.

**Comment by bryanmacfarlane** [comment]
Awesome.  Thanks for the heads up.  We will update docs.

**Comment by TingluoHuang** [comment]
You will hit this kind of weird exception in event view.
```
Faulting application name: Agent.Listener.exe, version: 0.0.0.0, time stamp: 0x57461460
Faulting module name: i-ms-win-crt-runtime-l1-1-0.dll, version: 6.3.9600.18233, time stamp: 0x56bb4ebb
Exception code: 0xc0000135
Fault offset: 0x00000000000ecdd0
Faulting process id: 0xe18
Faulting application start time: 0x01d1e763e1b53193
Faulting application path: C:\WinCoreCLRAgent\bin\Agent.Listener.exe
Faulting module path: i-ms-win-crt-runtime-l1-1-0.dll
Report Id: 1f61bd6f-5357-11e6-80c4-000d3a7028e7
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by TingluoHuang** [comment]
We don't need this anymore, since we package the CRT with the agent now.

**Comment by qmfrederik** [comment]
@TingluoHuang Does this also cover the PowerShell 3.0 requirement? (Windows 7 ships with 2.0)

**Comment by TingluoHuang** [comment]
@qmfrederik good point. :)

**Comment by drolevar** [comment]
I guess this can be referenced in requirements: [http://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx](url)

**Comment by TingluoHuang** [comment]
#823
