### ISSUE TITLE
Does ./config.sh accept parameters ?

### ISSUE THREAD

**Issue by ezeeetm** [Microsoft/vsts-agent#395]
Does ./config.sh accept parameters (e.g. vsts domain, PAT, etc) so we can script the install?

Or, does it write to a config  file that we can replace with a new and and start the service?

Looking for ways to automate the provisioning of Linux agents without human interaction

**Comment by bryanmacfarlane** [comment]
Look at bin/agent.listener --help

config.sh just passes on args to that.  there's a section at the end of the help with examples for automated config

essentially, config will prompt for answers.  But it won't ask for whatever params are passed via cli args

**Comment by ezeeetm** [comment]
Thanks  @bryanmacfarlane , closing.
