### ISSUE TITLE
Unable to use Azure virtual machine scale set agents - Azure Pipelines Extension error

### ISSUE THREAD

**Issue by v1adev** [Microsoft/vsts-agent#3995]
Azure VMSS scale set agents stopped working today. Getting the errors below when the Azure Pipelines Extension attempts to scale the VMSS out from 0 to 1.

**Ubuntu 20.04**
Extension type: `TeamServicesAgentLinux`
Extension version: `1.22`
Extension settings (managed by Azure DevOps):
```
{
  "isPipelinesAgent": true,
  "agentFolder": "/agent",
  "agentDownloadUrl": "https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-linux-x64-2.211.1.tar.gz",
  "enableScriptDownloadUrl": "https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/13/enableagent.sh"
}
```
Error message: `Azure Pipelines Extension failed with message: The Extension failed to execute: HTTP Error 409: Public access is not permitted on this storage account.`

**Windows Server 2019**
Extension type: `TeamServicesAgent`
Extension version: `1.29`
Extension settings (managed by Azure DevOps):
```
{
  "isPipelinesAgent": true,
  "agentFolder": "C:\\agent",
  "agentDownloadUrl": "https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-win-x64-2.211.1.zip",
  "enableScriptDownloadUrl": "https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Windows/15/enableagent.ps1"
}
```
Error message: `Azure Pipelines Extension failed with message: The Extension failed to execute: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (409) Conflict.". More information about the failure can be found in the logs located under 'C:\WindowsAzure\Logs\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.29.0.0' on the VM. To retry install, please remove the extension from the VM first.`

**Comment by LiliaSabitova** [comment]
Hi @v1adev this is not the issue with agent itself, but with VMSS.
Please create an issue [here](https://developercommunity.visualstudio.com/search?space=21&q=elastic).
