### ISSUE TITLE
Feature: unregister agent on stop

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#409]
## **Agent version and platform**
2.103.0
<br>
Linux Centos 7
<br>

## **VSTS type and version**
VisualStudio.com

## **Feature**

Is this worth considering to provide ``--unregister-on-stop`` command line arg, so that the agent makes best effort to unregister itself when it terminates normally (e.g. via `SIGINT` or `SIGTERM`)?

This is the kind of thing we have to do at the moment via wrapper bash script and signal traps.  The wrapper solution is far from ideal because: a) it's relatively tricky;  b) it's bash-specific so likely to require separate solution for Windows;  c) even on OS X may run into portability issues.

The feature would certainly be useful in scenarios where agents run in containers (which we do now), and especially in clusters, e.g. Azure Container Service (we don't do this yet but are working towards this).

It would also help with test scenarios where people start/stop the agents a lot.

I guess one question around this feature is per the new authentication design the agent would need to keep the PAT token (or whatever it might be) in memory in order be able to unregister?

**Comment by ppanyukov** [comment]
Actually, having given this a little more thought and in light that the "unregister" would need to have PAT token which the agent no longer keeps after registration -- this may be not as easy to implement. Unless someone can think of an easy approach, this feature is probably more trouble than worth.  Especially that there is bash script solution for those who really need it.

**Comment by bryanmacfarlane** [comment]
yep.  agreed.
