### ISSUE TITLE
Release management: filePath variables are not getting resolved properly in Windows

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#417]
*Nix behavior:
If task input is of type `filePath`, the agent path is prep-ended to the task input
`tl.getInput -> /home/usr/someagent/..../somefile`

Windows behavior:
Same task, same handler [nodejs], the property is not prep-ended with `agent path`  

This is reproduce-able in `Release` platform

**Comment by nigurr** [comment]
Tried with `Ant` task

*Nix Agent:
`2016-07-19T07:39:49.5967780Z ##[debug]testResultsFiles=/home/ddcloud/Repo/vsts-agent/_layout/_work/r1/a/Nitin-Test/Test/Test*.xml
`
Windows Agent:
`2016-07-19T10:57:34.8020598Z ##[debug]testResultsFiles=Nitin-Test/Test/Test*.xml`

**Comment by bryanmacfarlane** [comment]
I noticed you had /r1/a in your path on nix.  Is this an rm plugin issue or did you repo in build?  That's not what build would do

**Comment by nigurr** [comment]
@bryanmacfarlane i am testing out something in rm and caught it. Need to tryout in build yet

**Comment by bryanmacfarlane** [comment]
It works fine in build.

**Comment by kasubram** [comment]
Its due to the wildcard usage in the filepath input. Fix is available here. https://github.com/Microsoft/vsts-agent/pull/429/files
