### ISSUE TITLE
Error When Setting Clean = True on Windows

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#422]
## **Agent version and platform**
Windows Running Agent v2.103.1
<br>
Winodws 10
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
https://gmpsoftware.visualstudio.com
## **What's not working?** 
Setting Clean = True gives a TFS error
<br>
## **Agent and Worker's diag log**
 Prepending Path environment variable with directory containing 'tf.exe'.
 ##[command]tf vc scorch /diff /recursive C:\agent\_work\1\s /loginType:OAuth /login:.,******** /noprompt
 No appropriate mapping exists for C:\agent\_work\1\s.
 ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc scorch /diff /recursive C:\agent\_work\1\s /loginType:OAuth /login:.,******** /noprompt'.

**Comment by JKennedy24** [comment]
Ps. this only happens on the second build. The first one seems to work

**Comment by ericsciple** [comment]
From the build logs it looks like scorch is failing when the root sources folder (e.g. `_work\1\s`) is not mapped - i.e. workspace does not contain a root mapping.

One not great workaround is to set a variable `build.clean` to `all`.

Thanks for finding the issue. I'll get a fix in soon.

**Comment by ericsciple** [comment]
Fixed in https://github.com/Microsoft/vsts-agent/releases/tag/v2.104.0

Thanks for your help identifying this issue!

**Comment by zinov** [comment]
ericsciple I am having the same error, with build.clean = all I solved the issue, now the version of the agent I am using is greater than the one you posted with the fixes =>  vsts-agent-win7-x64-2.112.0
Does mine include those changes or not?

**Comment by Mertsch** [comment]
@ericsciple The Bug is back in 2.134.2
> Fixed in https://github.com/Microsoft/vsts-agent/releases/tag/v2.104.0
> Thanks for your help identifying this issue!

Can be "fixed" with the Map `$/Root/*` Mapping workaround, which is not really cool.

```
##[section]Starting: Job
Current agent version: '2.134.2'
##[section]Starting: Initialize Job
Prepare build directory.
Set build variables.
Download all required tasks.
##[section]Finishing: Initialize Job
##[section]Starting: Get Sources
Prepending Path environment variable with directory containing 'tf.exe'.
Setting environment variable TFVC_BUILDAGENT_POLICYPATH
Querying workspace information.
##[command]tf vc scorch E:\Builds\_work\24\s /recursive /diff /unmapped /loginType:OAuth /login:.,*** /noprompt
No appropriate mapping exists for E:\Builds\_work\24\s.
##[warning]Exit code 100 returned from process: file name 'tf', arguments 'vc scorch E:\Builds\_work\24\s /recursive /diff /unmapped /loginType:OAuth /login:.,*** /noprompt'.
```

**Comment by janniksam** [comment]
We're having the same problem:

Exit code 100 returned from process: file name 'tf', arguments 'vc scorch C:\agent\_work\8\s /recursive /diff /unmapped /loginType:OAuth /login:.,******** /noprompt'.

What do we need to do exactly to get rid of the "warning"?

**Comment by poonehfamili** [comment]
I am getting error when trying to build from my dockerfile that pulled from a git repo:  ERROR: failed to solve: process "/bin/sh -c bash /usr/local/src/valhalla/scripts/install-linux-deps.sh" did not complete successfully: exit code: 100 Could you please help me with that?
