### ISSUE TITLE
running ./svc.sh uninstall does not uninstall service on mac osx

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#428]
## **Agent version and platform**
Mac OSX running v2.103.1
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
Running ./svc.sh uninstall does not uninstall service
<br>
## **Agent and Worker's diag log**
if you install the service running ./svc.sh install it will install fine and start running. Now try running ./svc.sh uninstall and it says the service has been uninstalled.
Now try running locally using ./run.sh but it says there is already a connection. Restart the machine but still no change.

Run launchctl list and you will see the service running fine. I needed to run launchctl remove vsts.agent...

to fully uninstall my service meaning ./svc.sh uninstall didnt uninstall my service

**Comment by bryanmacfarlane** [comment]
Did you run stop first?

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/svcosx.md

**Comment by JKennedy24** [comment]
I didn't run stop first. I can't see anything in that document that says I must run stop. I presumed uninstall would do that for me. Am I missing something?

**Comment by bryanmacfarlane** [comment]
That's an OSX launchd thing.  We're just a convenience wrapper over that.  I'll look into either calling stop or updating the docs

**Comment by jsauvexamarin** [comment]
To force an uninstall, you can do:

1. Use Activity Monitor to kill all `Agent.Listener` processes.
2. Delete all .plist files in `~/Library/LaunchAgents/` that prefixed with `vsts.agent`

That's essentially what `./svc.sh stop && ./svc uninstall` does. 

I run 8 agents on my MacMini at the same time, so the manual delete is convenient. But it's dangerous if you're trying to uninstall one, but not others.

**Comment by bryanmacfarlane** [comment]
You can do that but it's not safe for all scenarios

You should go into the dir of the agent and run stop and then uninstall

Manually killing processes might short circuit some graceful shutdown code we have where we delete agent leases ( depends how you kill ).  It can also be dangerous to kill all agent listener process for multi agent scenarios.  The biggest benefit the wrapper script has is launchd commands take a path and that's baked in the script.  You really do want to use launchd to manage svc lifetimes and our script simply wraps that to dmsave you looking up the path and typing it

**Comment by bryanmacfarlane** [comment]
I updated docs to say stop before uninstall.  They are independent launchd commands and we're a thin wrapper

**Comment by jsauvexamarin** [comment]
Thanks for the feedback on safely stopping services.
