### ISSUE TITLE
agent no longer seems to know about nuget.exe location

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-agent#436]
## **Agent version and platform**
2.104.0
<br>
## OS of the machine running the agent? 
OSX
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## If VisualStudio.com, what is your account name? 
`http://josau.visualstudio.com`
<br>
## **What's not working?** 
`Unhandled: Unable to find tool nuget.exe`
My detailed system.dbug=true output:
https://gist.github.com/jsauvexamarin/98d99013683f96e0c2f397ba16c31489
The nuget.exe does not appear to be available in any of the paths that the task checks.
<br>
## **Agent and Worker's diag log**
https://gist.github.com/jsauvexamarin/1b90c2d1323793c384bbddd359611857

**Comment by shrub77** [comment]
I just got hit with this issue this morning

**Comment by hawksylver** [comment]
If you need a workaround you can execute in a terminal the command line "mdfind nuget.exe"

Copy path and paste it in your VSTS
Build -> your_build_definition -> Edit Build -> your_step_nuget_restore -> Advanced -> paste the path given by your terminal

And it works

Regards,

**Comment by jsauvexamarin** [comment]
Is this a bug in the vsts agent itself, or is it in the nuget task?: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/NuGetInstaller

**Comment by jmyersmsft** [comment]
it's in the task. I've committed a fix, but it'll take some time to get pushed out.

**Comment by jsauvexamarin** [comment]
Cool, thanks @jmyersmsft! Any ETA? I'll use workaround in the meantime.

**Comment by jmyersmsft** [comment]
Should be fixed by Microsoft/vsts-tasks#2136 / Microsoft/vsts-tasks#2135 which should now be deployed to all affected customers.

**Comment by jsauvexamarin** [comment]
Awesome, @jmyersmsft! You rock! I removed my custom (temporary) nuget.exe path from my build def and all seems well.
