### ISSUE TITLE
Error during NuGet Package Restore

### ISSUE THREAD

**Issue by mjacobs80** [Microsoft/vsts-agent#441]
## **Environment** 
VSTS account name? http://nchcorporation.visualstudio.com
Version of your agent: 2.104.0
OS of the machine running the agent: Windows Server 2012 R2

## **What's not working?** 
NuGet Package Installer task is failing with latest agent. We have 2 older build agent servers running with the 1.103.0 build agent and are looking to deploy the newer agent. However, after configuration and installation of the agent we cannot get past an error during package restore.

Our corporate environment requires a proxy server for our agent servers to access our VSTS account. This is configured with no authentication. We know this to be working as the get sources build step is working as expected.

The error we recieve is Error: connect ECONNREFUSED 23.98.150.230:443.

The build step log with debug enabled and also the agent _diag logs are attached.

[3_Restore packages.txt](https://github.com/Microsoft/vsts-agent/files/381441/3_Restore.packages.txt)
[Worker_20160725-120940-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/381442/Worker_20160725-120940-utc.log.txt)

**Comment by bryanmacfarlane** [comment]
Log an issue in vsts tasks repo.  Not an agent issue

https://github.com/Microsoft/vsts-tasks
