### ISSUE TITLE
Agent Updates can fail if Virus Scanning is enabled on work dir

### ISSUE THREAD

**Issue by bownie** [Microsoft/vsts-agent#445]
## **Agent version and platform**
Version of your agent? 2.103.1
<br>
OS of the machine running the agent? Windows 7 Enterprise 64 bit
<br>
## **VSTS type and version**
VisualStudio.com via Shell
<br>
<br>
Corporate VSTS - richard.bown at shell.com
<br>
Looks like agent is attempting to self update and failing. Agent install is left half completed and the agent won't run up again.  Could this be a proxy issue as I'm working in corporate land?

![failedupdate](https://cloud.githubusercontent.com/assets/2190729/17137776/4d1b1082-533d-11e6-8f76-6bdbd87baaaf.png)

<br>
## **Agent and Worker's diag log**

[SelfUpdate-20160726-121953.log.txt](https://github.com/Microsoft/vsts-agent/files/383766/SelfUpdate-20160726-121953.log.txt)
[Agent_20160726-121722-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/383767/Agent_20160726-121722-utc.log.txt)

**Comment by bownie** [comment]
BTW I've tried this a couple of times from clean - unpacking, config agent and running up with different agent names, working directories. Also tried as local admin and 'normal' user with same results.  Looks like a permissions issue on the folder move.  This from log of my latest attempt:

[Tue 07/26/2016 15:00:39.25] move "E:\vsoagent\work\_update\bin" "C:\Apps\vsoagent-2.103.1.second\bin" 
Access is denied.
        0 dir(s) moved.

**Comment by TingluoHuang** [comment]
@bownie  I noticed this issue, PR #434 fix the problem.

**Comment by bownie** [comment]
Awesome. Also looking at your patch I deduced that setting 'agent.disableupdate' on the agent makes for a nice workaround while the pull request is attended to.  Many thanks.

**Comment by TingluoHuang** [comment]
@bownie just a heads up, i will change agent.disableupdate to be VSTS_DISABLEAGENTUPDATE in that PR, since we are cleanup all naming convention on those agent environment variables.

**Comment by bryanmacfarlane** [comment]
We're going to have to pull the opt out of auto update because it's not reliable (server will continue to send update message and never send it a job).  We need server work to make that reliable:  https://github.com/Microsoft/vsts-agent/issues/446

The correct work around for this issue is to exclude virus scanning on the worker folder.  It's a good idea independent of auto update.

Also the PR that Ting mentioned will avoid the move which also alleviates the issue.  Finally, we have another bug to recommend post config

**Comment by bryanmacfarlane** [comment]
Closing since the solution is to exclude from virus scanning and we have issues to track recommending that and formerly supporting opting out of automatic updates (#446)
