### ISSUE TITLE
Document minimal required permission scopes for PAT

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#447]
## **Agent version and platform**
Version of your agent? 2.104.0

## **VSTS type and version**
VisualStudio.com

## **What's not working?** 

We would like to avoid creating PAT tokens with "all scopes" for use with VSTS agent. 

Additionally we'd like to have PAT with only those scopes which are required.

The existing docs don't mention anything on the subject.

I guess we could figure it out by trial and error but would be nice to have some docs for this.

**Comment by ppanyukov** [comment]
If I didn't mess anything up, looks like I get everything working only with these:

```
- Agent Pools (read)
- Agent Pools (read, manage)
```

**Comment by TingluoHuang** [comment]
![image](https://cloud.githubusercontent.com/assets/1750815/17152444/cf39170a-5345-11e6-86fe-563c0951213d.png)

Here is the minimal required scope for PAT, we add that scope recently, so old on-prem releases don't have them yet.

**Comment by bryanmacfarlane** [comment]
We will add it to the docs.  Thanks for the reminder!  I'll do it right now

**Comment by bryanmacfarlane** [comment]
Fixed: https://github.com/Microsoft/vsts-agent/commit/8ee965ff85be9dec8e09c02e6cda2b23ad6f4eaf
