### ISSUE TITLE
Full supported OS compat testing

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/vsts-agent#448]
We need make sure our agent is able to run on all supported OS.
-Win7
-Win8
-Win8.1
-Win10
-Server2008 (R2) ?
-Server2012 (R2)
-OSX
-Ubuntu 14
-Ubuntu 16
-Redhat 7

**Comment by bryanmacfarlane** [comment]
Lets track this on our back log as part of our acceptance testing
