### ISSUE TITLE
VSTS-logging tasks not working in Release Management

### ISSUE THREAD

**Issue by Mystere** [Microsoft/vsts-agent#449]
## **Agent version and platform**
Version of your agent? 2.104.0
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
On-Prem TFS
<br>
If On-Prem TFS, which release, 2015 QU3
<br>
## **What's not working?** 
I'm attempting to use the VSTS logging tasks in Release Management, but they appear to be ignored and stripped out.  They don't appear in the log output either.

For instance:
Add Attachment:
Write-Host "##vso[task.addattachment type=report;name=$attach;]$outputPath" 
UploadFile:
Write-Host "##vso[task.uploadfile]$outputPath" 

There is nothing in the log files that indicate an error, or that the lines were even processed.

Are these commands build-only?  If so, there should be documentation specifying this.  Why don't release and build work similarly?

**Comment by TingluoHuang** [comment]
@Mystere Can you share your releases log and worker log? worker log are under _diag folder.

**Comment by Mystere** [comment]
I can, but there's nothing in them that indicates any error, or any evidence of these tasks running at all.

There's a lot of sensitive info, so I've had to redact.

In the release log, at 20:15.29.26095 is a line that says Uploading Report....  That is a comment I have just before the task.uploadfile statement is executed.  As you see, nothing in the log.

[Worker_20160726-201448-utc - Redacted.txt](https://github.com/Microsoft/vsts-agent/files/384913/Worker_20160726-201448-utc.-.Redacted.txt)
[Agent_20160726-200308-utc - Redacted.txt](https://github.com/Microsoft/vsts-agent/files/384921/Agent_20160726-200308-utc.-.Redacted.txt)
[1_Release.txt](https://github.com/Microsoft/vsts-agent/files/384937/1_Release.txt)

**Comment by TingluoHuang** [comment]
@Mystere Can you try to add system.debug=true to variable tab, so the releases can print out more verbose log?

**Comment by Mystere** [comment]
The more verbose log does have this line in gray, but no indication of error:

Processing: ##vso[task.uploadfile]D:\Work\newagent\_work\r1\a\artifacts\GeneratedScript.sql

**Comment by TingluoHuang** [comment]
@Mystere  seems like the agent upload the file, but the server doesn't provide a way to get it, right?
You can set VSTSAGENT_TRACE=1 on the agent machine as environment variable, then restart the agent, the agent will produce verbose trace, it should print out the it upload that file.

**Comment by Mystere** [comment]
Ok, so there isn't a way to get it through the UI?  Kind of defeats the purpose...  I want my users to be able to download the results of several release processes.  Right now i'm emailing them, but i'd rather have it available in release itself.

**Comment by TingluoHuang** [comment]
@Mystere I agree, 
@GitHubSriramB I think we need fix it in server side.

**Comment by Mystere** [comment]
@TingluoHuang 

Yeah, after adding the environment variable, I get this:

[2016-07-26 22:46:17Z VERB JobServerQueue] Enqueue web console line queue: ##[debug]Processing: ##vso[task.uploadfile]D:\Work\newagent\_work\r1\a\artifacts\GeneratedScript.sql
[2016-07-26 22:46:17Z VERB JobServerQueue] Enqueue file upload queue: file 'D:\Work\newagent\_work\r1\a\artifacts\GeneratedScript.sql' attach to record b5bb2237-da23-4403-9e96-f9e3a6de8cde

And that's it.

**Comment by GitHubSriramB** [comment]
@TingluoHuang, @Mystere  - We will investigate this issue and give you an update.

**Comment by GitHubSriramB** [comment]
@Mystere - Files getting uploaded using ##vso[task.uploadfile] command can be downloaded as part of "Download all logs" action from Release/Build. The files that get uploaded will be part of the ZIP file that gets downloaded.

We don't support downloading files/attachments added using ##vso[task.addattachment] (neither in Build nor in Release).

**Comment by Mystere** [comment]
@GitHubSriramB  - Is that functionality that should work in TFS 2015 U3?  Or is that a TFS 15 feature?  I'm pretty sure I checked the logs and they did not include the uploaded file.  I'll double check though.

**Comment by Mystere** [comment]
@GitHubSriramB  - Just double checked, and it definitely is not including the uploaded file in the Download all logs feature in TFS 2015 U3

**Comment by GitHubSriramB** [comment]
@Mystere - This feature is available only with TFS "15" RC1 onwards. We do not support  ##vso[task.uploadfile] command or downloading the uploaded files in TFS 2015 U3 or below. Apologies for not noticing earlier that you were reporting this on TFS 2015.

**Comment by Mystere** [comment]
Okee then.  Consider this closed.
