### ISSUE TITLE
Redhat: Error "Failed to initialize CoreCLR" during the installation

### ISSUE THREAD

**Issue by DeV1L** [Microsoft/vsts-agent#455]
## **Agent version and platform**

vsts-agent-rhel.7.2-x64-2.103.1
<br>
Red Hat Enterprise Linux Server release 7.2 (Maipo)
<br>
## **VSTS type and version**

VisualStudio.com
<br>
## **What's not working?**

As described here: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envredhat.md
I've installed the packages: curl-devel expat-devel gettext-devel openssl-devel zlib-devel gcc perl-ExtUtils-MakeMaker

But when i tried to run ./config.sh i have an error.

Failed to initialize CoreCLR, HRESULT: 0x80004005

<br>
## **Agent and Worker's diag log**

Haven't it

**Comment by bryanmacfarlane** [comment]
We'll investigate.  Thanks

**Comment by bryanmacfarlane** [comment]
Does this help?

sudo yum -y install libunwind.x86_64 icu

**Comment by khowling** [comment]
I have the same on a new Azure VM marketplace Ubuntu 16.04 image, followed all the pre-reqs, and got : Failed to initialize CoreCLR, HRESULT: 0x80131500.

including :  sudo apt-get install -y libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip

**Comment by brandonh-msft** [comment]
still happening on fresh installs. the `sudo yum` command results in `sudo: yum: command not found`

**Comment by TingluoHuang** [comment]
@brandonh-msft  `yum` is a redhat version of `apt-get`

**Comment by TingluoHuang** [comment]
Please try out the latest agent release https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.0
The latest version contains a script to help you install all missing dependencies.

**Comment by lavahot** [comment]
@TingluoHuang What script is that?

**Comment by lavahot** [comment]
Hmm. Seems like that wouldn't work on macOS then?

**Comment by bryanmacfarlane** [comment]
Do you have a repro of a problem on Mac OS or is that a general question?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lavahot** [comment]
Not a very brief one. I need to try to isolate the issue in my cookbook. I'll make a new issue for macOS when I get closer to understanding the problem.

**Comment by TingluoHuang** [comment]
@lavahot https://github.com/Microsoft/vsts-agent/releases/tag/v2.126.0 is built on netcore 2.0, which means there is no requirements for macOS 10.12
https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x

**Comment by lavahot** [comment]
... isn't 2.125.0 also built on netcore 2.0?

**Comment by TingluoHuang** [comment]
it is, but 2.125.0 has a little bug that may broken on macOS. you can use 2.125.1 or 2.126.0
the error you get on 2.125.0 is something about "not support exception, the SSL backend is not support for setup customized SSL validation handler."

**Comment by lavahot** [comment]
Okay, I'm going to try a run on 2.126.0. I'll let you know the results.
