### ISSUE TITLE
Doc all pre-reqs on Ubuntu 14.04

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/vsts-agent#456]
## **Agent version and platform**

> Version of your agent? 2.102.0/2.100.1...

2.104.0

> OS of the machine running the agent? OSX/Windows/Linux...

Ubuntu 14.04.4 LTS (plain ubuntu VM installation on azure.com)

## **VSTS type and version**

> VisualStudio.com or On-Prem TFS?

VisualStudio.com

> If VisualStudio.com, what is your account name?

http://elbarzil.visualstudio.com

## **What's not working?** 

Setting things up had two very minor things that could be improved, in case of a plain ubuntu setup as I used:

1. Running Agent.Listener failed because libunwind was not installed.  So I needed to `sudo apt-get install libunwind8`.

2. Then, running a build in the agent failed because git wasn't there -- and turns out that the ubuntu version that I get with `apt-get` is some ancient 1.x instead of 2.x.  This got me the recent version:

    sudo add-apt-repository ppa:git-core/ppa
    sudo apt-get update
    sudo apt-get install git

They're minor enough that they could be fixed by adding verbiage to the VSTS instructions.  (I wouldn't even file this if it wasn't the default ubuntu version I got from azure, so it seems like a good idea to mention it.)

**Comment by bryanmacfarlane** [comment]
git covered in step 1 of ubuntu docs: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envubuntu.md

I'll add the libunwind8 but I thought that was just needed for dev (building).  Hmmm.  Did you pickup the 14.04 build and it needed that?

Thanks!

**Comment by elibarzilay** [comment]
@bryanmacfarlane I'm not sure what I looked at, but I definitely didn't see that page...  IIRC, the page that had the download link had some links that I read, so maybe that could be improved or something...

As for the libunwind8 thing -- it definitely happened when running the agent (before anything else happened, and the VM hadn't been used for anything before so it's pretty much the standard 14.04 setup).  I even tried running `./bin/Agent.Listener` directly and got that error.  (The setup doesn't include mono, so this is probably some implicit dependency that wasn't caught before?)

**Comment by elibarzilay** [comment]
I now recognize `docs/start/startubuntu.md` as what I was looking at -- the confusion is that I dismissed the "Read here to ensure system packages are installed" as something that must be irrelevant since I just set up the ubuntu vm recently so I didn't expect it to have anything outdated...  Sorry for the noise about that.

**Comment by bryanmacfarlane** [comment]
I updated the pre-req pages.  Let me know if you have any issues

**Comment by elibarzilay** [comment]
Thanks!
