### ISSUE TITLE
Xcode package task assumes that the .app folder and .ipa file would be inside the source folder, which doesn't seem right.

### ISSUE THREAD

**Issue by khronosX** [Microsoft/vsts-agent#458]
## **Agent version and platform**
2.103.1
<br>
OS X
<br>
VisualStudio.com
<b>
If VisualStudio.com, what is your account name? http://microsofthealth.visualstudio.com
<br>
## **What's not working?** 
The Xcode Package task seems to assume that the relatives path to .app or .ipa file is from the sources folder. This seems to contradicts to what we want to do, which is to separate the sources folder and artifacts folder. Xcode build task allows the user to enter output folder manually. It doesn't seem right that the package task should assume that the .app folder will be inside the sources folder.

**Comment by khronosX** [comment]
Also, Xcode build task allows the provisioning profile to be specified from relative path of the source. Xcode package seems to assume that the provisioning profile already exists and only take the name as the input. This seems to be inconsistent as well.

**Comment by bryanmacfarlane** [comment]
Log an issue in the vsts-tasks repo.   https://github.com/Microsoft/vsts-tasks

This is the agent
