### ISSUE TITLE
TF enhancements

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#46]
It would be nice if the default variables would always be included, even if their value is empty. For example, when building from Shelveset or in a Gated Checking the variable "Build.SourceTfvcShelveset" is set, but when the same build is executed normally, the variable is undefined and where referenced will actually output:

```
$(Build.SourceTfvcShelveset)
```

It would be nice if the standard variables would always be defined, but left empty if not applicable.

**Comment by bryanmacfarlane** [comment]
Not sure if we can do "always".  We could probably do it if it's a TfsVC build.  The issue is we have source provide plugins - one for git, tfsvc and svn.  That variable is owned by the tfsvc plugin so it could only potentially write if tfsvc build.  make sense?

**Comment by jessehouwing** [comment]
That makes sense.

**Comment by bryanmacfarlane** [comment]
Cool then assigning to eric to look into

**Comment by ericsciple** [comment]
- Always provide Build.SourceTfvcShelveset
 - I discussed with @patrickcarnahan it sounds like the best place for this might be the server side. I'll touch base with him again regarding this.
- Add TF and TEE to the PATH
- Pass login creds via env var and leave in environment if "Allow Scipts Access to OAuth Token" is checked.

**Comment by bryanmacfarlane** [comment]
while you're at it, confirm the git we drop is in the path

**Comment by ericsciple** [comment]
Tracking in the above referenced issue.
