### ISSUE TITLE
How to use VS extensions that are required for my UWP + sqlite build?

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-agent#461]
## **Agent version and platform**

2.104.0
<br>
## OS of the machine running the agent?

OSX
<br>
## **VSTS type and version**

VisualStudio.com
<br>
## If VisualStudio.com, what is your account name?

`http://josau.visualstudio.com`
<br>
## **What's not working?**

When the hosted agent tries to build my UWP app, it is unable to find my reference of `SQLite.UWP.2015`. This is because it's distributed as a Visual Studio Extension and needs to be installed on the hosted agent (https://visualstudiogallery.msdn.microsoft.com/4913e7d5-96c9-4dde-a1a1-69820d615936). Locally, I've installed the extension on my dev machine, but I don't see any way to install this extension on the hosted build agent.

Here's my detailed output from the build task:
https://gist.github.com/jsauvexamarin/b6d35516a2ca7a06c5e3cb0e6e5c5d15

Is there some other way to reference this VS extension in my project?

**Comment by bryanmacfarlane** [comment]
I believe the answer might be your own agent on a VM.  Adding Chris in case he knows of another way.

(BTW, not an agent issue - more of a hosted pool question)

**Comment by jsauvexamarin** [comment]
Right on. Makes sense. I was hoping that wouldn't be the answer, but I totally get it. It's too bad that Sqlite extension for UWP isn't  available as a package. :(  I'm sure it would be if it was possible.

**Comment by JKennedy24** [comment]
I asked a similar question here: http://stackoverflow.com/questions/37070617/could-not-find-sdk-sqlite-uwp-2015-when-building-uwp-application-using-hosted-tf

be nice for this to come with the hosted pool so I didnt have to manage my own machine, but managing your own pool is not the end of the world

**Comment by dominik-weber** [comment]
Check out the SO post @JKennedy24 mentioned, I have added an answer there how this can be done. Works perfectly for us with UWP builds on hosted agents.

**Comment by bryanmacfarlane** [comment]
We are looking into allowing admin functionality during the build since you own the machine for that leased period of time.

**Comment by nanddobanjo** [comment]
I'm still having an issue relating this http://stackoverflow.com/questions/43236497/references-not-included-in-vsts

**Comment by bryanmacfarlane** [comment]
Have you tried the vs2017 queue on your definition?  Are you using vs2017?

**Comment by nanddobanjo** [comment]
Yes I'm using VS2017 hosted agent

**Comment by chrisrpatterson** [comment]
I don't believe we ahve the SQL Lite extension installed on those VMs and currently you can't install them yourself due to not being an admin.  We are working on a image update for next week that will include them.

**Comment by bryanmacfarlane** [comment]
@nanddobanjo - We'll leave this issue open till you confirm you're good.

**Comment by nanddobanjo** [comment]
Hi, maybe I had to open another issue, but it was related to this. I'm able to include the extensions I want using the solution posted in [here](http://stackoverflow.com/questions/37070617/could-not-find-sdk-sqlite-uwp-2015-when-building-uwp-application-using-hosted-tf). I have a local folder in my repo with the extensions I need (SQLCipher and PDFTron). The Host Agent does not complain about not finding SDKs, it finds them indeed. When I compile the app with powershell and MSBuild I see that there is a step where the SDKs are enumerated and then Added to the project `Adding reference "References\CommonConfiguration\x86\pdftron.winmd".`
I don't see this step happening in the logs of the VS2017 agent and thus lots of namespaces and classes are not being found causing compilation to fail.

**Comment by bryanmacfarlane** [comment]
We can solve some popular extensions like SQLLite but can't install all.  We have another feature to run hosted as admin so you could automate pulling any needed at beginning of build ...

**Comment by nanddobanjo** [comment]
Yes I agree. I'm including my own SDKs in a local folder. I'm using currently this tweak in the csproj: ` <PropertyGroup>
    <SDKReferenceDirectoryRoot>..\SDKs\Microsoft SDKs;$(SDKReferenceDirectoryRoot)</SDKReferenceDirectoryRoot>
  </PropertyGroup>`

That makes the MSBuild agent to override the default location of the SDKs and go find first my PDFTron and SQLCipher libraries. Otherwise it yields that it cannot find the SDKs. So MSBuild is ABLE to find them in the Host Agent, what it doesn't do, is add them to the project as the powershell MSBuild I run locally does. And that's the only thing I would like to know. Why this line does not appear in the HostAgent logs: 
`Adding reference "References\CommonConfiguration\x86\pdftron.winmd`

**Comment by dachibox** [comment]
Hi, I'm interested on this issue. Some good news?

Now I'm trying on a VS2015 with SQLite.UWP.2015 extension
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets (2049, 5)
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2049,5): Error MSB3774: Could not find SDK "SQLite.UWP.2015, Version=3.17.0".
```

**Comment by bryanmacfarlane** [comment]
The agent in hosted now runs as admin.  You can install whatever you want.

**Comment by HppZ** [comment]
There is no SQLite for Universal Windows Platform in VSTS so how to install it?
Check this link below:
https://marketplace.visualstudio.com/search?term=sqlite&target=VSTS&category=All%20categories&sortBy=Relevance

**Comment by nbevans** [comment]
No update for @HppZ question? All UWPs worth setting up CI/CD for will be using the "SQLite for Universal Windows Platform" VS Extension - so why doesn't DevOps have support for this?

**Comment by dominik-weber** [comment]
@nbevans I think the industry is moving towards this project/nuget package instead: https://github.com/ericsink/SQLitePCL.raw as it supports sqlite on many more platforms. Also, there is no special DevOps integration required to make it work. Just install the NuGet package.

Personally I wouldn't expect the highest support level for the VS Extension ;)
