### ISSUE TITLE
README.md still pointing to 2.103.1

### ISSUE THREAD

**Issue by BluMist** [Microsoft/vsts-agent#462]
Should be updated to 2.104.0?

**Comment by bryanmacfarlane** [comment]
Yep.  The docs are getting replaced today

Thanks

**Comment by bryanmacfarlane** [comment]
401.1 is going out tonight as well

**Comment by bryanmacfarlane** [comment]
... Meant 104.1

**Comment by bryanmacfarlane** [comment]
Fixed.  I actually removed it as the getting started docs point to official vs.com docs which address this.  They tell you to download from your web UI.  That will be latent as after we created new agent, we roll updates through scale units and watch for potential issues with the early scale units servicing as canaries.

You can always go to releases tab and pick up latest.
