### ISSUE TITLE
coreclr agent is crashing on Windows Server 2012 R2/Win7 (Faulting module name: i-ms-win-crt-runtime-l1-1-0.dll)

### ISSUE THREAD

**Issue by vishnugms** [Microsoft/vsts-agent#463]
## **Agent version and platform**
Version of your agent? vsts-agent-win7-x64-2.104.0
<br>
OS of the machine running the agent? Windows Server 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? https://microsoftit.visualstudio.com
<br>
## **What's not working?** 
While configuring coreclr agent it's not working, no _diag folder is being created and event viewer gives following traces - 
Faulting application name: Agent.Listener.exe, version: 1.0.1.4500, time stamp: 0x576218d2
Faulting module name: i-ms-win-crt-runtime-l1-1-0.dll, version: 6.3.9600.18233, time stamp: 0x56bb4ebb
Exception code: 0xc0000135
Fault offset: 0x00000000000ecdd0
Faulting process id: 0x6e1c
Faulting application start time: 0x01d1e7e7d6e20175
Faulting application path: D:\Agent\bin\Agent.Listener.exe
Faulting module path: i-ms-win-crt-runtime-l1-1-0.dll
Report Id: 148ffb9e-53db-11e6-8118-000d3a919bbe
Faulting package full name: 
Faulting package-relative application ID:  
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by bryanmacfarlane** [comment]
See link about updating C runtime here:

https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-windows

**Comment by TingluoHuang** [comment]
#375 Install C runtime will fix it

**Comment by TingluoHuang** [comment]
https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
