### ISSUE TITLE
Update not working for version 2.104.0

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#466]
## **Agent version and platform**
2.104.0
<br>
OSX and Windows 10
<br>
## **VSTS type and version**
VisualStudio.com
## **What's not working?** 
I am going to agent pools in VisualStudioOnline and clicking Update All Agents but the agents are not updating to version 2.104.1.
What is the advised way to update the agent? I can't find any documentation on updating

**Comment by JKennedy24** [comment]
In the past I have removed both agents from my OSX and Windows and reinstalled from scratch but I dont want to keep doing that. Should my agent be updating to version 2.104.1 or am I missing something?

NB: Windows is running as service and OSX is running interactive

**Comment by TingluoHuang** [comment]
@JKennedy24 We haven't done host servicing to actually publish the new 2.104.1 agent to VSTS, we will do it pretty soon, I hope later today, then you can update all you agents through VSTS agent pool UI.

**Comment by JKennedy24** [comment]
@TingluoHuang Thanks for the quick reply. How can I tell if a release has been published for my agent to update to?

I'm guessing the page: https://github.com/Microsoft/vsts-agent/releases is not in sync with your published packages?

Be good to keep them both in sync

**Comment by bryanmacfarlane** [comment]
Go to you web admin UI, Queues, download agent dialog.  It will show you what version of the agent your account is pointing to.  If an update is triggered, it will update to that version.

**Comment by TingluoHuang** [comment]
![image](https://cloud.githubusercontent.com/assets/1750815/17300847/1ac62528-57e2-11e6-928f-1fd199ace02b.png)

**Comment by JKennedy24** [comment]
Thanks both. That Download agent dialog button has changed since the new VSTS agent which is why I haven't clicked it since (It used to download the Windows agent). Some feedback on the "Download agent" button. VSTS online team could update the UI to make it more obvious its a dialog because it looks like a download button at the moment.

Thanks for the help. look forward to new version

**Comment by JKennedy24** [comment]
Sorry to reopen this issue but it looks like version 2.104.0 is still not updating for windows.

The 2.104.1 has now been published and clicking update all agents successfully updates my mac but not my windows agent.

I have also tried stopping the service, updating and then restarting the service but still no luck. Can you reproduce this issue or am I doing something wrong?

**Comment by TingluoHuang** [comment]
@JKennedy24 the bug fix is in the 2.104.1, so update from 2.104.1 to later version should works fine. you can unblock by stop the service, then manually run _update.cmd under _work folder. Sorry for this.

**Comment by bryanmacfarlane** [comment]
fixed in 2.104.1
