### ISSUE TITLE
Incorrectly configuring with the collection url does not lead to an actionable error message

### ISSUE THREAD

**Issue by sanyogitaranade** [Microsoft/vsts-agent#468]
## **Agent version and platform**
Version of your agent?
2.103.1...
OS of the machine running the agent? 
Windows...
## **VSTS type and version**
On-Prem TFS
## **What's not working?** 

1. If the Server URL is specified as "http://accountName/tfs/DefaultCollection", then after configuration "TF14045: The identity could not be found." error is shown in the log.
2. After that, as a next configuration attempt, even when server URL is correctly mentioned, following error is shown - Access to the path 'F:\devel\agents\on-prem_agent\agent\.credentials' is denied."
3. Once that happens, unless .credentials file is deleted, agent remains in not configurable state

## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 
[agent_logs.zip](https://github.com/Microsoft/vsts-agent/files/394448/agent_logs.zip)

**Comment by bryanmacfarlane** [comment]
Obviously they need to specify the server url for on-prem per docs ...  Correct?

**Comment by sanyogitaranade** [comment]
Yes but the problem is once the user puts a wrong URL the first time, even if he corrects it the next time, he will keep getting the error. Also, if user tries to access(read/write) the credentials file, he can do it which further adds to the confusion that if he can access it, why the error message says otherwise.
That is why I raised the issue, but I think the way you have rephrased it sounds better.

**Comment by bryanmacfarlane** [comment]
Not sure if there's anything we can do up front (test connection?) to give heads up and fail config with better message.

**Comment by TingluoHuang** [comment]
This is caused by those files are hidden, you can't overwrite hidden file in .net. I will make a fix.

**Comment by TingluoHuang** [comment]
#473
