### ISSUE TITLE
OSX: An error occurred: The type initializer for 'Crypto' threw an exception.

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#470]
net core depends on updated openssl on OSX.

A recent change in brew makes force link fail.

Net core issue: https://github.com/dotnet/cli/issues/3964#issuecomment-236493536

**Comment by bryanmacfarlane** [comment]
So upfront during pre-req:

```bash
brew update
brew install openssl
```

From the root of the agent after download and extract (I will likely bake into cfg later):

```bash
install_name_tool -add_rpath /usr/local/opt/openssl/lib ./bin/System.Security.Cryptography.Native.dylib
```

If it already exists for some reason -delete_repath with same args can be used.  This tells the net core crypt dylib we distribute to use the openssl brew just installed.

**Comment by joshka** [comment]
@bryanmacfarlane `sudo` was only necessary for the dotnet installation as it installs the crypto lib to a directory that is only writeable by root.

**Comment by bryanmacfarlane** [comment]
Thanks for confirming!  I verified no sudo for our usage as well.

**Comment by bryanmacfarlane** [comment]
net core updated it's instructions:

https://www.microsoft.com/net/core#macos

```bash
brew update
brew install openssl
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

**Comment by joshka** [comment]
Those instructions are somewhat erroneous. They will work, but leave your system in an inconsistent state. The above mechanism is better IMO.

**Comment by bryanmacfarlane** [comment]
Thanks for the note.  Can you clarify more on the erroneous state?  I have a conversation going with the net core folks so details are appreciated.

**Comment by joshka** [comment]
There's an error repro on the original issue 597 in homebrew core iirc. Either way, a local change makes more sense to fix this than a global one

**Comment by joshka** [comment]
The homebrew guys would give a better indication on what's the full problem here.

**Comment by bryanmacfarlane** [comment]
Yes.  The problem is a key scenarios for us will be building net core apps (and calling dotnet).  So, folks will do the dotnet instructions in order for it to work

**Comment by bryanmacfarlane** [comment]
I updated the docs

**Comment by davibe** [comment]
In order to avoid linking openssl to system paths (which could cause problems) this is what we ended up doing

	brew update
        brew install openssl
	ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib .
	ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib .
	export DYLD_LIBRARY_PATH=`pwd` 

then `./configure.sh`, `./run.sh` whatever.
