### ISSUE TITLE
Not able to consume node modules installed as a part of task execution

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-agent#472]
## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
2.104.1
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
Windows
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
OnPrem TFS
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
2016 RC1
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>
Not able to use the npm packages that are installed as a part of task execution. 
Below is the mock task js which tries to install shelljs node module and import it
![image](https://cloud.githubusercontent.com/assets/11783897/17329168/089c64e0-58df-11e6-9b9a-8820544f4a08.png)
when we run this task on the agent it fails with the below error:
![image](https://cloud.githubusercontent.com/assets/11783897/17329094/a84f9d5a-58de-11e6-8ea1-ad2e56c94e7e.png)

**Comment by TingluoHuang** [comment]
@omeshp in the screenshot your exec(npm install shelljs) seems failed with ERROR can't open c:\vsts-agent\_layout\_work\3\s\package.json. is that the correct place of your package.json?

**Comment by omeshp** [comment]
@TingluoHuang there isn't any package.json, I am trying to install the npm package on the fly and consume it.

**Comment by TingluoHuang** [comment]
@omeshp I understand, but is the on the fly npm package installation succeed?

**Comment by bryanmacfarlane** [comment]
That line isn't installing the node module.  It's requiring it.  Requiring it *loads* it.  [Here's how](https://nodejs.org/api/modules.html) node modules are loaded.

The agent does not install npm packages.  You need to package them with your task.  For example, [in our tasks](https://github.com/Microsoft/vsts-tasks), the build process npm installs the tasks

Here's info on writing node tasks:

https://github.com/Microsoft/vsts-task-lib
