### ISSUE TITLE
Unable to start config.sh on Linux running as Docker image

### ISSUE THREAD

**Issue by vkanne-msft** [Microsoft/vsts-agent#474]
## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
<br>
OS of the machine running the agent? OSX/Windows/Linux...
Linux ( Ubuntu 14.04 running on Docker hosted in Windows) 
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
VisualStudio.com 
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://msresearch-ext.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
Config.sh fails to start with the below error.
Failed to initialize CoreCLR, HRESULT: 0x80131500
<br>
## **Agent and Worker's diag log**
No log has been generated. 

Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by bryanmacfarlane** [comment]
You need to be on 2.104.1

Also, your docker image needs to ensure:

https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/latebreaking.md 

Finally, since it's your docker image, try to reproduce outside your docker image (VM etc...) to ensure it's a product bug.  It's almost certainly a missing system pre-req from the link above and your docker container is getting them installed properly.

**Comment by vkanne-msft** [comment]
Thanks Bryan. I noticed it required an undocumented dependency ( atleast on the prereqs site) which is libicu52. It works after I installed that.

**Comment by bryanmacfarlane** [comment]
Thanks.  We had that in the past but it was when I was installing the 14.04 agent package on 15.10 or 16.04 Ubuntu.  Can you clarify exactly which package you downloaded and which ubuntu OS version you installed it on?

**Comment by vkanne-msft** [comment]
I am using 14.04 and I installed libicu52

Distributor ID:    Ubuntu
Description:  Ubuntu 14.04.4 LTS
Release: 14.04
Codename:   trusty

**Comment by bryanmacfarlane** [comment]
Thanks - one more piece of data to be sure.  Which agent download tar gz did you use?  I assume the 14.04 one (not the 16.04)?  If that's the case the assertion is we should add libicu52 to the 14.04 instructions.

**Comment by emusgrave** [comment]
I can confirm that for Ubuntu 14.04, libicu52 needs to be added to the prerequisites. Otherwise you get the error "Failed to initialize CoreCLR, HRESULT: 0x80131500" when attempting to run config.sh.
