### ISSUE TITLE
Secret build variables not working for iOS build definition

### ISSUE THREAD

**Issue by simplatek** [Microsoft/vsts-agent#485]
## **Agent version and platform**
Version of your agent? 2.103.1
<br>
OS of the machine running the agent? OSX
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://cccone.visualstudio.com
<br>
## **What's not working?** 
Our auto-publish to iTunes Connect is failing while using a secret build variable for the password.  When not set as secret it works fine.

2016-08-05T16:18:27.4612270Z [command]/bin/bash /Users/buildagent/myagent/_work/4/s/.build/scripts/xcode/iTunesConnectClient.sh validate /Users/buildagent/myagent/_work/4/a/iphoneos8.4/TestFlight/appstore/TestFlight-iphoneos/<AppName>.ipa

2016-08-05T16:18:27.4619860Z Validating ipa with iTunes Connect...
2016-08-05T16:18:28.5984800Z 2016-08-05 09:18:28.597 altool[70178:982822] *** Error: Unable to validate your application. Your Apple ID or password was entered incorrectly.
2016-08-05T16:18:28.5997280Z Validation of ipa done.
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@simplatek, i noticed your are just running an ad-hoc `iTunesConnectClient.sh` script via Bash task, right? Base on current design, ad-hoc script doesn't have access to secret variable.

**Comment by bryanmacfarlane** [comment]
Correct.  Secret variables should get passed via args into the script explicitly.  $(secretVar) in additional args.  In script use $1 etc...

**Comment by simplatek** [comment]
Thanks guys for your assistance, will pass em secrets in as advised.   New coreclr build system is pretty sweet btw, good work!

**Comment by bryanmacfarlane** [comment]
Cool.  Let us know if you have issues.  We had long discussions around this.  The reason is if set as envvars, then child processes may get them but by passing them as args to your script, your scripts decides who to pass them off to.

It's one of those security vs convenience things :/

**Comment by ppanyukov** [comment]
Not having env vars is a bit safer but wanted to point out that child processes can still easily do:

    ps -ef 

and get all those secret command line args, if children run as the same UID as parent at least.
