### ISSUE TITLE
Documentation RHEL vsts

### ISSUE THREAD

**Issue by Dan-Co** [Microsoft/vsts-agent#487]
Cannot reconcile a RHEL file called /etc/bash.rs - its /etc/bashrc
Also stated on linked page:
http://tecadmin.net/install-git-2-x-on-centos-rhel-and-fedora/#

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envredhat.md

Old:
**In /etc/bash.rs**

export PATH=$PATH:/usr/local/git/bin

Should read:
**In /etc/bashrc**

export PATH=$PATH:/usr/local/git/bin

**Comment by TingluoHuang** [comment]
@Dan-Co Thanks, would you like to create a Pull Request to address the issue?

**Comment by bryanmacfarlane** [comment]
This was just fixed
