### ISSUE TITLE
Archive tasks not working in 2.104.0

### ISSUE THREAD

**Issue by schnitty** [Microsoft/vsts-agent#488]
## **Agent version and platform**
Version of your agent? 2.104.0
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? https://pulselogistics.visualstudio.com
<br>
## **What's not working?** 
Archive task no longer works.  I have a build definition that includes some tasks to archive that used to work with an older agent (2.102.0 from memory) but isn't working now.

From the log on screen it looks like it is trying to execute 7zip command from the work folder: 

`exec tool: C:\Agent\_work\1\s\7zip\7z.exe`

It isn't in that location so fails?
Weird though because the _diag log shows it is pulling it from the relevant _tasks sub folder.

<br>
## **Agent and Worker's diag log**

[ConsoleArchiveFail.txt](https://github.com/Microsoft/vsts-agent/files/408151/ConsoleArchiveFail.txt)
[Worker_20160809-025605-utc.txt](https://github.com/Microsoft/vsts-agent/files/408152/Worker_20160809-025605-utc.txt)

**Comment by TingluoHuang** [comment]
@schnitty I think there is a behavior change in the agent that cause the problem. We used to have 2 agents that in different code base and written by different people. Unfortunately, in those 2 agents, how we set working folder for a task execution is a little bit different. As a result, when we come up with one agent in coreclr, we pick one of the behavior that we think is more correct. I would like to log an issue in the vsts-task repo, let the task author fix it properly.
As a temporary workaround, you can modify the downloaded task script file.
in your `C:\Agent\_work\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.0.2\archivefiles.js`
change line 19
from: 
```var winSevenZipLocation = path.join(tl.cwd(), '7zip/7z.exe');```
to: 
```var winSevenZipLocation = path.join(__dirname, '7zip/7z.exe');```

**Comment by schnitty** [comment]
Thanks, I will do that for now to get past the blocker.

**Comment by bryanmacfarlane** [comment]
Not an agent issue.  This task ships that tool.  It's a task issue:

https://github.com/Microsoft/vsts-tasks/issues/2242
