### ISSUE TITLE
Gated builds are associating to work items from previous builds

### ISSUE THREAD

**Issue by user273835** [Microsoft/vsts-agent#491]
## **Agent version and platform**
Version of your agent? 2.104.1
<br>
OS of the machine running the agent? Windows 8.1
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://qqdevelopment.visualstudio.com
<br>
## **What's not working?** 
Gated builds are associating the current changeset to all work items from previous builds.  For example, I check-in a changeset with two work items, A and B.  Then I do another checkin associated to work item C.  The gated build associates the second changeset to work items A, B, and C, even though I didn't choose to associate to A and B.

![image](https://cloud.githubusercontent.com/assets/17420310/17519755/430e675e-5e1b-11e6-8a3a-85817a5f50bf.png)

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@patrickcarnahan, can you take a look of this?
@user273835 Can you provide a clear repro screenshot? and point out which is check-in A and check-in B, and which is workitem A, B, C

**Comment by bryanmacfarlane** [comment]
I don't think this is an agent issue (this repo).  It's associated service side.  Please send a mail to us and we will follow up.  My email alias is bryanmac and I'll the appropriate folks and dig in.

**Comment by RadoslavGatev** [comment]
## **Agent version and platform**
Version of your agent? 2.104.2
<br>
OS of the machine running the agent? Windows Server 2012 DR Datacenter
<br>
## **VSTS type and version**
http://cloudepc.visualstudio.com
<br>
## **What's not working?** 
We have the same problem as described above on our side. 
@bryanmacfarlane Any update on this?

**Comment by andrewtechhelp** [comment]
We're also having this issue. Every gated check-in is just assigning dozens and dozens of work items to that changeset.

**Comment by Jazaret** [comment]
This issue is happening with us. We have tried contacting @bryanmacfarlane but have not heard a reply.  Thanks.

**Comment by ericsciple** [comment]
Tracking on this issue now: https://github.com/Microsoft/vsts-agent/issues/559
