### ISSUE TITLE
Unable to build UWP app targeting 10.0.14393.0 on hosted agent

### ISSUE THREAD

**Issue by dominik-weber** [Microsoft/vsts-agent#499]
## **Agent version and platform**
Version of your agent? 1.103.2
<br>
OS of the machine running the agent? Windows (VSTS Hosted Agent)
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://openasapp.visualstudio.com
<br>
## **What's not working?** 
When setting TargetPlatformVersion to 10.0.14393.0 the build fails with:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets (2049, 5)
Could not find SDK "WindowsMobile, Version=10.0.14393.0".
Process 'msbuild.exe' exited with code '1'.

**Comment by bryanmacfarlane** [comment]
The repo here is for the 2.x agent.  You're reporting the 1.x closed agent.  In addition to that, msbuild returned an error code of 1 (failure) so it seems like the agent did it's job.  

The key to figuring out issues like that is to look at the log and see the exact command line we ran.  Run that on the machine that your agent runs on.  If it's a hosted build machine, it might be that a certain toolset isn't present on that image - setup your own agent to troubleshoot it.

https://aka.ms/tfbuild

https://www.visualstudio.com/en-us/docs/build/troubleshooting

**Comment by dominik-weber** [comment]
Ah, I see. I wasn't sure where to post this issue, thank you for your answer!

I believe the problem here is that the UWP tools installed on the hosted agent are not up to date, I was hoping they are getting updated by MS automatically. Do you know who I can contact to solve the issue?

**Comment by bryanmacfarlane** [comment]
Send an email to me.  My alias is bryanmac.   I'll get the right folks looped in.  Keeping the image at latest is always a challenge ...
