### ISSUE TITLE
Download task susceptible to file in use errors

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#503]
Task manager logic needs to be changed away from the pattern of extracting and then moving the folder. 

Need to switch to the pattern of writing a file that indicates whether the download/extraction finished.

Tasks that contain many files (e.g. node modules) are susceptible to file in use errors on slow machines on Windows (due to anti-virus).

**Comment by bryanmacfarlane** [comment]
I think this means that all tasks would get redownloaded first time this fix is in.  Not sure it can be avoided.
