### ISSUE TITLE
Issue with Agent setup with TFS in different timezone

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#507]
TFS server is running in my local machine, which is running IST
Agent is running on VM, which is running under PDT

When I try to configure Agent to the TFS, I am getting this error

> The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.

Seems like this commit https://github.com/Microsoft/vsts-agent/commit/89512284b7f84dea84f2d4ebb7a311ccc4d82004 added this check.

**Comment by bryanmacfarlane** [comment]
And is your machine more than five minutes out of sync?  We currently have build agents running in different time zones.

**Comment by nigurr** [comment]
@bryanmacfarlane, not sure which time it's comparing with. TFS machine to Agent machine, out of day almost. I installed `ntp` and sync with internet time in build agent machine.

**Comment by TingluoHuang** [comment]
@nigurr timezone shouldn't matter, we compare UTC time. are you able to connect your agent after sync your clock?

**Comment by nigurr** [comment]
I had to force reset the clock with ntp. It's working now. 

```
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
```
