### ISSUE TITLE
Infinite loop on Agent.Listener --configure unattended command

### ISSUE THREAD

**Issue by devito** [Microsoft/vsts-agent#512]
## **Agent version and platform**
Version of your agent? 2.104.2
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://msasg.visualstudio.com
<br>
## **What's not working?** 
I was upgrading the agent on one of our server machines from Windows agent (version 1.103.2) to the xplatform agent (version 2.104.2) and hit an infinite while loop when using the unattended command.  Turns out I was missing the “--replace" command line argument so that it replaces the Windows agent with the xplat one.  I noticed this won’t repro (with the original command line) if I was to create a new agent (e.g. agent-V2-1 instead of agent-1) and try to replace it since the “config remove” properly updates the server’s record of the xplat agent but not the windows agent.

Likely the fix is to have an error and breakout [here](https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Listener/Configuration/ConfigurationManager.cs#L222).  

The commandline I used to repro:
bin\Agent.Listener configure --unattended --url https://msasg.visualstudio.com --agent Agent-Falcon-1 --pool Falcon --nostart --acceptteeeula --auth PAT --token *** --work D:\data\Agent_falcon_08_16_2016_Test\_work

**Comment by TingluoHuang** [comment]
#527
