### ISSUE TITLE
TF226001: Unable to create the detail nodes for factory QueueDetails.

### ISSUE THREAD

**Issue by TehWardy** [Microsoft/vsts-agent#513]
## **Agent version and platform**
Version of your agent? Latest (download yesterday)
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
Error in the title whenever I try to trigger a build.
Started since server reboot.

VSTS seems to think all is fine through it's options but we have a CI + gated build on check in and VS reports the above error.

Tried reinstalling the build service ... seems to have made no difference.

**Comment by TehWardy** [comment]
After the 17 hour wait from the rest of yesterday then overnight the two builds I have stacked are still sat there ... queues are showing "idle" going on to one of the builds to look into more detail just shows the message "Waiting for an agent to be requested".

I have a funny feeling this is not a problem with the build agent but VSTS itself and have no idea how to debug a service hosted by Microsoft.

**Comment by bryanmacfarlane** [comment]
Send me an email.  I will get someone to look at the backend.  my alias is bryanmac.  Send me your account name in the email as well.

**Comment by TehWardy** [comment]
Hi Bryan, thank you :) ... one question .... how do I get your email address? (sorry not a github user at all really)

**Comment by bryanmacfarlane** [comment]
my alias is bryanmac.  I work for Microsoft.

**Comment by TehWardy** [comment]
Ok sent ... sorry about that ... probably the heat in here!

**Comment by bryanmacfarlane** [comment]
This ended up being a service side issue
