### ISSUE TITLE
URL double encoding when building on OSX

### ISSUE THREAD

**Issue by thedruggist** [Microsoft/vsts-agent#516]
Agent 2.105.1 on OSX
On-Prem TFS 2015 U2

The tfs collection is named "Comans Collection". The build fails with the following:
An error occurred: The SOAP endpoint http://internalapps:8080/tfs/comans%2520collection/Services/v1.0/Registration.asmx could not be contacted.  HTTP status: 404
Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml -collection:http://internalapps:8080/tfs/Comans%20Collection/ -jwt:******** -noprompt'.

It's looks like the percent(%) is double encoded.

**Comment by bryanmacfarlane** [comment]
Is this a TEE issue or something in the agent workspace management?

**Comment by ericsciple** [comment]
Ting told me about this on Friday (I had forgotten until now). Based on conversation w/ Ting it sounds like it's probably the collection URL is already escaped, we pass to tf, and tf doubles the escaping.

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-agent/pull/626

Will be fixed when 2.108.0 releases (probably next week or so).
