### ISSUE TITLE
How to remove on-prem agent if VSTS URL has changed?

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-agent#528]
## **Agent version and platform**
Version of your agent? 2.105.0
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com 
<br>
## **What's not working?** 
The VSTS URL has changed but when I try to do `.\config remove` I get:

$ .\config remove
Removing service
Removing agent from the server
Enter authentication type (press enter for PAT) >
Enter personal access token > ****************************************************
Failed: Removing agent from the server
The resource cannot be found.

**Comment by TingluoHuang** [comment]
@jdshkolnik what do you mean by `VSTS URL has changed` ?

**Comment by jdshkolnik** [comment]
@TingluoHuang Change the Account URL under Advanced administration tasks in the settings page: https://<accounturl>.visualstudio.com/_admin/_home/settings

**Comment by bryanmacfarlane** [comment]
You can delete in the web admin UI and just wack the agent folder.

**Comment by eakoning** [comment]
If what you're trying to do is re-register the agent with a new visualstudio.com account (because the old one is no longer operational), you can delete the `.agent`, `.credentials` and `.credentials_rsaparams` files in the root of the folder. After that run `./config.cmd` again and reconfigure as if it were a fresh install. 

I think the same applies to when the _visualstudio.com_ account has been renamed (through the Admin settings).

**Comment by VictorioBerra** [comment]
I just had this same issue... was ugly.

Do the following

1. Using the Web UI, delete the agent.
2. `.\config.cmd remove`
3. It will ask for PAT/credentials. Just hit ctrl+c. At this point, the agent has been removed as a service from the machine, its only asking for creds to try and remove itself from Azure.
4. Paste the new register command with PAT that you copied from the UI.

If there is a simple place to update the URL for the azagent like the registry or a config file, I would sure love to know it.

**Comment by vinaysandela** [comment]
Thanks. 
What If the servers are decommissioned and I want to remove the Build Agents which are offline on Web UI. Is there any option to remove the Red ones. 
Thanks

**Comment by VictorioBerra** [comment]
I think you just go to organization settings and then find the deployment agents and click remove in the upper right. I'm not at a computer so those aren't exact steps but the UI has a remove button.
