### ISSUE TITLE
Input prompts not falling back to english

### ISSUE THREAD

**Issue by AshwiniChalla** [Microsoft/vsts-agent#53]
The prompt for inputs are showing prompt0 and prompt0Default1 while linux agent gives proper prompts for inputs(server url, pat etc.,). Same sequence of inputs as linux didnt work to connect to server either

**Comment by simmdan** [comment]
I experienced this as well when connecting to the mac through remote logon/ssh.  If I open the terminal window from the mac directly, then when I run the run.sh script the prompts appear properly.

**Comment by bryanmacfarlane** [comment]
yes, I think this is a remote/local thing

**Comment by bryanmacfarlane** [comment]
@AshwiniChalla - can you clarify this with more details perhaps?

> Same sequence of inputs as linux didnt work to connect to server either

You're connecting to VSTS, not on-prem correct?  (ntlm linux is in a pull request - PAT is for VSTS)

**Comment by kasubram** [comment]
I was able to reproduce the issue by changing my language & region to en-IN (from en-US). Only en-US locale string exists now. This should be fixed with this PR https://github.com/Microsoft/vsts-agent/pull/57 

If the expected locale string does not exists it should take en-US by default.

**Comment by ups216** [comment]
@simmdan @kasubram I just reproduced this issue, it's unrelated to remote/local, it's only about the locale, it doesn't give the correct string even when I'm running local terminal with Chinese locale, but when I switch the system to English, it prompts correct strings.

**Comment by kasubram** [comment]
Yes, this should be fixed with the above PR https://github.com/Microsoft/vsts-agent/pull/57

**Comment by bryanmacfarlane** [comment]
merged
