### ISSUE TITLE
JAVA system capability not detected on windows with only JDK installed

### ISSUE THREAD

**Issue by pcoombe** [Microsoft/vsts-agent#530]
## **Agent version and platform**
Version of your agent? 1.95.3
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
On-Prem TFS
2015 Update 3
<br>
## **What's not working?** 
The system cabability of 'JAVA' does not get detected if only the JDK is installed.
vsts-agent/src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1
<br>
## **Expectation**
If the JDK is installed, then it also installs the JRE, this should be detected
eg. C:\Program Files (x86)\Java\jdk1.8.0_102\jre

**Comment by bryanmacfarlane** [comment]
This repo is for the 2.x agent.  You supplied the 1.x for QU3.
