### ISSUE TITLE
Config.cmd throws "The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. "

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/vsts-agent#535]
## **Agent version and platform**
Version of your agent? 2.105.1
<br>
OS of the machine running the agent? Windows 8.1
<br>
## **VSTS type and version**
VisualStudio.com and On-Prem TFS?
<br>
If On-Prem TFS, which release, latest?
<br>
If VisualStudio.com, what is your account name? http://mseng.visualstudio.com
<br>
## **What's not working?** 
Agent.Listner is failing to start when I run config.cmd as it is not able to find api-ms-win-crt-runtime-l1-1-0.dll. I can see this dll in bin folder though. As per document there doesn't seem to be any pre req for windows 8.1 (https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envwin.md)
Please include error messages and screenshots
![image](https://cloud.githubusercontent.com/assets/1168823/17922443/a0c68920-69fc-11e6-9d56-faf11a1ed1d7.png)
Let me know if more info is required. I can share the repro machine as well.
<br>
## **Agent and Worker's diag log**
Not available as the exe didn't start even

**Comment by acesiddhu** [comment]
Just a correction api-ms-win-crt-runtime-l1-1-0.dll is not bundled in the agent. The machine where it repros doesn't have vs runtime installed and I don't see this dll in c:\windows\system32. do we need to install vc runtime on the machine that is running windows 8.1 (I see that as a pre req for windows 7 and windows server 2012)?

**Comment by bryanmacfarlane** [comment]
It looks like we do.  Validate it resolves the problem (installing the runtime) and create a PR for the doc.

**Comment by acesiddhu** [comment]
it worked fine after I installed VS (which internally install the runtime as well). After that it started to work. Checked that this api.crt*.dll were dropped into c:\windows\system32 folder after installing VS. Will update the document.

**Comment by bryanmacfarlane** [comment]
The pre-req can't be VS.  Can you validate the cruntime works?

Java customers won't install VS.

**Comment by acesiddhu** [comment]
Yes only Universal C runtime is required. I am validating that. Will send the PR after validation.

**Comment by acesiddhu** [comment]
Validated it after installing universal c runtime and it started working. updated the doc in this PR https://github.com/Microsoft/vsts-agent/pull/537
