### ISSUE TITLE
Automatic update and bundled tool versions

### ISSUE THREAD

**Issue by bgever** [Microsoft/vsts-agent#539]
We're using v2.104.2 on Win10 with VSTS, and it is unclear how the agent is updated.

Do we need to do this manually, or does it happen automatically?

[This page](https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-windows) hints the following:

> The agent automatically updates itself soon after we release a new version.
> 
> > **Note:** If your agent version is older than 102.1, then you must download and configure the agent to get the newest version.

Does that note mean that we need to upgrade manually?

We also noticed that the latest version 2.105.2 comes with NuGet 3.3.0.212, which is outdated as 3.4.4 is already available, fixing an issue we have with .NETStandard PCL's.

Since our version is still stuck at 2.104.2, does it mean automatic update doesn't happen?

**Comment by bryanmacfarlane** [comment]
In pools web admin UI there is s context menu item to update the agent.  It might take a little bit as it sends a message to the agent which downloads to the side and updates itself

We've had a few bugs in that area but it has been working for the most part.  Let us know how it goes

**Comment by bgever** [comment]
@bryanmacfarlane It was a bit hidden, but we spotted the context menu (right-click) on the Default and Hosted agent pools on the Agent Queues in the VSTS Control Panel.

After clicking, it updated the build agent to v2.105.2.

It created an alias for the original folders in the install directory, with version specific folders per version. We were not aware that the agent would do this, and it would be helpful to indicate this auto-update behavior in the installation notes.

However, even the latest v2.105.2 is still using outdated NuGet 3.3, which is not able to compile PCL assemblies targeting .NET Standard. For that we need NuGet 3.4. It would be better if the Build Agent could support this, rather than us needing to configure a custom NuGet path in all our build definitions.

**Comment by oatsoda** [comment]
I second the update to the shipped NuGet.  Would it not be better to always ship with the latest?

https://github.com/Microsoft/vsts-agent/blob/3c6145febf80de375e103c2a247bec2d4b732802/src/Misc/externals.sh#L140

You could just alter the URL to `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`

**Comment by oatsoda** [comment]
Have logged a new issue #582
