### ISSUE TITLE
When aborting the config.cmd process before setting up a service you are not asked again

### ISSUE THREAD

**Issue by Mertsch** [Microsoft/vsts-agent#541]
## **Agent version and platform**
2.105.2 Windows

When setting up a new agent, it asks you whether you want to set up a service account. If you cancel the process (or hit no?) you will never be asked again.

Starting `config.cmd` will cause a process to run in the background without any prompt and just quit without notifying the user about anything.

### Expected
Continue setup after "Setup `_work` dir" or offer some kind of reset.

### Workaround
Delete the settings files and run `config.cmd` again

**Comment by bryanmacfarlane** [comment]
Ends up being the same issue as https://github.com/Microsoft/vsts-agent/issues/330 

Running as a service is asked after the agent is configured (once).  It also has the downside of what that bug points out is you find out very late that you need to be elevated.

On the Linux/OSX code paths we fixed it by making run as svc, not run as svc and independent command (which on Linux required sudo but config doesn't).

./config.cmd remove is the workaround and reconfigure.
