### ISSUE TITLE
system.TeamFoundationServerUri is not set

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#542]
TeamFoundationCollectionUri is the correct one per docs:

https://www.visualstudio.com/en-us/docs/build/define/variables

I ran a quick build and confirmed:

SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=https://bryanmac.visualstudio.com/

TeamFoundationServerUri was from early preview.  Ironically, even in the new agent, it's marked as back compat, do not doc:

https://github.com/Microsoft/vsts-agent/blob/a809452f9235cd0ef1799fab3d1854abde8552eb/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L254

public static readonly string TFServerUrl = "system.TeamFoundationServerUri"; // back compat variable, do not document

It looks like the server stopped setting it which influence the agent to stop setting it.
https://github.com/Microsoft/vsts-agent/blob/d8e60bb361ef365106a2f37e989e17f9e344b63f/src/Agent.Worker/JobRunner.cs#L327

We will add it back to the agent as back compat ASAP before we go to next scale unit.  Thanks!

You should accept the PR for the correct one

**Comment by TingluoHuang** [comment]
#552 releases/dev15rc2
