### ISSUE TITLE
Consider granting logon as a service rights to the service user supplied

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#544]
## **Agent version and platform**
Version of your agent? 2.105.2.
<br>
Windows
<br>
## **VSTS type and version**
VSTS

**Comment by TingluoHuang** [comment]
@bryanmacfarlane  can you send me the agent diag log when you saw the behavior, we should already did it in the code?

**Comment by bryanmacfarlane** [comment]
Are you saying we already do it?

This was a DTS request:  https://mseng.visualstudio.com/b924d696-3eae-4116-8443-9a18392d8544/_workitems?id=651572&projectId=b924d696-3eae-4116-8443-9a18392d8544&src=alerts&src-action=cta&fullScreen=true&_a=edit

**Comment by TingluoHuang** [comment]
Yes, we already did it. i can following up with them for agent diag log.

**Comment by bryanmacfarlane** [comment]
I'll let them know.

**Comment by bryanmacfarlane** [comment]
Ting said we are doing this in the latest agent.  If anyone has a case where they believe we are not, reactivate this and supply _diag log.
