### ISSUE TITLE
Package Universal CRT on Windows with Agent

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/vsts-agent#556]

**Comment by TingluoHuang** [comment]
I update the build definition to copy CRT into the package. i will test it out on clean VM winserver 2012 r2

**Comment by ericsciple** [comment]
I thought we were going to prereq

**Comment by bryanmacfarlane** [comment]
wasn't this fixed?

**Comment by TingluoHuang** [comment]
I fixed it by package the CRT during releases build on build machine.
