### ISSUE TITLE
Please provide package repository's for major distributions

### ISSUE THREAD

**Issue by ruben-herold** [Microsoft/vsts-agent#558]
Hi,

please provide package repository's for your supported linux distributions. This will make it much easier 
to keep our systems on track with the releases.

**Comment by bryanmacfarlane** [comment]
The agent supports updates from the service / web UI.  Go to admin pool web UI and click update pool.  The agents will download tar gz from service and update itself.  It's also the same code paths for windows, osx and all distros of linux.  This is why it's not a package repository in linux.

**Comment by ruben-herold** [comment]
Yes but this is hard to automate and to monitor for new versions. 

For Example we use only rpm packages on our systems and so we can use a nagios plugin that is called check_updates to check for new updates for all software.
