### ISSUE TITLE
How to connect to on-premise TFS 2015?

### ISSUE THREAD

**Issue by aplex** [Microsoft/vsts-agent#56]
Looks like it is not possible to get PAT token in TFS 2015 Update 2.

And when specifying ALT credentials type, after providing user name and password, I get an error:
"An error occured.  Must call ReadCredential first."

OS X 10.11

**Comment by bryanmacfarlane** [comment]
It's feature work going on right now to do NTLM from linux.  It's in a PR

https://github.com/Microsoft/vsts-agent/pull/50 

We're working with the core CLR team on a couple of issues

**Comment by bryanmacfarlane** [comment]
closing since this is pending feature work.  I'll clarify in the docs.

**Comment by bryanmacfarlane** [comment]
BTW, thanks for trying it out.  Keep an eye out for the PR.  I'll do a patch release as soon as it comes in
