### ISSUE TITLE
Support for .NET v4.6.2

### ISSUE THREAD

**Issue by tomkerkhove** [Microsoft/vsts-agent#570]
## **Agent version and platform**
Version of your agent? 2.105.5 on Windows (Hosted VSTS Agent so I'm not sure)
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
It is not really a bug but I was wondering if there is a possibility to have .NET v4.6.2 support for hosted VSTS build agents?
- If so, how can I achieve this?
- If not, is this on the roadmap?

**Comment by bryanmacfarlane** [comment]
Yeah, not an agent bug.

Hosted image will get soon.

**Comment by tomkerkhove** [comment]
Will get the support soon or what do you mean?
