### ISSUE TITLE
Decouple config from agent

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vsts-agent#571]
It seems that the configuration location [is coupled](https://github.com/joaomoreno/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/Util/IOUtil.cs#L82) together with that of the released package; it seems to need to sit right next to the `run.sh` script et al. It would be great to decouple this similarly to how it was done for the `work` folder.

**Motivation:** I've started a [`docker`](https://github.com/joaomoreno/vsts-agent/tree/docker) branch which provides the agent as a docker container. The idea is to be allow clients of `vsts-agent` to create their own images based on that one which already contains the agent ready to run. It's required to extract the configuration out of the container, such that the same image can be used for different agents.

**Suggestion:** We could use `cwd` for this, for simplicity's sake:
- The user should be able to run the `run.sh` and `config.sh` scripts from any directory in the system.
- The configuration should be picked up based on that directory.
- That location would need to be part of the service's configuration.

I'd be glad to sketch up a PR if you think this is a good idea.

**Comment by joaomoreno** [comment]
ping @bryanmacfarlane

**Comment by bryanmacfarlane** [comment]
We will consider as part of our docker investigations.

@chrisrpatterson as well since he's digging into that

**Comment by bryanmacfarlane** [comment]
Our agent docker approach is going to be the agent/worker running in the host which executes tasks in the container.  So, I don't think we are going to do this.  Let us know if you still think it's needed.

**Comment by joaomoreno** [comment]
Let's close this.
