### ISSUE TITLE
installation instruction should specify linux or osx

### ISSUE THREAD

**Issue by ups216** [Microsoft/vsts-agent#58]
vsts-agent-linux-1.999.0-0405.tar.gz is for linux 
vsts-agent-linux-1.999.0-0405.tar.gz is for osx

people not familiar with OSX won't tell the difference, this should be clearly stated on the readme.md file. 

Also in the README.md file, the curl command is referring to the linux package and the following command is referring to osx package.

**Comment by bryanmacfarlane** [comment]
Agreed.  We're working on a vsts acquisition experience from your account where there's a download link, we detect your os and the web UI will give you the cmd lines to run (including urls).  We're even talking about streaming a script into the download with all the args set.

**Comment by bryanmacfarlane** [comment]
fixed.  updated readme

**Comment by ups216** [comment]
Great, much better. thanks a lot.
