### ISSUE TITLE
tf undo at end of a shelveset/gated build

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#588]
workaround: enable multiple checkout

alternate workaround (2x agent only): check "allow scripts access to oauth token" and add an always-run/continue-on-error step to the end of the definition to tf undo.

**Comment by ericsciple** [comment]
related:
http://stackoverflow.com/questions/39259327/tfs2015-gated-check-in-build-locking-files 

https://social.msdn.microsoft.com/Forums/office/en-US/fbf47430-471b-48b6-a67e-bc060f88681f/tfs-2015-update-2-gated-checkins?forum=tfsbuild

**Comment by bryanmacfarlane** [comment]
Is this an RTM item?  I want to understand the downside of us not doing it.  Is it annoyance (notice checked out files) or is it blocking?

**Comment by vimalthiagaraj** [comment]
![filelocked](https://cloud.githubusercontent.com/assets/22312970/18658650/8419f312-7f22-11e6-80fe-c817f8572a75.jpg)

this is what my customer is facing, Customer is in VSTS

**Comment by bryanmacfarlane** [comment]
OK.  And what issue does that cause?  What issue are you facing?

**Comment by vimalthiagaraj** [comment]
As the file is locked by the service account, even admin account could not unlock it for check out, we have to use the tf  undo command line to unlock it, this happened several times.

**Comment by ericsciple** [comment]
@vimalthiagaraj was it locked or just checked out? if just checked out, did it actually present any problem? if so, did you try the workarounds mentioned above (namely, enabling multiple-checkout)

**Comment by TingluoHuang** [comment]
#615

**Comment by danielstefanescu** [comment]
@bryanmacfarlane because of this issue we're facing the fact that the gated check-in builds are unusable (in conjunction with "Enable multiple check-out" option which is disabled).

**Comment by bryanmacfarlane** [comment]
@danielstefanescu - looks like it was fixed yesterday.  Should be in next update (2.107.1)
