### ISSUE TITLE
Enhancement suggestion: setting for delaying start of task execution

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-agent#589]
I have a Mac Mini running eight build agents. The agent frequently kicks off 4 or 5 build defs every time I commit because I have 5 separate apps in the repo whose build status I want to track independently.

Sometimes during the NuGet Restore, I receive sharing violations which make the build fail. It seems that the separate builds are sometimes trying to access a nupkg file at the same time. If one job has the file open, the other can't seem to touch it.

This happens rarely, but it does impede the quality of my build statuses.

It would be nice to have the ability to delay the start of a build def. This way, I could stagger the 4 or 5 builds that spool up each time I commit.

**Comment by TingluoHuang** [comment]
@jsauvexamarin how did you setup your agents' work directory? are those 8 agents share the same work directory, but default, each agent should have its own work directory `_work` under agent root directory, and work directory is not shareable.

**Comment by bryanmacfarlane** [comment]
As Ting noted, separate builds should never fight over a resource since the server ensures one build at a time goes to a specific agent.  Adding a wait doesn't fix anything as it's just a race at that point.  We have a workitem to prevent configuring two agents using the same _work dir (writing which agent owns).  It's an unsupported config if that is what's happening here.

**Comment by jsauvexamarin** [comment]
@TingluoHuang, I do have separate folders for each agent, named `001` through `008`. So, yes each one has its own `_work` directory.

Maybe this sharing violation is something else. It only just recently started happened. Perhaps something in side the NuGet Restore task has recently changed. It wouldn't be the first time the vsts-tasks team has broken something in the NuGet Restore task.

Which raises another issue: tasks really ought to be versioned. I ought to be able to setup a build def which references a specific version of a task. This way, ongoing changes to the task will never break my builds. This is how a competing service, Bitrise, handles tasks, and it would be a very good strategy for vsts to model.

**Comment by bryanmacfarlane** [comment]
I'll loop in the packaging folks to see what else could be causing it.  Good to hear not sharing _work

**Comment by jsauvexamarin** [comment]
Thanks @bryanmacfarlane

**Comment by jsauvexamarin** [comment]
Just to provide a little more context, it does indeed seem that this sharing violation will happen in one of those concurrently started build defs. And when I manually queue a build of that failed build def, it succeeds without issue, assumedly because the other builds aren't somehow causing a sharing violation.

I totally understand what you're saying about the different agents running in different areas of the filesystem, and I can definitely confirm that they are indeed operating in different directories.

However, it still seems that running concurrent builds is causing some kind of sharing violation.

Here's the console output, for context:
https://gist.github.com/jsauvexamarin/5c26adde6855cdba688ca42016c3c230

**Comment by bryanmacfarlane** [comment]
Can you create an issue in the tasks repo?  Not really an agent issue ...  I will get it to the packaging team
