### ISSUE TITLE
2.107 No svc.sh in OS X release download

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vsts-agent#602]
## **Agent version and platform**
Version of your agent? 2.107
<br>
OSX
<br>
## **What's not working?** 
I just downloaded the vsts-agent-osx.10.11-x64-2.107.0.tar.gz for OSX from the GitHub releases and there is no svc.sh file. The documentation still lists this to be used for running as a service. Has there been a change for this pattern?

**Comment by bryanmacfarlane** [comment]
investigating ...

**Comment by TingluoHuang** [comment]
@damienpontifex  Did you config the agent, the svc.sh is generated after you config?

**Comment by bryanmacfarlane** [comment]
I verified it's there.  @TingluoHuang is correct.  The instructions have you configure and then optionally configure as a svc.

```bash
-=B=- ~/Testing/107$ ./config.sh 

>> Connect:
Enter server URL > https://removedaccount.visualstudio.com
Enter authentication type (press enter for PAT) > 
Enter personal access token > ****************************************************
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) > 
Enter agent name (press enter for bryanmacpro) > 107osx
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
Enter work folder (press enter for _work) > 
2016-09-20 23:54:15Z: Settings Saved.
-=B=- ~/Testing/107$ ls -la
total 72

-rwxr--r--    1 bryan  staff   191 Sep 20 19:54 .agent
...
-rwxr-xr-x@   1 bryan  staff   309 Sep 19 11:23 config.sh
-rwxr-xr-x@   1 bryan  staff   670 Sep 19 11:23 env.sh
drwxr-xr-x@   5 bryan  staff   170 Sep 19 11:23 externals
-rwxr-xr-x@   1 bryan  staff   225 Sep 19 11:23 run.sh
**-rwxr-xr-x    1 bryan  staff  3207 Sep 20 19:54 svc.sh**
-=B=- ~/Testing/107$ 
```

**Comment by damienpontifex** [comment]
I did a clean download and the config reported it had already been run.
Thanks, I will run a new config and overwrite old settings and should fix as suggested
