### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by jorncommentor** [Microsoft/vsts-agent#604]
## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by bryanmacfarlane** [comment]
There's no issue specified.  Reactive with error, issue and problem.
