### ISSUE TITLE
Compiler error when building:  BuildConstants missing

### ISSUE THREAD

**Issue by OsirisTerje** [Microsoft/vsts-agent#610]
Forked and cloned the repo, started solutions for Agent worker and test (followed the instructions for creating them). 
When I compile I get a compiler error saying:
![image](https://cloud.githubusercontent.com/assets/203432/18827326/9e6d5790-83d2-11e6-8789-7af2d9fef8b9.png)

Looking the reference it is version 1.0.0.

This is with VS 2015 Update 3. 
What am I missing here?

**Comment by TingluoHuang** [comment]
@OsirisTerje you need at latest run `./dev.cmd layout` once to get that file generated then i guess you can compile it within VS.

**Comment by OsirisTerje** [comment]
Thanks!  
That did it.  This information should be added to the readme file for the project.  I'll add it in with an upcoming pull request.  :-)

**Comment by bryanmacfarlane** [comment]
@OsirisTerje - great.

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-agent/commit/a5202e94d221eeef0681ca8db2cdf4a043086ab3#diff-486e9274d3e2103abab4584f97dfc1e8
