### ISSUE TITLE
Issue downloading artifacts from VSTS to server Agent is running on

### ISSUE THREAD

**Issue by kyurthich** [Microsoft/vsts-agent#614]
## **Agent version and platform**
Version of your agent? 2.107.0.
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
https://aultcare.visualstudio.com
<br>
## **What's not working?** 

![image](https://cloud.githubusercontent.com/assets/3331097/18861843/2ba2fccc-8456-11e6-9319-4b51d96bd0e5.png)

No matter which one I try to copy files none of them make it to the server the agent is running on.

![image](https://cloud.githubusercontent.com/assets/3331097/18861834/1f0010d6-8456-11e6-877a-6bde0d128be9.png)

Not sure if this is supported or not. Looking to find out how to solve it, if it is a supported feature.

**Comment by GitHubSriramB** [comment]
@kyurthich Currently, as part of release we only support downloading only 2 types of Build artifacts - Container, FilePath. Other artifact types do not get downloaded automatically.

Could you clarify the scenario where you would like to download TfvcLabel artifact type? Also could you clarify, how you published this artifact type into Build?

**Comment by kyurthich** [comment]
I will do visuals since I do not know all the ins and outs of VSTS yet.

My goal. Have a agent running on each of: development, certification, production.

Utilize that agent to move files to that server, then possible use the WINRM tools or powershell to deploy a site in IIS.

![image](https://cloud.githubusercontent.com/assets/3331097/18961147/f5f84880-8639-11e6-99c5-ed7187578b80.png)


Build:

![image](https://cloud.githubusercontent.com/assets/3331097/18960922/577b65ca-8639-11e6-827b-e000787fd3ba.png)

![image](https://cloud.githubusercontent.com/assets/3331097/18960945/64b3a52c-8639-11e6-9568-cdd721c0bb8d.png)


![image](https://cloud.githubusercontent.com/assets/3331097/18960957/6c2351cc-8639-11e6-8958-617bd6d9d5a1.png)

Release:

![image](https://cloud.githubusercontent.com/assets/3331097/18960984/82551408-8639-11e6-9592-a06fc4263e47.png)

Tried this:
![image](https://cloud.githubusercontent.com/assets/3331097/18961029/a52dbdb8-8639-11e6-9874-b72aa9d067c4.png)


and this:

**Comment by GitHubSriramB** [comment]
Build is supposed to have two artifacts - aultcas_dev & build.SourceLabel. Release should have downloaded aultcas_dev artifact as it is of type Container. Is 20160926.8 the version of Build used in the release whose logs you shared initially? Can you confirm that the Build used for the release has "aultcas_dev" artifact published as part of it? You can do it by browsing the artifacts from the build's summary page.

**Comment by kyurthich** [comment]
So I must have made some configuration changes since that build. Because that one did not have it, 
But another one did.

And now it is copying!
So it looks like it was me not having the artifact is what caused the issue!

![image](https://cloud.githubusercontent.com/assets/3331097/18994913/ebf2a538-86f7-11e6-9f91-e391afef0118.png)

**Comment by GitHubSriramB** [comment]
Glad that you are unblocked.
