### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by alxbog** [Microsoft/vsts-agent#618]
## **Agent version and platform**
2.104.1 on MacOS
2.105.5 on Windows

## **VSTS type and version**
Team Services

## **What's not working?** 

I have two agents installed on Mac and Windows.
2.104.1 on MacOS Sierra.
2.105.5 on Windows 10.
Both agents are running as services.

The latest release is 2.107.0. Why it's not automatically updated?

**Comment by TingluoHuang** [comment]
@alxbog did you click `update all agents` in your pool admin page?
![image](https://cloud.githubusercontent.com/assets/1750815/18956294/ea14f6a0-8628-11e6-8285-2ca07477bbb7.png)

**Comment by alxbog** [comment]
Works. Thank you!

Expected that it's completely automatic.

**Comment by TingluoHuang** [comment]
@alxbog we have a story in our backlog to improve this experience, thanks for your feedback.
