### ISSUE TITLE
PAT required when you run configure.cmd remove?

### ISSUE THREAD

**Issue by DRCawthon** [Microsoft/vsts-agent#624]
## **Agent version and platform**
Version of your agent? 2.107.0
<br>
OS of the machine running the agent? Windows Server 2012 r2 Standard 
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://configureit.visualstudio.com
<br>
## **What's not working?** 
Whenever I try to reconfigure the Agent installed (or had an error installing it b/c .NET 4.5.2 wasnt installed) it says I must run configure.cmd remove to remove the old Agent. Whenever I do that it asks for the PAT during the un-install. If we didn't save this somewhere - how do we un-install? This happened on one of my VMs as well as my customer's site today (10-4-16). If you have the PAT recorded somewhere the removal process seems to work as expected.
[Agent_20161004-195400-utc.txt](https://github.com/Microsoft/vsts-agent/files/509434/Agent_20161004-195400-utc.txt)

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@DRCawthon 
There are 2 major things happen during agent uninstall.
```
1. clean any local agent setting, like uninstall windows service
2. remove the agent from server, this will make a REST call.
```
Since we don't save your pool admin token on disk, we generate a low privilege token for normal agent/server communication, so during uninstall, we need ask your pool admin PAT again.

if for some reason, you can't get the token, you have 2 options.
1. generate a new one. :)
2. manually delete all config file local and remove the agent from server.
![image](https://cloud.githubusercontent.com/assets/1750815/19091228/bc26db2a-8a4f-11e6-841f-0f4ee54cdca5.png)

**Comment by DRCawthon** [comment]
Ok so recommended practice is to save the PAT token during configuring the agent? I wasn't sure if this was by design or not. I knew this was a recent change as in the past the config simply asked if you wanted to overwrite the existing changes, not force you to remove the Agent and re-install.

**Comment by TingluoHuang** [comment]
@DRCawthon the behavior you described is for 1.x agent. Yes, the recommendation i would provide is generate a token with correct permission during agent setting up, you may config/unconfig multiple times till your finish setup your entire agent pool. after your agents are all setup, revoke the PAT or store in a security place.
