### ISSUE TITLE
Individual nuget/npm cache per agent 

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/vsts-agent#627]

**Comment by ericsciple** [comment]
Npm has a cmdline parameter to specify where the cache dir should be. Also it looks like you can specify any cmdline parameter/flag via env var.

**Comment by zjrunner** [comment]
There should be no repo overlap for sure, both nuget and npm suffer from identity confusion (the content hash is not stored in the user config, and neither has a true publisher lock yet for range/wildcard configs).  So if anything this must be a per-repo cache (or at least per project though repo is the safest), not a per-agent cache.

**Comment by milliamp** [comment]
[partial log.txt](https://github.com/Microsoft/vsts-agent/files/712742/partial.log.txt)
I have parallel builds on different build configurations and if I add a new Nuget package to the solution the first build on the build agents all fail as the first one starts downloading to the cache and then the partially downloaded file disappears and the other parallel agents report "Object reference not set to an instance of an object". 

This is on OSX, I am building a Xamarin project and it is failing during "nuget restore".
Agent.OS = darwin
Agent.Version = 2.105.7

Attached truncated log. I think this enhancement might actually fix the issue I'm having but have a check first.

**Comment by zjrunner** [comment]
Even if they were sharing a cache, on windows they take a lock on the cache folder so two instances of nuget don't fight.  What version of nuget?  I do remember a bug in one of their versions around this lock and parallel builds.

**Comment by TingluoHuang** [comment]
I am going to close this, i think we end up with creating the work temp folder per job.
