### ISSUE TITLE
Maven release plugin support and GIT broken in TFS (can be easy fix)

### ISSUE THREAD

**Issue by iano123** [Microsoft/vsts-agent#642]
## **Agent version and platform**
Version of your agent? 2.107
<br>
OS of the machine running the agent? Linux...
<br>
## **VSTS type and version**
TFS
<br>
2015
<br>

## **What's not working?** 
When we want to use the maven-release-plugin. then it has a requirement that the full repo is available. You guys are using the command: Git checkout --progress --force #####. This checks out a detached head of the REPO with the commit hash instead of the required full branch. This results in breaking the maven-release-plugin as it cannot commit the new version numbers anymore.
<br>
Solution:
please use git checkout <branchname>

**Comment by TingluoHuang** [comment]
@iano123 the reason we checkout to a detached head is to avoid create any local branch. 
you can do your own branch creation before running maven-release-plugin. 
add a command line task that run `git checkout -b maven-release` before your need run maven-release-plugin.
add another command line task to run `git branch -D maven-release` as the last step to 
make sure you delete any branch you created during the build. 

https://www.visualstudio.com/en-us/docs/build/scripts/git-commands

**Comment by iano123** [comment]
Ok fair enough. That's a good reason. We'll try it this way. Many thanks for the suggestion.
