### ISSUE TITLE
VSTS OAUTH Login Window appears during Gated Check-In Builds On Agent 2.108.0

### ISSUE THREAD

**Issue by andrewtechhelp** [Microsoft/vsts-agent#659]
## **Agent version and platform**

Version of your agent? 2.108.0
<br>
OS of the machine running the agent? Mac OS X 10.11.6
<br>
## **VSTS type and version**

VisualStudio.com or On-Prem TFS? Visual Studio Team Services
<br>
If VisualStudio.com, what is your account name? Rather not disclose publicly
<br>
## **What's not working?**

We were having problems with Issue #559 and were looking forward to version 2.108.0 of the agent fixing the issue (may have been technically fixed in 2.107.2, but our agents automatically went from 2.107.0 to 2.108.0)

However, it appears that the fix to that issue has introduced a new issue for us. During gated check in builds, when clean workspace is set to false (which is what we want to save downloading everything every time), an OAUTH window pops up asking to log into Visual Studio Team Services, blocking the build from commencing until it is closed. Closing this dialog produces the following message in the build log.

```
Cleaning last saved checkin metadata.
Failed to retrieve credentials interactively.  Check the program log files for details. To bypass web browser based interactive authentication, please set the TF_BYPASS_BROWSER_LOGIN environment variable to true. 
Default credentials are unavailable because no Kerberos ticket or other authentication token is available.
A client error occurred: Authentication credentials were not explicitly provided and could not be determined from any workspace, or argument paths provided.  Use the workspace or login option (if the noprompt option is specified, the login option value must contain the username, domain, and password).
Username: 
##[warning]Unable to clean last-saved-checkin-metadata. Exit code 100 returned from process: file name 'tf', arguments 'add /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata'.
##[command]tf undo -recursive /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata -jwt:******** -noprompt
No pending changes were found for /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata.
##[warning]Unable to undo '/Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata'. Exit code 100 returned from process: file name 'tf', arguments 'undo -recursive /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata -jwt:******** -noprompt'.
```

Following the advice there around setting the TF_BYPASS_BROWSER_LOGIN to false works in that it stops the blocking OAUTH dialog appearing and now the build does continue and succeeds, but still with problems issue #559 was trying to fix (lots of work item links being created for that changes). The build log ends up very similar to the one above, but just slightly different.

```
Cleaning last saved checkin metadata.
Default credentials are unavailable because no Kerberos ticket or other authentication token is available.
A client error occurred: Authentication credentials were not explicitly provided and could not be determined from any workspace, or argument paths provided.  Use the workspace or login option (if the noprompt option is specified, the login option value must contain the username, domain, and password).
Username: 
##[warning]Unable to clean last-saved-checkin-metadata. Exit code 100 returned from process: file name 'tf', arguments 'add /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata'.
##[command]tf undo -recursive /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata -jwt:******** -noprompt
No pending changes were found for /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata.
##[warning]Unable to undo '/Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata'. Exit code 100 returned from process: file name 'tf', arguments 'undo -recursive /Agents/Agent2/_work/24/s/__tf_clean_wksp_metadata -jwt:******** -noprompt'.
```

I can avoid all this by setting the Clean to true on the repository tab of the build definition in VSTS, but that's not a great long term solution as we're now downloading the entire codebase every check-in. There's never been login issues like this before, other than for this new "Cleaning last saved checkin metadata" step. 

Any solutions for this issue?

**Comment by bryanmacfarlane** [comment]
There was an LSI on the service with tfsvc and authentication.  That might be the issue ... Can you try again with a new set of changes?

**Comment by andrewtechhelp** [comment]
So I've tried again this morning and still having the issue. Authentication is working fine for all other parts of the build except this "Cleaning last saved checkin metadata" part.

**Comment by TingluoHuang** [comment]
@andrewtechhelp Have you ever change permission around the "Project Collection Build Service (XXX)" identity for your TFVC repository?
![image](https://cloud.githubusercontent.com/assets/1750815/19752743/a1e057b6-9bcd-11e6-9d4d-2d4bc742e87c.png)

**Comment by andrewtechhelp** [comment]
@TingluoHuang I've never changed those. The permissions for that account match the screenshot you provided.

**Comment by ericsciple** [comment]
It sounds like on OSX/Linux (uses TEE CLC), the login parameters are requried for the `tf add` cmd. I'm not sure why I didn't hit this when I tested using my vsts account.

@andrewtechhelp can you verify the workspace is a local worskpace and not a server workspace. If you send me (ersciple) one of the build logs with system.debug=true, I can skim through the log (at microsoft.com).

**Comment by andrewtechhelp** [comment]
Logs emailed. I believe they're local workspaces, whatever the VSTS agent creates by default

**Comment by ericsciple** [comment]
Thanks @andrewtechhelp. I had expected the workspaces command to indicate whether the workspace is local or server, but unfortunately it doesn't print that info. One thing you can try is dropping the workspace once to confirm the workspace gets recreated as `-location:local`.

I'll try and get a repro on this. It sounds like the fix is likely straight forward, just need to spend a little time finding the right combination of additional parameters that need to be passed to the `add` command for TEE (probably `-jwt:[...] -collection:[...] -noprompt`).

**Comment by ericsciple** [comment]
Sorry, I didn't see your latest comment when i replied. There was a point in the 2x agent when we created server workspaces, then ended up switching to local workspaces at a later point. So it depends on which version of the agent when the workspace was created.

**Comment by andrewtechhelp** [comment]
Ah yes, I remember that change now (I actually think the server workspaces caused us issues actually, so the change to local workspaces was good).

I created a new temporary build definition to reproduce this problem, so it would have created a new workspace using the 2.108.0 version of the agent, so it should be local. 

The rest of our workspaces would also be local workspaces because whenever there's an issue, the first thing I normally do is switch the Clean option on the Repository tab to true and just run a build (which seems to delete the workspace and recreates it) and then switch it back to false again. That fixes a surprisingly large number of problems actually when they occur, it's the number 1 troubleshooting solution I've personally found. So all of the build definitions would be on local workspaces by now, simply due to that.

**Comment by ericsciple** [comment]
Ok it turns out that my creds were stored in the OSX keychain. I was able to get a repro and confirm this fixes it: PR https://github.com/Microsoft/vsts-agent/pull/664

I think a workaround is to execute some tf cmd from the cmdline, which should prime the keychain. E.g. cd to the workspace and run tf status. You can use the tf cmd that is bundled with the agent (under externals/tee). Since the workspaces are created as "Public" workspaces, any valid creds with access to the workspace/repo should be OK.

**Comment by ericsciple** [comment]
this has been fixed

**Comment by andrewtechhelp** [comment]
I can confirm this is now working for us :) - Our agent updated to 2.109.1 the other day and all is well again :)
