### ISSUE TITLE
config.cmd not compatible with this version of Windows.

### ISSUE THREAD

**Issue by pierceboggan** [Microsoft/vsts-agent#665]
## **Agent version and platform**

**Agent Version**: 2.105.7
**OS Version**: Windows 10

Note that this is a virtual machine running Windows 10.

## **VSTS type and version**
VisualStudio.com

alias: piboggan

## **What's not working?** 
When running .\config.cmd, I get the following error:

> This version of C:\agent\bin\Agent.Listener.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by TingluoHuang** [comment]
@pierceboggan is your windows 10 VM 32bits or 64bits. the error is coming from windows, not the agent. the agent only support x64.

**Comment by ericsciple** [comment]
closing. please reopen if new information

**Comment by pcleckler** [comment]
System requirements indicate 32-bit compatibility.  See https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/start/envwin.md
