### ISSUE TITLE
intermittent upload artifact async command HttpRequestException: Error while copying content to a stream.

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#666]
(continuing discussion here from https://github.com/Microsoft/vsts-tasks/issues/2978)

HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: A security error occurred

@smattt do you have a proxy server? anything in eventvwr when this occurs?

**Comment by ericsciple** [comment]
@TingluoHuang this post sounds similar, although it's unclear whether it's the same issue: http://stackoverflow.com/questions/33233780/system-net-http-httprequestexception-error-while-copying-content-to-a-stream - i see in the ctor of filecontainerservice the connection passed in isnt disposed before opening a new one. i also don't know whether it matters in that particular case (i.e. if the object is really "connected" at that point). however it makes me wonder if connections are leaked elsewhere. if leaked connections is the issue, we should be able to repro by just opening a bunch of connections and not disposing.

**Comment by smattt** [comment]
We do not have a proxy server tied in to our build machine.

I poked around in the event logs on the build machine and found a ton of Schannel errors, which I initially thought may be related since other folks have correlated Schannel errors with dropped network connections.

I tried this out:

> In Group Policy Editor (run: gpedit.msc),  went to Computer Configuration > Administrative Templates > System > Distributed COM > Application Compatibility and enabled "allow local activation security check exemptions"
-https://social.technet.microsoft.com/Forums/en-US/9dfb4d09-8096-40c9-ac75-1e23f75417c9/frequent-event-id-36888-windows-schannel-errors-in-the-event-viewer?forum=W8ITProPreRel

It appears to have resolved some of our reliability issues with builds and deployments, but it did not help the Publish Artifact step - we still see regular failures that break our builds :(

**Comment by smattt** [comment]
Publish Artifacts still fails every now and then but the frequency appears to have slowed down. I'm chalking this up to the Schannel change but that may have been a red herring.

**Comment by smattt** [comment]
I take that back - it's failing consistently now. Sigh.

**Comment by TingluoHuang** [comment]
@smattt are you able to catch Fiddler trace while this error happen?

**Comment by smattt** [comment]
@TingluoHuang I actually got fed up and tried moving my build VM from West US to North Central US - which appears to have resolved the issue. I've completed 10 builds in a row without a problem, so it is looking good so far. Previously, I'd tried re-deploying my VM within the same datacenter multiple times but it never seemed to improve the network issues.

If anyone else is experiencing random network issues and your server is in the West US location, I'd recommend moving it to a new datacenter to see if it clears things up.

Thanks for the help investigating this problem!

**Comment by cornillemichiel** [comment]
Sorry for necroing this, but I believe we are facing similar issues here at our company. http://stackoverflow.com/questions/43604961/vsts-build-agent-issues-in-step-publish-artifact-drop Our build agent server is not on azure, but on an internal server on-prem, so moving it to a different data center is not possible for us.
