### ISSUE TITLE
run.sh sh shell comment is missing

### ISSUE THREAD

**Issue by ratok-mk** [Microsoft/vsts-agent#671]
## **Agent version and platform**
Version of your agent? 2.109.0
<br>
OS of the machine running the agent? Ubuntu 14.04 LTS
<br>
## **VSTS type and version**
On-Prem TFS 2015
<br>
If On-Prem TFS, which release, 2015 QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 
The run.sh script cannot be used in a manual service configuration, since the bash shell comment at the beginning is missing and the service start stop service complains.
expected: #!/bins/sh
<br>
## **Agent and Worker's diag log**
n. a.

**Comment by TingluoHuang** [comment]
@ratok-mk you should use `runsvc.sh` in order to configure service on Linux, is that what you looking for?

**Comment by ratok-mk** [comment]
Thats right I would use the svc. sh script if systemd is installed on the system. Unfortunately, when systemd is not available the run.sh script is missing the #!/bin/bash comment at the beginning. That should be easy to fix as far as I am concerned.

**Comment by ericsciple** [comment]
ah, it looks like we added `#!/bin/bash` to the other sh scripts, but missed run.sh and config.sh

**Comment by ericsciple** [comment]
Thanks! The [commit](https://github.com/Microsoft/vsts-agent/commit/1472d24ebee1584b2a67358e40e07de0a43a07f0) will be included in the next agent release (109.2)
