### ISSUE TITLE
./config.sh remove errors

### ISSUE THREAD

**Issue by sidharthnayyar** [Microsoft/vsts-agent#674]
## **Agent version and platform**
Version of your agent? 2.105.6
<br>
OS of the machine running the agent? OSX
<br>
## **VSTS type and version**
VisualStudio.com 
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 
running `./config.sh remove` 
gives the following error:

> Failed: Removing agent from the server
> The type initializer for 'System.Net.Http.CurlHandler' threw an exception.

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

in the _diag directory, the Agent log has:
> [2016-11-07 15:12:32Z INFO AgentProcess] Agent is built for OSX - osx.10.11-x64.
> [2016-11-07 15:12:32Z INFO AgentProcess] RuntimeInformation: Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64.
> [2016-11-07 15:12:32Z INFO AgentProcess] Version: 2.105.6
> [2016-11-07 15:12:32Z INFO AgentProcess] Commit: b3827d025dc36474c2a2dc419f49e05df1e9ae9d
> [2016-11-07 15:12:32Z INFO AgentProcess] Culture: en-US
> [2016-11-07 15:12:32Z INFO AgentProcess] UI Culture: en-US
> [2016-11-07 15:12:32Z INFO HostContext] Well known directory 'Bin': '/Users/pembuilduser/myagent/bin'
> [2016-11-07 15:12:32Z INFO HostContext] Well known directory 'Root': '/Users/pembuilduser/myagent'
> [2016-11-07 15:12:32Z INFO AgentProcess] Validating directory permissions for: '/Users/pembuilduser/myagent'
> [2016-11-07 15:12:32Z INFO CommandLineParser] Parse
> [2016-11-07 15:12:32Z INFO CommandLineParser] Parsing 1 args
> [2016-11-07 15:12:32Z INFO CommandLineParser] parsing argument
> [2016-11-07 15:12:32Z INFO CommandLineParser] HasArgs: False
> [2016-11-07 15:12:32Z INFO CommandLineParser] Adding Command: remove
> [2016-11-07 15:12:32Z INFO AgentProcess] Arguments parsed
> [2016-11-07 15:12:32Z INFO ProxyConfiguration] No proxy setting found.
> [2016-11-07 15:12:32Z INFO Agent] ExecuteCommand
> [2016-11-07 15:12:32Z INFO ConfigurationStore] currentAssemblyLocation: /Users/pembuilduser/myagent/bin/Agent.Listener.dll
> [2016-11-07 15:12:32Z INFO ConfigurationStore] binPath: /Users/pembuilduser/myagent/bin
> [2016-11-07 15:12:32Z INFO ConfigurationStore] RootFolder: /Users/pembuilduser/myagent
> [2016-11-07 15:12:32Z INFO ConfigurationStore] ConfigFilePath: /Users/pembuilduser/myagent/.agent
> [2016-11-07 15:12:32Z INFO ConfigurationStore] CredFilePath: /Users/pembuilduser/myagent/.credentials
> [2016-11-07 15:12:32Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/pembuilduser/myagent/.service
> [2016-11-07 15:12:32Z INFO CommandSettings] Flag 'help': 'False'
> [2016-11-07 15:12:32Z INFO CommandSettings] Flag 'version': 'False'
> [2016-11-07 15:12:32Z INFO CommandSettings] Flag 'commit': 'False'
> [2016-11-07 15:12:32Z INFO CommandSettings] Command 'configure': 'False'
> [2016-11-07 15:12:32Z INFO CommandSettings] Command 'remove': 'True'
> [2016-11-07 15:12:33Z INFO Terminal] WRITE LINE: Removing service
> [2016-11-07 15:12:33Z INFO ConfigurationStore] IsServiceConfigured()
> [2016-11-07 15:12:33Z INFO ConfigurationStore] IsServiceConfigured: False
> [2016-11-07 15:12:33Z INFO Terminal] WRITE LINE: Removing agent from the server
> [2016-11-07 15:12:33Z INFO ConfigurationStore] IsConfigured()
> [2016-11-07 15:12:33Z INFO ConfigurationStore] IsConfigured: True
> [2016-11-07 15:12:33Z INFO ConfigurationStore] HasCredentials()
> [2016-11-07 15:12:33Z INFO ConfigurationStore] stored True
> [2016-11-07 15:12:33Z INFO ConfigurationManager] GetCredentialProvider
> [2016-11-07 15:12:33Z INFO CommandSettings] Arg 'auth': ''
> [2016-11-07 15:12:33Z INFO CommandSettings] Flag 'unattended': 'False'
> [2016-11-07 15:12:33Z INFO PromptManager] ReadValue
> [2016-11-07 15:12:33Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
> [2016-11-07 15:12:33Z INFO Terminal] READ LINE
> [2016-11-07 15:12:36Z INFO Terminal] Read value: 'PAT'
> [2016-11-07 15:12:36Z INFO ConfigurationManager] Creating credential for auth: PAT
> [2016-11-07 15:12:36Z INFO CredentialManager] GetCredentialProvider
> [2016-11-07 15:12:36Z INFO CredentialManager] Creating type PAT
> [2016-11-07 15:12:36Z INFO CredentialManager] Creating credential type: PAT
> [2016-11-07 15:12:36Z INFO PersonalAccessToken] EnsureCredential
> [2016-11-07 15:12:36Z INFO CommandSettings] Arg 'token': ''
> [2016-11-07 15:12:36Z INFO CommandSettings] Flag 'unattended': 'False'
> [2016-11-07 15:12:36Z INFO PromptManager] ReadValue
> [2016-11-07 15:12:36Z INFO Terminal] WRITE: Enter personal access token > 
> [2016-11-07 15:12:36Z INFO Terminal] READ SECRET
> [2016-11-07 15:13:28Z INFO Terminal] Read value: '********'
> [2016-11-07 15:13:28Z INFO PersonalAccessToken] GetVssCredentials
> [2016-11-07 15:13:28Z INFO PersonalAccessToken] token retrieved: 52 chars
> [2016-11-07 15:13:28Z INFO ConfigurationManager] cred retrieved
> [2016-11-07 15:13:28Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
> [2016-11-07 15:13:28Z ERR  Agent] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
>  (Exception from HRESULT: 0x8007007E)
>    at Interop.CryptoInitializer.EnsureOpenSslInitialized()
>    at Interop.CryptoInitializer..cctor()
>    --- End of inner exception stack trace ---
>    at Interop.CryptoInitializer.Initialize()
>    at Interop.HttpInitializer..cctor()
>    --- End of inner exception stack trace ---
>    at Interop.HttpInitializer.Initialize()
>    at Interop.Http..cctor()
>    --- End of inner exception stack trace ---
>    at Interop.Http.GetSupportedFeatures()
>    at System.Net.Http.CurlHandler..cctor()
>    --- End of inner exception stack trace ---
>    at System.Net.Http.CurlHandler..ctor()
>    at System.Net.Http.HttpClientHandler..ctor()
>    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler..ctor(VssCredentials credentials, VssHttpRequestSettings settings)
>    at Microsoft.VisualStudio.Services.Agent.Util.ApiUtil.CreateConnection(Uri serverUri, VssCredentials credentials, IEnumerable`1 additionalDelegatingHandler)
>    at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<UnconfigureAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
> [2016-11-07 15:13:29Z ERR  Terminal] WRITE ERROR: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.

**Comment by sidharthnayyar** [comment]
BTW the openssl version is:
```
openssl version
OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by TingluoHuang** [comment]
@sidharthnayyar 
Have you try update openssl version?
```
brew update
brew install openssl
brew link --force openssl
```

**Comment by sidharthnayyar** [comment]
Hi,
Was just about to message that scratch that: `brew link --force openssl` fixed it. Thank you anyway @TingluoHuang.

Kind regards
Sidharth

**Comment by TingluoHuang** [comment]
@sidharthnayyar cool, glad you unblock.
