### ISSUE TITLE
Where do I add variables for "VSTS_GITPATH" or "VSTS_variableNameHere"?

### ISSUE THREAD

**Issue by Kollibri** [Microsoft/vsts-agent#676]
I've seen several mentions in the issues about setting variables for the build agent such as follows:

VSTS_GITPATH=%PathToGit%

But where do I set these variables?  Is there a config file used by the build agent that I need to set it in?  If so, where is it located?

We are using TFS 2015 On Premises with update 2.

**Comment by TingluoHuang** [comment]
@Kollibri It's environment variable on your build machine.

**Comment by Kollibri** [comment]
Thanks!
