### ISSUE TITLE
Git fails with self-signed certificate?

### ISSUE THREAD

**Issue by Kollibri** [Microsoft/vsts-agent#677]
## **Agent version and platform**
Version of your agent? 2.109.1
<br>
OS of the machine running the agent? OSX/Windows/Linux...
Windows
<br>
## **VSTS type and version**
On-Prem TFS 2015 with Update 2
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
2015 Update 2
## **What's not working?** 
In order to use GIT locally on my workstation to connect to our TFS server, I have to add the ssl cert to the end of the "ca-bundle.crt" file in my git global installation location (which happens to be "C:\Program Files\Git\mingw64\ssl\certs").  This allows git to recognize the ssl cert for our self-signed certificate on the TFS server.

GIT is not installed globally on the build server, instead we were hoping to reply on the GIT that is included with the build agent.  We have added the cert for the tfs server to the end of the .cert file for the build agent located at "'D:\TFSAgents\VSBuild3\externals\git\mingw64\ssl\certs", but the build still fails when trying to get sources from the git repository.

We even tried setting the global git config variable "http.sslVerify" to "false" to completely ignore sslVerification globally on the build server, but the "get sources" step always fails with the following error:

> fatal: unable to access 'https://test-tfs.company.com/tfs/Treasury/TL41%20Industrial%20Facility%20Exemption/_git/TL41%20IFE%20Git/': SSL certificate problem: unable to get local issuer certificate

We are not sure what else to do.  Does the agent not support git over ssl with self-signed certificates?

I have attached the build log for review.
[1_Build.txt](https://github.com/Microsoft/vsts-agent/files/583384/1_Build.txt)

And also the output from the "git config --list" command showing the git configuration for the build agent.
![l_2795 tmp](https://cloud.githubusercontent.com/assets/533377/20177602/9a4190e8-a71b-11e6-9ecc-7d9fdc2929c5.PNG)

We have also tried manually setting the "http.sslcainfo" value in the git config to the explicit location of the cert file, with no effect.

Any ideas?

**Comment by TingluoHuang** [comment]
@lukekim is your agent running as windows service or interactive? if it's running as service, you need set system level git config if the service is running as an account other than your logon account, like NETWORKSERVICE.  
```
git config --system http.sslVerify false
```

**Comment by TingluoHuang** [comment]
click the wrong button...

**Comment by Kollibri** [comment]
That appears to have resolved the issue.  Thank you so much!

**Comment by Burbert** [comment]
I still have the issue, I have an TFS 2018 RC2 and currently one agent, both running on differend servers with 2012 R2 as OS. The Root- and Sub CA Cert is installad within the git store and it worked until today, I don't really get it, because the only issue that seems to be present is the one where the cert is not installed. Even 'git config --system http.sslVerify false' did nothing :( any suggestions?

**Comment by TingluoHuang** [comment]
@Burbert the agent carries its own copy of `MinGit`. `git config --system` will only affect git installed in your  `%PATH%`, you can use `git config --global` as long as you run the `git config` as same user your agent run as.
