### ISSUE TITLE
If using an envvar (not file config), Proxy authentication credentials displayed in plain text under Agent Capabilities

### ISSUE THREAD

**Issue by yugmac** [Microsoft/vsts-agent#686]
## **Agent version and platform**
Version of your agent? 2.109.2
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://vsosse.visualstudio.com
<br>
## **What's not working?** 
When running an Agent behind a proxy server, the authentication credentials need to be stored as Environmental Variables. The information is masked in logs and console output, however they are displayed in plain text under Capabilities on the Agent Pool page in VSTS. Screenshot below shows this. 
<br>
![image](https://cloud.githubusercontent.com/assets/23236859/20353014/54111b98-ac11-11e6-99fb-7927b2b4df54.png)

**Comment by TingluoHuang** [comment]
We need mask secrets in agent capabilities as well

**Comment by bryanmacfarlane** [comment]
closing since the fix is merged.  should be in next version of agent
