### ISSUE TITLE
On-Prem Update All Agents

### ISSUE THREAD

**Issue by Gimpan** [Microsoft/vsts-agent#691]
## **Agent version and platform**
Version of your agent? 2.105.6
<br>
Windows Server
<br>
## **VSTS type and version**
On-Prem TFS 2017
<br>
2016 november release
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 

Is it possible to update the agents through "Agent Pools -> All Pools -> Pool -> Update All Agents"? Currently when I try to do this, my agents(AgentListener) shuts off and nothing happens.

How do you update agents On-Premise? Do I have to download it from here?

**Comment by TingluoHuang** [comment]
@Gimpan update all agents will update all your agents within the pool to the latest version within the same major version.
in TFS2015, we shipped the new build agent which is version 1.x, it only works for windows platform.
in TFS2017, we shipped a newer major version agent 2.x, it written in dotnet core, which will works in Linux and OSX as well.
Your TFS server has the knowledge of all the agent version we shipped. we don't support update across major version, which mean, 1.x agents will not update to 2.x
Since you already in 2.105.6, which is the latest version for TFS2017, you won't get any update until 2017 QU1.

**Comment by bryanmacfarlane** [comment]
If you want 2.x agents on prem, go to the admin pages and download the agent.  TFS 2017 RTM points to 2.105.6.  You can manually download a later one from releases in this repo if you need to (there's a bug fix you need in a later version).  As Ting pointed out, QU1 will point to a later agent.  The server points to the agent version it was tested and released with.

**Comment by jabbera** [comment]
Sorry to bring this back up be we need https://github.com/Microsoft/vsts-agent/issues/898 deployed to all of our build agents (about 70). Is there a way to "teach" TFS 2017 update 2 about it so we don't have to manually deploy it?

**Comment by sheldonhull** [comment]
I have found that the _update agents_ will not work on premise, with TFS 2017 Update 2. For instance, if an agent is  `2.117.2` and I choose to run update agents, it will not update them to `2.124.0` 

I can do this manually with a powershell script using post/etc, but was hoping that the update process would have removed the need to update individual agents with bug fixes

**Comment by TingluoHuang** [comment]
@sheldonhull `2.117.2` is the latest version of the agent at the time we shipped with 2017 QU2
https://github.com/Microsoft/vsts-agent/releases/tag/v2.117.2
I think we can add a feature to allow on-prem customer keep updating their agent to latest.
@chrisrpatterson @bryanmacfarlane  for thoughts.

**Comment by bryanmacfarlane** [comment]
I agree.  This is on our backlog along.  Right now you can download latest from github but that's a manual update. (download, unzip, config).

**Comment by sheldonhull** [comment]
@bryanmacfarlane @TingluoHuang  following up a while later. Hoping you can clarify if this was ever completed or any general idea of timeframe. Would like to ensure my on-prem agents are updated without all the scripted workaround I've had to use. A chocolately package or feed url for direct download of latest would simplify it a lot, vs parsing github release listing to match with regex. thanks!

**Comment by bryanmacfarlane** [comment]
@sheldonhull - it's schedule for the next sprint as we're targettng next major release of on prem TFS.

**Comment by sheldonhull** [comment]
So will this be available for TFS 2017 v2 as part of the new agent, or will it require a new TFS version? Thanks!

**Comment by bryanmacfarlane** [comment]
It will require server work so it will be available on upgrade.  The server offers the update feature for versions it knows about.

**Comment by sheldonhull** [comment]
@bryanmacfarlane ok, so i still need to manually update agent if I'm on an older version but want the latest minor releases applied?

**Comment by sheldonhull** [comment]
If this is the case, could you consider adding some type of consistent feed url or chocolately package so it would be easy to script he update. Right now I have to parse github body text and it has changed slightly so things break. Someway to get release listing in consistent format for windows would be great

**Comment by TingluoHuang** [comment]
The feature is in Azure DevOps Server 2019
https://docs.microsoft.com/en-us/tfs/release-notes/azuredevops2019#locally-update-your-agent

**Comment by DalpheSDC** [comment]
How do you configure the path to the local agent zip file?

**Comment by kjsmithtx** [comment]
I would also like to know how to configure the path to the local agent zip file.  Can't find any documentation on the process, just that it supposedly can be done.

**Comment by TingluoHuang** [comment]
@kjsmithtx https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2019#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool?

**Comment by sheldonhull** [comment]
For those on TFS it's also a Choco package now. Just run `Choco upgrade azuredevopsagent` . This saved me a lot of time
