### ISSUE TITLE
.NET Core 1.1 tooling on hosted agent

### ISSUE THREAD

**Issue by henkmollema** [Microsoft/vsts-agent#693]
Windows hosted agent `2.109.1` on VisualStudio.com.

Is there a timeline for the latest .NET Core 1.1.0 preview to be installed on the hosted agent in VSTS? Currently only 1.0.0 and 1.0.1 are installed and this forces us to manually install 1.1.0 on every build.

**Comment by TingluoHuang** [comment]
@henkmollema it's on our radar, probably next week? @thechrisjohnson

**Comment by henkmollema** [comment]
@TingluoHuang thanks for the update!

**Comment by bryanmacfarlane** [comment]
This repro is about the agent (which does not carry the tools).  The hosted image does.

**Comment by henkmollema** [comment]
@bryanmacfarlane is there a repo for the hosted image?

**Comment by baywet** [comment]
I think this issue should be reopened, The 1.1 version of dotnet core went RTM a couple of weeks ago. Building and deploying from vsts hosted agent to Azure app services results in no error during the CI  process.   
However the application on the app service never start and you get a 502.5 enable to start application error when trying ot access it. (see attachment)
Thanks @MaximRouiller for helping me troubleshooting this.
[ErrorPage000030.zip](https://github.com/Microsoft/vsts-agent/files/624930/ErrorPage000030.zip)

**Comment by MaximRouiller** [comment]
It is important to note that, publishing through Visual Studio works but publishing through VSTS doesn't.

**Comment by MaximRouiller** [comment]
Where should this issue be reported?

**Comment by bryanmacfarlane** [comment]
developercommunity.visualstudio.com

However, it's being worked on today and it's known work so not sure it will buy you anything.  Good to know going forward.

**Comment by bryanmacfarlane** [comment]
>> It is important to note that, publishing through Visual Studio works but publishing through VSTS doesn't.

It works if you provision your own VM (always the way to control the toolsets).  There's just latency in the convenient hosted pool image getting updated.
