### ISSUE TITLE
MacOS - Visual Studio Support

### ISSUE THREAD

**Issue by thomas-goerlich** [Microsoft/vsts-agent#694]
## **Agent version and platform**
2.109.2
MacOS
<br>
## **VSTS type and version**
On-Prem TFS
TFS 2015 Update 3 (14.102.25423.0 ) 
<br>
## **What's not working?** 
Visual Studio for Mac is not supported in the current Version. The agent checks only for the hard coded path "/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" (https://github.com/Microsoft/vsts-agent/blob/f7e9a7ee42d0c30f0d31d449bb51d95bd6e9e0fb/src/Agent.Listener/Capabilities/NixCapabilitiesProvider.cs#L66) to set the "Xamarin.iOS" support feature.
<br>
## **Agent and Worker's diag log**
There is no relevant log.
<br>
## **Work around**
As a work around we set the Xamarin.iOS variable manually in the build agent and changed the mdtool path in the Xamarin iOS Build step to "/Applications/Visual Studio.app/Contents/MacOS/vstool".

**Comment by TingluoHuang** [comment]
@thomas-goerlich Cool, thanks for report, we haven't try VS for Mac. Do you want to create a PR to fix this? :)

**Comment by TingluoHuang** [comment]
@madhurig FYI

**Comment by thomas-goerlich** [comment]
I don't really know how to fix this (i am not that familiar with the TFS infrastructure/build agents).
Since mdtool was renamend to vstool in Visual Studio for Mac i would think i need to copy the builder.Check() command but what if Xamarin Studio and Visual Studio are both installed on the server? Wouldn't there be two entries for Xamarin.iOS in the build agent or one would override the other?

Sorry i am not much of a help here but at least the problem is reported now :-)

**Comment by madhurig** [comment]
@thomas-goerlich : Thank you for reporting the issue. We will address the issue. You can workaround it by adding the Xamarin.iOS capability manually on your build agent from the web UI. 

Thanks,
Madhuri

**Comment by TingluoHuang** [comment]
Close as #744 merged
