### ISSUE TITLE
Agent Crashing Agent.Listener.exe KERNELBASE.dll

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vsts-agent#700]
## **Agent version and platform**
Version of your agent? .2.108.0.
<br>
## **OS**
Server 2016
<br>
## **VSTS type and version**
VisualStudio.com
<br>

## **What's not working?** 
Had an issue last night where agent went offline. I checked the build server and tried the usual things restart of service and then when that failed the server.  However it was still not working and when I looked into event viewer logs I saw that the Agent.Listener.exe was crashing.  Once I removed config and reconfigured agent it all started working again.

However it would be good to understand why this failed?  The error message is as follows:

<br>
Faulting application name: Agent.Listener.exe, version: 1.0.1.4500, time stamp: 0x576218d2<br>
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c4f0<br>
Exception code: 0xe0434352<br>
Fault offset: 0x0000000000017788<br>
Faulting process id: 0x1fa4<br>
Faulting application start time: 0x01d24ae5465ab81d<br>
Faulting application path: d:\agent04\bin\Agent.Listener.exe<br>
Faulting module path: C:\Windows\System32\KERNELBASE.dll<br>
Report Id: b9dfa07d-3056-4ec8-a7c7-c336a69cfaef<br>
Faulting package full name: <br>
Faulting package-relative application ID: <br>

<br>

Anyideas on what might cause it to be crashing?

From

Russell

**Comment by TingluoHuang** [comment]
@russelldyas I did some search online, seems like a windows update issue, are you also on win10 anniversary update?

**Comment by russelldyas** [comment]
@TingluoHuang It is server 2016 and is on 14393.351.  

Have you got a link for information about update issue?  

Got a couple of updates to install major one is https://support.microsoft.com/en-us/kb/3200970 but being as currently some problems with this at the moment want to try and hold off installing that.

From

Russell

**Comment by TingluoHuang** [comment]
@russelldyas try out the latest released agent since we consume dotnet core 1.1, they may improve their reliability, the error is coming from KERNELBASE.dll which the agent doesn't carry.
