### ISSUE TITLE
Support of Intel Stack on Visual Studio Online Continuous Integration

### ISSUE THREAD

**Issue by mancoast** [Microsoft/vsts-agent#719]
I require Intel Stack on VSO CI.
Please considered the added value of an additional compiler platform.

**Comment by bryanmacfarlane** [comment]
The agent doesn't deliver tools and never should.  That creates a bad coupling.

This is about the OS / image that that agent is installed on.  If you're referring to the hosted pool (our convenience image), then it should be noted that it will never contain all the possible developer tools and every version.  

To control the toolsets you want installed, you can configure your own private agent - on an azure VM or your own machine.  That gives you tool control, incremental build and incremental source as well.

https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-windows

**Comment by mancoast** [comment]
This issue marks initiation of conversation of Intel Stack CI support in VSO.
Is there a more fitting Microsoft project with which to open an issue?
This issue requires support/interoperation between Intel & Microsoft.
