### ISSUE TITLE
Authentication issue running any build on Ubuntu 16.04

### ISSUE THREAD

**Issue by kzettlmeier** [Microsoft/vsts-agent#724]
## **Agent version and platform**
Version of your agent? 2.109.2
<br>
OS of the machine running the agent? Ubuntu 16.04
<br>
## **VSTS type and version**
On-Prem TFS
<br>
2015 Update 2.1
<br>
## **What's not working?** 
I have gotten the agent up and running on my machine successfully, but anytime I run a build, I see it connect but it fails every time after about 3 seconds.  When I look in the logs, the last message I see is:`[2016-12-16 20:57:31Z ERR  Program] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://****:8080.`
Does http://***:8080 need to be accessible, because most are unauthorized from viewing that portion of TFS on our side?  The agent user has access to http://***:8080/tfs which is what is configured for the build agent as the URL.

**Comment by ericsciple** [comment]
@kzettlmeier Can you try [these steps](https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md) (documentation from older agent)?

I think our current docs may be missing some instructions when configuring against TFS 2015.

**Comment by ericsciple** [comment]
...specifically the `Account and Roles` section (make sure account is added to Agent Pool Service Accounts and Project Collection Build Service Accounts)

**Comment by ericsciple** [comment]
I'm unable to reproduce the issue against TFS 2015 U3. It looks like the current auth issues are all for TFS 2015 RTM or TFS 2015 U2. I'll setup one of those server and see if I can repro.

**Comment by kzettlmeier** [comment]
@ericsciple we have made sure that the account is added to the Agent Pool Service Accounts and Project Collection Build Service Accounts.  We would appreciate any help with setting up a TFS 2015 update 2 server and trying.

We did read somewhere about it maybe wanting https?  Our server is currently internal only and was not setup with SSL/HTTPS, could this be causing any issue?

**Comment by ericsciple** [comment]
When I attempted to repro the issue against TFS 2015 U3, IIS was setup like this:
* Team Foundation Server Website authn settings:
 - Anonymous Authentication Enabled
 - All others disabled
* tfs web app authn settings:
 - Windows Authentication Enabled (NTLM provider only; Enable kernel mode authentication checked)

App pool is running as Network Service.

I created a local user on the TFS machine (using lusrmgr.msc), and specified those creds when configuring the agent.

**Comment by ericsciple** [comment]
The only binding I had was http on port 8080 and ip address *. I think HTTPS is only required when attempting to use Basic authentication.

**Comment by ericsciple** [comment]
@kzettlmeier I tried today and was able to successfully configure against a TFS 2015 Update 2 server.

Can you send ersciple a zip of your _diag folder? (at microsoft com)

**Comment by TingluoHuang** [comment]
@kzettlmeier 
1. Have you try configure a windows agent to the same TFS service? I want to understand whether this is an issue for Non-windows platform only
2. If you have access to your TFS AT, can you check the event log? there should be an error correspond to the client side error.

**Comment by kzettlmeier** [comment]
@TingluoHuang @ericsciple 

Thank you for taking a look.  It looks like another colleague of mine has gotten everything working by using the tar file here: https://github.com/Microsoft/vsts-agent/releases/tag/v2.109.2 while I was trying to run the source code by cloning the repository.

Either way everything seems to working at this point.  Thank you again.
