### ISSUE TITLE
Issue with visual studio build agent behind a proxy

### ISSUE THREAD

**Issue by abeally85** [Microsoft/vsts-agent#726]
## **Agent version and platform**
Version of your agent? 2.110
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? https://markerstudy-tfs.visualstudio.com
<br>
## **What's not working?** 
I am currently setting up continuous integration using visual studio online with onsite build agents, but I am having issues with my company's proxy.

I have tried adding the .proxy file but my companys proxy is still blocking it (it is a very old proxy).

Speaking to my infrastructure guys they can bypass the proxy but need all the urls that the build agent calls. 

Unfortantely I can not find a list online of all the urls that it requires, I know it needs the following:

 https://xxxxxxxxx.visualstudio.com
 https://xxxxxxxxx.vssps.visualstudio.com
 
Does anyone know all the other urls that an onsite build agent calls?
<br>

**Comment by jessehouwing** [comment]
Initial stab over at StackOverflow http://stackoverflow.com/a/41197922/736079

**Comment by TingluoHuang** [comment]
@abeally85 
Here is a list of Url VSTS might use:
https://msdn.microsoft.com/en-us/library/mt604698.aspx

**Comment by TingluoHuang** [comment]
https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#how-do-i-configure-the-agent-to-bypass-a-web-proxy-and-connect-to-team-services
