### ISSUE TITLE
File being Used by another proccess after first run

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/vsts-agent#728]
## **Agent version and platform**
2.110.0
<br>
Windows 10
<br>
## **VSTS type and version**
VisualStudio online
<br>
https://gmpsoftware.visualstudio.com/
<br>
## **What's not working?** 
After running once the next time the automated build runs it returns:

> The process cannot access the file '\\?\C:\agent\_work\2\s\F\FS\FieldStrikeMove.Droid' because it is being used by another process.

This error happens at the "Get Sources" stage

After restarting my on site build machine it works again

**Comment by bryanmacfarlane** [comment]
I assure you it's not the agent holding onto your .Droid file.  It knows nothing about that.  It's something in your build process.

You need to find out what in your build / test process is holding onto to that file.

See file in use section here:
https://www.visualstudio.com/en-us/docs/build/troubleshooting
