### ISSUE TITLE
##vso[task.uploadfile] does not work (VSTS)

### ISSUE THREAD

**Issue by AlexHimself** [Microsoft/vsts-agent#732]
## **Agent version and platform**
vsts-agent-win7-x64-2.109.1.zip
<br>
Windows Server 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? https://axtras.visualstudio.com
<br>
## **What's not working?** 
File uploads don't appear to work with PowerShell. I'm using VSTS with a local build agent running in interactive mode as administrator.

I have a very basic PowerShell script that runs this:

Write-Host "Uploading C:\TEMP\TestUploadFile.txt"
Write-Host "##vso[task.uploadfile]C:\TEMP\TestUploadFile.txt"

I've used Charles (like Fiddler) and I see at some point the file contents are being passed but I can't find the uploaded file anywhere. This is just a very basic test to upload a local file. In my actual use case, the file will be a large non-txt file, so I can't just output the contents.

<br>
## **Agent and Worker's diag log**

[Agent_20161222-190332-utc.txt](https://github.com/Microsoft/vsts-agent/files/669620/Agent_20161222-190332-utc.txt)
[Worker_20161222-190339-utc.txt](https://github.com/Microsoft/vsts-agent/files/669619/Worker_20161222-190339-utc.txt)

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md
>Upload user interested file as additional log information to the current timeline record. The file shall be available for download along with task logs.
Example: 
##vso[task.uploadfile]c:\additionalfile.log

**Comment by ericsciple** [comment]
artifact.upload might be what you are looking for

**Comment by AlexHimself** [comment]
Ah so are you saying it only uploads *.log files?

**Comment by ericsciple** [comment]
no you can upload anything, but the way to retrieve it is to click the Download Logs button to download the zip containing the build logs. so it would be useful if your scenario is that you generate additional logs and want to attach them to the same place the rest of the build logs are stored.

otherwise, artifact.upload might be more interesting for you, if you are looking for a quick way to download a file from the artifacts tab after the build completes. also the artifacts can be accessed via the REST API.

**Comment by AlexHimself** [comment]
Artifact.upload is definitely interesting to me. The problem still exists though I think. I download all logs, and no file exists?  I renamed the file to *.log just in case.

See screenshots. I did a PowerShell tree to just display the downloaded log contents.

![image](https://cloud.githubusercontent.com/assets/10466466/21438253/dff8edf6-c83c-11e6-9a46-60177c0f573d.png)
![image](https://cloud.githubusercontent.com/assets/10466466/21438256/e3d9d6b0-c83c-11e6-87bd-4432ae2ae43a.png)
![image](https://cloud.githubusercontent.com/assets/10466466/21438270/f40c761e-c83c-11e6-8507-4ea0f9cfb9cb.png)

**Comment by AlexHimself** [comment]
I did just test artifact.upload and that does work for file upload, so that's fantastic. Is there any file-upload progress if I were to upload a 1GB file?

I do also want to use task.uploadfile to upload actual log files though. Am I doing it wrong? It just doesn't seem to work.

**Comment by ericsciple** [comment]
is there anything in the file, or is it zero bytes?

can you run a build with the variable `system.debug` set to `true`. then the agent should print `Processed: ##vso...` for the command that was processed.

what does your ps1 script look like?

**Comment by AlexHimself** [comment]
The file I'm trying to upload has data. I've included a screenshot of the PowerShell script, and what's interesting is the line I have commented out worked fine and uploaded the file.

Ignore the part where it says "Uploading C:\Temp\C:\Temp"... as that's just copy/paste error, but the actual line is correct.

With `debug` set to `true` it does say `Processed`

![image](https://cloud.githubusercontent.com/assets/10466466/21438717/5a27ca3c-c83f-11e6-979b-a9050b5e0148.png)
![image](https://cloud.githubusercontent.com/assets/10466466/21438738/69ff574a-c83f-11e6-9ca7-1aadcc1dd69b.png)

![image](https://cloud.githubusercontent.com/assets/10466466/21438745/6e3bcac8-c83f-11e6-9ea8-62977a7ad51a.png)

**Comment by ericsciple** [comment]
you are right. something is busted. i've got a repro.

**Comment by ericsciple** [comment]
i'm not sure right now whether it's a bug on the server or agent. leaving this issue open for now (this repo tracks agent issues, not server).

**Comment by AlexHimself** [comment]
Ok great. The artifact thing solves my immediate need, so that's good.

**Comment by ericsciple** [comment]
@scottdallamura helped me track this down. it's a bug on the server side. i'm going to close the issue here and open a bug. some code in the 2.0 REST API controller is missing in the 3.0 controller.

if you really wanted to, a workaround would be to craft the download URL yourself. if you have a custom script that runs during your build, you could build up the URI yourself using the [env vars](https://www.visualstudio.com/en-us/docs/build/define/variables) available at build time.

e.g. `https://MY_ACCOUNT.visualstudio.com/MY_PROJECT/_apis/build/builds/1711/logs?$format=zip&api-version=2.0`

...1711 is the build ID.

**Comment by ericsciple** [comment]
it looks like a small bug so i would expect it either to land in the next release (early jan) or three weeks after that (late jan - early feb)

**Comment by AlexHimself** [comment]
I don't think I totally follow on the work around. The issue seems to be it's not uploading the local file, so crafting the download URL wouldn't help unless I'm reading it wrong.

My current work-around is just to dump the logs to the console or uploading the artifact. Right now I'm just experimenting/learning anyway so if it's solved in a few weeks, that'd be great.

Thanks for the help!

**Comment by ericsciple** [comment]
the log is uploaded and it comes down in the zip when the 2.0 REST API is used to download the logs.

when the 3.0 REST API was created, some code was missed. or it landed in the 2.0 API but wasn't ported to 3.0. or something - somehow it got missed :)

the URL i pasted above explicitly uses the 2.0 API to download the zip. if you try it out on your build, you will see the log in the zip. (you will need to plug in correct values for account, project, and build id).

**Comment by AlexHimself** [comment]
AH I see what you're saying. So when I upload, it does land there, but just the server-side REST 3.0 API that is returning the ZIP to me isn't pulling the file in to the ZIP it creates.

I'm in no rush, so I'll just sit tight until the fix.

**Comment by ericsciple** [comment]
@AlexHimself fyi a fix was merged today for this issue and will roll out with the next deployment (started today and will finish rolling out everywhere over the next week or so)

**Comment by AlexHimself** [comment]
Wonderful! Look forward to it.
