### ISSUE TITLE
Pull request prefix is wrong: 'refs/remotes/pull' should be 'refs/remotes/origin/pull'

### ISSUE THREAD

**Issue by maximpashuk** [Microsoft/vsts-agent#733]
vsts-agent version 2.10.7 on Windows, TFS 2017 On-Premise RTM.

Then vsts-agent checkout pull request, it uses prefix 'refs/remotes/pull'
https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Build/GitSourceProvider.cs#L123

This is wrong.

By git convention after word 'remote' you should specify remote name - 'origin' in this case, and only after that specify folder for pull requests - 'pull'.

Now if I see branch name 'remotes/pull/2538/merge', I think that repository should have a remote called 'pull', but this is not true since vsts-agent uses only 'origin' remote, and 'pull' is only a folder.

Please correct ```_remotePullRefsPrefix``` - it should be 'refs/remotes/origin/pull'.

**Comment by ericsciple** [comment]
@maximpashuk i believe this is related to how PR branches are managed in TFS. when you `git clone` from the command line, the PR branches aren't part of the repo.

**Comment by ericsciple** [comment]
@maximpashuk is it causing any impact, or just appears unconventional?

@TingluoHuang may be able to explain the pecuilarties of this... knows the details better.

**Comment by maximpashuk** [comment]
@ericsciple I have some troubles because of wrong branch prefix.

I am using libgit2sharp 0.22 for some custom git logic.
Current pull request prefix made libgit2sharp not work correctly.

If branch named correctly, i.e. 'remotes/origin/pull/2538/merge', then libgit2sharp [Branch](https://github.com/libgit2/libgit2sharp/blob/8daef23223e1374141bf496e4b310ded9ae4639e/LibGit2Sharp/Branch.cs) object have properties:
```
Branch.IsRemote = true
Branch.Remote = <reference to Remote object>
Branch.UpstreamBranchCanonicalName = "refs/heads/pull/2538/merge"
```

If branch named like now, i.e. 'remotes/pull/2538/merge', then libgit2sharp [Branch](https://github.com/libgit2/libgit2sharp/blob/8daef23223e1374141bf496e4b310ded9ae4639e/LibGit2Sharp/Branch.cs) object have properties:
```
Branch.IsRemote = true
Branch.Remote = null
Branch.UpstreamBranchCanonicalName = null
```

So libgit2sharp can't detect some branch properties correctly in case branch named not by convention.
So my custom logic scripts became broken after updated to TFS 2017 build agent.

**Comment by ericsciple** [comment]
(another thing to consider would be scripting git.exe)

**Comment by TingluoHuang** [comment]
@maximpashuk i think this is a bug in Libgit2sharp, i would suggest create issue in there project.
all pull requests refs are belong to a different remote `pull` other than the default remote `origin`. 
you can have multiple remotes in a git repository, with separated remote, you won't get those useless pull request refs when you do a `git fetch/pull` since it's default to fetch/pull origin only.
