### ISSUE TITLE
Failure of "'OutputPath' property is not set for this project" with custom Build Configuration on xBuild

### ISSUE THREAD

**Issue by jamesatgithub** [Microsoft/vsts-agent#738]
## **Agent version and platform**
vsts-agent-osx.10.11-x64-2.103.1
<br>
OS of the machine running the agent? OSX 10.11.6
<br>
## **VSTS type and version**
VisualStudio.com 
<br>
If VisualStudio.com, what is your account name? http://boundlss.visualstudio.com
<br>
## **What's not working?** 

Got below errors which are related to the custom build configuration. Is this not supported with xBuild or any extra steps to do to fix this?

Target ResolveProjectReferences:
		Project "/Users/dev1/myagent/_work/1/s/Boundlss.Core.PCL/Boundlss.Core.PCL.csproj" (default target(s)):
			Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
			Task "Error" execution -- FAILED
			Done building target "_CheckForInvalidConfigurationAndPlatform" in project "/Users/dev1/myagent/_work/1/s/Boundlss.Core.PCL/Boundlss.Core.PCL.csproj".-- FAILED
		Done building project "/Users/dev1/myagent/_work/1/s/Boundlss.Core.PCL/Boundlss.Core.PCL.csproj".-- FAILED
		Project "/Users/dev1/myagent/_work/1/s/Mobile/Analytics/Analytics.csproj" (default target(s)):
			Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
			Task "Error" execution -- FAILED
			Done building target "_CheckForInvalidConfigurationAndPlatform" in project "/Users/dev1/myagent/_work/1/s/Mobile/Analytics/Analytics.csproj".-- FAILED
		Done building project "/Users/dev1/myagent/_work/1/s/Mobile/Analytics/Analytics.csproj".-- FAILED
		Project "/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.PCL/AppBoundlss.PCL.csproj" (default target(s)):
			Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
			Task "Error" execution -- FAILED
			Done building target "_CheckForInvalidConfigurationAndPlatform" in project "/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.PCL/AppBoundlss.PCL.csproj".-- FAILED
		Done building project "/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.PCL/AppBoundlss.PCL.csproj".-- FAILED
		Project "/Users/dev1/myagent/_work/1/s/Mobile/SharpMobileCode.ModalPicker/SharpMobileCode.ModalPicker.csproj" (default target(s)):
			Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
			Task "Error" execution -- FAILED
			Done building target "_CheckForInvalidConfigurationAndPlatform" in project "/Users/dev1/myagent/_work/1/s/Mobile/SharpMobileCode.ModalPicker/SharpMobileCode.ModalPicker.csproj".-- FAILED
		Done building project "/Users/dev1/myagent/_work/1/s/Mobile/SharpMobileCode.ModalPicker/SharpMobileCode.ModalPicker.csproj".-- FAILED
		Project "/Users/dev1/myagent/_work/1/s/Mobile/XibFree/XibFree.csproj" (default target(s)):
			Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
			Task "Error" execution -- FAILED
			Done building target "_CheckForInvalidConfigurationAndPlatform" in project "/Users/dev1/myagent/_work/1/s/Mobile/XibFree/XibFree.csproj".-- FAILED
		Done building project "/Users/dev1/myagent/_work/1/s/Mobile/XibFree/XibFree.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "ResolveProjectReferences" in project "/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj".-- FAILED
Done building project "/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj".-- FAILED
Build FAILED.

Errors:
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/dev1/myagent/_work/1/s/Boundlss.Core.PCL/Boundlss.Core.PCL.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_CheckForInvalidConfigurationAndPlatform target) ->
	/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/dev1/myagent/_work/1/s/Mobile/Analytics/Analytics.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_CheckForInvalidConfigurationAndPlatform target) ->
	/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.PCL/AppBoundlss.PCL.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_CheckForInvalidConfigurationAndPlatform target) ->
	/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/dev1/myagent/_work/1/s/Mobile/SharpMobileCode.ModalPicker/SharpMobileCode.ModalPicker.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_CheckForInvalidConfigurationAndPlatform target) ->
	/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
/Users/dev1/myagent/_work/1/s/Mobile/AppBoundlss.IOS/AppBoundlss.IOS.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/dev1/myagent/_work/1/s/Mobile/XibFree/XibFree.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_CheckForInvalidConfigurationAndPlatform target) ->
	/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AXABoundlss Platform: iPhone.
	 13 Warning(s)
	 5 Error(s)
Time Elapsed 00:00:29.4420120
XamariniOS task failed with error Error: /usr/local/bin/xbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

**Comment by ericsciple** [comment]
closing since this doesnt look to be related to the agent infrastructure. if i'm wrong please reopen

this looks like it is either related to the build task ([vsts tasks repo is here](https://github.com/Microsoft/vsts-agent/issues/738)) or a question about msbuild.

**Comment by ericsciple** [comment]
(updated above comment to fix the vsts-tasks repo hyperlink)
