### ISSUE TITLE
Xcodebuild tests, Cannot pass DestinationSpecifier with quotes from TFS

### ISSUE THREAD

**Issue by Vinzz** [Microsoft/vsts-agent#751]
## **Agent version and platform**
Version of your agent? 2.109.2
<br>
OS of the machine running the agent? OSX
<br>
## **VSTS type and version**
 On-Prem TFS?
<br>
2015 Update3
<br>
## **What's not working?** 
We want to launch xcode tests via the xcodebuild task, and struggle with the [destinationspecifier ](http://www.5neo.be/use-xcodebuild-cli-to-launch-ios-simulator-and-device/)parameter.

In our case, the platform name is 'iPhone 5', so the destinationspecifier for our command ought to be:
`-destination name="iPhone 5",OS="10.2"`

How to pass such double quotes from TFS to an OSX agent? All we tried seemed to fail us (\" or "" or even '")

Thanks

**Comment by ericsciple** [comment]
This sounds like an issue specific to one of the tasks, and not related to the agent infrastructure. The tasks repo is [here](https://github.com/Microsoft/vsts-tasks).

Please reopen if I'm mistaken.

**Comment by ericsciple** [comment]
@madhurig fyi

**Comment by Vinzz** [comment]
OK, issue registered in the [task repo](https://github.com/Microsoft/vsts-tasks/issues/3417)
Thanks
