### ISSUE TITLE
ubuntu build failed,log:VS30063: You are not authorized to access

### ISSUE THREAD

**Issue by tigerlei010** [Microsoft/vsts-agent#753]
OS: ubuntu 14.04
Agent version: 2.111.1
TFS: On-perm 2015 Update2

when config agent, I use Negotiate as the authentication type, my domain account as user name, agent can connect to server, and begins listen for jobs successful, but when I queue a build from TFS . the build will failed. the Worker log : VssUnauthorizedException: VS30063: You are not authorized to access http://xxxxx:8080.
I have tred agent 2.109.2. the same problem.

**Comment by ericsciple** [comment]
I'm unable to reproduce the issue against TFS 2015 U3. It looks like the current auth issues are all for TFS 2015 RTM or TFS 2015 U2. I'll setup one of those server and see if I can repro.

**Comment by tigerlei010** [comment]
this is agent log:

[Worker_20170113-073746-utc.txt](https://github.com/Microsoft/vsts-agent/files/705806/Worker_20170113-073746-utc.txt)

**Comment by tigerlei010** [comment]
@ericsciple , the upper comment is worker log, this is the agent log: 
[Agent_20170113-071106-utc.txt](https://github.com/Microsoft/vsts-agent/files/705808/Agent_20170113-071106-utc.txt)

**Comment by ericsciple** [comment]
@tigerlei010 thanks for the update. I'm close to testing against TFS 2015 RTM and Update 2. I setup servers for those environments on Friday, and I'll be able to resume testing when I'm back in the office tomorrow.

Last week I tested against TFS 2015 U3, and couldn't repro the issue.

**Comment by ericsciple** [comment]
@tigerlei010 It looks like you are using a proxy in other places. You may need [configure proxy settings](https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-linux#web_proxy) for the agent.

**Comment by ericsciple** [comment]
also, i tried to repro the issue against 2015 RTM and 2015 U2, but was able to run builds successfully.

**Comment by ericsciple** [comment]
it looks like the agent was configured against tfs.host.xxx_yyy_zzz.com, but i see that the hostname from the server URL in the job message is 10.93.193.139

**Comment by tigerlei010** [comment]
yes, tfs.host.xxx_yyy_zzz.com and 10.93.193.139 is the same server :-) , which and the agent are both in the intranet .  I will try to configure the proxy settings and try again.

**Comment by TingluoHuang** [comment]
@tigerlei010 
1. Have you try configure a windows agent to the same TFS service? I want to understand whether this is an issue for Non-windows platform only
2. If you have access to your TFS AT, can you check the event log? there should be an error correspond to the client side error.

**Comment by TingluoHuang** [comment]
Please reopen if you still hit this problem.
