### ISSUE TITLE
Can't build Cordova apps

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vsts-agent#77]
We've got an Ionic (Cordova-based) app and build definition that worked fine with the VSO Agent. Upon migrating to the VSTS Agent, we're getting failures in the build which look like:
```
Results at '/Users/brandonh/djbuildagent-internal/_work/1/s/platforms/ios/build/device/MarketWatch.ipa' 
Module cache at /Users/brandonh/.taco_home/node_modules
cordova already installed.
Skipping packaging. Detected cordova-ios verison that auto-creates ipa.

/usr/bin/security delete-keychain /Users/brandonh/djbuildagent-internal/_work/1/s/_tasktmp.keychain

/bin/rm -f /Users/brandonh/Library/MobileDevice/Provisioning Profiles/b629873d-31b6-4608-8d99-245065d41099.mobileprovision
Arguments to path.resolve must be strings
```
these never happened in the VSO agent and we haven't changed the build definition in VSTS at all.

as a sanity check I installed the old vso-agent and ran a build which passed flawlessly. the matching area of the build log when that agent runs it looks like:
```
Results at '/Users/brandonh/djbuildagent-internal1/_work/2/s/platforms/ios/build/device/MarketWatch.ipa' 
Module cache at /Users/brandonh/.taco_home/node_modules
cordova already installed.
Skipping packaging. Detected cordova-ios verison that auto-creates ipa.

/usr/bin/security delete-keychain /Users/brandonh/djbuildagent-internal1/_work/2/s/_tasktmp.keychain

/bin/rm -f /Users/brandonh/Library/MobileDevice/Provisioning Profiles/b629873d-31b6-4608-8d99-245065d41099.mobileprovision

******************************************************************************

Running CopyPublishBuildArtifacts
```

**Comment by bryanmacfarlane** [comment]
I think this commit fixed it.  https://github.com/Microsoft/vsts-agent/commit/ebda4a348ac28e09708eeec5e5cd7cb588d500c6 

The preview I will drop early next week will have it and should be pretty much feature complete for xplat.  Watch releases on GitHub page

**Comment by bryanmacfarlane** [comment]
Should be resolved with https://github.com/Microsoft/vsts-agent/releases/tag/v2.99.0
