### ISSUE TITLE
Timeline record's `progress` value does not affect build progress.

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-agent#772]
## **Agent version and platform**
2.111.1

Windows

## **VSTS type and version**

VSTS (https://vs01.visualstudio.com)

## **What's not working?** 

Setting the progress value of any logging commands including both task.setprogress and task.logdetail doesn't have any impact on any counters of build progress. The left sidebar percentage shows a fixed percentage for the duration of a PowerShell Script test, even if the script itself outputs a logging command specifying a value for progress. The progress is also not shown in any timeline views.

What does this value actually influence?

EDIT: It also appears that the 'current operation' value for the task.setprogress command also does not have any effect on the UI. What exactly is task.setprogress supposed to do?

**Comment by TingluoHuang** [comment]
@agc93 how long does your script run? the status gets updated every 3 seconds, 
Here is my test script:
```
Write-Host "##vso[task.setprogress value=5;]"
Start-Sleep -Seconds 15
Write-Host "##vso[task.setprogress value=15;]"
Start-Sleep -Seconds 15
Write-Host "##vso[task.setprogress value=25;]"
Start-Sleep -Seconds 15
Write-Host "##vso[task.setprogress value=50;]"
Start-Sleep -Seconds 15
Write-Host "##vso[task.setprogress value=75;]"
Start-Sleep -Seconds 15
Write-Host "##vso[task.setprogress value=95;]"
```
Here is the result in UI:
![image](https://cloud.githubusercontent.com/assets/1750815/22473505/2b50431a-e7a7-11e6-958c-ce70bf6b901c.png)

**Comment by agc93** [comment]
Thanks @TingluoHuang !

My overall script runs for about 90 seconds, and the calls to `task.setprogress` are all spaced around 10-15 seconds apart. According to [the documentation](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md), there is also a 'current operation' value (i.e. 'Upload Log' in the below example)

```
##vso[task.setprogress value=75;]Upload Log
```

Should this have any impact on how `value` is interpreted?

**Comment by agc93** [comment]
@TingluoHuang I used your example and eventually worked out that my `value` was being left out of the command for some reason. I'm now seeing the progress numbers on the left as intended.

Only remaining point is that the 'current operation' doesn't appear anywhere in the UI. Is this intended behaviour?

**Comment by TingluoHuang** [comment]
@agc93 we current do show 'current operation' in UI, it's just in Database for now.
