### ISSUE TITLE
Setting a timeline record's state to `skipped` in a logging command results in no icon

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-agent#773]
## **Agent version and platform**
2.111.1

Windows

## **VSTS type and version**

VSTS (https://vs01.visualstudio.com)

## **What's not working?** 

Using the [commands documentation](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md), the following is a valid timeline record command:

```
##vso[task.logdetail id=guid here;state=skipped;progress=100;]Task D
```

However, using this command in a PowerShell Script step results in the record appearing in the timeline with a 0:00 duration and a white square for an icon, as in the below screenshot:

![pasted_image_at_2017_01_31_01_11_am](https://cloud.githubusercontent.com/assets/1369269/22428598/674bab6a-e753-11e6-90b2-c009328bbf9f.png)

**Comment by bryanmacfarlane** [comment]
Thanks for reporting!  This is a service side web UI issue (and not an agent issue).  We'll get it taken care of.  Unfortunately the service side bugs and tasks aren't open.
