### ISSUE TITLE
Is there any plan to update AzureRM PowerShell Version for the hosted agent?

### ISSUE THREAD

**Issue by tousinn** [Microsoft/vsts-agent#777]
## **Agent version and platform**
2.111.1
<br>
Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://vmob.visualstudio.com
<br>
## **What's not working?** 
Get-AzureRmNotificationHubListKeys
Get-AzureRmNotificationHubsNamespaceListKeys

Error:
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@thechrisjohnson FYI,

**Comment by TingluoHuang** [comment]
@tousinn  This is the repository for agent, not for the Hosted Image, I will let production team know, close this issue now.
