### ISSUE TITLE
Can't install/run as service on OSX

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vsts-agent#78]
Continuing from [microsoft/vso-agent#283](https://github.com/Microsoft/vso-agent/issues/283)...

installing the OSX agent per instructions and electing `Y` when prompted to run as service results in an error.
```
Enter Work Folder (press Enter for _work) > 
Enter Run Agent as service (press Enter for N) > Y
An error occured.  The method or operation is not implemented.
```
Mac is running OSX El Capitan v10.11.4

log from `_diag` can be found [here](https://onedrive.live.com/redir?resid=42F6DD917641A9A8!114504&authkey=!AC5YhkSepB5_3gA&ithint=file%2clog)

**Comment by bryanmacfarlane** [comment]
Thanks.  

From main page: What's missing from the preview? Run as svc on OSX, TfsVC support, RM, test publishing (all being worked on). On-prem NTLM support is in the works so preview with VSTS.

:)

I have local changes so this is coming soon.  Like I said on vso-agent, it will do the same here (just create a plist) so we should understand the issue you had over there.

**Comment by bryanmacfarlane** [comment]
Initial implementation in: https://github.com/Microsoft/vsts-agent/releases/tag/v2.99.0

I'm writing up troubleshooting etc... if you have issues
