### ISSUE TITLE
IOS build agent not renewing the lock for VSTS build

### ISSUE THREAD

**Issue by nikhilgoud** [Microsoft/vsts-agent#782]
### **Agent version and platform** 
Version of your agent? 2.111.1
### OS of the machine running the agent? 
OSX (10.12.2)
### **VSTS type and version**  
VisualStudio.com 
## **What's not working?** 

The job has been abandoned because agent 'administrators-Mac-mini' did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.
<br>

## **Agent and Worker's diag log**
![image](https://cloud.githubusercontent.com/assets/21196948/22657046/27f14412-ecbb-11e6-94a8-8daa7f11d136.png)

![image](https://cloud.githubusercontent.com/assets/21196948/22656847/971bf7f2-ecba-11e6-9e22-71f2f5cd9fb3.png)
 
### Terminal
![image](https://cloud.githubusercontent.com/assets/21196948/22656675/0e3c08dc-ecba-11e6-9c9d-510804287cba.png)

**Comment by TingluoHuang** [comment]
@nikhilgoud Can you share the diag log with me? as long as the build log that fail to renew the lock? you can send both log to tihuang@microsoft.com.

**Comment by TingluoHuang** [comment]
@nikhilgoud under your agent root directory, there is a hidden file `.agent`, 
in the 
```
"WorkFolder": "KinesiaOne\u0000\u0000\u0000"`
```

remove those '\u0000's, i have no idea how they end up with this, but looks like this is causing problem.

**Comment by nikhilgoud** [comment]
Thanks a lot, Ting, the issue has been resolved. we are able to generate
builds now.

**Comment by TingluoHuang** [comment]
Cool, glad you unblock
