### ISSUE TITLE
VSTS Agent installation Ubuntu error: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. Failed to connect.

### ISSUE THREAD

**Issue by subodhsohoni** [Microsoft/vsts-agent#787]
I am installing VSTS Agent on Ubuntu 16.04.1 LTS. VM is created in Azure by Azure Container Service. It was created in last 2 days and I am configuring it for the first time. While running ./config.sh it asks for server name which is my URL Account https://subodhsohoni.visualstudio.com
I am using PAT for authentication.
It then shows the error. The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
Failed to connect.
I saw issues about this error on OSX but none on Ubuntu.
I have installed OpenSSL Version 1.0.2j

## **Agent version and platform**
Version of your agent? 2.111.1
<br>
OS of the machine running the agent? Linux Ubuntu 16.04.1
<br>
## **VSTS type and version**
VisualStudio.com 
<br>

If VisualStudio.com, what is your account name? http://subodhsohoni.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots

Enter server URL > https://subodhsohoni.visualstudio.com
Enter authentication type (press enter for PAT) >
Enter personal access token > ****************************************************
Connecting to server ...
The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
Failed to connect.  Try again or ctrl-c to quit
Enter server URL > Exiting...

I have tried with https also but same error
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@subodhsohoni 
here is the list of dependencies that netcore take. https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0.md

try update libcurl on your box.

**Comment by TingluoHuang** [comment]
please reopen if update libcurl doesn't help.

**Comment by sharedito** [comment]
What is the command to update libcurl?

**Comment by sharedito** [comment]
Just updated libcurl using this: http://www.brocade.com/content/html/en/sdn-controller/3.0.0/software-installation/GUID-BF7C280A-A9C6-4C13-A253-7A425FE5CD3F.html

But still, I'm getting the same error

**Comment by sharedito** [comment]
I got it working updating the .Net Core version, using the instructions provided at the .Net Core site: https://www.microsoft.com/net/learn/get-started/linuxubuntu

**Comment by TingluoHuang** [comment]
@sharedito Please try out the latest released agent https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.1
the latest version is netcore 2.0 and made up a script can help customer install dependencies more easily.

**Comment by sharedito** [comment]
Thanks!! It works!!
