### ISSUE TITLE
Agent fails to configure on Ubuntu 16.10

### ISSUE THREAD

**Issue by knizami** [Microsoft/vsts-agent#797]
## **Agent version and platform**
2.111.1
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
Ubuntu 16.10
## **VSTS type and version**
VisualStudio.com

When you run .configure, result:
Failed to initialize CoreCLR, HRESULT: 0x80131500

Ran all the pre-reqs and extended reqs listed but doesn't appear to work and can't find any workaround for Ubuntu 16.10 support...

**Comment by ericsciple** [comment]
@knizami did you download the released agent or did you build it?

**Comment by TingluoHuang** [comment]
@knizami Try this: https://github.com/dotnet/cli/issues/2018

**Comment by ericsciple** [comment]
you may need libicu52

**Comment by brandonh-msft** [comment]
This still happens today.

**Comment by TingluoHuang** [comment]
@brandonh-msft the agent is built for ubuntu 16.04

**Comment by brandonh-msft** [comment]
same error occurs on 16.04. I'm using the Docker on Ubuntu Server image from Azure which is 16.04.

**Comment by bryanmacfarlane** [comment]
This looks like the net core OS dependencies are not on your docker image.

https://github.com/dotnet/core/blob/master/Documentation/prereqs.md

Core CLR is failing to initialize.  Not an agent issue.

**Comment by Mctalian** [comment]
`dotnet --version` was working fine for me (Core 2.0.0)

I loosely followed this guidance and was able to get it to configure and run on Ubuntu 16.04- I had to alter the URLs and filenames, but I was able to figure it out pretty quickly from the below link.
https://kvaes.wordpress.com/2016/12/10/issue-with-vsts-agent-on-ubuntu-failed-to-initialize-coreclr-hresult-0x80131500/

**Comment by brandonh-msft** [comment]
@bryanmacfarlane of course it's not an agent issue; the agent ends up running. However the *additional work required* is something we might want to cite in our documentation.

**Comment by bryanmacfarlane** [comment]
@brandonh-msft - that's because net core is not the dependency.  We build a self contained net core app.  It's about the OS dependencies (the dependency of our dependency).

We are addressing with moving our agent to core clr 2.0 self contained app

**Comment by bryanmacfarlane** [comment]
I'm going to re-open to ensure our ubuntu 16 docs are up to snuff.  @TingluoHuang can go over.

**Comment by Naninani** [comment]
Here is a [fix](https://austin.cady.io/install-microsoft-powershell-on-ubuntu-17-10-artful/)
Installing the libicu55 version on ubuntu 17.10 and the agent is working fine.

**Comment by bryanmacfarlane** [comment]
Note that your "fix" is for 17.10 and this issue is about confirming our docs for the supported LTS 16.10 version is correct.

**Comment by Naninani** [comment]
@bryanmacfarlane the fix is applicable for 16.10 as well as 17.04.

**Comment by TingluoHuang** [comment]
please try out latest agent release https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.0
the latest version will detect any dependencies missing and contains a script that will install all required dependencies for you
