### ISSUE TITLE
agent should console write basic start/stop, queue failures

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#80]
in *nix distros, many write output to service logs.  very useful, 

unhandled/critical failures should go to stderr.

**Comment by stiliev** [comment]
We already print to stderr unhandled exceptions in Agent.Listener (with Console.Error.WriteLine). I will research about writing to service logs.

**Comment by bryanmacfarlane** [comment]
Just write to stdout and stderr in the cases I outlined


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by stiliev** [comment]
fixed
