### ISSUE TITLE
Question - Force Agent Update From Build Server

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vsts-agent#800]
Is it possible to force an agent to force an update from the server where it is installed for example using PowerShell?

As we currently have within repo a PS script and copy of the agent folder.  The script copies and installs the agent at the moment for various reasons don't want to pull latest agent download zip from online.

What I would like to do after it has been setup etc. is to get the PS script to force the agent to update to latest version?

**Comment by russelldyas** [comment]
Changed title

**Comment by ericsciple** [comment]
@russelldyas are you on an on-premises version of TFS or are you using VSTS? you can update from the pool admin UI, but only to the version that your server points. you can't specify the URL or anything like that.

**Comment by russelldyas** [comment]
@ericsciple 

We are using VSTS.

I do understand can update via VSTS web page what I am trying to do is after I do an automatic install of the agent on the build server that I force it to update (without user interaction) so that I know the agent is on latest version etc.

So process at the moment when triggered.

1- Server Set process sends over the agent folder from local store
2- Powershell setups  the agent and adds to vsts

In step 3 I would like the agent to force an upgrade as the copy of agent in step one might not be the latest. Hence why asking from where the agent is installed can force/trigger an update 

for example can the same message that pool admin UI sends can this be sent via PowerShell?

**Comment by bryanmacfarlane** [comment]
The web UI to update the pool calls a public rest api.  Open up fiddler or browser debugging tools to see the call

**Comment by TingluoHuang** [comment]
HttpPost:
```
Update entire pool -> https://<account>.visualstudio.com/_apis/distributedtask/pools/<poolid>/messages
Update a given agent within a pool -> https://<account>.visualstudio.com/_apis/distributedtask/pools/<poolid>/messages?agentId=<agentid>
```
