### ISSUE TITLE
Duplicate logrotate entry

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/vsts-agent#801]
Our build VM gets a daily email notification from the cron daemon starting from 2016-11-11:

    /etc/cron.daily/logrotate:
    error: waagent.logrotate:1 duplicate log entry for /var/log/waagent.log

looking at the logrotate configuration files, there are indeed two entries:

    # ls -la /etc/logrotate.d
    [...]
    -rw-r--r--   1 root root    92 Jan  5  2016 waagent
    -rw-r--r--   1 root root    92 Jan 26  2016 waagent.logrotate

It seems like maybe the chosen filename has changed, but it wasn't careful enough to remove the old file, leading to the duplicate entry.

> ## **Agent version and platform**
> Version of your agent? 2.102.0/2.100.1...

2.105.3

> OS of the machine running the agent? OSX/Windows/Linux...

Ubuntu 16.04.1 LTS

> ## **VSTS type and version**
> VisualStudio.com or On-Prem TFS?

VisualStudio.com

> If VisualStudio.com, what is your account name? http://account.visualstudio.com

`elbarzil@microsoft.com`, and the machine name is `elbarzil-vm`.

> ## **What's not working?** 
> Please include error messages and screenshots

See above.

> ## **Agent and Worker's diag log**
> Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

Unfortunately, I don't see any log files there from November.

**Comment by TingluoHuang** [comment]
@elibarzilay 
This is the repository for VSTS agent, i guess your problem is releated to Azure Agent, right? Here is the project's repository: https://github.com/Azure/WALinuxAgent
