### ISSUE TITLE
Question-Is it possible to upload attachments to the test results screen in TFS?

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-agent#808]
When one of our tests fails it dumps some information to an external log file that would be really great to attach to the test results?  Is this possible to do?

**Comment by chrisrpatterson** [comment]
Moved this issue to https://github.com/Microsoft/vsts-tasks/issues/3679

**Comment by acesiddhu** [comment]
@bbusacker replied over here Microsoft/vsts-tasks#3679
