### ISSUE TITLE
Agent fails to extract all files from vsix

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#810]
## **Agent version and platform**
Version of your agent? '2.109.1 & 2.111.1
<br>
OS of the machine running the agent? Linux
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 

The task is downloaded and expanded without a number of subfolders, e.g. `node_modules\7zip-bin-linux\x86`, the folder is present in the vsix extension
[jessehouwing.vsts-extension-build-release-tasks-DEV-100.0.97.zip](https://github.com/Microsoft/vsts-agent/files/796483/jessehouwing.vsts-extension-build-release-tasks-DEV-100.0.97.zip)

![image](https://cloud.githubusercontent.com/assets/4173387/23260284/4faec5a6-f9d1-11e6-818a-abba60504180.png)

But it is missing on the agent: after the task has been downloaded
![image](https://cloud.githubusercontent.com/assets/4173387/23260308/7a011d2c-f9d1-11e6-8104-7c433b7d69d1.png)

**Comment by ericsciple** [comment]
@jessehouwing this might be failing upstream somewhere. have you tried shortening the paths? it could be a path limitation for extensions.

**Comment by jessehouwing** [comment]
The paths are relatively short compared to some of the others that do get
extracted.

**Comment by ericsciple** [comment]
@jessehouwing I copied the PublishExtension folder out of the zip using Windows Explorer and there is no x86 folder under the the Linux 7zip node modules folder. I'm on win 10

Is the zip malformed?

**Comment by ericsciple** [comment]
![image](https://cloud.githubusercontent.com/assets/12102068/24591647/be8cbae8-17d4-11e7-9627-f3bbdf48e12f.png)

**Comment by jessehouwing** [comment]
The ia32 and x64 were missing when running on a Unix agent.

On Apr 3, 2017 00:47, "ericsciple" <notifications@github.com> wrote:

[image: image]
<https://cloud.githubusercontent.com/assets/12102068/24591647/be8cbae8-17d4-11e7-9627-f3bbdf48e12f.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-agent/issues/810#issuecomment-291020724>,
or mute the thread

**Comment by ericsciple** [comment]
Sorry I'm confused. Is there supposed to be an x86 folder? That's the path you specified above, and I don't see one present when I unzip with Windows Explorer.

**Comment by jessehouwing** [comment]
None of the executable folders were extracted. I passed along the log from
a colleague MVP and mixed in some of my windows-ness it seems.

On the windows agent the executable folders were extracted. On Linux they
were not.

**Comment by ericsciple** [comment]
The agent was updated recently to net core 1.1 (in the 2.114 or 2.115 agent), so that may be fixed now. I haven't searched the net core repo for an issue, so not sure.

**Comment by jessehouwing** [comment]
I've since worked around it, cause the marketplace doesn't eat zip files
created on Linux by 7z.if they now get extracted as they should, then
that's nice for future tasks.

**Comment by ericsciple** [comment]
How was the zip created when the Linux agent was unzipping it incorrectly?

**Comment by jessehouwing** [comment]
Tfx-cli

On Apr 3, 2017 9:39 AM, "ericsciple" <notifications@github.com> wrote:

How was the zip created when the Linux agent was unzipping it incorrectly?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-agent/issues/810#issuecomment-291069873>,
or mute the thread

**Comment by ericsciple** [comment]
@trevorsg

**Comment by TingluoHuang** [comment]
I am going to close the issue, doesn't seems like to be a problem of the agent.
Repo for tfx-cli: https://github.com/Microsoft/tfs-cli
