### ISSUE TITLE
Unable to download build agent from release

### ISSUE THREAD

**Issue by dougperkes** [Microsoft/vsts-agent#819]
The build agents listed on https://github.com/Microsoft/vsts-agent/releases cannot be downloaded. Accessing the URLs return a timeout from Amazon's AWS.

**Comment by TingluoHuang** [comment]
@dougperkes we noticed this issue as well. :( we hope github can recover quicker.

**Comment by dougperkes** [comment]
@TingluoHuang Is there another location we can grab the release from in the meantime?

**Comment by TingluoHuang** [comment]
@dougperkes sorry, no other place at this time. :(

**Comment by dougperkes** [comment]
No prob. At least we aren't the only ones experiencing issues: https://www.theregister.co.uk/2017/02/28/aws_is_awol_as_s3_goes_haywire/

**Comment by TingluoHuang** [comment]
it's back online. :)
