### ISSUE TITLE
Agent creates a hidden $TF folder at random in one of all mapped folders

### ISSUE THREAD

**Issue by jesfer** [Microsoft/vsts-agent#859]
## **Agent creates a hidden $TF folder at random in one of all mapped folders**
See screenshots below. Depending on how I structure the local folders the $TF folder will appear in a different folder. Unpredictable behaviour and it has already messed up multiple build artifacts for us. 

## **Agent version and platform**
Agent Version: 2.112.0
OS: Windows Server 2008 R2 Standard
TFS: 2017.1 (15.112.26301.0)

(TFS and build server are separate machines)

## **Screenshots** 
![workspace error 1](https://cloud.githubusercontent.com/assets/17148069/23957306/5567ec1a-099f-11e7-9d23-c1a29d9c4296.png)
![workspace error 2](https://cloud.githubusercontent.com/assets/17148069/23957260/3c9bb004-099f-11e7-8806-03cea6c880cc.png)

**Comment by ericsciple** [comment]
@jesfer i think a root mapping folder would bring predictability

**Comment by jesfer** [comment]
@ericsciple A root mapping folder? Can you explain/give an example?

**Comment by ericsciple** [comment]
```
type: map
server path: $/
local path:

type: cloak:
server path: $/notThisFolder

type: map
server path: $/thisFolder
local path: thisFolder

type: map
server path: $/alsoThisFolder
local path: alsoThisFolder
```

If that would require too many cloaks, another thing that might be easier to define would be define your root as a single-level map (e.g. $/my/root/directory/*) and then it only pulls direct descendants under that location (likely empty folders?)

**Comment by jesfer** [comment]
After experimenting a bit I see that the appearance of the $tf folder is consistent with how a "complex" local workspace mapping works on my machine as well... So guess I'll have to live with that, even if it is annoying :)

Your mapping/cloaking suggestion works as long as there are only a few folders involved.

In my case this was easier:
![workspace mapping 1](https://cloud.githubusercontent.com/assets/17148069/23962894/da8fc286-09af-11e7-96ce-9ea75e476211.png)
![workspace mapping 2](https://cloud.githubusercontent.com/assets/17148069/23962906/e22bada2-09af-11e7-8d6f-5e1d89a3e549.png)

Gives me a nice and predictable result. Was that what you meant by "define your root as a single level map" @ericsciple ?

**Comment by jesfer** [comment]
I am closing this issue as it really has nothing to do with the agent (it is just how local workspaces work) and I now have a way to get a consistent and predictable behaviour.

**Comment by bryanmacfarlane** [comment]
Thanks!  @ericsciple - anything to document here in the agent troubleshooting or best practices section?

**Comment by ericsciple** [comment]
@jesfer actually this this problem came up in the context of build artifacts. Assuming you are on VSTS and use the Copy Files task (stage contents) and then the Publish Build Artifacts task (publish staging folder), then you can specify an exclude pattern, e.g. `!**/$tf/**`

reference doc for [pattern syntax](https://www.visualstudio.com/en-us/docs/build/steps/file-matching-patterns) is here

**Comment by jesfer** [comment]
Yes, that would also work ☺

**Comment by maheswar** [comment]
Can we clock the **$tf**  folder, If i clock i am getting following error

**The path '$/Documentation/Files/$tf' contains a '$' at the beginning of a path component. Remove the '$' and try again.**

Please help me to solve this issue.

**Comment by TingluoHuang** [comment]
`$/Documentation/Files/$tf` is not a valid TFSVC path, why you have a nested `$tf` folder?
