### ISSUE TITLE
Question - Build number format.

### ISSUE THREAD

**Issue by p13x** [Microsoft/vsts-agent#862]
Hi,
Is it possible to get Build number format variable from a file?

In XAML builds to handle that I edit build definition template.

**Comment by Dejulia489** [comment]
Can you elaborate a bit on your questions. 

Would you like to read a file at build time and create an environmental variable, or would this variable only be needed for on task\step?

Here is some info on where to set the build number format and what variables can be used:

https://www.visualstudio.com/en-us/docs/build/define/general

**Comment by p13x** [comment]
I have two vNext build definitions.

I build an application with build number format:
**Application1_1.0.58**

Then I want to build a second application with build number format:
**Appliaction2_1.0.58.1**

So, I would like to copy "1.0.58" from first build number format to second.
To have right build number format in both applications.

In XAML first applications write 1.0.58 to file. Then second applications read 1.0.58 from the file and add 1.

I don't see a way to do that in vNext build definitions.
Maybe there is different way?

**Comment by Dejulia489** [comment]
Assuming both applications are in the same team project, place the build number format in the variables table, reference the variable in the build number format. 

Something like 
Variable:
Version = 1.0

Build Number Format:
Build Number Format = $(Version)$(Rev:.r)

This will work if both applications are in the same build. 

If they are in separate releases you will need to create a variable group under the library tab. 

https://www.visualstudio.com/en-us/docs/build/concepts/library/variable-groups

**Comment by p13x** [comment]
Thank you for an answer.

Solution:
I've created PowerShell task and then I pass a variable from the file.

We can close the case.
