### ISSUE TITLE
Hosted Agent: "The machine request type DistributedTask was not found."

### ISSUE THREAD

**Issue by tevert** [Microsoft/vsts-agent#864]
## **Have you try trouble shooting doc?**
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## **Agent version and platform**
VSTS cloud agent

## **VSTS type and version**
Running on tylerevert.VisualStudio.com

## **What's not working?** 
Agent 'fails' all builds and releases given to it, providing only the error "The machine request type DistributedTask was not found."
<br>
Screenshot: https://i.imgur.com/JdYZdTm.png
<br>
From the agent pools side, the build or release shows up as queued and assigned, but does not become "completed" for almost an hour at times. At this point, it will appear canceled and have an empty duration. In the meantime, my build/release pipeline is considered in-use and nothing else will go through. 
<br>
Screenshot: https://i.imgur.com/xnQUssl.png
<br>
As the last screenshot shows, this started happening on 3/17 and has been reliably continuing since. Also worth noting is that if I host an agent myself, it works fine. The cloud agents are the only ones who choke. There were no changes in build/release configs before this point, and the behavior applies to any and all build/release configs, including brand-new ones. 

## **Agent and Worker's diag log**
Is it possible retrieve these from a hosted agent?

**Comment by TingluoHuang** [comment]
@tevert this should be fixed right now, we rolled back the server change that break this.
