### ISSUE TITLE
Binding redirect for dependnecy is ignored when running tests

### ISSUE THREAD

**Issue by drGarbinsky** [Microsoft/vsts-agent#865]
Agent version and platform: 2.112.0
<br>
OS: Window 6.3.9600
<br>
type: VisualStudio.com 
<br>
account name: https://cloudmedinc.visualstudio.com
<br>
Binding redirect settings in app.config, vstest.executionengine.x86.exe.Config, and machine.confg are ignored when executing tests.  There are other binding redirects that are functioning just fine. The redirect that is failing is specifically from Couchbase.Linq -> Couchbase.NetClient Looking for info on how to get more details about what is going on here. Typically the fusion log is enough, but as you can see the post-policy reference is unchanged. The reference was added via NuGet and the binding redirects were updated correctly.
<br>
Fusion Log: 
The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.executionengine.x86.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Couchbase.NetClient, Version=2.3.8.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2
 (Fully-specified)
LOG: Appbase = file:///d:/_work/r1/a/Master CI Release/drop/Tests/CloudMedClient.Tests/bin/Release
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = vstest.executionengine.x86.exe
Calling assembly : Couchbase.Linq, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.executionengine.x86.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Couchbase.NetClient, Version=2.3.8.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///d:/_work/r1/a/Master CI Release/drop/Tests/CloudMedClient.Tests/bin/Release/Couchbase.NetClient.DLL.
LOG: Assembly download was successful. Attempting setup of file: d:\_work\r1\a\Master CI Release\drop\Tests\CloudMedClient.Tests\bin\Release\Couchbase.NetClient.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Couchbase.NetClient, Version=2.3.11.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

 Agent console message:
2017-03-20T21:01:36.5570341Z ##[error]Error Message:
2017-03-20T21:01:36.5570341Z ##[error]   Assembly Initialization method CloudMedStorage.Tests.StorageTestsBase.Init threw exception. System.IO.FileLoadException: System.IO.FileLoadException: Could not load file or assembly 'Couchbase.NetClient, Version=2.3.8.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). Aborting test execution.
2017-03-20T21:01:36.5570341Z ##[error]Stack Trace:

**Comment by TingluoHuang** [comment]
@drGarbinsky Can you share a build log and an agent diag log? also can you provide more detail about what you are doing? which app.config file you try to modify, and where are they?

**Comment by drGarbinsky** [comment]
I am attempting to resolve a fusion Bind error in test automation. There are many bindings that are redirected successfully but one is failing. The app.config file for all test projects contain the binding redirect for the Couchbase.NetClient assembly. I tried to resolve this by adding the same redirect to the .config for the test process as well as the machine.config

.config file that I modified:
-  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.executionengine.x86.exe
- C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config

-- working on getting logs. I need to move the repo to another brank to get  the team unblocked. I'll post up here when I get that done.

**Comment by TingluoHuang** [comment]
@drGarbinsky what kind of test automation? Are you using any build task like VSTEST?

**Comment by drGarbinsky** [comment]
Running c# tests that interact with Couchbase via the VsTest. Running the "Visual Studio Test" 1.x task as part of a release template.

**Comment by TingluoHuang** [comment]
@drGarbinsky then you need open the issue with Vsts-Tasks repo. https://github.com/Microsoft/vsts-tasks
this repo is only for the build agent.

**Comment by drGarbinsky** [comment]
Rog
