### ISSUE TITLE
'vstest' capability on macOS Build Agent

### ISSUE THREAD

**Issue by dombarnes** [Microsoft/vsts-agent#866]
## **Have you try trouble shooting doc?**
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## **Agent version and platform**
Version of your agent? 2.114.0
<br>
OS of the machine running the agent? OSX/Windows/Linux: 10.11.6
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? VSO
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com trilbymultimedia
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

## **Issue**  
Given that .Net Core is cross-platform, is there any ability to support test/build actions for dotnet core projects on a macOS based agent? I can restore, build and run my project on a Mac, but my Agent doesn't support the vstest capability, according to the list of abilities.

**Comment by TingluoHuang** [comment]
@dombarnes
1. can you run test for your project from command line in Mac?
2. if so, then it's become a question of how the agent discover the capability on Mac, can you run 'which vstest' to get the location of vstest?

**Comment by dombarnes** [comment]
I've just noticed that my current working project is on the preview2 SDK and rc4 is out which has a 'dotnet vstest' command so I can probably add this as a custom capability. I'll test this and report back

**Comment by ericsciple** [comment]
@cltshivash

**Comment by michelmoorlag** [comment]
My macOS Build Agent is also missing the vstest capability. Any instructions how to add this capability?

**Comment by TingluoHuang** [comment]
Only [VSTest](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/VsTestV2) task is demand "vstest" in it's task.json, and the VSTest task is [Windows Only](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/runvstest.ts#L15). I don't think we need to populate `vstest` demand for Linux/Mac
