### ISSUE TITLE
Agent sending all ENV VARS is a security issue

### ISSUE THREAD

**Issue by dombarnes** [Microsoft/vsts-agent#867]
As a developer, a number of other command line tools I use rely on passwords and secrets stored as ENV VARS on my computer, things like AWS keys, specific tool/file locations, keys for third party tools like Airbrake, Sendgrid, etc. 

It strikes me that uploading all of these to VSO Agent Pool as capability options is a bit of a security risk. I understand the need to get things like paths to node/npm tools, etc but providing all of the ENV VARS doesn't seem very secure. Can the agent not just provide the vars for the tools it expects to use only?

**Comment by Dejulia489** [comment]
Correct me if I'm wrong here...

Those passwords can be stored as secure variables under the Build \ Release variables tabs. 

Rather than storing them as ENV variables, store them securely within TFS

**Comment by ericsciple** [comment]
Yes if secure variables works for your scenario that would be best. Otherwise you can add a variable `VSO_AGENT_IGNORE` that contains comma delimited list of vars not to publish as capabilities.

**Comment by bryanmacfarlane** [comment]
Correct, that's the reason the ignore variable exists.
