### ISSUE TITLE
dotnet commands can fail if pinned to some older SDKs

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vsts-agent#872]
Doesn't matter if I use the built in netcore preview command or command line, both fail with the same error message.

## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
(Hosted Agent 2017)

OS of the machine running the agent? OSX/Windows/Linux...
Hosted 2017

## **VSTS type and version**
VisualStudio.com

If VisualStudio.com, what is your account name? http://4dtech.visualstudio.com

## **What's not working?** 
2017-03-22T17:15:23.8315016Z ##[command]dotnet publish -c release -o C:\a\1\a
2017-03-22T17:15:27.1784810Z ##[error]Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

All dotnet calls fail with the same error.

## **Agent and Worker's diag log**
2017-03-22T17:15:23.8184462Z ##[section]Starting: Run dotnet
2017-03-22T17:15:23.8234703Z ==============================================================================
2017-03-22T17:15:23.8234703Z Task         : Command Line
2017-03-22T17:15:23.8234703Z Description  : Run a command line with arguments
2017-03-22T17:15:23.8234703Z Version      : 1.1.2
2017-03-22T17:15:23.8234703Z Author       : Microsoft Corporation
2017-03-22T17:15:23.8234703Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2017-03-22T17:15:23.8234703Z ==============================================================================
2017-03-22T17:15:23.8315016Z ##[command]dotnet publish -c release -o C:\a\1\a
2017-03-22T17:15:27.1784810Z ##[error]Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

2017-03-22T17:15:27.1984816Z ##[error]Process completed with exit code -532462766 and had 1 error(s) written to the error stream.
2017-03-22T17:15:27.2004812Z ##[section]Finishing: Run dotnet

**Comment by bryanmacfarlane** [comment]
the agent doesn't distribute dotnet cli.  we just call it.

the problem is with the dotnet install on your OSX box.

You should also pull a new agent down (web UI download) and install it.  That version is from a very early preview of the 2.x agent.

**Comment by JohnGalt1717** [comment]
This is the hosted 2017 agent which I can't get a version from. So it isn't any osx box.

**Comment by bryanmacfarlane** [comment]
From the info above:

Version of your agent? **_2.102.0/2.100.1..._**
(Hosted Agent 2017)

OS of the machine running the agent? **_OSX_**/Windows/Linux...

The Hosted Agent 2017 queue should have version 2.114.0 on it so I'm confused.

**Comment by JohnGalt1717** [comment]
Per above which you directly quoted:

**(Hosted Agent 2017)**

For which I could find no where to get the actual version number to provide you.

This is VSTS on visualstudio.com which is a complete mess right now with almost nothing actually working out of the box for vs.net 2017 (i.e. just yesterday we FINALLY got Hosted Agent 2017 support, and even then nuget services don't have v4.0 support so you have to manually include nuget just to make the basics work and all of the dotnet commands are broken.

You can easily repro this: Create an empty .net core site in vs.net 2017 and then create a new build and choose dotnet core (preview) and the Hosted 2017 Agent and it blows up with this error.

Or do a command line call for "dotnet restore". Same problem.

Or use the Task for dotnet core. Same problem.

How vsts wasn't ready for the final release of vs.net 2017 is beyond me but this stuff needs to be fixed ASAP.

**Comment by bryanmacfarlane** [comment]
It's at least not a straight forward repro.  I just tried projects with cmdlines and tasks and it's behaving properly so something is different about your specific state/data.

Do you have a global.json pinning you to an older version of the SDK?  There is an issue that's rolling out today which affects some older versions of the SDK.

**Comment by bryanmacfarlane** [comment]
Here's my output:

```bash
==============================================================================
 Task : Command Line
 Description : Run a command line with arguments
 Version : 1.1.2
 Author : Microsoft Corporation
 Help : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
 ==============================================================================
 ##[command]dotnet --version
 1.0.0
 ##[section]Finishing: Run dotnet
 ##[section]Starting: dotnet --version
 ==============================================================================
 Task : .NET Core (PREVIEW)
 Description : Build, test and publish using dotnet core command-line.
 Version : 0.4.1
 Author : Microsoft Corporation
 Help : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
 ==============================================================================
 [command]C:\Program Files\dotnet\dotnet.exe --version
 1.0.0
 ##[section]Finishing: dotnet --version
 ##[section]Starting: Run restore
 ==============================================================================
 Task : Command Line
 Description : Run a command line with arguments
 Version : 1.1.2
 Author : Microsoft Corporation
 Help : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
 ==============================================================================
 ##[command]restore 
 'restore' is not recognized as an internal or external command,
 operable program or batch file.
```

**Do you have a global.json pinning you to an older version of the SDK? There is an issue that's rolling out today which affects some older versions of the SDK.**

**Comment by bryanmacfarlane** [comment]
We reproduced pinning to some older SDKs.  We have a fix that's rolling out today and tomorrow across scale units.  We will target SU5 earlier which is where your account is.

**Comment by JohnGalt1717** [comment]
Great! Thanks!
