### ISSUE TITLE
Remote Build Agent Installation - Run As Windows Service with Negotiate Authentication

### ISSUE THREAD

**Issue by Dejulia489** [Microsoft/vsts-agent#877]
## **Agent version and platform**
Agent: 2.112.0
OS: Windows Server 2012
<br>
## **VSTS type and version**
On-Premises TFS 2017 
<br>
## **What's not working?** 
Agent Installation is failing when Invoking the command remotely. 

        .\config.cmd --unattended --url $TFSURL --agent "$ENV:COMPUTERNAME-$drive" --pool $PoolName --auth Negotiate --username $CredentialObject.UserName --password $CredentialObject.GetNetworkCredential().password --runasservice --windowslogonaccount $CredentialObject.UserName --windowslogonpassword $CredentialObject.GetNetworkCredential().password

Error: 
--runasservice was unexpected at this time.
    + CategoryInfo          : NotSpecified: (--runasservice ...d at this time.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

I am able to install the agent locally with integrated authentication.
I am able to install the agent remotely with negotiate authentication. 

I would like to create a remote Build Agent Creation script and it seems that the config.cmd cannot handle this combination of parameters: -Negotiate, -runasservice

<br>
No Log available because the command never starts.

No Event is created either. 

Thanks, 
Dejulia489

**Comment by TingluoHuang** [comment]
@Dejulia489 do you have any special char in your password that make the command line no longer valid?
try move --runasserver up front?

**Comment by Dejulia489** [comment]
Thank you for the suggestion. 

I tried a few different orders of the command parameters and was unsuccessful.

**Comment by TingluoHuang** [comment]
@Dejulia489  Have you try run the command in cmd prompt, not in PS.

**Comment by TingluoHuang** [comment]
@Dejulia489 any luck?

**Comment by TingluoHuang** [comment]
please reopen if this issue still happen.
