### ISSUE TITLE
Using MSBuild, "Solution not found using search pattern" with double slashes in paths

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Microsoft/vsts-agent#879]
I wasn't sure if this issue belongs in `Microsoft/vsts-tasks`, but because this only affects one agent version, 2.X, I thought here was better.

## **Agent version and platform**
2.111.1
Windows Server 2012 R2

(FWIW it works on the old 1.105.6 version)

## **VSTS type and version**
VSO

## **What's not working?** 
We have our agents automated through puppet (both 1.X and 2.X) and in hiera we have the work directory as `F:\\_work`.

Using MSBuild works fine on the 1.X agents, but on the 2.X agents it fails to find any files because of the double slash in the path (which should just be ignored).

We're using a project path of something like `**/Nightly.Acceptance.Tests.csproj`, which then expands to something like `F:\\_work\2\s\foo\**\Nightly.Acceptance.Tests.csproj`.

**Comment by stephenmichaelf** [comment]
Please reopen if you continue to have this issue.

**Comment by ElvenSpellmaker** [comment]
As far as I know the issue is still there, but we haven't encountered it in a while as we stripped the double slashes in puppet as a workaround
