### ISSUE TITLE
ContainerNotFoundException with 2.114.0

### ISSUE THREAD

**Issue by kirkone** [Microsoft/vsts-agent#880]
## **Agent version and platform**
Version of your Agent: 2.114.0
OS of the machine running the Agent: Windows Server 2016
## **VSTS type and version**
VisualStudio.com
account Name: http://ptd.visualstudio.com
## **What's not working?** 
I Upgraded to version 2.114.0 from v2.112.0 today and after that my releases stopped working with this error at th download artifacts step:
```
An error occurred during download: Microsoft.VisualStudio.Services.FileContainer.ContainerNotFoundException: The container 670588 could not be found
```
After roling back to version 2.112.0 everything is back to normal.
I double checked if the artifact ist there and I cleaned up my build agent.
Also I rebuild all linked definitions.

There are 2 other artifacts that works fine in the same task. The only difference I can see at the moment is that th not working arifact only has 1 zip file in it and the other has more files.
I switched to an other artifact from another build with als only a zip in it and got the same error.

Did I miss something?

Best regards,
Kirsten

**Comment by TingluoHuang** [comment]
@kirkone #868 will fix the issue.

**Comment by kirkone** [comment]
OK, thank you very much.

I presume this fix can not make it in the 2.115.0 release. Is there a eta when we get a fixed Version?

Thank you for your great work.
Kirsten

**Comment by TingluoHuang** [comment]
@kirkone We will make it into 2.115.0 agent. you can try the pre-release 2.115.0 from github, it should contains the fix.

**Comment by kirkone** [comment]
Hello,

I can confirm this is fixed with 2.115.0

Thank you

**Comment by Bhuard1** [comment]
I installed 2.115.0 from here https://github.com/Microsoft/vsts-agent/releases and got the same error.

My problem is releated to this one https://developercommunity.visualstudio.com/content/problem/33326/vsts-release-the-container-568443-could-not-be-fou.html

We updated TFS 2017 CU1 yesterday and this problem started.

My workaround is put the builds artifact in the same team project as the release. Not too many of our releases are affected so far.

**Comment by TingluoHuang** [comment]
@GitHubSriramB FYI,
@Bhuard1 which version your were using before upgrade to TFS 2017 CU1?

**Comment by erendrake** [comment]
We are having issues with this in our VSTS instance. with many releases stalled because they cant pull builds. We are paying for hosted build agents so we do not control their agent version. The natives are restless :)

**Comment by GitHubSriramB** [comment]
@Bhuard1, did you face this issue when you downloaded & configured agent from TFS 2017 CU1? Or did you face it only after configuring 2.115.0 version of agent against TFS 2017 CU1?

**Comment by GitHubSriramB** [comment]
@erendrake - will follow up and let you know solution for this issue when using hosted agents.

**Comment by Bhuard1** [comment]
@GitHubSriramB 

Terribly sorry. My error. When I reinstalled version 115 my test build was being queing to another build agent which I had not yet upgraded with the fix (I need to do so with the operations team so it is a little long).

The build 115 works fine.  It grabs artifacts from builds that are in another team project.

So to recap, I face the issue after the TFS upgrade (which installed version 114 but did not update the agent capabilities for some reason, still indicating agent,version,;1.105.6; but that is not important).

I will upgrade my other agent machine with 115 tomorrow.

Thank you so much for the quick fix.

**Comment by GitHubSriramB** [comment]
@Bhuard1 - thanks for the quick response. Glad that you are unblocked.

**Comment by erendrake** [comment]
This is working for us now that 2.115 as been deployed. I think we can close this?

**Comment by TingluoHuang** [comment]
@erendrake Cool, glad you unblock.
