### ISSUE TITLE
Commands are misinterpreted if the message contains the new line

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#882]
## **Agent version and platform**
Version of your agent? Latest
<br>
OS of the machine running the agent? Windows
<br>

If the command message contains `new line` the command message gets split into multiple and the message is misinterpreted

Original message string:
First 
Second
Third

`##vso[task.debug] Message string`

Only First is marked as debug and rest of the string is parsed as non command.
The message can contain "New lines" especially in logging messages. This shouldn't break the command

**Comment by chrisrpatterson** [comment]
This is currently by design.  The message cannot contain line breaks as how would we know you the next line is part of the command rather than just another log line.

**Comment by ericsciple** [comment]
newlines can be escaped using the query string escape sequence

**Comment by nigurr** [comment]
Wouldn't it be good to provide lib function in `vsts-task-lib` to write message by escaping it. I am not sure what's the `query string escape` in this context, is it [QueryString](https://nodejs.org/api/querystring.html) Api?
