### ISSUE TITLE
The job has been abandoned because agent <Servername> did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.

### ISSUE THREAD

**Issue by k3flo** [Microsoft/vsts-agent#883]
Hello Visual Studio Team Services Team,

we face the problem that in a real high frequency our build job with build vNext crashes. The error message is that the agent could not renew the lock.
Our build agent is installed on a local windows 2008R2 server. We attached the worker and also the agent logs as text files. Also we made two screenshots where you can see that the console crashed while executing our build job. The problem occurs in different steps when our build job is running. Sometimes
the build agent crashes while the deployment of the test agent is started. Sometimes it crashes when the solution is build (for running the integration tests later) and also sometimes the agent crashes while the integration tests are executed. We already uninstalled the build agent and reinstalled it. But that didn't fixed
the problem. It is really important for us that this problem get fixed because we have 1000 Integration Tests that should run every night. But the last 10 times it never finished successfully.

![vstest exception](https://cloud.githubusercontent.com/assets/12381373/24346147/75ec261c-12d3-11e7-91b3-e52c82d8af87.jpg)

![buildjob vsts](https://cloud.githubusercontent.com/assets/12381373/24346154/7d511b2e-12d3-11e7-8ebb-e6b74a39581c.jpg)

[Worker_20170324-200007-utc.txt](https://github.com/Microsoft/vsts-agent/files/871775/Worker_20170324-200007-utc.txt)

[agent_log.txt](https://github.com/Microsoft/vsts-agent/files/871776/agent_log.txt)

With kind regards

Florian Ertelt, labs

Account Name: http://lupusalpha.visualstudio.com
Agent Version: 2.110.0
Agent.OSVersion: 6.1.7601

**Comment by TingluoHuang** [comment]
@Nitin the app crash screenshot point to the DTAExecutionHost, can you take a look?

**Comment by nigurr** [comment]
@k3flo are you running build agent and test agent on same machine? This is currently not-supported scenario.

If you are using different test agent machine, please can you let us know the Test Agent version and Attach the Event Viewer logs?

**Comment by k3flo** [comment]
@nigurr yes were running the build and test agent on the same machine. We moved the test agent to another machine but now we are facing another error with the testrunner (https://github.com/Microsoft/vsts-agent/issues/891). The test runner crashes every run after some time.
