### ISSUE TITLE
dotnet restore failing on Hosted VS2017

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/vsts-agent#884]
## **Agent version and platform**
Current agent version: '2.114.0'
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://builttoroam.visualstudio.com
<br>
## **What's not working?** 
When running the dotnet restore task on an ASP.NETCore project created in Visual Studio 2017, the process fails to resolve project references for .netstandard projects that are referenced by the head project.

At the begging of the restore process, the following error message is shown for each .netstandard project that is included in the solution:

`C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross\FormsMvvmcross.Server.Core\FormsMvvmcross.Server.Core.csproj(83,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

dotnet restore then continues to restore packages for the head netcore project as normal, then ends with the following error messages:

`C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Unable to resolve 'C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.Models\FormsMvvmcross.Models.csproj' for '.NETCoreApp,Version=v1.1'. [C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.sln]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Unable to resolve 'C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.Server.Core\FormsMvvmcross.Server.Core.csproj' for '.NETCoreApp,Version=v1.1'. [C:\a\1\s\Temporary\FormsMvvmcross\FormsMvvmcross.sln]`
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by duckwaffle** [comment]
To add: I have tried the exact same build steps on the Hosted 2015 agent, and dotnet restore works perfectly fine, however the build tasks fail because the agent does not understand the new csproj format of the dotnet core project.

**Comment by bryanmacfarlane** [comment]
The agent doesn't have anything to do with dotnet.  It's a task runner.

If you're using hosted, you need to pick the hosted 2017 queue, not hosted.  If you're running a private agent, ensure it has the full 2017 tool set installed.

Finally, the in the VSBuild or MSbuild task in your def, pick VS 2017 in the dropdown to use.

**Comment by duckwaffle** [comment]
@bryanmacfarlane if you had read the title of my submission, you would see that that I am using the hosted queue, and not using a private agent. You would also see that the issue I am experiencing is ONLY on the 2017 queue, not the older queue. Clearly there is something up with the way the 2017 agent is configured, unless I'm completely missing something?

**Comment by bryanmacfarlane** [comment]
There's 3 things:
- the agent ( this repo ) which is a task runner.  No knowledge of tools, image etc
- tasks: the things that run the tools
- the image: the vm with everything installed like vs etc ( the hosted 2017 image )

I'm simply pointing out it's not an issue with the agent application ( thus repo ).

You should create the issue in the vsts-tasks repo.
