### ISSUE TITLE
VSTS: Hosted Build Agent trying to reach VSTS API via Powershell yields ESC

### ISSUE THREAD

**Issue by lukx** [Microsoft/vsts-agent#885]
## **Agent version and platform**
Current agent version: '2.114.0'

OS of the machine running the agent? Windows (VSTS Hosted Agent)

## **VSTS type and version**
VisualStudio.com

If VisualStudio.com, what is your account name? http://tss-projects.visualstudio.com

## **What's not working?** 
We're trying to reach the VSTS APIs from a Release Build Step using PowerShell.
However, when using `Invoke-WebRequest -UseBasicParsing`, or also the longer System.Net.WebClient-Form, the response will eventually contain a HTML document wrapping the following error message:
> Microsoft Internet Explorer's Enhanced Security Configuration is currently enabled on your environment. This enhanced level of security prevents our web integration experiences from displaying or performing correctly. To continue with your operation please disable this configuration or contact your administrator.

IMHO, This appears to mean that 
* The Hosted Agent has IE ESC enabled
* The Hosted Agent doesn't trust the VSTS REST APIs

**Comment by bryanmacfarlane** [comment]
Not really an agent issue - more of our hosted image, but we'll take it :)

Thanks for reporting.

**Comment by ericsciple** [comment]
pinging offline to check the status of this

**Comment by thechrisjohnson** [comment]
Image is being released this week that disables this.

**Comment by pabrams** [comment]
It's back. I get this when  trying to get a list of environments from the API.
