### ISSUE TITLE
Add a recursive checkout tab for submodules

### ISSUE THREAD

**Issue by hsommer** [Microsoft/vsts-agent#886]
We would like to be able to unset the recursive checkout for submodules implemented in version 2.114.0 of the agent.
Please follow the discussion on this topic here:
https://github.com/Microsoft/vsts-agent/pull/690#issuecomment-290057905

**Comment by bryanmacfarlane** [comment]
Ting, let's add

**Comment by TingluoHuang** [comment]
#887
