### ISSUE TITLE
Leaf path not found: 'D:\Agent2\Agent\Worker\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll'

### ISSUE THREAD

**Issue by IkeStarnes** [Microsoft/vsts-agent#890]
## **Agent version and platform**
2.114.0

<br>
Windows Server 2012

<br>
## **VSTS type and version**
On perm TFS 2015

## **What's not working?**

Build always fails.

## **Agent and Worker's diag log**

Task         : Visual Studio Build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.0.26
Author       : Microsoft Corporation
Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=613727)
==============================================================================
Leaf path not found: 'D:\Agent2\Agent\Worker\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll'
[Worker_20170331-020637-utc.log.txt](https://github.com/Microsoft/vsts-agent/files/884345/Worker_20170331-020637-utc.log.txt)

**Comment by TingluoHuang** [comment]
@IkeStarnes 
base on https://github.com/Microsoft/vsts-agent#supported-usage
Windows should always use the agent coming with TFS.

**Comment by ericsciple** [comment]
Ting's analysis still applies in this case, but minor correction to his statement: Windows should always use the agent coming with TFS, *against TFS 2015*
