### ISSUE TITLE
vstest.executionengine.exe has stopped working

### ISSUE THREAD

**Issue by k3flo** [Microsoft/vsts-agent#891]
Dear Microsoft Team,

after you sugessted not executing the integration tests on the build server (https://github.com/Microsoft/vsts-agent/issues/883)  I set up a new VM where our application, the tests agent and the tests binaries gets deployed. The deployment works fine but when the tests gets executed the test runner is always crashing after some time (it is mostly running about 70 minutes).
The new VM is also a Windows 2008R2 Server (like before). I attached the screenshot that shows how the test runner crashes and also I attached the DTAExecutionHost.exe.log file and two event viewer log screenshots. 

Please help us soon. It is really important for us that our integration tests run every day.

Thanks for your help.

With kind regards
Florian Ertelt

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-agent/files/885627/DTAExecutionHost.exe.txt)

![test_agent_crash](https://cloud.githubusercontent.com/assets/12381373/24550973/d8d5ad52-1620-11e7-9981-097e41975b45.PNG)

![eventlog1](https://cloud.githubusercontent.com/assets/12381373/24550974/db169c48-1620-11e7-92a3-aba785e2d5ce.jpg)

![eventlog2](https://cloud.githubusercontent.com/assets/12381373/24550976/dd01ceec-1620-11e7-9375-962b8156e876.jpg)

**Comment by TingluoHuang** [comment]
@nigurr Where should be point the customer to? doesn't seems to be a build agent issue.

**Comment by nigurr** [comment]
Please point to vsts-task repo for these issues.

@k3flo can you please file here https://github.com/microsoft/vsts-tasks/issues

**Comment by k3flo** [comment]
@nigurr thank you, I created an issue in the other repo.
https://github.com/Microsoft/vsts-tasks/issues/3926
