### ISSUE TITLE
ASCII bell character in test causes vsts-agent to fail to publish results.

### ISSUE THREAD

**Issue by GaTechThomas** [Microsoft/vsts-agent#899]
## **Agent version and platform**
Agent version: 2.112.0
Agent machine OS: Windows Server 2012 R2
## **VSTS type and version**
VisualStudio.com
## **What's not working?** 
Switching from vstest v1 to v2 fails to publish test results with warning

"Failed to publish test results: '', hexadecimal value 0x07, is an invalid character."

The special character is "\a", which is an ASCII bell/alert character. I've tracked the "Failed to publish test results" to the vsts-agent repository. The test is as follows:

```
    [InlineData(@"^[0-9a-zA-Z_-]+$", "\abcdefg", false)]
    public static void Regex_IsMatch_ParameterizedTest(string regexPattern, string testValue, bool expectedResult)
    {
      // Arrange
      Regex sut = new Regex(regexPattern);

      // Act
      bool match = sut.IsMatch(testValue);

      // Assert
      Assert.Equal(expectedResult, match);
    }

```
<br>

**Comment by TingluoHuang** [comment]
@nigurr

**Comment by nigurr** [comment]
Please close the issue here - ref https://github.com/Microsoft/vsts-tasks/issues/3932
