### ISSUE TITLE
Ship VSTS-Agent with TFS Installer

### ISSUE THREAD

**Issue by RangerDjanger** [Microsoft/vsts-agent#903]
As of TFS 2017, the vsts-agent is no longer packaged with the TFS installer, and to install the agent, internet access is required. This has now caused some major issues with more secure customers that do not permit internet access.

1) What was the reason behind removing the vsts-agent from being packaged into TFS installer and updates - consdering that the download URL is fixed to a specific agent version anyway?
2) Customers that have internet restrictions cannot make use of agent auto-update when TFS updates are applied. 
3) The agent has to manually be downloaded, and then for each agent machine, take the agent offline, apply new files and run configure.  When there are many agents this considerable effort.

Can we please have the vsts-agent shipped back onto TFS installer?

**Comment by TingluoHuang** [comment]
@RangerDjanger 
One reason that I know is package size.
today we have 5 agent packages for each platform. 
```
win: 70MB
osx: 50MB
Ubuntu 14: 50MB
Ubuntu 16: 50MB
Redhat: 50MB
```
if we put all of them into the TFS installer, means the size of the installer will increase almost 300MB.
I believe the current installer is only 600MB, so i don't think we are allowed to do it. 

@bryanmacfarlane @chrisrpatterson for correction.

**Comment by bryanmacfarlane** [comment]
Internet access is not required from the server or build machine.

You download the agent and put it on a thumb drive from another internet accessible machine.  Just like you did to acquire tfs itself.  Even though the tfs machine didn't have internet access you downloaded it from some machine, correct?

Go to github agent repo, releases tab and download from an internet enabled machine.  Put it on a thumb drive.  Carry it around to all your build machines that don't have internet access.

Ting is correct.  We have not only many agents for each platform but we offer all versions of all agents.

Bryan

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
