### ISSUE TITLE
Agent install failure: VS30063: You are not authorized to access https://tfs

### ISSUE THREAD

**Issue by RangerDjanger** [Microsoft/vsts-agent#904]
## **Have you try trouble shooting doc?**
Yes

## **Agent version and platform**
Agent Version: 2.105.7
Windows Server 2012 R2
<br>
## **VSTS type and version**
TFS 2017.1
<br>
## **What's not working?** 
Recently upgraded TFS from TFS 2017 RTM to TFS 2017.1.   Build agents were previously working.  After upgrade agents were no longer running.

This has been tested in both our TFS Test environment and TFS prod environment. Same issue on both TFS instances.

Permission for TFS is TFS server admin, TPC admin etc.

Removed agent and attended reconfigure.  Stack trace below:

[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 INFO RSAEncyptedFileKeyManager] Loading RSA key parameters from file D;\TfsAgents\Agent01\.credentials_rsaparams
[2017-04-06 ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://tfs.

**Comment by TingluoHuang** [comment]
@RangerDjanger have you check your TFS AT's event log, is there any error around the same time you configure the agent? Can you try to collect Fiddler trace from the agent machine?

**Comment by RangerDjanger** [comment]
@TingluoHuang  the event log contains no data.  The fiddler trace does not pick up anything interesting about the requests from what I can tell.

I switched on Verbose logging and this did not provide any additional information to the stack trace listed above.

**Comment by RangerDjanger** [comment]
@TingluoHuang I've narrowed down the issue to somewhere in this code.

// Testing agent connection, detect any protential connection issue, like local clock skew that cause OAuth token expired.
            _term.WriteLine(StringUtil.Loc("TestAgentConnection"));
            var credMgr = HostContext.GetService<ICredentialManager>();
            VssCredentials credential = credMgr.LoadCredentials();
            VssConnection conn = ApiUtil.CreateConnection(new Uri(serverUrl), credential);
            var agentSvr = HostContext.GetService<IAgentServer>();
            try
            {
                await agentSvr.ConnectAsync(conn);
            }
            catch (VssOAuthTokenRequestException ex) when (ex.Message.Contains("Current server time is"))
            {
                // there are two exception messages server send that indicate clock skew.
                // 1. The bearer token expired on {jwt.ValidTo}. Current server time is {DateTime.UtcNow}.
                // 2. The bearer token is not valid until {jwt.ValidFrom}. Current server time is {DateTime.UtcNow}.                
                Trace.Error("Catch exception during test agent connection.");
                Trace.Error(ex);
                throw new Exception(StringUtil.Loc("LocalClockSkewed"));
            }

**Comment by RangerDjanger** [comment]
@TingluoHuang 

On further investigation using Fiddler, I can now see the requests that are failing with 401.

_URL /_apis/connectionData?connectioOPtoins=1&lastChangeId=-1&lastChangeId64=-1_

Server is responding with 401 - Unauthorized: Access is denied to due invalid credentials.

Creds I'm using to run agent install are mine (TFS server admin, TPC admin).  Using Integrated. Have also tried using PAT.  The install process seems to connect to TFS fine, its just when the Agent.Listener attempts to connect. 

As I mentioned at the start - this only occurred after TFS was upgraded from 2017 to Update 1.

**Comment by TingluoHuang** [comment]
@RangerDjanger 
when you config we use your credential to acquire an OAuth token, the during agent running, we just use the OAuth token. can you send me the Fiddler trace to tihuang at microsoft.com ?

**Comment by RangerDjanger** [comment]
Just solved this. I identified that IIS did not have Anonymous Authentication enabled.

**Comment by Tarig0** [comment]
Is this actually the expected fix for this?

**Comment by TingluoHuang** [comment]
@Tarig0 yes, Anonymous Authentication is required for TFS2017, which should be turned on by default when you install it or upgrade to it.

**Comment by bryanmacfarlane** [comment]
@Tarig0 - auth is still applied.  The auth module behind IISs front door does OAuth JWT auth.  When you configure an agent, we authenticate 'you' via integrated / ntlm to register the agent on-prem (PAT in VSTS).  That gives back a signed JWT token to listen to the queue.  Then, per build, we generate an OAuth jwt token per build which expires when that build completes.  So, to (1) enable untrusted domain scenarios and (2) make build much more secure, we use OAuth scoped access.  To do that, we get past the IIS front door.

**Comment by Tarig0** [comment]
Ok, think I have a different issue with authentication, my builds stop
before the console log reports to tfs. I'll see about getting the log files.

**Comment by bryanmacfarlane** [comment]
You can send me _diag logs from the agent.  my email is bryanmac and that's at microsoft.

**Comment by tkorc** [comment]
Hi, same issue for us. Anyway our solution was that there was no local accounts on the new machine (we're using a local account instead of access token for this task for a certain reason) when we did the upgrade from TFS 2015 to TFS 2017.

Take this as a kick-off in case the same thing happened to you ;-)

Cheers.
