### ISSUE TITLE
Bad Interaction between vsts-agent and aspnetcore-builds

### ISSUE THREAD

**Issue by ChristianSauer** [Microsoft/vsts-agent#915]
## **Agent version and platform**
Linux agents, on premise: TFS 2015

## **What's not working?** 
We use the tfs agents to build aspnetcore apps. Unfortunately, the docker Containers of the build are running as ROOT (see here: https://hub.docker.com/r/microsoft/aspnetcore-build/~/dockerfile/).
Therefore, all files are created as root, but the Agent itself cannot as root.
When the Agent tries to remove files created by the build, it Fails b/c the Agent has insufficient permissions to remove the Folder containing the files.
How can we fix this? it would be ideal if we could stop writing Workaround scripts

**Comment by TingluoHuang** [comment]
@ChristianSauer  when you launch the docker image, can you run it as your instead of Root? you can add yourself to container by `docker exec useradd -m -u <UID>`

**Comment by ChristianSauer** [comment]
@TingluoHuang Yes, I could try that. But I would have liked to use the same mechanisms visual Studio uses (which generates the files). Also, currently the solution contains an "dockerproj", which causes a nonzero exitcode on Linux (fix is underway from MS, but not there yet). "up" can ignore that, but a docker run can not.

**Comment by TingluoHuang** [comment]
@ChristianSauer  do you know what mechanism VS is using?

**Comment by TingluoHuang** [comment]
@ChristianSauer i think you should have the same permission problem when you run the docker command without the agent, just from a regular command prompt.

**Comment by ChristianSauer** [comment]
@TingluoHuang Yes, we would have the same problems if we used the regular command prompt. In my opinion, the problem is not that any of the behaviour is wrong per so, but that the interaction is problematic.
Docker builds are a primary feature of visual studio 2017, so it should work rather painless, which it is not.
There are multiple possible solutions (a root agent, using as non root user by default etc.)

**Comment by chrisrpatterson** [comment]
@ChristianSauer VS is different because it is running on windows with a directory mapped into the Linux VM as a particular user.  In that case all of the files are owned by the user that is used to map the share form windows.  You are working on Linux so the user id 0 is the same both in and out of the container.

**Comment by bryanmacfarlane** [comment]
Closing since I don't think there's any action item for the agent application here.
