### ISSUE TITLE
Get Sources always misses out a specific folder 

### ISSUE THREAD

**Issue by bthomsons** [Microsoft/vsts-agent#917]
## **Agent version and platform**
Version of your agent? 2.112.0
<br>
OS of the machine running the agent? Windows 2016
<br>
## **VSTS type and version**
On-Prem TFS
<br>
If On-Prem TFS, which release,15.112.26307.0
<br>
## **What's not working?** 

I have just set up TFS 2017 with a backup of our TFVC repository but when the build agent runs a build, at the get sources task, it **never** gets the sources for one specific folder and only that folder.

I created a build from scratch and mapped over to our workspace directory in source. 

![image](https://cloud.githubusercontent.com/assets/20319781/24910918/304bb9ca-1ec1-11e7-90cb-d1d2f2b5195b.png)

This is the command that I can see being run on the build console:

```
##[command]tf vc get /version:48472 /recursive /overwrite C:\TFSAgent\_work\1\s /loginType:OAuth /login:.,******** /noprompt
```

However, if I log onto the agent and run the following from the cmd promt:

```
tf vc get /version:48472  C:\TFSAgent\_work\1\s\ /login:"[user,pass]" /noprompt /recursive
```

The folder in question is downloaded.

The folder structure is like this

Source Root
 \Folder1
 \Folder2
 \\**MissingFolder**
 \Folder3
 \etc
  
Missing folder did have some explicit permissions on it but I have removed those and the service user which the agent runs on has permission anyway.

The agent is on premise and runs on windows under a service user which has full permissions on our source.

**Comment by ericsciple** [comment]
@bthomsons based on your description i'm led to believe you haven't tried the things i [mentioned here](https://github.com/Microsoft/vsts-tasks/issues/3992). can you confirm?

**Comment by bthomsons** [comment]
hi @ericsciple when I run the tf vc get command on the server using the same credentials as the agent runs under, it gets the files. I also removed all specific permissions on that folder. It was the first thing I tried.

**Comment by bthomsons** [comment]
One thing I didn't mention in my original question was that this was a migration from TFS 2013. I don't know if that would have had anything to do with it?

**Comment by ericsciple** [comment]
The agent doesn't communicate back to TFS as your service account. It uses the TFS-built-in build identity. Check permission for `Project Collection Build Service` or `Project Build Service` depending on the authz scope setting on your definition.

**Comment by bthomsons** [comment]
I managed to solve this by clearing explicit permissions and turning inheritance back on. It's odd because I had set the exact same permissions explicitly e.g. 

![image](https://cloud.githubusercontent.com/assets/20319781/24963592/ede41e84-1f96-11e7-9b58-35c3d6e20878.png)

'Project Build Service' didn't exist

**Comment by ericsciple** [comment]
Closing since this is resolved now
