### ISSUE TITLE
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Redirect

### ISSUE THREAD

**Issue by seven1986** [Microsoft/vsts-agent#919]
## **Agent version and platform**
vsts-agent-win7-x64-2.112.0
vsts-agent-win7-x64-2.114.0
vsts-agent-win7-x64-2.115.0
<br>
OS of the machine running the agent?
Windows 10 (Version:14393)
<br>
## **VSTS type and version**
On-Prem TFS
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
Microsoft Visual Studio Team Foundation Server
version:15.112.26307.0
<br>
## **What's not working?** 
![image](https://cloud.githubusercontent.com/assets/20808494/24939410/b6b8b0cc-1f6f-11e7-94ee-3287e3889693.png)

**Comment by TingluoHuang** [comment]
@seven1986 can you try config against http:// instead of https://

**Comment by seven1986** [comment]
@TingluoHuang  
http instead of https, than output:
```
Basic authentication requires a secure connection to the server.
```

this means I need to config IIS to  sopport http connection, am I right?

**Comment by TingluoHuang** [comment]
@seven1986 it dependency on how is your TFS server configured. is the Tfs server configured with Https?
what url do you use when you connect through browser?

**Comment by seven1986** [comment]
it ok,the reason is iis config
