### ISSUE TITLE
Warning for agent with lower than recommended Git Version should be optional

### ISSUE THREAD

**Issue by MattGal** [Microsoft/vsts-agent#924]
## **Agent version and platform**
Version of your agent? 2.109.0
<br>
OS of the machine running the agent? Various.
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://devdiv.visualstudio.com
<br>
## **What's not working?** 
This line:
https://github.com/Microsoft/vsts-agent/blob/700eb4cfe9767382f3262c18396ebb962a6905ce/src/Agent.Worker/Build/GitCommandManager.cs#L142
Routinely adds a warning to our builds, especially on the linux machines.   We have a lot of build agents and are frankly not interested in this warning.  It is not optional as far as I can tell, and makes it hard to have a "clean" build with no warnings since most of the linux flavors we build on start with 1 warning, this one.

**Comment by TingluoHuang** [comment]
git 2.9 is required when clone git repository from on-prem tfs server. also there are lots of perf fix in recent git updates, would you like to take this chance to upgrade git on your build machine?

**Comment by MattGal** [comment]
We don't use on-premises TFS servers, so yes I understand that doing what this warning says is one way to make it go away.  What's a reason to not allow the customer to suppress this?

**Comment by TingluoHuang** [comment]
it's just a recommendation and something we want to bring your attention.

**Comment by shawnro** [comment]
We don't want the recommendation and it shouldn't be forced on us - it creates noise as we can't differentiate warnings of this nature with product warnings that need to be fixed.  Please provide your customers a way to disable these or make them INFO or something else so we can filter them out.

**Comment by TingluoHuang** [comment]
We will change it to be a warning in next agent release.

**Comment by TingluoHuang** [comment]
#926
