### ISSUE TITLE
JAVA_TOOL_OPTIONS breaks TeeCommandManager<WorkspacesAsync:Line 255> Workspace Already Exists Error

### ISSUE THREAD

**Issue by craigjar** [Microsoft/vsts-agent#927]
## **Agent version and platform**
Version of your agent? 2.115.0
<br>
OS of the machine running the agent? Linux...
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? On-Prem
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2? 14.102.25423.0
<br>
## **What's not working?** 
When using TFVC on a Linux build agent, consecutive builds fail with "An error occurred: The workspace ws_X_X:Project Collection Build Service (TEAM FOUNDATION) already exists on computer XYZ."
<br>
The reason for this failure is that if the JAVA_TOOL_OPTIONS environment variable is set, the first output line during the "Querying workspace information" step is "Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8" followed by the XML output the agent expects.
<br>
It is the following line of code which is getting preventing the XML results from being parsed successfully and detecting the existing workspace:
https://github.com/Microsoft/vsts-agent/blob/v2.115.0/src/Agent.Worker/Build/TeeCommandManager.cs#L255
<br>
I am using Microsoft's own vsts-agent-docker container to host my Linux build agent which sets the JAVA_TOOL_OPTIONS environment variable and causes the issue.  With the hosted build configuration this is not a problem because a brand new docker container is provisioned for each build thus no existing workspace defined.  If you create your own Linux build agent which is persistent, then this issue will occur. 
<br>
Please let me know if you require any other details, I hope I have diagnosed and explained this issue effectively so that it can be resolved easily.

**Comment by ericsciple** [comment]
@craigjar Thanks I'll try and repro. It sounds like we should search for the first `<?xml` and trim whatever comes before.

I'm not sure who publishes that container. If they left any contact info, it might be good to let them know.

**Comment by craigjar** [comment]
@ericsciple, thanks.  I am using the "microsoft/vsts-agent:ubuntu-16.04-tfs-2017-docker-1.13.1-standard" docker image.  See: https://hub.docker.com/r/microsoft/vsts-agent/

**Comment by ericsciple** [comment]
thanks, i think i know who publishes that now. i'll follow up with them.

**Comment by ericsciple** [comment]
the fix is in master. it will go out with the 2.117.0 agent which will start rolling out to scale units ~ may 8 and finish rolling out over the course of a week or two.

**Comment by craigjar** [comment]
Thank you @ericsciple, I built the latest master branch code and deployed to my environment and can confirm the fix works.

Really impressed with the fast turnaround time on this one.

**Comment by ericsciple** [comment]
@craigjar awesome, thanks for confirming the fix!

**Comment by truongnht** [comment]
hi @craigjar, @ericsciple, I am also using vsts-agent-docker. Do you know if the fix has been in the latest image, since I still have this issue with ubuntu-16.04-tfs-2017-standard and ubuntu-16.04-docker-17.06.0-ce-standard.
