### ISSUE TITLE
Latest source not being pulled from external git repository

### ISSUE THREAD

**Issue by jwyoung9** [Microsoft/vsts-agent#935]
## **Agent version and platform**
2.115.0 on OSX
## **VSTS type and version**
VisualStudio.com
## **What's not working?** 
When running subsequent builds on our OSX build agent, the latest source is not being retrieved from our external git repository.  Here are the relevant commands being exectuted:

```
[command]git version
[command]git config --get remote.origin.url
[command]git config gc.auto 0
[command]git config --get-all http.https://nameofmyrepo.com/myrepo.git.extraheader
[command]git config --get-all http.proxy
[command]git remote set-url origin https://********:********@nameofmyrepo.com/myrepo.git
[command]git remote set-url --push origin https://********:********@nameofmyrepo.com/myrepo.git
[command]git fetch --tags --prune --progress origin
.
.
[command]git checkout --progress --force feature/automated_build
Already on 'feature/automated_build'
Your branch is behind 'origin/feature/automated_build' by 1 commit, and can be fast-forwarded.
   (use "git pull" to update your local branch)
command]git submodule update --init --force --recursive
```
<br>
Note the messages regarding the branch being behind the source repo.  The agent never performs a pull or fast forward merge to catch up so the build never updates to the latest source.  The git version on the OSX build machine is 2.10.1 (Apple Git-78).

**Comment by TingluoHuang** [comment]
@jwyoung9 what step do you have in your build? the agent git checkout should always ends up in detached head.

**Comment by jwyoung9** [comment]
This is the standard "get sources" task set to pull from a remote repo.  The only advanced option checked is to checkout submodules.

**Comment by TingluoHuang** [comment]
@jwyoung9 what other tasks do you have in your definition? are you hitting this problem with any branch or just this branch feature/automated_build?

**Comment by TingluoHuang** [comment]
@jwyoung9 how did you queue the build? can you share your VSTS account name and definition name with us? so we can check backend. in the meantime, you can try queue against refs/heads/feature/automated_build.

**Comment by jwyoung9** [comment]
Using "refs/heads/feature/automated_build" works.

**Comment by TingluoHuang** [comment]
@jwyoung9 ok, i will check server code, since the server should always send branch name with refs/heads prefix.

**Comment by TingluoHuang** [comment]
@lukekim can you share a sample of worker diag log when you hit the error?

**Comment by TingluoHuang** [comment]
@jwyoung9 we have identified the issue we have on server and have made a fix. should deploy to service soon, i will keep you update.

**Comment by TingluoHuang** [comment]
fix was merged, will deploy in a week.
