### ISSUE TITLE
Environment variable to detect VSTS/TFS type

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-agent#936]
## **Agent version and platform**
2.115.0 Windows

## **VSTS type and version**
Both

## **What's not working?** 
The agent environment includes the `TF_BUILD` environment variable to detect running under either VSTS or TFS, and `AGENT_NAME` is always set to "Hosted Agent" for Hosted Agents.

However, there is no variable that I can see that allows to tell between VSTS and TFS regardless of agent type? Could there potentially be `VSTS_BUILD`/`TFS_BUILD` variables, or a `TF_BUILD_TYPE`?

Currently, the only way to semi-reliably tell is using the `BUILD_REASON` variable, which isn't set for TFS builds, but this seems fragile.

## **Agent and Worker's diag log**
*Available if required*

**Comment by TingluoHuang** [comment]
@agc93 what's your scenario? i don't think there is any reliable way to determine VSTS/TFS type, a hack way i can think might be account url match *.visualstudio.com.

**Comment by agc93** [comment]
@TingluoHuang [we](https://github.com/cake-build/cake) have users who want to be able to differentiate build behaviour based on platform and our [current logic](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TFBuild/TFBuildProvider.cs#L45) for identifying TFS mistakenly picks up VSTS builds running on self-hosted agents.

**Comment by TingluoHuang** [comment]
@agc93 ok, as i said server Url might be the only way you want to try. you can use ENV: SYSTEM_TEAMFOUNDATIONCOLLECTIONURI get the url, then match with *.visualstudio.com.
The build agent doesn't care whether you config against TFS or VSTS.

**Comment by agc93** [comment]
@TingluoHuang that seems very messy/hacky, but I'll look into it. Thanks.

**Comment by bryanmacfarlane** [comment]
This still doesn't answer why a build process should care about whether the source if tfs or vsts.

I don't understand this:
>> identifying TFS mistakenly picks up VSTS builds running on self-hosted agents.

Agents configured in a queue that a definition picks up a build.  Regardless of whether TFS or VSTS, the agent that's configured in the queue will pick up a build.

The task or build script shouldn't care whether the server is on-prem or VSTS - it's an url enpoint.

Reactivate with a concrete scenario.

**Comment by agc93** [comment]
Sorry for the delay @bryanmacfarlane : lost this one in my notifications.

Concrete scenario is a bit difficult as we're just providing [a tool](https://github.com/cake-build/cake) our users can manage their builds with. One of our users was controlling build behaviour based on build system (i.e. VSTS or TFS), but since hosted agents can be attached to either, we were looking for a better heuristic than trying to match on account name..
