### ISSUE TITLE
Exit code 100 returned from process "vc scorch" warning When Setting Clean = True on Windows

### ISSUE THREAD

**Issue by imsh** [Microsoft/vsts-agent#937]
## **Agent version and platform**
2.105.7, Windows 
<br>
## **VSTS type and version**
On-Prem 15.105.25910.0
<br>
## **What's not working?** 
Setting Clean = True gives TFS warning, similar to already fixed #422 
<br>

2017-04-24T07:02:00.6063417Z ##[command]tf vc scorch D:\B\A2\_work\6\s /recursive /diff /unmapped /loginType:OAuth /login:.,******** /noprompt
2017-04-24T07:02:03.2938672Z No appropriate mapping exists for D:\B\A2\_work\6\s.
2017-04-24T07:02:03.3251213Z ##[warning]Exit code 100 returned from process: file name 'tf', arguments 'vc scorch D:\B\A2\_work\6\s /recursive /diff /unmapped /loginType:OAuth /login:.,******** /noprompt'.
<br>
Here is my build mapping:
![mapp](https://cloud.githubusercontent.com/assets/9258159/25326374/38289e4c-28d0-11e7-80e0-573db14b1fd7.PNG)
I'm building the solution in Projects\SomeProject\Mainline folder.

<br>Is it expected behaviour with my mapping?

**Comment by ericsciple** [comment]
@imsh Scorch doesn't work well when there is no root mapping. What you can do is add a minimal root mapping:

`Map` `$/ROOT/*` `$(build.sourcesDirectory)\`

That will create a minimal (single-level) root mapping folder.

**Comment by imsh** [comment]
@ericsciple Your suggestion worked fine, and it is also quite safe unless somebody decides to put huge files directly into root folder, so this issue can be closed.

Thanks!

**Comment by dalle** [comment]
If anyone else stumbles on this, the wildcard in the workspace mapping represent a [non-recursive folder mapping](https://docs.microsoft.com/en-us/vsts/tfvc/optimize-your-workspace).
