### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by Hirayuki** [Microsoft/vsts-agent#943]
I have a docker cluster behind a VPN. And also I have a TFS on visualstudio.com, I have downloaded TFS agent container, and want to connect to our TFS but it cannot connect with an alarm of:

    Determining matching VSTS agent...
    Downloading and installing VSTS agent...
    curl: (35) gnutls_handshake() failed: Error in the pull function.
    
    gzip: stdin: unexpected end of file
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now

It can ping google.But cannot ping public TFS. I would consider this as a network issue but nginx container was pulled and started with success.

      docker run \
      -e VSTS_ACCOUNT= xxx \
      -e TFS_HOST= yyy \
      -e VSTS_TOKEN= zzz \
      -it microsoft/vsts-agent

also tried this:

    docker run \
      -e VSTS_ACCOUNT= xxx \
      -e VSTS_AGENT='$(hostname)-agent'\
      -e VSTS_TOKEN= yyy \
      -e TFS_URL= zzz \
      -e VSTS_POOL= eee \
      -e VSTS_WORK='/var/vsts/$VSTS_AGENT' \
      -v /var/vsts:/var/vsts \
      -it microsoft/vsts-agent:ubuntu-14.04

Although it is behind VPN, I can access the repo from browser btw.

**Comment by TingluoHuang** [comment]
@Hirayuki base on the error, it doesn't looks like an agent issue, it's more like an image issue.

**Comment by Hirayuki** [comment]
@TingluoHuang what exactly you would advise ? Image is not changed by me, it is default image from docker hub, which works on my local, but does not work on remote

**Comment by TingluoHuang** [comment]
@Hirayuki i mean share your network config with the image owner, which is (Microsoft/vsts-agent-docker).
let them figure our how to make the image works on your environment. 
I will cloes the issue for now, since the error looks like to be fail to download the agent package.

**Comment by Alirezanet** [comment]
i have same problem ... did you fix that? @Hirayuki
