### ISSUE TITLE
_work folder instructions

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-agent#945]
Hi Folks,

I am not understand what to put in the _work folder.  I am trying to build using my machine is the build server.  

I have the files on my machine here:

Enter work folder (press enter for _work) > **/Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/Responder.xcworkspace**

You can see I have enter that as my work folder.  I have also tried leaving it as the default "_work" folder.

In both cases the build errors out with:

==============================================================================
Task         : Xcode Build
Description  : Build an Xcode workspace on Mac OS
Version      : 2.116.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
==============================================================================
**Xcode workspace was specified but it does not exist or is not a directory: /Users/jordanmc/Documents/src/Responder/Microsoft.Responder/platforms/Responder.xcworkspace/1/s/*.xcodeproj/project.xcworkspace**

Can you send me in the right direction of what is supposed to happen here?

Thanks

**Comment by TingluoHuang** [comment]
https://www.visualstudio.com/en-us/docs/build/get-started/ci-cd-part-1
https://www.visualstudio.com/en-us/docs/build/apps/mobile/xcode-ios
https://www.visualstudio.com/en-us/docs/build/concepts/agents/agents
https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-osx

The _work folder is the directory where the agent use it to store the repository fetch/pull from you VSTS/TFS source control, you need push your source code to TFS/VSTS git/tfs source control.

**Comment by bryanmacfarlane** [comment]
For xcode task issues, you should create an issue in the vsts-tasks repo.  The agent knows nothing about xcode.  It runs tasks.
