### ISSUE TITLE
config.sh breaks in Terraform

### ISSUE THREAD

**Issue by gislikonrad** [Microsoft/vsts-agent#963]
I've been writing a terraform script to provision and register a private linux build agent for visualstudio.com.

The repo is located on [github](https://github.com/SOLIDSoftworks/terraform-azure-vsts-private-build-agent). Most of the terraform script runs without a hitch. It's when it gets to the null_resource in virtual_machine.tf that I hit a snag.

When the null_resource runs provision.sh on the remote machine it gets to the ./config.sh line and just hangs. Looking at my private agent list on visualstudio.com shows the new agent, so config.sh must've completed along with the rest of provision.sh. The null_resource just gets marked as tainted.

This is a weird issue because I'm not totally sure where to turn. Should I talk to you guys or Terraform?

**Comment by TingluoHuang** [comment]
@gislikonrad you can also check the agent _diag log see whether agent got configured or not. i would think you might need reach to Terraform, since we didn't receive any report about the ./config.sh script.
