### ISSUE TITLE
Recursive submodules not supported

### ISSUE THREAD

**Issue by erigusaab** [Microsoft/vsts-agent#966]
## **Agent version and platform**
2.116.1
<br>
Linux (Ubuntu 16.04)
<br>
## **VSTS type and version**
On-Prem TFS
<br>
2015
<br>
## **What's not working?** 
Trying to set up TFS builds for git repositories with submodules in more than one level (i.e. main/sub/sub). Build fails because even with "checkout submodules" enabled only the first level of submodules are fetched.

The command:
git -c http(.......) submodule update --init --force
Should include the --recursive flag as well, i.e.
git -c http(.......) submodule update --init --force --recursive

This probably applies to other git commands, e.g. "git submodule foreach"

**Comment by TingluoHuang** [comment]
@erigusaab we added the support to checkout nested submodule in TFS2017 Update2, which will be released later this year.
