### ISSUE TITLE
latest agent from master can't start

### ISSUE THREAD

**Issue by kasubram** [Microsoft/vsts-agent#968]
## **Agent version and platform**
master branch
<br>
Both windows and linux
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
<br>
## **What's not working?** 
The .agent file looks like this, notice the empty notification* parameters
{
  "agentId": 2,
  "agentName": "KALYAN-DEV",
  "notificationPipeName": "",
  "notificationSocketAddress": "",
  "poolId": 1,
  "serverUrl": "http://localhost:8080/tfs/",
  "workFolder": "_work"
}
This is causing the below exception when the agent starts

<br>
## **Agent and Worker's diag log**

> Unhandled Exception: System.ArgumentException: pipeName cannot be an empty string.
>    at System.IO.Pipes.NamedPipeClientStream..ctor(String serverName, String pipeName, PipeDirection direction, PipeOptions options, TokenImpersonationLevel impersonationLevel, HandleInheritability inheritability)
>    at System.IO.Pipes.NamedPipeClientStream..ctor(String serverName, String pipeName, PipeDirection direction, PipeOptions options)
>    at Microsoft.VisualStudio.Services.Agent.JobNotification.<StartClient>d__7.MoveNext() in C:\vsts-agent1\src\Microsoft.VisualStudio.Services.Agent\JobNotification.cs:line 94
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>

**Comment by TingluoHuang** [comment]
@kasubram pull master try again. this has been fixed. #967
