### ISSUE TITLE
Need environment variable that includes a list of all artifact names for release

### ISSUE THREAD

**Issue by jabbera** [Microsoft/vsts-agent#975]
## **Have you try trouble shooting doc?**
This variable does not exist per documentation. https://www.visualstudio.com/en-us/docs/build/concepts/definitions/release/variables

## **What's not working?** 
I'm writing a task that will git tag all artifacts at the end of a release. The only way I've been able to determine all the artifact names is iterating over the environment variables and regexing. I'd love a new variable that include a json array or comma delimited (if that's not a reserved character).

**Comment by ericsciple** [comment]
i feel like we should not add this, since it will bloat the process env block more. we have an issue already. we need to figure out how to move away from over-using the env block.

note, there is also a function in the task lib to get all variables, so you dont have to infer from env vars directly.

**Comment by jabbera** [comment]
Thanks for the hint! I totally understand.
