### ISSUE TITLE
Release Artifact Variables: No team project name variable exists.

### ISSUE THREAD

**Issue by jabbera** [Microsoft/vsts-agent#976]
## **What's not working?** 
I'm writing a task that will git tag all artifacts at the end of a release. Since releases can now reference builds from other team projects, I need the team project name to properly resolve the friendly name of the Repository. Without this I have no way to access builds, repos, or pretty much anything about artifacts that live in other team projects. If there is an obvious solution to this let me know. I might have just overlooked something.

## **Have you try trouble shooting doc?**
This variable does not exist per documentation. https://www.visualstudio.com/en-us/docs/build/concepts/definitions/release/variables

**Comment by jabbera** [comment]
I can back into this from the buildid. It's ugly, but works.

**Comment by ericsciple** [comment]
@jabbera don't you need to back into it from the build ID anyway? a team project can contain many repos. furthermore a build can target an external repo (not saying you must support this scenario, but something to be aware of).

**Comment by jabbera** [comment]
@ericsciple actually I don't so far except for this one data point. commit id (Release.Artifacts.{Artifact alias}.SourceVersion) and repo name (Release.Artifacts.{Artifact alias}.RepositoryName) are both available already. The repository name is undocumented though. I know about the external git repo which I'm going to pass on. Without the team project name (or the repo ID) I can't support a release that doesn't have a build and is linked directly against a vsts git repo.

**Comment by ericsciple** [comment]
@GitHubSriramB ?

**Comment by GitHubSriramB** [comment]
@jabbera - Thanks for the feedback. It makes sense to add project ID & repository ID to the list of artifact variables. We will do this & also update documentation & also include repository name in the documentation.

**Comment by jabbera** [comment]
I went to implement this myself and was disheartened to find that the variables come from the server:-/

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB - system artifacts directory is also not specified by the release plugin in the agent

**Comment by GitHubSriramB** [comment]
@jabbera - We have added ProjectId & Repository Id to list of artifact variables.

@bryanmacfarlane - We do set system.artifactsdirectory in release plugin:
https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Release/ReleaseJobExtension.cs#L352

**Comment by GitHubSriramB** [comment]
Closing this issue given the issues identified have been fixed.

**Comment by jabbera** [comment]
@GitHubSriramB This is working great for build artifacts (TfsGit), but the repositoryid has not been included in "Git" artifacts that are direct links to vsts git repos. Can this be added? I'm actually stuck for this feature because there is no build to go back to. If I don't hear back in a couple of days I'll open a new issue since I can't re-open this one.

Thanks!
Mike

**Comment by GitHubSriramB** [comment]
@jabbera - RepositoryId for Git artifact is available as DefinitionId artifact variable. Would this work?
