### ISSUE TITLE
How can the version of Node.js be updated in the build agent?  I have a module that requires 6.X or higher and 5.x ships with the agent.

### ISSUE THREAD

**Issue by mjwoodsphx** [Microsoft/vsts-agent#979]
I have a custom build task with a node module that requires 6.x or higher of node, however the agent ships with a 5.x version.  I attempted to install node 7.x on the agent, including the path to point to 7.x but the agent still uses 5.x.  Any suggestions?

**Comment by TingluoHuang** [comment]
agent will start use node 6.10.3 from next version release. i will target next week to  2.117.0 agent.

**Comment by bryanmacfarlane** [comment]
Note that means your task will have to demand a minimum agent version of 2.117.0.  That means if your task is used, it will trigger an update of any 2.x agent.

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-agent/commit/28831e3e90861c5aec2adeddae2a5bab48e9dd01

**Comment by mjwoodsphx** [comment]
Will the new agent be compatible with  either TFS 2017 or 2017 update 1?

**Comment by TingluoHuang** [comment]
yes, it should.

**Comment by bryanmacfarlane** [comment]
2.117.1 agent is available for this - it's rolling through the hosted pools now finishing up tomorrow.  you can download if needed.  it has node 6 LTS

**Comment by IAMtheIAM** [comment]
The agent is way behind, were on node v9.0 now and its using 6.11, please update asap

**Comment by chazguerrero** [comment]
you can use the nodejs tool installer to specify a version of node to use in your builds. heres a link to the docs https://docs.microsoft.com/en-us/vsts/build-release/tasks/tool/node-js
