### ISSUE TITLE
MSBuild 15.0 not found when using Build Tools for Visual Studios 2017

### ISSUE THREAD

**Issue by discorev** [Microsoft/vsts-agent#984]
## **Agent version and platform**
Version of your agent? 2.116.1
<br>
OS of the machine running the agent? Windows Server 2012 R2

## **VSTS type and version**
VisualStudio.com

## **What's not working?** 
MSBuild 15.0 from Build Tools for Visual Studio 2017 is not found by the build agent.

As a full version of the IDE should not be needed for a headless build machine, VS2017 build tools was installed on the build server. Whilst this worked with an older build agent, it stopped working last Friday when the server's VSBuild task updated to version 1.117.0 and started using vswhere.exe

As that machine was having other un-related issues, we created a new Windows Server 2012 R2 VM, installed VS2017 build tools and the VSO agent. However, this machine does not report MSBuild 15.0 as being available due to vswhere not returning the path to it.

This is related to:
[vswhere issues/67](https://github.com/Microsoft/vswhere/issues/67)
[vswhere issues/68](https://github.com/Microsoft/vswhere/issues/68)

```
PS C:\agent\externals\vswhere> .\vswhere.exe -products *
Visual Studio Locator version 1.0.62 [query version 1.10.80.60812]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 5eda18f2
installDate: 5/22/2017
installationName: VisualStudio/15.2.0+26430.6
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
installationVersion: 15.0.26430.6
displayName: Visual Studio Build Tools 2017
description: The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without req
uiring the Visual Studio IDE. There are options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI
 support.
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualS
tudio.Setup.Service
channelId: VisualStudio.15.Release
channelPath: C:\Users\Ollie.Hayman\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\catalog.json
channelUri: https://aka.ms/vs/15/release/channel
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660284#15.1.26430.06
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660300

PS C:\agent\externals\vswhere> .\vswhere.exe -version '[15.0,15.1)' -latest -format json
[]
```

**Comment by ericsciple** [comment]
does vswhere find it if you add `-products *`?

**Comment by discorev** [comment]
Yes, that's the first command I ran in the powershell snippet above (copied output into this reply as well)

```
PS C:\agent\externals\vswhere> .\vswhere.exe -products *
Visual Studio Locator version 1.0.62 [query version 1.10.80.60812]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 5eda18f2
installDate: 5/22/2017
installationName: VisualStudio/15.2.0+26430.6
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
installationVersion: 15.0.26430.6
displayName: Visual Studio Build Tools 2017
description: The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without req
uiring the Visual Studio IDE. There are options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI
 support.
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualS
tudio.Setup.Service
channelId: VisualStudio.15.Release
channelPath: C:\Users\Ollie.Hayman\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\catalog.json
channelUri: https://aka.ms/vs/15/release/channel
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660284#15.1.26430.06
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660300
```

**Comment by Thilas** [comment]
I got the exact same issue: I installed a new agent and deployed Visual Studio Build Tools 2017 but it is not found.

FYI, I have an other agent but in version 2.115.0 (therefore without vswhere) with Visual Studio Build Tools 2017, and it is correctly detected.

**Comment by ericsciple** [comment]
tracking the issue here: https://github.com/Microsoft/vsts-tasks/issues/4403

...and workaround is listed there too
