### ISSUE TITLE
Update azure node modules for vsts agent

### ISSUE THREAD

**Issue by v2kiran** [Microsoft/vsts-agent#987]
Hi 
the ability to deploy a resource to multiple resourcegroups(https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-cross-resource-group-deployment) was added recently to the azure resource manager but it requires that the powershell azure module be updated to the latest version. This I already did but since the azure resource group deployment task depends on node modules and not powershell I would like to know how to updte the node_modules to the latest version so they can use the latest azure arm api's.

## **Agent version and platform**
Version of your agent? 2.111.1
<br>
OS of the machine running the agent? Windows 2012R2
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?VisualStudio.com
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://v2kirar.visualstudio.com
<br>
## **What's not working?** 
The api-version '2016-07-01' used to deploy the template does not support 'ResourceGroup' property.
<br>

**Comment by ericsciple** [comment]
this sounds like an issue for the [tasks repo](https://github.com/microsoft/vsts-tasks)
