### ISSUE TITLE
Feature:  Allow auditing of automatic agent update, and possibly warn / prevent users from queueing builds that cause this behavior

### ISSUE THREAD

**Issue by MattGal** [Microsoft/vsts-agent#990]
Figuring out both when and why my VSTS agents self-updated today basically involves going to the _diag log folder and finding the logs of this happening.   If our build history doesn't go back far enough to see it, I have no possible way to figure out when or which build definition caused the automated upgrade.

This is a regular problem for the .NET Engineering build team and we'd very much like to lock in to single versions as breaking changes in the build agent behavior can and have broken our builds post-automated-update.

I'd **_really_** love to see a button when queueing builds that says "Hey! Clicking OK will cause this pool to update the following agents from X to Y version.  Is that ok?," ideally along side the existence of a new permission that limits random users who can enqueue builds from doing that

@TingluoHuang FYI.

**Comment by ericsciple** [comment]
@MattGal send an email to bigbldt. closing the issue here since we dont track our backlog here.
